### PR TITLE
Fix 3FHL spectral indexes for PowerLaw model

### PR DESCRIPTION
**Pull request by jjlk**
Hi @cdeil , @adonath ,
This PR fix the 3FHL spectral indexes for the sources modeled with a PowerLaw.

@cdeil : I didn't find anything wrong in the print output

Oké to merge?

### CODE REVIEW

**Comment by jjlk** [comment]
Not oké to merge, I have a problem with git. I'll go back to you

**Comment by cdeil** [comment]
@jjlk - I think in the printout there's the same mistake for 3FHL, no?
https://github.com/gammapy/gammapy/pull/1127/files#diff-99130bfaec86b7c20f2213209a553ee0R700
It always prints the `Spectral_Index` field, which is not the right value for the PL case.

I think the corresponding 3FGL or GammaCat printout function is done better, putting the whole printout for spectral model in if / else block, not trying to combine the cases, which IMO makes the code harder to understand. So in this case I prefer completely independent if / else blocks for the spectral model printout, even if it means duplicating a few lines of code.

**Comment by cdeil** [comment]
I think if I start editing here there will be merge conflicts. So I'm merging this now, and will make a follow-up commit in master, mostly to improve tests. (note how the change here didn't require a change in the tests, the tests didn't cover spectral index)

@jjlk - Félicitations pour avoir trouvé et réparé ce bug!

**Comment by cdeil** [comment]
Correction: actually `TestFermi3FHLObject.test_spectral_model[352-PowerLaw-desired0]` did fail. I'll adjust the assert and do other improvements to the tests in master.

**Comment by cdeil** [comment]
I've tried to improve the Fermi source printout code a bit in 8b7ab1343f7bb06e1cf6798d1908e5559020ea7f and the tests in 567a0a093ddb0cb0529bc92569b1374cb1e766ea .

I think the tests are a bit better now (easier to read and extend). For the 3FHL spectral info printout, I checked the two sources that are also used in the test, I think it's better now. For the 3FGL spectral info printout, I didn't really manage to make it better, the code is very hard to read / maintain as-is, but probably correct for all cases, and quite hard to write in a better way. Moving on ... of course, future issue report or PRs to improve things welcome any time.

**Pull request merged**
