### PR TITLE
Add lightcurve with 3D map analysis

### PR DESCRIPTION
**Pull request by AtreyeeS**
This PR re-implements `LightCurve` and `LightCurveEstimator` as per PIG 11. This is a work in progress.

### CODE REVIEW

**Comment by cdeil** [comment]
@AtreyeeS - Thanks!

@registerrier - You continue here?

There's a merge conflict, needs a rebase.

What's the strategy here in this PR to get this in?
Keep `lightcurve_new.py`?
What about tests?
I think duplicating at least the `Lightcurve` class isn't needed / useful, for `LightCurveEstimator` I'm not sure.

Basically: what do you want to replace and what to improve in this PR, also concerning tests?

**Comment by AtreyeeS** [comment]
@cdeil : As per PIG 11, the two classes in the `lightcurve.py` file will be replaced with the ones in `lightcurve_new.py`. I have not removed the old classes yet as that would required adapting all the tests and notebooks and wanted to keep them till we have a new working class. 

I think @registerrier will speak in details about this today, but some of the changes I wanted to implement:



- [ ] Add the tests for `LightCurveEstimator` : The issue here is that the data preparation takes more time than the fitting if we start from the DC1 examples. We discussed this a little bit during the last dev call, and @adonath proposed that we might have some prepared maps on which to do the fitting. 

- [ ] Plotting the likelihood profile is broken at present.

- [ ] Have an intergrated_flux column on the `LightCurveEstimator`? This is something which most users would want as the basic option while making lightcurves - have only the normalisation free and see how the integrated flux varies with time for a simple spectral model. This is simple to implement, we just call the `spectral_model.integrate()` function and add a new column. But, if there are more than one free parameter in the model, then computing the error on the integrated flux is an issue. Also, what if some more complicated model is passed... Perhaps this needs to be discussed as well.

**Comment by cdeil** [comment]
My concern with this approach is that you get a long-running branch on the side, whereas in my experience a series of short PRs is more effective. What happens is that you would now re-write tests from scratch. As a reviewer, it's hard, because I have to look a lot back and forth - e.g. what actually is different in the LightCurve class here compared to the existing one? 

Proceed as you like, but please aim to have this PR merge by Friday this week, so that it is in v0.13 which is scheduled for Monday next week, and not aim to have this as a huge long-running lightcurve rewrite PR that you keep on working and we review many times in the coming months.

I'll try to review the LC PIG today.

**Comment by registerrier** [comment]
This new version of the `LightCurveEstimator3D` now follows the `FluxPointsEstimator` implementation . There is a significant amount of code duplication, but it can now produce light curves that follow the SED specifications of `dnde`, `flux` and `e2dnde` columns. It uses the same approach to compute errors, asymmetric errors as well as likelihood scans. 
Some effort will be needed in the future to limit code duplication between the two classes.

The new notebook performs the same light curve analysis as the current 1D estimator (i.e. 4 Crab runs). It gives consistent results.

It sill misses some tests.

**Comment by registerrier** [comment]
I also removed the `TIME` column from the table expected in light curve. A light curve is a time bin series and is defined between two time values. Defining it at a given time value is irrelevant here.
The `LightCurve.time` property now returns the middle of the time bin.

The tests were adapted accordingly.

**Comment by cdeil** [comment]
In the notebook table output I see that `time_min` and `time_max` don't have a unit set. Presumably it's seconds? Can you set the unit, please?

**Comment by cdeil** [comment]
Suggest to change:
```
for time_interval in time_intervals:    
    obs = crab_obs.select_time(time_interval)
    if len(obs) > 0:
        dataset = ...
        datasets.append(dataset)
 ```
to
```
for time_interval in time_intervals:    
    obs = crab_obs.select_time(time_interval)
    if len(obs) == 0:
        log.warning("Skipping ...")
        continue

    dataset = ...
    datasets.append(dataset)
 ```
This means the "meat" if the computation is indented one level less, and the user notices when some of the time bins she wants to measure are skipped, instead of skipping it silently.

**Comment by adonath** [comment]
Thanks @registerrier, the implementation looks good to me! I agree there is a lot of code duplication, but I think in the current situation it's hard to avoid it. The code is mostly very simple and some parts (freezing background model parameters etc.) can probably go on the dataset classes in future.  So I completely agree with @cdeil this PR should go in.

What do we do about the "old" class and tutorial? I think I have the preference to just remove it. I can spend ~2-3 hours today to help with the clean-up if needed.

**Comment by adonath** [comment]
Thanks @registerrier and @AtreyeeS. As discussed with @registerrier and @cdeil offline we'll continue the clean-up in follow-up commits in separate branches.

**Pull request merged**
