### PR TITLE
Add test for on-off fitting

### PR DESCRIPTION
**Pull request by AtreyeeS**
**Description**

This pull request adds a test and extends the ring tutorial for `MapDatasetOnOff` modelling and fitting.

**Dear reviewer**

### CODE REVIEW

**Comment by adonath** [comment]
@AtreyeeS I just checked the residual map of the on-off fit and it doesn't look right. I think we have to overwrite the `npred()` of the `MapDatasetOnOff` to include the background...

**Comment by AtreyeeS** [comment]
Yes indeed @adonath ! The residual maps do not change because the source models are not taken into account. I filed #2989  for this exact reason - the estimator does not consider the `npred` for `MapDatasetOnOff` while making the residual maps

**Comment by adonath** [comment]
@AtreyeeS I meant something in addition: even the `dataset_on_off.plot_residuals()` does not look right, because the `MapDatasetOnOff.background` is not included in the npred. However in `stat_array()` I think it's handled correctly...

**Comment by AtreyeeS** [comment]
Closing due to merge conflicts

**Pull request closed without merging**
