### PR TITLE
Improve catalog classes and gammapy-extra data handling

### PR DESCRIPTION
**Pull request by cdeil**
This PR started as #341 by @JonathanDHarris, rebased on master. It looks OK to me (+270 lines, -2 lines). There's all commits from that PR here, except https://github.com/JonathanDHarris/gammapy/commit/9ace5e9f0310b743c3487fbe2a6421f18c01bbda which was causing the trouble with the rebase. I had to do `git rebase --skip` and then it worked.

I started adding a web app `gammapy-catalog-browse` with the goal to browse Fermi and HESS catalogs, plot spectra, finder charts, etc.

Then I got sidetracked with how catalogs are fetched for tests: it's much better now, a `requires_data` and `requires_dependency` decorator was added in `gammapy.utils.testing` so that it's easy to declare what's needed in a given test, and files from the `gammapy-extra` repo are loaded via `gammapy.datasets.gammapy_extra.filename()`, and `gammapy-extra` is found via the `GAMMAPY_EXTRA` environment variable and is available on travis-ci so that now almost all tests run on travis-ci without needing `--remote-data`.

I'm merging this now and will continue working on the catalog classes and catalog browser in a new PR.

### CODE REVIEW

**Comment by cdeil** [comment]
@kingj90 There's still an issue with gammapy-extra not being found in the travis-ci builds:
https://travis-ci.org/gammapy/gammapy/jobs/87645494#L659
And I want to tidy some things up concerning @remote_data ... ~ 1 more hour.

**Comment by cdeil** [comment]
With this PR all test tests that were marked `@remote_data` before now run on travis-ci:
https://travis-ci.org/gammapy/gammapy/jobs/87662698#L1215

Overall Gammapy test coverage improved from 44% to 49%:
https://coveralls.io/builds/3962398

**Comment by kingj90** [comment]
thanks a lot!

**Comment by cdeil** [comment]
@kingj90 – I broke some things (spectral analysis, cube background modeling) while restructuring the data handling code and marked tests as `xfail` in cases where I didn't want to spend the time to update the code. Sorry about that. E.g. re-activating this test and getting it working would be a good place to start for you:
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/tests/test_spectrum_analysis.py#L8

**Comment by kingj90** [comment]
don't worry - this test were not implemented properly anyways. It's the next point on my agenda

**Pull request merged**
