### PR TITLE
Introduce `WcsNDMap.convolve()` method

### PR DESCRIPTION
**Pull request by adonath**
Image convolution is used in many places in Gammapy (`gammapy.cube`, `gammapy.detect`, `gammapy.image`). This PR introduces a `WcsNDMap.convolve()` method to unify the usage of image convolutions in Gammapy. So far different functions from astropy as well as scipy have beem used.  To make a choice, which functions to use for  `WcsNDMap.convolve()` I wrote a [notebook comparing the performance](https://github.com/adonath/notebooks-public/blob/master/convolution_functions_comparison.ipynb) of the different convolutions functions in astropy and scipy. The clear winners are `scipy.signal.fftconvolve` and `scipy.ndimage.convolve`. The notebook also shows, that for `scipy.signal.fftconvolve` the runtime only weakly depends on the kernel size. Choosing the fft convolution we might avoid the need for energy dependent kernel sizes.

### CODE REVIEW

**Comment by cdeil** [comment]
This is what I get on my Macbook with 2,5 GHz Intel Core i7 and scipy from Anaconda:

perf

**Comment by adonath** [comment]
@cdeil No there was no specific reason to use non-fft for Li&Ma images, except that I wanted to keep the tests unchanged for this PR. The unit tests are still in `gammapy/cube/test/test_psf_kernel.py`, I agree they should probably be copied over to `gammapy.maps`. I'll work on a follow up PR now and also reintroduce the pixel size check...

Unfortunately the results of the convolution comparison on your mac book is not visible, just an empty image. Does it give similar results?

**Comment by cdeil** [comment]
@adonath - Thanks!

Yes, the results were very similar, except that the crossing point where scipy.signal.fftconvolve is faster than scipy.ndimage.convolve was already a little sooner, at a kernel width of 6 or 7. So probably fftconvolve is the better default. Although that comes with the caveat that we haven't looked at it in some more detail yet, namely dependency of speed (and maybe also precision) on float type (32 and 64 bit) and on image size. Is fftconvolve well-behaved, i.e. similar for any image size? Or does it go in steps and e.g. 513 is much slower than 512?

**Comment by cdeil** [comment]
Does FFT convolve work well for kernels with hard edges, like a disk for the on region or a ring for the background? Or does it give ringing artefacts or anything like that?

**Pull request merged**
