### PR TITLE
Fix bug in LightCurveEstimator

### PR DESCRIPTION
**Pull request by lmohrmann**
Due to this bug, the energy threshold is not applied when calculating the expected counts.

### CODE REVIEW

**Comment by jlenain** [comment]
Hi @lmohrmann,
Actually, @bkhelifi raised this issue also, and he rather suggested the [attached fix](https://github.com/gammapy/gammapy/files/1838134/lc.patch.txt).

**Comment by cdeil** [comment]
@lmohrmann @jlenain @bkhelifi - Any preference on which fix to put?
```
diff --git a/gammapy/time/lightcurve.py b/gammapy/time/lightcurve.py
index 7d227ff9..28c6b1dd 100644
--- a/gammapy/time/lightcurve.py
+++ b/gammapy/time/lightcurve.py
@@ -428,7 +428,7 @@ class LightCurveEstimator(object):
                 model=spectral_model
             )
             counts_predictor.run()
-            counts_predicted_excess = counts_predictor.npred.data.data[e_idx[:-1]]
+            counts_predicted_excess = counts_predictor.npred.data.data[e_idx[:]]
 
             obs_predicted_excess = np.sum(counts_predicted_excess)
 
```

@lmohrmann - Can you please add a regression test, i.e. an assert that would change the reference value with this fix?

**Comment by lmohrmann** [comment]
> Any preference on which fix to put?

I definitively think the fix I proposed is the correct one. The fix proposed by @bkhelifi will raise an `IndexError` whenever the upper threshold is above the specified energy binning.

> Can you please add a regression test, i.e. an assert that would change the reference value with this fix?

Turns out the tests were already covering this. I fixed them.

**Comment by cdeil** [comment]
@lmohrmann - Thanks!

@bkhelifi @jlenain - Please try again with Gammapy master, and please do open issues in the tracker when you find them.

**Pull request merged**
