### PR TITLE
Require astropy>=5.0

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request pushes the Astropy version required by Gammapy to >=5.0. This is an LTS version and the version that should be used for Gammapy v1.0.

Addresses #3763.

### CODE REVIEW

**Comment by adonath** [comment]
By requiring `astropy>=5.0` we also have to drop support for Python 3.7.

**Review by registerrier — DISMISSED** [review]
+1 @adonath . What should be the CI grid now?

**Comment by adonath** [comment]
I think we should add Python 3.10 and possibly 3.11 instead.

**Comment by adonath** [comment]
@registerrier I cannot get the CI fails resolved. I'll split the PR and update the Python version first.

**Pull request merged**
