### PR TITLE
Fix dict ARTIST_TO_LINE_PROPERTIES

### LINKED ISSUE #5235: `plot_regions` fails when using linewidth with a  `PointSpatialModel` and extended spatial model
**Gammapy version**
gammapy v1.2

**Bug description**
When utilising `plot_regions` to plot different models, if a `PointSpatialModel` is included it somehow tries to include some of the `**kwargs` instead of only utilising `kwargs_point`. Trying to utilise `linewidth` specifically results in an error. 
This is not present when only non `PointSpatialModels` are used.

**To Reproduce**
To reproduce see the small code [here](https://gist.github.com/Astro-Kirsty/cfa975c9938043a37b6043a3ad968ee3). 
```
models.plot_regions(ax=ax, kwargs_point=dict(marker="o", fillstyle='full'),
                      edgecolor="deepskyblue", facecolor="deepskyblue", linewidth=2)
```

### PR DESCRIPTION
**Pull request by AtreyeeS**
This fixes #5235

### CODE REVIEW

**Comment by Astro-Kirsty** [comment]
Do you still get an error when running the [example code](https://gist.github.com/Astro-Kirsty/cfa975c9938043a37b6043a3ad968ee3), or just me?

**Comment by AtreyeeS** [comment]
> Do you still get an error when running the [example code](https://gist.github.com/Astro-Kirsty/cfa975c9938043a37b6043a3ad968ee3), or just me?

Seems to work for me!

Screenshot 2024-04-26 at 12 50 01 PM

**Review by Astro-Kirsty — APPROVED** [review]
Okay great, thanks @AtreyeeS

**Review by registerrier — APPROVED** [review]
Thanks @AtreyeeS . This looks good!

**Pull request merged**
