### PR TITLE
Spectral point and likelihood profile estimation

### PR DESCRIPTION
**Pull request by cdeil**
This PR:

- [x] Refactors `DifferentialFluxPoints.compute` into a separate `FluxPointEstimator` class.
- [x] Start a new `SEDLikelihoodProfile` class.

Pair coding with @joleroi .

### CODE REVIEW

**Comment by cdeil** [comment]
@joleroi - If you work on this branch, could you please mark the test with `requires_dependency` as needed?
https://travis-ci.org/gammapy/gammapy/jobs/161638006#L992

**Comment by cdeil** [comment]
@joleroi - I've pushed what we wrote just now in 0ab064d831229677b3f2967cc9a15514bcbc6768 to this branch. Please push everything you have here tonight, so that we can continue from `master` tomorrow and more easily apply it to the data release and HGPS.

**Comment by joleroi** [comment]
The plotting method in https://github.com/fermiPy/fermipy/blob/1cbbb2b80ab2e3181140b31ecbad68a8a5fdab4a/fermipy/sed_plotting.py are actually quite elaborate, I don't know if I'll be able to produce a reasonable plot on a sane time scale.

**Comment by cdeil** [comment]
Maybe just plot the curves `x=log(flux)` versus `y=stat` instead for now, so that we'll have a way to  check quickly if it "looks OK" when we compute such SED likelihood profiles for HESS data with Gammapy?

**Comment by cdeil** [comment]
@joleroi - I'm merging this now. Let's re-start further work from master.

**Pull request merged**
