### PR TITLE
Add test images for gammapy.image tests

### PR DESCRIPTION
**Pull request by OlgaVorokh**
I am working on a better tests for gammapy.image, so I made images for all major coordtypes(GAL, CEL) and projections(CAR, TAN, AIT) and applied them to solid angle, as a beginning

@cdeil 
It's based on a new [PR568](https://github.com/gammapy/gammapy/pull/568), so the values for are incorrect at this moment(the shape one less then original image), but I imagine it like this

The results will be corrected once solid_angle is fixed.

### CODE REVIEW

**Comment by OlgaVorokh** [comment]
Oops, Not sure what  happened, but now it says
 OlgaVorokh closed this 4 minutes ago
I'll look into this

**Comment by OlgaVorokh** [comment]
@cdeil updated expected values, not sure if those look good and if there is a way to initialize test images to make it test results more descriptive

**Comment by cdeil** [comment]
@OlgaVorokh - Now that #568 is merged, this PR needs to be rebased. Please do this now, so that the diff only shows changes from this PR and tests on travis-ci run.

Concerning the image tests ... in principle it's exactly what we talked about, thank you!
However, I don't like to have so many hard-coded numbers for the reference output and indented so far to the right on the screen. I'll talk to @adonath today about options to make this shorter ... maybe just assert on one or a few pixels, instead of all of them?

Also, I would prefer if the test images have much larger pixels, so that they cover a significant portion of the whole sky. Only for such huge pixels some of the non-linear distortions become noticeable.
Specifically in AIT all-sky images, there's usually pixels at the edge that don't represent a point on the sky: http://fermi.gsfc.nasa.gov/ssc/Fermi_5_year.jpg
It would be good to run such an image through `SkyMap.coordinates` and `SkyMap.solid_angle` and to see what value gets filled at the edge of the sky region and outside the sky region. Having `NaN` values there would be best, but let's just see what we currently get, whether the routines error out or do put something.

One possibility would be to use binsz = 60 deg pixels and then to have `6 x 3` pixels to cover all-sky `-180 deg ... +180 deg` in longitude and `-90 deg ... + 90 deg` in latitude.

@adonath @OlgaVorokh - Do you see a benefit of keeping the small pixel (~0.1 deg) images as well for tests or should they just be replaced with the big pixel images? I can't think of something specifically that is only well-tested on small images, so I'm thinking maybe just keep the large-pixel images for tests to avoid having to write extra reference values for all the tests? But I'm not sure...

**Comment by OlgaVorokh** [comment]
@cdeil this is an interesting point, but I like keeping the whole output because this makes it easier to see the full impact of algorithm change. I feel like when you take several pixels from center you risk to miss some incorrect border processing, when you take several pixels from corners you risk to find near-zero values if everything interesting is happening in the center.

Maybe we should keep whole expected output in some json file, hidden somewhere in gammapy-extra?

To make a large pixel image I need to somehow setup WCS to specify that +1 in pixel coordinates means +60 pixels, right?

**Comment by cdeil** [comment]
> Maybe we should keep whole expected output in some json file, hidden somewhere in gammapy-extra?

Hmm ... I'm not sure yet what's the best solution here:
- keep reference values with the test (as-is)
- keep reference values with example images (use a test fixture)
- split reference values out into separate files (like txt or json)

Maybe we just have to think and discuss some more ... maybe we just merge as-is and continue adding tests, and when we think of a better pattern to organise this we change later?

> To make a large pixel image I need to somehow setup WCS to specify that +1 in pixel coordinates means +60 pixels, right?

You can use the `binsz=60` option in [SkyMap.empty](http://docs.gammapy.org/en/latest/api/gammapy.image.SkyMap.html#gammapy.image.SkyMap.empty)

**Comment by adonath** [comment]
I agree with @OlgaVorokh that testing on the whole array is the safer option. So I would just choose, few but large pixels for the map tests. 

Having the numbers hard-coded for the test is fine by me for now.

**Comment by OlgaVorokh** [comment]
@cdeil, please, take a look!

**Comment by cdeil** [comment]
Thank you!

**Pull request merged**
