### PR TITLE
Remove old flux point classes

### PR DESCRIPTION
**Pull request by adonath**
This PR removes the old `DifferentialFluxPoints` and `IntegralFluxPoints` classes, from the `gammapy.spectrum` module, tests and docs and all uses of it.

@joleroi @cdeil There's a `SpectrumFit.compute_fluxpoints()` method which seems to never have worked. I added `raise NotImplementedError` let me know, if I should remove it completely

### CODE REVIEW

**Comment by cdeil** [comment]
🎉 , thanks for the cleanup!

I don't remember if I was involved with adding `SpectrumFit.compute_fluxpoints` or if it's something @joleroi did:
https://github.com/gammapy/gammapy/blame/080a1498d6e390b6d4a7feabafb6f2a71b28f4aa/gammapy/spectrum/fit.py#L225

I'll add @joleroi as reviewer now.
But @adonath - if you want to merge this now, no worries, we can always bring stuff back from version history.

**Comment by adonath** [comment]
@joleroi Could you please update [this notebook](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_analysis.ipynb) to use `FluxPoints` instead of `DifferentialFluxPoints`? Once the change is done Travis-CI should pass...Thanks!

**Comment by adonath** [comment]
Thanks @joleroi!

**Comment by joleroi** [comment]
``+65 -265 ``
itwasagoodday

**Pull request merged**
