### PR TITLE
Fix filename handling in read/write methods

### PR DESCRIPTION
**Pull request by alexiscoutinho**
Wrapped `filename` in `make_path()`, as in `Map.read`, to allow for environment variables.

### CODE REVIEW

**Comment by alexiscoutinho** [comment]
I see... I searched all python scripts for the strings `read`, `write`, `open` and `file` and found that the same problem occurs in: `DataStoreMaker.read_events_info`, `FluxPointsDataset.write`, `IRFMap.read`, `IRFMap.write`, `PSF3D.write`, `HESSMultiGaussPSF._read_ascii`, `EnergyDependentMultiGaussPSF.write`, `PSFKing.write` and `EnergyDependentTablePSF.write`. Should I rename this PR and push these fixes or wait for the _automation_?

On the other hand, I'm not sure if this fix should apply to:
- Is `MapDataset._read_lazy` intended to not treat/expand environment variables?
- Is it appropriate to treat environment variables in _download.py_, _downloadclasses.py_, _jupyter.py_, _notebooks_links.py_ and _notebooks_process.py_?

**Comment by adonath** [comment]
Thanks @alexiscoutinho for looking into this. I agree expanding environment variables could be useful for writing as well. 

A few comments:
- `MapDataset._read_lazy`, always goes through `Map.read()` no change needed there...
- `DataStoreMaker.read_events_info` is not part of our public API, no change needs there...
- Again `HESSMultiGaussPSF._read_ascii` is not part of our public API, no change needs there...
- I remember in older version of Astropy `fits.open()` and `hdulist.writeto()`, didn't support a `Path` object, just to be sure please convert to a string before, like `hdulist.writeto(str(filename))`

I think all the other places are appropriate, so please go ahead and add the change to this PR...

**Comment by alexiscoutinho** [comment]
It seems like `IRFMap` is not part of the public API, so should I keep it as it is? The issue with `MapDataset._read_lazy` I tried to point out is on line 872: `kwargs["gti"] = GTI(Table.read(filename, hdu="GTI"))`. `Table.read` would raise a `FileNotFoundError` and this method is accessible through the public `MapDataset.read`.

**Comment by adonath** [comment]
Thanks @alexiscoutinho, I see what you mean with `._read_lazy`, simply changing the line to `GTI.read(filename)` should fix the issue...

**Review by adonath — APPROVED** [review]
Thanks @alexiscoutinho! I have no further comments...

**Pull request merged**
