### PR TITLE
Adding a background model fit

### PR DESCRIPTION
**Pull request by AtreyeeS**
In progress now.

### CODE REVIEW

**Comment by adonath** [comment]
As discussed in our call, please just remove the covariance dispatching in  https://github.com/gammapy/gammapy/blob/master/gammapy/cube/models.py#L154 and https://github.com/gammapy/gammapy/blob/master/gammapy/cube/models.py#L165. And set the covariance on the spectral models in the `analysis_3d` notebook "by hand". I'll do a final review. once the remaining changes are in.

**Comment by AtreyeeS** [comment]
This PR adds the implementation of background models in gammapy, specially addressing (#1804).
This also solves the issue of getting nans in the covariance matrix as pointed out in #1868

**Comment by AtreyeeS** [comment]
Thanks @adonath! I have made the changes as you commented

**Comment by adonath** [comment]
@AtreyeeS Thanks, I just pushed a few minor clean-up commits. Now the PR is ready to merge...

**Pull request merged**
