### PR TITLE
Fix stacking backscale

### PR DESCRIPTION
**Pull request by JouvinLea**
@joleroi  @registerrier 
Change the way to compute the mean off backscale for a stacked observation. I didn't update the test for the moment. We can do it once we agreed this is the good way to go

### CODE REVIEW

**Comment by JouvinLea** [comment]
@joleroi
I updated the test

**Comment by joleroi** [comment]
Thanks for this fix. The test failures are unrelated. We need to update the documentation to show the correct formulae here
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/observation.py#L611
@JouvinLea can you do that?

**Comment by JouvinLea** [comment]
@joleroi
I updated the docs! Is it ok? It's quite ugly since the equation are not alined....

**Comment by joleroi** [comment]
> I updated the docs! Is it ok? It's quite ugly since the equation are not alined....

Perfect, thanks. Let's care about the style later :wink:

**Pull request merged**
