### PR TITLE
Refactor content in User Guide and Getting Started docs

### PR DESCRIPTION
**Pull request by Bultako**
This PR continues with the improvement of the docs, addressing the suggestions issued in the first group of items of #3818 

- cosmetic modifs on the top navigation bar
- adding boxes and refactoring content in User Guide and Getting Started sections

You may access how the docs shows with this PR in the [usual link](http://www.iaa.csic.es/~jer/gammapydocs).

### CODE REVIEW

**Comment by Bultako** [comment]
Bringing some comments from #3818 

> Probably remove the Gamma-ray data analysis link. 

I think it could be useful to have a page describing briefly the standard Gamma-ray data analysis process.

> Package Structure should be a big button, where the bulk of the content can be moved.

Agree.

> I do not know if Dependencies should stay here. It can maybe move to the page after Getting Started and Installation

Dependencies is now under the [Development](https://docs.gammapy.org/dev/development/index.html) section.

**Review by AtreyeeS — DISMISSED** [review]
Thank you @Bultako ! I really like the `Getting Started` section now.

The `User Guide` also looks very nice, specially the icons that you have chosen :)

**Review by registerrier — APPROVED** [review]
Thanks @Bultako . This looks very nice.

On my browser, the menu bar disappears and is replaced by a single icon if the screen size is too small. Is it expected behavior?

**Comment by Bultako** [comment]
@registerrier 

> On my browser, the menu bar disappears and is replaced by a single icon if the screen size is too small. Is it expected behavior?

Yes, this is called responsive behaviour, which means that for small screen devices like phones or tablets the menu bar is accessible by clicking on the menu icon. This is a feature of the pydata sphinx theme, and you can also see it in the dev docs already published. In this PR I just changed the color of that menu icon to give it more visibility.

**Comment by registerrier** [comment]
Merging now. Sorry for the delay.

**Pull request merged**
