### PR TITLE
Add example of DataStore.from_events_files in CTA notebook

### PR DESCRIPTION
**Pull request by QRemy**
This PR copy the usage example of  `DataStore.from_events_files()`
from its docstring  to the CTA notebook. This illustrates an alternative solution if ones can't get the index files  (received report about download link broken and bad file received from someone else...).

### CODE REVIEW

**Comment by QRemy** [comment]
Works locally but fails in the tests because of $CALDB ?
 `No such file or directory: '$CALDB/data/cta/1dc/bcf/South_z20_50h/irf_file.fits'`

**Review by registerrier — APPROVED** [review]
Thanks @QRemy . This looks good to me.

Maybe at some point we will have to add the new CTA IRFs BTW.

**Comment by QRemy** [comment]
This notebook focus on CTA 1DC that uses the old IRFFs. Maybe we can add in a separate PR the latest IRFs to gammapy-data and create a how to about "getting the CTA IRFs in gammapy"

**Comment by registerrier** [comment]
We have to see with CTAO whether we can add them to gammapy-data. But a minima, an howto is indeed a good idea.
I merge this PR now.

**Pull request merged**
