### PR TITLE
Rename gammapy/stats/significance.py

### PR DESCRIPTION
**Pull request by cdeil**
Currently we have `gammapy/stats/significance.py`, i.e. `gammapy.stats.significance` as a module name, and also a function `significance` in `gammapy/stats/poisson.py`, exposed in the `gammapy.stats` namespace as `gammapy.stats.significance`.

It's not obvious if this will give the function or unrelated module:
```
from gammapy.stats import significance
import gammapy.stats.significance
```
Turns out, due to the order of imports in `gammapy/stats/__init__.py`, you always get the function and that's usually what you need.

However, there is now no way anymore to reach the module, which is bad, and also static code analysis quality tools get confused by this, see [here](https://lgtm.com/projects/g/gammapy/gammapy/snapshot/01f9069e90a493f597dfb629abded4e67381167a/files/gammapy/detect/lima.py?sort=name&dir=ASC&mode=heatmap#x65ea48078e573d0:1).

Suggest we rename the file `gammapy/stats/significance.py` to something else. Maybe `gammapy/stats/normal.py` given that it only contains helper functions to convert between significances and p-values for the normal distribution?

@adonath @registerrier - OK to put `normal.py`, or do you have a better idea?

### CODE REVIEW

**Comment by adonath** [comment]
@cdeil Just merge the content of `period.py` and `exptest.py` into `variability.py`. Both are small files anyway...

**Comment by cdeil** [comment]
I still don't like putting the `exptest` into a `variability.py`, because we will get more events-based variability tests (it's a whole literature field), and then you'll have functions like `_noise` where it's not clear to what code they belong.

One change I will make now is to put `plot_periodogram` into `period.py`, because it's a single function and completely related to the code there.

**Comment by cdeil** [comment]
There's also still the `PhaseCurveTableModel` which is about variability, but which I'd prefer to keep in `models.py` for now.

**Comment by registerrier** [comment]
For `significance.py`, you could also rename it `pvalue.py` since it mostly deals with conversion of pvalues to significances. `normal.py` does not sound very explicit either, in particular the content do not really compare to what is in `poisson.py`.

Or even more simply, you could simply call this file `utils.py`.

Same thing for `exptest.py`, this is a simple utility function.

**Comment by cdeil** [comment]
Ha ha ... so basically each of us would choose different names. But in the end those filenames don't matter, because only the sub-package namespaces are used. We'll have to be really careful when we re-name everything towards consistency in Gammapy, not to ask for feedback too early. Probably do it in a structured way, via a PIG which lists the ~ 200 names we propose to change to. For now I'll decide here and merge.

**Comment by cdeil** [comment]
Merging this now. It does resolve the function/module name shadowing issue pointed out by our code quality analysis. We will review code organisation anyways soon throughout Gammapy and make changes / decisions, via one or two PIGs.

**Comment by cdeil** [comment]
I forgot to rename the corresponding test filenames. Fixed in master in 79610837e67a78453e88a8a232879ad830566c54 and 2d7fadf5237bc0e747726594291a9a28c15247a0

**Pull request merged**
