### PR TITLE
Fix spectrum_analysis notebook

### PR DESCRIPTION
**Pull request by joleroi**
together with https://github.com/gammapy/gammapy-extra/commit/1243a820bc461464c8dbcdb7ada814903c512135

### CODE REVIEW

**Comment by cdeil** [comment]
If indeed the spectrum notebook is fixed, you could re-activate it's testing by changing this line:
https://github.com/gammapy/gammapy-extra/blob/master/notebooks/notebooks.yaml#L41

**Comment by joleroi** [comment]
Done

**Comment by joleroi** [comment]
The remaining failure is due to 
https://github.com/sherpa/sherpa/issues/248

**Comment by joleroi** [comment]
I introduced a dirty hack to avoid the sherpa issue - merging this

**Pull request merged**
