### PR TITLE
Sort sampled events by time in `MapDatasetEventSampler`

### PR DESCRIPTION
**Pull request by fabiopintore**
This PR fixes the issue #5429 .
It allows to simulate a realistic event list, with the times of the events sorted.

### CODE REVIEW

**Review by AtreyeeS — APPROVED** [review]
Thank you @fabiopintore ! No comments from my side

**Review by cgalelli — APPROVED** [review]
Thanks @fabiopintore

**Review by registerrier — APPROVED** [review]
Thanks @fabiopintore . Looks good to me.

**Comment by registerrier** [comment]
CI fail is unrelated. Merging.

**Pull request merged**
