### PR TITLE
Fixing docstring for stat_sum in several dataset class

### PR DESCRIPTION
**Pull request by MRegeard**
The docstring for `stat_sum`in sevral dataset class was saying "Likelihood", which is misleading. 

Fixed by replacing it by "statistic function value". 

Question: Do we stick to this also in `Dataset` which says "Total statistic"?

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @MRegeard, indeed this was misleading. Could even add the correct definition of `stat = -2 * log(L)`... what do you think @registerrier ?

**Comment by MRegeard** [comment]
> Thanks @MRegeard, indeed this was misleading. Could even add the correct definition of `stat = -2 * log(L)`... what do you think @registerrier ?

But from what I understand it's not even a proper Likelihood, because it is not normalised, right ?

**Comment by registerrier** [comment]
> > Thanks @MRegeard, indeed this was misleading. Could even add the correct definition of `stat = -2 * log(L)`... what do you think @registerrier ?
> 
> But from what I understand it's not even a proper Likelihood, because it is not normalised, right ?

Well it is defined as `-2 log(L) + cst` strictly speaking. 
I think it is fine like this.

**Review by registerrier — APPROVED** [review]
Thanks @MRegeard ! Looks good.

**Review by adonath — APPROVED** [review]
No further comments from my side either.

**Comment by registerrier** [comment]
CI fail is unrelated. Merging.

**Pull request merged**
