### PR TITLE
Grouping

### PR DESCRIPTION
**Pull request by joleroi**
This continues https://github.com/gammapy/gammapy/pull/471

### CODE REVIEW

**Comment by joleroi** [comment]
Since I don't have access to leas modifies test files I will mark test as failing

**Comment by joleroi** [comment]
There are still some fails but I am pretty sure they are due to bugs in the ObservationGroups class. But I don't find an open PR dealing with this. @cdeil Have you updated the ObservationsGroups class already?

**Comment by cdeil** [comment]
Yes, the ObservationGroups class is heavily modified in #468.
If you need it here, you'll have to wait for that to go in first.
I'll try to finish it up ASAP (~2 hours).

**Comment by joleroi** [comment]
Yes the grouping functionality is used here, and I get strange test failures that look like the bugs you've described offline. I'll wait

**Pull request closed without merging**
