### PR TITLE
If statement bug in pointing

### LINKED ISSUE #4914: Miswritten if condition in pointing.py
**Gammapy version**
gammapy 1.1

**Bug description**
Miswritten if condition (never enter the elif) in gammapy/data/pointing.py

```
if self.mode is PointingMode.POINTING:
            header["OBS_MODE"] = "POINTING"
            header["RA_PNT"] = self.fixed_icrs.ra.deg, u.deg.to_string("fits")
            header["DEC_PNT"] = self.fixed_icrs.dec.deg, u.deg.to_string("fits")
elif self.mode is PointingMode.POINTING:
            header["OBS_MODE"] = "DRIFT"
            header["AZ_PNT"] = self.fixed_altaz.az.deg, u.deg.to_string("fits")
            header["ALT_PNT"] = self.fixed_altaz.alt.deg, u.deg.to_string("fits")
```

`elif self.mode is PointingMode.POINTING` should likely be `elif self.mode is PointingMode.DRIFT`

**Other information**
Also in the dev version :
https://github.com/gammapy/gammapy/blob/daa25abce5d6ff081ba332d5d24a86f2b7a2aa2c/gammapy/data/pointing.py#L303C1-L311C1

### PR DESCRIPTION
**Pull request by MRegeard**
This PR fix #4914.

### CODE REVIEW

**Comment by Astro-Kirsty** [comment]
Thanks @MRegeard. 
Do we have a test for this? If not, I guess one should be added

**Comment by maxnoe** [comment]
Obviously wrong before... so obvious that it probably should have been caught in review... sorry

**Comment by maxnoe** [comment]
Test for drift data (even an artificial one) would be good, yes

**Review by registerrier — COMMENTED** [review]
Thanks @MRegeard !

Could you add a test simply creating two `PointingMode` and making sure that the header contains the required keywords? Or add the to_header test in each of the test in `test_fixed_pointing_icrs` and `test_fixed_pointing_altaz`?

Indeed this was completely missed during the review. Albeit there were two positive reviews...

**Review by maxnoe — APPROVED** [review]

**Review by registerrier — APPROVED** [review]
Thanks @MRegeard . Looks good.

**Pull request merged**
