### PR TITLE
Add simple model language

### PR DESCRIPTION
**Pull request by joleroi**
This is a proposal for a simple model language

It supports simple operations like
```
pwl + 2 * logpar
```

No connected parameters and fancy stuff. It should, however, cover most use cases, e.g. #1060 

TODO
* [x] Make CompoundModels Fittable

### CODE REVIEW

**Comment by joleroi** [comment]
@jjlk - would this cover your EBL absorption studies?

**Comment by jjlk** [comment]
Hi @joleroi , 
For the EBL studies I need to link parameters between models, e.g hyp1 * exp(-alpha * E) + hyp2 * exp(-alpha * E) where alpha is commun to the models (with the sherpa parameter function `link`). 

In addition, I need to be able to attribut datasets to models, e.g., hyp1 *exp(-alpha * E) will be fitted on dataset1 and so on (with the `sh.set_source(id, 'model')`).

**Comment by joleroi** [comment]
So after all, this does not seem to be super useful, but could be a starting point. @cdeil @adonath I let you vote if we should merge this or not.

**Comment by cdeil** [comment]
I'm +1 to merge this in, to push forward with `gammapy.utils.modeling` and see how good we can make it, with the understanding that modeling will be a major topic of development and discussion for the coming year, and what we merge now doesn't have to be in Gammapy for the coming years.

My reasoning for this is that if we have the modeling under our control, we can be bold and use backends like https://scikit-optimize.github.io or even https://www.tensorflow.org with the potential to run on CPU clusters or GPUs and be 100x faster than what we have now. I'm not saying we will or should do this necessarily, but IMO at this point it's easier to develop `gammapy.utils.modeling` and treat Sherpa as one fitting backend. Already doing 3D analysis with Sherpa or joint Fermi-IACT fitting or XML model I/O or other things we want **now** is cumbersome with Sherpa.

I'd like to merge all open PRs in and do a Gammapy 0.7 release next week. @joleroi - Is this PR ready from your side? Can you please rebase it and see if tests still pass to make trying it out / collaboration easier? After that, I can do a code review or take over if you don't have time.

**Comment by joleroi** [comment]
@cdeil Is [this](https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.2630/job/gi2wwj07o74uh56o#L616) a known issue?

**Comment by cdeil** [comment]
> @cdeil Is this a known issue?

I introduced it yesterday evening and saw it just now. I'll fix it now. It's an `ü` character in a `.py` file, which is not allowed by default on Python 2.

**Comment by joleroi** [comment]
> It's an ü character in a .py file

god help us :scream_cat:

**Comment by joleroi** [comment]
The remaining failures are unrelated to this PR, merging

**Pull request merged**
