### PR TITLE
Changes to gammapy.spectrum

### PR DESCRIPTION
**Pull request by joleroi**
* [x] Integrate grouping code
* [x] Add functionality to write configfiles (usefull for debugging e.g. pipeline analysis)
* [x] Use Obstable consistently to store meta info

### CODE REVIEW

**Comment by joleroi** [comment]
https://travis-ci.org/gammapy/gammapy/jobs/113736146#L1909

This fail looks unrelated to this PR. I cannot reproduce it locally. Ideas?

**Comment by cdeil** [comment]
@joleroi - Yes, the libgfortran install issue is completely unrelated to this PR.
This is an attempt to fix it: #483

**Comment by joleroi** [comment]
so can I merge?

**Comment by cdeil** [comment]
I'm not sure the cached dict to index `OBS_ID` is a good idea.
Are the common or edge cases where the table changes without a new one being created?
I.e. can the cached index get out of sync with the main table?

Probably a better way to implement this would be to put an index on that column:
http://astropy.readthedocs.org/en/latest/table/indexing.html

I haven't tried this, and there's other code that uses a dict on the side to index a table in the same way [here](https://gammapy.readthedocs.org/en/latest/api/gammapy.catalog.SourceCatalog.html).

So OK to merge for now, but maybe add a TODO entry saying that the use of http://astropy.readthedocs.org/en/latest/table/indexing.html here should be investigated?
(unless you want to try this now.)

**Comment by joleroi** [comment]
The warning on top of

http://astropy.readthedocs.org/en/latest/table/indexing.html

seems reasonable to me. I encountered some strange thing very quickly. I guess we should wait until the indexing stuff is more stable. I will add a TODO for now.

**Pull request merged**
