### PR TITLE
Fixing the test on `plot_distribution`

### PR DESCRIPTION
**Pull request by MRegeard**
It appears that the test on `plot_distribution` was failing in some case. Since it was not failing locally, the only thing I could think of was the random draw. Therefore I use a seed for the random draw.

### CODE REVIEW

**Review by bkhelifi — APPROVED** [review]
Thanks @MRegeard ... I hope that the CI will work whatever the OS

**Review by AtreyeeS — APPROVED** [review]
Thanks @MRegeard ! I don't know if `nfev` is a good parameter to assert on. It reflects the number of evaluations of the objective function, so it might vary depending on the machine or the OS. An assert on the `param` would be more physical.

The other test fail seems unrelated. The caplog is picking some other warning before the gammapy warning I think.

**Comment by MRegeard** [comment]
> Thanks @MRegeard ! I don't know if `nfev` is a good parameter to assert on. It reflects the number of evaluations of the objective function, so it might vary depending on the machine or the OS. An assert on the `param` would be more physical.
> 
> The other test fail seems unrelated. The caplog is picking some other warning before the gammapy warning I think.

It's true that now that you say it, it si probably not a very good idea to test nfev.
For the test on `param`, at the beginning I was test the parameter and the covariance matrix, but they were not the same depending on the OS. However, now that I am using a seed for the random drawing, I guess the parameter and covariance matrix may be more stable.

**Comment by AtreyeeS** [comment]
> For the test on `param`, at the beginning I was test the parameter and the covariance matrix, but they were not the same depending on the OS. 

The `param` should be `[0,1]` within a given tolerance (1% on the mean and ~2% on the sigma I think). Just put a relatively high `rtol` around 5% in the assert

**Pull request merged**
