### PR TITLE
WIP: Add Wstat to gammapy.stats

### PR DESCRIPTION
**Pull request by joleroi**
* This add the WStat statistic as described in 
https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html 
to ``gammapy.stats``.

Note that another implementation using exactly the same notation as for XSPEC exists here
https://github.com/gammapy/gammapy/blob/master/dev/sherpa/stats/xspec_stats.py

* This PR also add tests comparing the existing stats to sherpa

### CODE REVIEW

**Comment by joleroi** [comment]
The comparison to Sherpa is off by a few percent fot WStat. Under investigation :rotating_light:

**Comment by cdeil** [comment]
> The comparison to Sherpa is off by a few percent fot WStat. Under investigation

Is this for one bin or a sum?
When calling sum for large arrays it's always important to put `dtype=np.float64`, to make sure the accumulator is 64 bit.

**Comment by cdeil** [comment]
I would prefer to have automatic tests that just assert some reference numbers and don't import Sherpa.
Then have a script e.g. in `dev/sherpa/stats` that computes the reference numbers with Sherpa and prints them to the console, and link to it from the test.

This way Gammapy and tests are more independent of Sherpa, and Gammapy tests don't start breaking when there's an issue with Sherpa stats results (although it could be argued if that is a good or bad thing).

**Comment by cdeil** [comment]
Thanks for adding this. I've assigned myself for review.

There's several typos: `prediced` -> `predicted`.

Can we please spend some time to discuss variable names and description, to make sure it's good?
The starting point is the description here: https://gammapy.readthedocs.io/en/latest/stats/index.html#introduction

I've tried to use this consistently `mu_something` as the ML estimate for observed `n_something`.
This gets a bit fishy for excess and background though, because `alpha * n_off` could be seen both as the "observed" background for one observation (depends on data `n_off`) and as the ML estimate `mu_background` for the background.

Specifically let's discuss these two points:

1. you changed `mu_observed` to `mu_expected`. The old logic was that `mu_observed` is the expected value for `n_observed`. With `mu_expected` this symmetry in `n_` and `mu_` that's used for the on/off stats variable names is gone. I'm not sure this is a good change, but I  don't feel strongly either way.

2. the other question I have is what `n_bkg` is in the `wstat` call. The docstring just says "Background counts". Is that `n_off`? If yes, can we call it `n_off`? If no ... can you put a better description?

I don't know if you want to do it in this PR, but another change that would be nice would be if all the stat docstrings (like [cash](https://gammapy.readthedocs.io/en/latest/api/gammapy.stats.cash.html)) had a reference back to the high-level docs page like as first bullet in the list of references:
```
* For further explanations on statistics and meaning of the variables, see :ref:`stats`
```
(or create extra labels that even more closely link to the relevant definitions in the high-level docs)

**Comment by joleroi** [comment]
> I would prefer to have automatic tests that just assert some reference numbers and don't import Sherpa.

I see you're point but I don't think I will have time to change this. I can leave a TODO.

> I don't know if you want to do it in this PR, but another change that would be nice would be if all the stat docstrings had a reference back to the high-level docs page like as first bullet in the list of references:

:+1: 

> Is this for one bin or a sum?

For the sum. Sherpa does not provide bin-wise values. You noticed this [here](https://github.com/gammapy/gammapy/blob/b6d3671a2ecdc36f6c12dcee6f5098c137d1c123/dev/sherpa/stats/sherpa_stats_compute_direct.py#L13). I couldn't figure out what ``fvec`` is (the quadratic some as you suggest neither gives the overall stat).

> you changed mu_observed to mu_expected

I though it was super confusing, especially since all subscripts are written out in the formulars, e.g. [here](https://gammapy.readthedocs.io/en/latest/api/gammapy.stats.cash.html#gammapy.stats.cash). For me all symbol in this equation look the same. There is anyway no symmetry when it comes to ``n_on`` vs. ``mu_signal`` and ``mu_background`` unless we introduce ``mu_on == mu_signal + mu_background``. 
So I would leave ``mu_expected``

> the other question I have is what n_bkg is in the wstat call.

It's ``alpha * n_off`, Introduced ``n_bkg`` in the high level docs [here](https://github.com/gammapy/gammapy/pull/600/files#diff-62667baecdb4a375b929df588c82ad99R34), but I can make a more explicit docstring

**Comment by joleroi** [comment]
As discussed offline the WStat definition of XSPEC
https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html
is no exactly what should be used for hess (since signal and background region differ).
This might be the reason for the discrepancy.

**Comment by joleroi** [comment]
> In any case, no need for further review on this ... please merge whenever you want and then I'll have a look next week.

OK!

**Comment by cdeil** [comment]
Typos: https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=prediced

**Comment by cdeil** [comment]
I would suggest to change the argument order to for consistency:
```
n_on, n_off, alpha, mu_signal
```
Most (all?) of the other functions in `gammapy.stats` have the observed counts and especially `n_on` first.

**Pull request merged**
