### PR TITLE
Remove use of NDDataArray from  CountsSpectrum

### PR DESCRIPTION
**Pull request by adonath**
This PR removes the use of `NDDataArray` from the `CountsSpectrum` class and makes `CountsSpectrum.data` a plain `np.ndarray`. This simplifies the data access, without loosing any functionality and makes the API more uniform with the `Map` object.

### CODE REVIEW

**Comment by cdeil** [comment]
Docstring says:
```
    data : `~astropy.units.Quantity`, array-like
        Counts
```
Actually it was a `NDDataArray` and now it's a `numpy.ndarray` and the `unit` attribute isn't documented.

Shouldn't a spectrum have an energy axis?

OK to go this way if you think it's best, then just fix the class-level docstring.

**Comment by adonath** [comment]
Thanks @cdeil! I cleaned-up the docstring and a few more callers to `CountSpectrum.data.data`. Note the `CountsSpectrum` has an energy axis (represented by a `MapAxis`) defined under the `CountsSpectrum.energy` attribute (that is for historical reasons...).

**Comment by cdeil** [comment]
So the energy grid is stored twice, and probably half of the callers use `counts.energy` and the other `counts.energy_lo`, `counts.energy_hi`? Get rid of `counts.energy_lo` and `counts.energy_hi`?

**Comment by adonath** [comment]
No, `CountsSpectrum.energy_hi` and `CountsSpectrum.energy_lo` does not exist, it is just used in `__init__`, to create a `MapAxis` object (again for historical reasons...).

**Comment by registerrier** [comment]
Sorry to comment a bit late. Unifying the data access API is indeed a good thing. Another approach, more complex though, could have been to make `CountsSpectrum` a `NDDataArray` directly, no?
This is the main difference with our usages of `Map`, where all the objects are directly `Maps`. Each time we have a `NDDataArray` there is another layer of object containing it.

**Comment by adonath** [comment]
@registerrier If you take a look at the current state of the code, the `NDDataArray` does not really offer anything useful. It is used to bundle the data axes and setup the `ScaledRegularGridInterpolator`. I also think it has the fundamental design mistake of giving up numpy broadcasting in `.evaluate()`. It's completely clear to me, that the current `Map` design is much better. 

Midterm my much preferred solution would be to get completely rid of `NDDataArray` and replace it with a `Map` like data structure, that does not require a spatial axis.  This can then be used for spectra and IRFs as well. In that sense the `NDDataArray` is almost this kind of data structure, maybe it could be refactored as well...

**Pull request merged**
