### PR TITLE
Validate nside parameter for HpxGeom 

### PR DESCRIPTION
**Pull request by luca-giunti**
**Description**

This pull request solves #4006

### CODE REVIEW

**Comment by luca-giunti** [comment]
I just realized that the proposed solution creates problems because it relies on a function contained in `healpy`, which is not a mandatory dependency: 
`from healpy.pixelfunc import check_nside`

Should I copy-paste that function in a `HpxGeom._check_nside()` mehod? It's a pity because it, looks like this, not trivial
```
    if hasattr(nside, "__len__"):
        if not isinstance(nside, np.ndarray):
            nside = np.asarray(nside)
        is_nside_ok = (
            (nside == nside.astype(int)) & (nside > 0) & (nside <= max_nside)
        )
        if nest:
            is_nside_ok &= (nside.astype(int) & (nside.astype(int) - 1)) == 0
    else:
        is_nside_ok = nside == int(nside) and 0 < nside <= max_nside
        if nest:
            is_nside_ok = is_nside_ok and (int(nside) & (int(nside) - 1)) == 0
    return is_nside_ok
```

**Comment by adonath** [comment]
@luca-giunti Just use a delayed import, like:

```python3

def __init__(self, ..):
    from healpy.pixelfunc import check_nside
```

Healpy is required anyway when working with HEALPix maps...

**Comment by registerrier** [comment]
You might need the `@require_dependency` decorator for the test though

**Comment by luca-giunti** [comment]
> You might need the `@require_dependency` decorator for the test though

@registerrier is that really needed? There is an overall `pytest.importorskip("healpy")` in the test file

**Review by registerrier — APPROVED** [review]
Thanks @luca-giunti . This looks good.

**Review by adonath — APPROVED** [review]
Thanks @luca-giunti!, looks good to me as well!

**Pull request merged**
