### PR TITLE
Fix SkyMap.reproject() and .fill() methods

### PR DESCRIPTION
**Pull request by adonath**
This PR fixes a few remaining issues with the `SkyMap` class:
* fix `.reproject()` and add a minimal test
* fix `.fill()` method, allow float values and add test
* remove duplicated and unused binning functions from `EventList`

@cdeil It would be great to still get this in 0.4, or is it too late?

### CODE REVIEW

**Comment by cdeil** [comment]
Thanks!

This can go in 0.4 ... I also still want to work on the Getting Started docs today before I make the release.

If you have more time ... I think SkyMap.plot is untested and broken. I tried using it [here](https://github.com/gammapy/gammapy-extra/blob/master/notebooks/gammapy-image-crab.ipynb) and got an error.

**Comment by cdeil** [comment]
There's a fail for `test_spectrum` on three travis-ci builds:
https://travis-ci.org/gammapy/gammapy/jobs/124414698#L1549

I don't see it locally and don't see a change in gammapy-extra that would cause it, and this is with Astropy 1.1.2. So I don't understand why this is happening.

**Comment by adonath** [comment]
I'll look into it. Can I modify the crab notebook or do you have any un-comitted changes...?

**Comment by cdeil** [comment]
> Can I modify the crab notebook or do you have any un-comitted changes...?

Go head, no uncommitted changes.
Lunch?

**Comment by joleroi** [comment]
Thanks!

**Pull request merged**
