### PR TITLE
Improved analysis_3d.ipynb

### PR DESCRIPTION
**Pull request by IAMinaya**
Hi!

In the Madrid Gammapy sprint code I modified the "analysis_3d.ipynb" tutorial notebook to add the galactic diffuse emission subtraction to our model in order to get a better agreement between 1DC input and model fit (with Axel's help). I have used some files from the DC1 (complete gps/index and cube_iem.fits) so the $CTADATA environment is needed (I have also added link to the DC1 website with information about how to download files and set environment variables).

I think this could be interesting to show how to treat different models at the same time and how to deal with diffuse emission as well, not only bright sources.

Thanks!

Ignacio Minaya

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @IAMinaya, I think this is a very nice addition to the notebook. Ideally we could put a small cut-out of the  diffuse emission model in `gammapy-extra`. Is this possible @cdeil?

**Comment by Bultako** [comment]
My problem with this notebook is not only that it needs a really big dataset (not provided by `gammapy download`) , but overall that it takes too much time to execute /test (around 15 min). So it is difficult to deliver it as part of the documentation /tutorials.  
```
gammapy jupyter --src notebook/analysis_3d.ipynb test
INFO:gammapy.scripts.jupyter:   ... TESTING notebook/analysis_3d.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 14.41 mn
INFO:gammapy.scripts.jupyter:   ... PASSED
```
The published version of `analysis_3d.ipynb` executes in nearly half a minute.
 ```
 TESTING notebooks-0.9.dev7580/analysis_3d.ipynb
INFO:gammapy.scripts.jupyter:   ... Executing duration: 0.58 mn
INFO:gammapy.scripts.jupyter:   ... PASSED
```

I think the doc building process in the whole should not take more than a few minutes. The doc building process needs to run the notebooks in order to fill the output cells and also check that there are not broken notebooks. With this version I guess we could easily get to ~20 min when building the docs.

@IAMinaya Does it make sense to work with a much more reduced list of observations? Or do you have any other ideas to speed up the execution time? It is the Mapmaker of all these observations that takes 5 min of the execution time of the notebook. 

captura de pantalla 2018-10-08 a las 17 33 23

and then 6 more minutes when fitting with the counts of all the observations.
captura de pantalla 2018-10-08 a las 17 39 42

I would also try with a cut-out of the diffuse emission model, just to check that it is not the big file for the diffuse model that slows the execution time (though I'm afraid it also counts), but I don't know how to get this cut-out. Maybe also reducing the offset in the Mapmaker? Any idea to speed up the notebook is welcome.

We already have a few notebooks needing datasets not delivered by `$GAMMAPY_DATA`, (i.e. fermi_lat.ipynb, spectrum_pipe.ipynb, sed_fitting_gammacat_fermi.ipynb) For me, that's not a blocking point at this moment to publish this notebook.

Anyway, if you guys think that this updated version is highly valuable we can go forward and live with it.

**Comment by IAMinaya** [comment]
You are completely right @Bultako ,if I am not wrong I think that in some part of the notebook I mentioned something like "a cut-off in the image would speed things up" because it is indeed too slow... 

I used the whole GPS dataset and the complete diffuse emission map just to be sure that the results were not limited by a small number of observations, but it is true that we don't really need to load the complete cube_iem.fits.gz file (almost 800Mb) for this analysis. If "forcing" the user to download extra datasets (as in some of the Fermi tutorials) is not the preferred option then I would try with a cut-off of the cube to see how fast it gets (actually, it was the first suggestion of @adonath), but I don't know how to do it right now, I would need to take a look and see if I figure it out (my Gammapy knowledge is limited, I warned you!). 

Another solution that Axel suggested was leaving the notebook as it was at the beginning but adding all the new stuff at the end, saying something like "if you want to improve the analysis considering the galactic diffuse emission and a larger dataset you can download the DC1 files and run the following cells", so the user could run the basics without downloading anything else, and if they want to deepen into the analysis then they can follow the DC1 instructions. It is kind of an intermediate solution, so it sounds good to me.

Let's see what @cdeil thinks about it and we can make a final decision.

**Comment by cdeil** [comment]
@IAMinaya - thank you for your pull request!

This is tricky. Of course we would like to have a better tutorial also showing how to model the diffuse. But yes, we want tutorial notebooks to work just with public and relatively small data files, and to run fast, both so that the Gammapy continuous integration and docs build remains fast (should be made faster, not slower), and because new users need an example that runs quickly to learn and be able to play with parameters.

So I'm -1 to access non-public `CTADATA` from Gammapy tutorial notebooks like in the change you do here.

Note that cutting out part of a diffuse model sky map is easy with Gammapy. That's what we did for the Fermi-LAT example:
https://github.com/gammapy/gammapy-extra/blob/master/datasets/fermi_3fhl/make.py
http://docs.gammapy.org/0.8/notebooks/fermi_lat.html
We could in principle load that diffuse model and use it for IACT example notebooks, although I'm not sure if the extrapolation beyond the last energy node will work, i.e. evaluating that Fermi-LAT diffuse model at TeV energies might give an error. But that can be worked around or fiexed.

Note that the CTA 1DC sky model is not public. I asked for DC-1 to be open beyond CTAC and this request was rejected. We can't just do a cutout of `$CTADATA/models/cube_iem.fits.gz` and distribute it publicly. So bottom line, I don't think we should use it in Gammapy tutorials. Once CTA sets up a Confluence or other means of having internal documentation, we can do CTA specific Gammapy tutorials and share them with the CTA consortium members (maybe in 2019).

If you still have time for Gammapy and want to try to use `datasets/fermi_3fhl/gll_iem_v06_cutout.fits` or try to prepare a new diffuse model somehow (e.g. take some public gas image and assume a power-law spectrum with index 2.6), that is possible. I think if you keep everything in the notebook as-is (i.e. just the 3 runs that process quickly), and just add that model component with a free norm parameter, the fit should still run quickly.

**Comment by IAMinaya** [comment]
Thanks @cdeil . OK, I get it! it makes sense... so no DC-1 data in the notebook yet, I will keep it for those CTA specific tutorials when (if) they are released in the future. But anyway I think that it could be interesting to update this notebook to add the diffuse emission even for a simple case, so the user knows how to deal with it, how to update a model with different components, etc. without searching in different notebooks.

One idea could be doing the same as I have but with the original small data sample and the cutoff diffuse map from Fermi. Obviously, the results are not so "impressive" as in the case of the 1DC dataset + CTA diffuse map, but still could be useful as a tutorial. 

These are the residuals and fit results I get with my previous update:

cta_comparison

And these are the results only using original dataset and Fermi diffuse (note that the left fit is the original PowerLaw but the right one is modified to the ExponentialCutOffPowerLaw just to make it "more realistic"):

short_comparison

The red line could be suppressed from these plots if needed.

As an extra suggestion(/question), if it is possible without breaking any rule, it could be good to add at the end of the notebook the first picture shown here (using the 1DC data) just as a way to show that, even if the residuals are only a bit better in this case, if this analysis is performed using CTA datasets and models the results get much better (but I don't know if showing only the plots or even the red line is as wrong as making the dataset public... so no idea if this could be possible or not).

Cheers!

**Comment by cdeil** [comment]
@IAMinaya - This GC analysis is really nice, thanks for posting!

But no, we can't post it publicly, that's DC-1 and CTA internal.

Note that GC is one of the analysis being done for tools check (see [here](https://forge.in2p3.fr/projects/data-challenge-1-dc-1/wiki/DC-1_tool_assessment_-_GC) and [here](https://github.com/gammasky/cta-analyses/blob/master/dc-1-checks/gc/notebooks/GC_3D_fit.ipynb)) Two months ago @registerrier ran a 3D analysis for GC with Gammapy and at the time it wasn't working well yet, but looking at your plots above now it clearly does.

So @registerrier and @robertazanin - would it be helpful if @IAMinaya posts scripts or notebooks there (e.g. in a new sub-folder) with the Gammapy 3D GC analysis? Or will someone else take care of this and it doesn't help to add someone new to the task so late in the game?

**Comment by IAMinaya** [comment]
OK! So... I think that the safest way to go then is to update the notebook with the diffuse model (just to show the procedure) but using only the original files that already exist for the other tutorials, and in parallel I will share the complete notebook with the DC-1 results through the gammasky repository. Does that sound good to all of you?

I will make a new commit tomorrow with these changes and we can decide. If not, then I will start the plan B: paying some tapas in Granada to @Bultako will help to reach an agreement...

**Comment by Bultako** [comment]
Independently of the decision taken relative to add this notebook to `gammasky` repo, I think the plots shown by @IAMinaya are appealing enough to be shown in the notebook. I like one of the suggestions made above:

> Another solution that Axel suggested was leaving the notebook as it was at the beginning but  adding all the new stuff at the end, saying something like "if you want to improve the analysis  considering the galactic diffuse emission and a larger dataset you can download the DC1 files and  run the following cells", so the user could run the basics without downloading anything else, and  if they want to deepen into the analysis then they can follow the DC1 instructions. It is kind of an  intermediate solution, so it sounds good to me. 

In addition, we could show the plots as static png images stored in the `tutorials/images` folder, we already serve notebooks with static images. So, this **static addition** of code and plots could be seen as a small non-interactive part at the end of the notebook, useful and appealing for gammapy users.

**Comment by dcfidalgo** [comment]
Just to put my 2 cents in, IMO a static addition to notebooks where interactivity is not possible, sounds like a very good idea. I think we should make use of the tutorials not only to cover the basics, but also to show the users what Gammapy is capable of.

**Comment by cdeil** [comment]
At first I was going to say 👎 to have nice GC analysis images from CTA DC-1 in Gammapy docs, because really given that DC-1 isn't public, I don't feel it's our place to produce and share such images publicly via the Gammapy docs. But I see that's actually done in the ctools docs [here](http://cta.irap.omp.eu/ctools/users/tutorials/1dc/first_fitting.html), and in CTA there's no concrete paper or project you could join to put this. Maybe papers in a year or two, maybe not.

I'm not a huge fan of static images in the tutorial notebooks. It's not so nice to give people just the image, and not show how it was made. Plus we have to ship them as PNGs in the code repo here: https://github.com/gammapy/gammapy/tree/master/tutorials/images

So overall, after this discussion, I'd suggest this:
- Make a small addition to `analysis_3d` or `simulate_3d` showing one example how to work with a diffuse model. If it just works, use the Fermi diffuse model I mentioned earlier. It's key that it doesn't slow down too much, we should rather aim to have quicker example notebooks than slower ones.
- Share your notebook accessing `$CTADATA` publicly with the nice results and images, and then we link to it at the start and / or end of some of the existing notebooks, e.g. `analysis_3d` and `cta_data_analysis`. The privacy concern is alleviated by the fact that ctools did the same. The problem that the notebook will break as we change the Gammapy code is still there. But there's not much we can do for notebooks that access GB of data and take an hour or more to run. We can only post it separately, say this is a notebook for v0.8, and then maybe update it after v0.9 comes out, but not test and run it for every pull request to the Gammapy repo.
- One place where you could put it is in gammapy-extra. Note that we already have https://github.com/gammapy/gammapy-extra/tree/master/figures/time which has a long-running analysis and makes a nice figure that is then shown and the example explained here: https://docs.gammapy.org/dev/time/period.html One solution might be to have a list or script of these "extra" parts of the documentation somewhere, so that maintainers can check and update them e.g. before making a new release (i.e. every ~ 2 months moving forward).
- Another option would be to put it in https://github.com/gammapy/gammapy-paper and to have it as one of the application examples, and that repo will be fixed to Gammapy v0.9 and we want nice Figures there. But we kind of already discussed whether to use DC-1 there, and decided to avoid it and not write that paper "for the CTA consortium". But we did decide to put something very similar as CTA application example (see [here](https://github.com/gammapy/gammapy-paper/blob/master/text/3.1-cta.tex)) and to simulate GC data using code similar to `simulation_3d`. So @IAMinaya - If you have time in the coming weeks and would be interested to do that application example, let me know and we would start with a short call to develop the exact proposal what sky model and pointings to put for that simulation. But since you've already written the notebook for DC-1 and have good results, and we probably do want to have that in the Gammapy docs and maintain it, let's do the last suggestion and put it in `gammapy-extra`, at least for now.

**Comment by Bultako** [comment]
Ok.
I raise my hand now for a bit of controversy ;-)

> I'm not a huge fan of static images in the tutorial notebooks. It's not so nice to give people just the image, and not show how it was made. 

I think it's understandable for this case, where proprietary data are used, to stick a small static part (in addition of the link to the notebook using CTADATA in `gammapy-extra`)

We should not forget that notebooks are not only scripts to run, they are also used to build appealing documentation. Couldn't they be used to advertise (and not only document) the awesome gammapy capabilities? Or should we only stick to RST files for static docs? 

This reminds me about a suggestion I was told in the last coding sprint, related with adding at the end (even as static snippets of code) the results of the exercises proposed in the notebooks. 

Maybe we should also think in publishing (or advertising/linking to) examples of longish-run gammapy python scripts, together with the results, as part of the documentation? For example, give some visibility to the work done in `gamma-sky` for those wanted to use gammapy in *.py scripts.

Well, I'm afraid the discussion has slightly drifted to other topics, sorry for that..

**Comment by cdeil** [comment]
@Bultako - What exactly is your suggestion?

Is there something different or more we could do, apart from putting a nice notebook with output cells filled and nice plots in `gammapy-extra/analyses/cta-1dc-gc`, and linking to it prominently from the documentation?

I guess we could pull that into the docs build to have it on `docs.gammapy.org`, but then it's more work for you to set up, to have some notebooks that aren't executed, just converted to HTML. And we have the same version-coupling issue again and have to commit to update it at the very least before every stable Gammapy release.

Yes, having a Python script based tutorial would be very nice and important. I guess that would be an RST page pointing to Python scripts that are also shipped via `gammapy download tutorials`?

I'm a bit 👎 to just add more docs and tutorials, because we already have a lot of them and many aren't in great shape, and the more we add the more effort it is for developers and maintainers to update them in the coming months as the Gammapy package evolves. Note that https://docs.gammapy.org/0.8/notebooks/cta_1dc_introduction.html and https://docs.gammapy.org/0.8/notebooks/cta_data_analysis.html aren't in great shape already, really we need someone that spends a few weeks on developing a good plan (a PIG) for content and organisation of docs and tutorials that we want for Gammapy 1.0 in fall 2019, and then in the coming months works step by step towards this goal, helping update docs as the code and package evolve over the coming year.

That said: this DC-1 GC analysis is very nice, we should share and advertise it somehow. If you guys are available for the weekly Gammapy call Friday 10 am, we could discuss / decide the things discussed here.

**Comment by cdeil** [comment]
Oh, if the suggestion was just to also add nice results images in the Gammapy docs, we could do it like here: https://docs.gammapy.org/dev/time/period.html
That doesn't work for notebooks, so there, it's not my preference, but if you want to add one or two more PNG in https://github.com/gammapy/gammapy/tree/master/tutorials/images and include them in the notebooks, OK, we can do that.

**Comment by Bultako** [comment]
> but if you want to add one or two more PNG in https://github.com/gammapy/gammapy/tree/master/tutorials/images and include them in the notebooks, OK, we can do that.

Yep, that was my suggestion, just to show a small glimpse of what you will find in the `gammapy-extra` notebook, and not only to its link. 

In general I agree with the rest, and I support the idea of downloading also *.py scripts. Yes, content and organization of docs is something that would have to be addressed in a PIG 🐷

**Comment by cdeil** [comment]
Superseded by #1884 . Closing this PR now.

**Pull request closed without merging**
