### PR TITLE
Add support for astropy 6.0.0rc1

### PR DESCRIPTION
**Pull request by maxnoe**
**Description**

This pull request ...

**Dear reviewer**

### CODE REVIEW

**Comment by registerrier** [comment]
Thanks @maxnoe ! Indeed we have an issue with the coming astropy v6

**Comment by maxnoe** [comment]
This seems mostly to be related with the removal for support of adding unit-less quantities to times.

In astropy 5.x, this was always interpreted as days, astropy v6 raises an error and requires units.

**Comment by AtreyeeS** [comment]
The issue is in adding an empty list to a Time object

```
start = [] * u.s
reference_time + u.Quantity(start)
```

This give the error `Unsupported operand type(s) for ufunc add: 'Time,Quantity'`

This breaks most of our tests because creating an empty dataset calls `GTI.create` with an empty `start` and `stop` list.

If the `start` list is non empty, there is no problem.

To solve this, we can change the default to `[0]*u.s`. @registerrier @bkhelifi @maxnoe @adonath

**Comment by maxnoe** [comment]
@AtreyeeS the old behavior was to create an empty time object:

```
>>> Time.now() + [] * u.s
<Time object: scale='utc' format='datetime' value=[]>
```

So you could do:

```
start = self.reference_time + start if len(start) > 0 else Time([], format='mjd')
```

**Comment by registerrier** [comment]
This is now corrected in astropy. devdeps is now running. 
See https://github.com/astropy/astropy/pull/15604

Thanks @maxnoe !

**Comment by registerrier** [comment]
CI is now running with devdeps. Closing now. Thanks @maxnoe

**Pull request closed without merging**
