### PR TITLE
Fix HowTo accordions

### LINKED ISSUE #5523: HowTo link to tutorials broken
In the dev version when you go to the [HowTo](https://docs.gammapy.org/dev/user-guide/howto.html#how-to) you cannot click on the links to the tutorials. It only makes the dropdown initiate!

### PR DESCRIPTION
**Pull request by Astro-Kirsty**
This resolves #5523

It was not as easy as I expected, I tried many solutions but this one the only that worked to have it how we had before. 
When running the docs each time I had to do `make clean-repo` for the changes to be effective, therefore it took a very long time to run this each time. 
I am trying to find a cleaner solution.

Screenshot from 2024-10-24 16-23-50

### CODE REVIEW

**Review by bkhelifi — DISMISSED** [review]
Let's try it! Thanks

**Comment by bkhelifi** [comment]
@Astro-Kirsty, when you have open a topics, can you close it by clicking on the + (-) button? It was the case before....

**Comment by morcuended** [comment]
Thanks @Astro-Kirsty! It works like a charm.

> @Astro-Kirsty, when you have open a topics, can you close it by clicking on the + (-) button? It was the case before....

For me, it works like this: clicking the "(+) Title of HowTo" part again closes it.

**Review by morcuended — APPROVED** [review]
Thanks @Astro-Kirsty

**Review by QRemy — APPROVED** [review]
Thanks no further comments

**Pull request merged**
