### PR TITLE
Execute notebooks in parallel

### PR DESCRIPTION
**Pull request by maxnoe**
**Description**

This pull request parallelizes the notebook execution

### CODE REVIEW

**Comment by maxnoe** [comment]
Executing the notebooks in in parallel gives us the exact factor of two speed up. Notebooks now only take 6 minutes in the CI (+2min setup time)

**Review by adonath — APPROVED** [review]
Thanks @maxnoe, no comments from my side.

**Comment by Bultako** [comment]
Thanks @maxnoe, it works nicely !

I guess we should do the same with `utils.notebook_process-py` which is used in `gammapy-docs` github repository to build the documentation. Sure, this would go in another PR, we have to improve the CI speed also in `gammapy-docs` repo.

**Review by Bultako — APPROVED** [review]

**Comment by adonath** [comment]
CI file is unrelated. Will go ahead and merge...

**Pull request merged**
