### PR TITLE
Change css and conf to allow for smaller screens

### LINKED ISSUE #5196: Docs display on small window sizes broken
**Gammapy version**

Current main.

**Bug description**

The documentation does not behave correctly on window size transitions anymore.

Comparing current dev docs with the Gammapy 1.2 docs:

### Gammapy 1.2
old_small_gammapy

### Gammapy dev

gammapy_new_small

**Expected behavior**
Correctly adapt content to window size

**To Reproduce**

Visit dev docs, decrease window width

### PR DESCRIPTION
**Pull request by Astro-Kirsty**
This makes some changes to fixes #5196
I also adjust the number of headers along the top

In the end utilising the default works well, however, it causes other issues! :( 
Actually our css is quite complicated (and it should not be!), we can work on that further for v2.0

### CODE REVIEW

**Comment by Astro-Kirsty** [comment]
This is a temporary fix. As shown here it works but the secondary sidebar is still visible. 
(It doesn't however overlap with the content which is good)
Screenshot from 2024-11-18 15-52-27

image

**Comment by Astro-Kirsty** [comment]
Screenshot from 2024-11-18 15-52-27
Screenshot from 2024-11-18 15-52-33

**Comment by bkhelifi** [comment]
It looks rather good now, is not it? If there is remaining issue, you can add a small issue as reminder.
Thanks a lot @Astro-Kirsty !!!

**Review by bkhelifi — APPROVED** [review]
Thanks a million

**Review by registerrier — APPROVED** [review]
Thanks @Astro-Kirsty . Looks good. Let's have a look at the dev docs.

**Pull request merged**
