### PR TITLE
Fix get index of a PLSuperExpCutoff spectral model (fermi catalog)

### PR DESCRIPTION
**Pull request by aaguasca**
**Description**

This pull request fixes the error when using `.info()` on a `SourceCatalogObject4FGL` object with a PLSuperExpCutoff spectral model. This error is caused due to the missing key  "PLEC_Index" in a PLSuperExpCutoff spectral model.

**Dear reviewer**

The PR is ready for review.

### CODE REVIEW

**Review by bkhelifi — COMMENTED** [review]
Thank you very much. Tests are missing such that it will not happen anymore. All the if conditions should at least be well covered.

**Comment by aaguasca** [comment]
> Tests are missing such that it will not happen anymore

I can take care of the tests. I would follow the approach in [test_info()](https://github.com/gammapy/gammapy/blob/a6b1bc23f9bb0eaffc140f38efaf85b7ba204e87/gammapy/irf/psf/tests/test_parametric.py#L21). Should I do it in this PR or an additional one?

> All the if conditions should at least be well covered.

Do you mean moving the step to get the spectral index information on each spec_type conditional?

**Comment by Astro-Kirsty** [comment]
> I can take care of the tests. I would follow the approach in [test_info()](https://github.com/gammapy/gammapy/blob/a6b1bc23f9bb0eaffc140f38efaf85b7ba204e87/gammapy/irf/psf/tests/test_parametric.py#L21). Should I do it in this PR or an additional one?

Please add the tests to this PR

**Comment by bkhelifi** [comment]
@aaguasca  can you update your branch and check the tests?

**Comment by aaguasca** [comment]
Sorry for the delay! I adapted the test for 4FGL DR4 to check `.info()` works through `.__str__()`.

**Review by QRemy — APPROVED** [review]
Thanks no further comment.

**Review by bkhelifi — APPROVED** [review]
Thank you a lot. Looks good

**Pull request merged**
