### PR TITLE
Add template generation of quickstart in documentation

### PR DESCRIPTION
**Pull request by registerrier**
**Description**

This pull request is a proposal to help simplify the release process w.r.t. doc generation.

- First the Makefile is modified to avoid the necessity of performing part of step 3 described in dev doc:
```
In the 0.14/docs/_downloads folder, rename notebooks-dev.tar file as notebooks-0.14.tar.
```
- Second a python script is added to generate the quick start and gammapy download sections of the getting started
  - The section is included for a release but not for a dev version. This avoids the inconsistency with the versioning in the dev doc.
- Third the Makefile is adapted to automatically create the files before compiling the doc.

**Dear reviewer**

This is a proposal two remove two manual steps in the release process. It is a first step towards a possible automation of the doc deployment.

Some of the solutions proposed are not ideal e.g. having the text of the quick start in a python script is not very intuitive.

Note that it is not possible to use the sphinx substitution mechanism in the `code-block` hence the proposal to programmatically generate the code block. 

Note that this requires testing. But I am not sure where to put the tests.

### CODE REVIEW

**Comment by registerrier** [comment]
Here is what is generated by `make docs-sphinx release=0.20.1`:
Capture d’écran 2022-06-20 à 21 45 41

Here is what generated by `make docs-sphinx`:
Capture d’écran 2022-06-20 à 21 49 03

**Comment by adonath** [comment]
Thanks @registerrier! What about https://stackoverflow.com/questions/44761197/how-to-use-substitution-definitions-with-code-blocks?

**Comment by adonath** [comment]
And then we introduce a `|stable-release|` substitution which is automatically generated from `version`?

**Comment by registerrier** [comment]
See an alternative implementation following @adonath suggestion in #4004

**Comment by registerrier** [comment]
Closing now. Superseded by #4004

**Pull request closed without merging**
