### PR TITLE
Use mamba in CI jobs

### PR DESCRIPTION
**Pull request by maxnoe**
Add options to `setup-miniconda` to use mamba

### CODE REVIEW

**Comment by maxnoe** [comment]
The time for "Updating and activating environment" is down from 32 minutes in the previous run (17 minutes on master, seems to vary a lot) to 2 minutes for the notebook / all other build

**Comment by maxnoe** [comment]
The last run for the notebooks without mamba even took 46 minutes:
Screenshot_20220117_165932

**Comment by adonath** [comment]
Thanks @maxnoe! Partly addresses #3614.

**Review by adonath — APPROVED** [review]
No comments from my side...

**Review by Bultako — APPROVED** [review]

**Review by registerrier — APPROVED** [review]
Thanks @maxnoe !

**Pull request merged**
