### PR TITLE
Updating astropy-helpers to 2.0.5

### LINKED ISSUE #1248: Gammapy test fails with Python 2 and Numpy 1.14
We have a bunch of CI fails that are all Python 2 and appeared with the recent Numpy 1.14 release:
https://travis-ci.org/gammapy/gammapy/builds/328225839

I've looked through them, and they are all due to one bug that was introduced in `np.einsum`, see my comments here https://github.com/astropy/astropy/issues/7051#issuecomment-357468791
It's already fixed in Numpy master (see https://github.com/numpy/numpy/pull/10371), but I'm not sure if that will go out via Numpy 1.14.1 and if so when that will be.

I'm not sure how to get a green CI build again with minimal effort. @bsipocz - Would pinning Python 2 CI builds to Numpy 1.13 be easy to achieve? I think adding skip or xfail markers for all the tests that fail on Python 2 now would be a bit annoying, but of course that could be done as well.

### PR DESCRIPTION
**Pull request by bsipocz**
~DO NOT MERGE YET~

~This is to test the top of the 2.0.x branch of the helpers to see whether it indeed fixes #1248~

This now has the actual 2.0.3 release of the helpers and can be merged when tests pass.

### CODE REVIEW

**Comment by cdeil** [comment]
There is a weird failure here:
https://travis-ci.org/gammapy/gammapy/jobs/330482318#L2408

```
[1m============================= test session starts ==============================[0m
platform linux2 -- Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /home/travis/miniconda/envs/test/bin/python
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/main.py", line 103, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/_pytest/terminal.py", line 390, in pytest_sessionstart
INTERNALERROR>     config=self.config, startdir=self.startdir)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/tests/pytest_plugins.py", line 182, in pytest_report_header
INTERNALERROR>     module = resolve_name(module_name)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/utils/introspection.py", line 80, in resolve_name
INTERNALERROR>     ret = __import__(str('.'.join(module_name)), fromlist=fromlist)
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/uncertainties/__init__.py", line 224, in <module>
INTERNALERROR>     from .core import *
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/uncertainties/core.py", line 946, in <module>
INTERNALERROR>     ord(sup): normal for (normal, sup) in TO_SUPERSCRIPT.items()}
INTERNALERROR>   File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/uncertainties/core.py", line 946, in <dictcomp>
INTERNALERROR>     ord(sup): normal for (normal, sup) in TO_SUPERSCRIPT.items()}
INTERNALERROR> TypeError: ord() expected a character, but string of length 3 found
```

The error is triggered by the unicode characters in uncertainties being passed to `ord`:
https://github.com/lebigot/uncertainties/blob/7112a2faeaccea7d458951cf86ad5902ef6bbb39/uncertainties/core.py#L925
which is imported via an `__import__` from `astropy.utils.introspection` which is called from `pytest_report_header`.

I don't understand and am not able to trigger that issue locally. E.g. this works for me:
```
$ python2
>>> from uncertainties.core import TO_SUPERSCRIPT
>>> TO_SUPERSCRIPT
{43: u'\u207a', 45: u'\u207b', 48: u'\u2070', 49: u'\xb9', 50: u'\xb2', 51: u'\xb3', 52: u'\u2074', 53: u'\u2075', 54: u'\u2076', 55: u'\u2077', 56: u'\u2078', 57: u'\u2079'}
>>> {ord(sup): normal for (normal, sup) in TO_SUPERSCRIPT.items()}
{8304: 48, 178: 50, 179: 51, 8308: 52, 8309: 53, 8310: 54, 8311: 55, 8312: 56, 185: 49, 8314: 43, 8315: 45, 8313: 57}
```
and I also tried an `__import('uncertainties')` directly from the repl, a py file and the py file executed via pytest.

So my guess is that there is a subtle bug in `astropy.utils.introspection` or `astropy.tests.pytest_plugins` (but could also be in `pytest` itself or `uncertainties` that only occurs when executing that code in a special mode (pytest does some magic, `__import__` does some more).

One thing that is striking is that this only appears now for the first time. I don't see any changes in astropy-helpers that touch this. @bsipocz or maybe @astrofrog - any thoughts on what might be going on here or how to reproduce the issue locally?

**Comment by bsipocz** [comment]
OK, so my suspect was that conda-forge is used, and usually takes precedent. Running the test suite using only defaults (and astropy and sherpa) channels, I couldn't reproduce this very same error, but see some other test failures:
https://travis-ci.org/bsipocz/gammapy/jobs/330788282

**Comment by drdavella** [comment]
@bsipocz you are correct. When I install the package `uncertainties` from `conda-forge` instead of using `pip`, I can reproduce the error.

It seems pretty clear that this is a problem in the `uncertainties` package since just doing `import uncertainties` will fail under Python 2.

**Comment by cdeil** [comment]
@drdavella - Thank you very much!
Can you please report in the uncertainties tracker and link to this issue?

**Comment by bsipocz** [comment]
@drdavella - Thanks for checking. This case, I'll go ahead with the release and will recycle this PR to update for that one.

**Comment by cdeil** [comment]
The uncertainties issue from conda-forge should now be resolved:
https://github.com/conda-forge/uncertainties-feedstock/pull/12

@bsipocz - I'd like to cut the Gammapy 0.7 release early next week.

Can this update to astropy-helpers go in?
I don't think there's any fix that we really need, but if the update now works, maybe best to put it in and wrap up this PR, no?

**Comment by bsipocz** [comment]
@cdeil - This update will be needed until you support python2.7 (otherwise the helpers will try to pick up the 3.0 release that is python3 only). I'll update it asap to have the actual release.

**Comment by cdeil** [comment]
Then this is a blocker for the Gammapy v0.7 release. I put that as milestone.
@bsipocz - Thank you for your work on this!
Let me know if there's anything I can do to help this along next week.

**Comment by bsipocz** [comment]
@cdeil - This should be good to go now. If there is still some testing issues it should be unrelated to the helpers, at least I very much hope so.

**Comment by cdeil** [comment]
There's still the Numpy 1.14.0 bug that will be fixed in the upcoming Numpy 1.14.1 release causing Python 2 builds to fail: https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.2997/job/2cmg90s10lw7lof0

Maybe we'll just hold off on this PR and the Gammapy 0.7 release until next week, they said that Numpy 1.14.1 should come out end of January.

**Comment by bsipocz** [comment]
@cdeil - You run into that via astropy, and the new 2.0.4 release should have a workaround. (2.0.4 will be released along with 3.0, asap the new RC testing goes well, hopefully next week, too.)

**Comment by cdeil** [comment]
@bsipocz - If possible, I'd like to do the Gammapy 0.7 release tomorrow. I still don't understand if / why this PR is important. From the diff, I don't see any important fixes in the astropy-helpers.

The upstream issues in Astropy and Numpy are independent of Gammapy, and will resolve the few test fails we currently have on Python 2.7.

?

**Comment by bsipocz** [comment]
If you don't have this update, then the builds will try to pick up the latest astropy helpers release, that is python3 only. This was the critical fix: https://github.com/astropy/astropy-helpers/pull/362

But I agree that it's safe to do a release as the upstream issues will be fixed soon.

I got to run now (my 🚋 is about to arrive), but will have a look later tonight, and let you know how far we're with the new astropy release.

**Comment by cdeil** [comment]
If I understand correctly, Python 2 users might have an issue in rare circumstances.
It's a risk I'm willing to take, moving this issue to the Gammapy 0.8 milestone and starting the 0.7 release stuff now ...

**Comment by bsipocz** [comment]
@cdeil - I think they will see this all the time they try to build gammapy. Though probably it's fine if it's installed from a wheel/conda (but yet again you probably will run into issues trying to build those wheels in the first place)

**Comment by bsipocz** [comment]
@cdeil - The 2.0.4 release is out, though it may take a few days until it becomes available on the default conda channels. Even though the tests are still failing, this should be safe to merge now.

**Comment by cdeil** [comment]
@bsipocz - could you please just do the astropy-helpers update here, and remove the changing turning Python 2.7 tests on travis-ci on again, which are holding up this PR?

Now that https://pypi.python.org/pypi/Sphinx/1.7.0 is out, Gammapy devs (cc @labsaha) are running into this issue when doing `python setup.py build_docs`: https://github.com/astropy/sphinx-automodapi/pull/43

**Comment by cdeil** [comment]
Just a note that a Numpy release is not out that should fix the einsum bug: https://github.com/numpy/numpy/releases/tag/v1.14.1
There's no conda-forge package yet (see https://anaconda.org/conda-forge/numpy) but probably in a few days it'll be there and then the Python 2 build should work again.

**Comment by bsipocz** [comment]
@cdeil - removed the py2 changes, but now this is running into the cython issue, too.

We're about to release a very quick helpers with a workaround once Tom manages to make it pass our tests...

**Comment by cdeil** [comment]
@bsipocz - we really need a release from Gammapy ASAP.

Do you have time to update here, or should I try?
Do we want astropy-helpers 2.0.5 or 3.0.1? (we're still supporting Python 2 in Gammapy)

**Comment by bsipocz** [comment]
@cdeil - I plan to do automated updates this afternoon, but since this is already open did the update to 2.0.5 now.

Bottom line is that packages should stay on 2.0.x as long as they support python2. And we won't do automated updates for the 3.0.x series only after packages opted into it.

**Comment by bsipocz** [comment]
@cdeil - New failure may be numpy 1.14.1 related, but definitely not helpers update issues (that was just released and we had issues with it with astropy, too).
Do you want me to try adding back the py2 tests and see how that commit behaves?

**Comment by cdeil** [comment]
Yes, please add py2 back. I'll have a look at this later today. We also have one test broken in master. I'll fix that non-helpers related stuff.

**Comment by cdeil** [comment]
I've xfailed the unrelated fail in 7691457f in master. Restarting CI here now. I think all is good, but let's see.

**Comment by cdeil** [comment]
This is the most green I've seen in a long time. @bsipocz - Thanks!

Any idea how to fix this?
```
RuntimeError: Test dependencies are missing. You should install the 'pytest-astropy' package.
```
https://travis-ci.org/gammapy/gammapy/jobs/345220391#L2543

And what about this?
```
/home/travis/build/gammapy/gammapy/astropy_helpers/astropy_helpers/setup_helpers.py:390: AstropyDeprecationWarning: Use of the exclude parameter is no longer supported since it does not work as expected. Use add_exclude_packages instead. Note that it must be called prior to any other calls from setup helpers.
```
https://travis-ci.org/gammapy/gammapy/jobs/345220375#L1128

The other errors / warnings I understand - will fix those now and add a commit here.

**Comment by cdeil** [comment]
I've re-started the docs builds, those should pass now.

There's still the two issues mentioned in my last comment that I don't know how to resolve. @bsipocz ?

**Comment by astrofrog** [comment]
> RuntimeError: Test dependencies are missing. You should install the 'pytest-astropy' package.

Add pytest-astropy to the ``CONDA_DEPENDENCIES`` (@bsipocz, should we just install that by default on ci-helpers?)

**Comment by astrofrog** [comment]
@drdavella - can you comment on this:

> /home/travis/build/gammapy/gammapy/astropy_helpers/astropy_helpers/setup_helpers.py:390: AstropyDeprecationWarning: Use of the exclude parameter is no longer supported since it does not work as expected. Use add_exclude_packages instead. Note that it must be called prior to any other calls from setup helpers.

What needs changing here?

**Comment by drdavella** [comment]
@astrofrog I just tried to reproduce this locally in a conda environment with no luck. There's no evidence that gammapy's `setup.py` is using this deprecated behavior. The only thing I can think of is the concern I mentioned to you earlier this week: is it possible that another package that is a dependency of gammapy has an older version of `astropy_helpers`, which is overriding this version?

This warning is not currently causing any hard failures, correct?

**Comment by drdavella** [comment]
Actually the issue was that `astropy_helpers` itself was using the deprecated behavior. This is fixed in https://github.com/astropy/astropy-helpers/pull/379. Since it's just a warning, and since `gammapy` itself is not using the deprecated behavior, this shouldn't hold up the release, imo.

**Comment by bsipocz** [comment]
@astrofrog - yes, it should be installed and already had a commit in of the WIP ci-helpers PR for it. I aim to wrap those up soonish.

**Pull request merged**
