### PR TITLE
Regenerate name to avoid starting with underscore

### PR DESCRIPTION
**Pull request by QRemy**
Prevent a random fail in the CI when auto-generated name start with underscore :
FAILED ..\..\.tox\py310-test-alldeps_noray\lib\site-packages\gammapy\visualization\tests\test_datasets.py::test_plot_spectrum_datasets_off_regions - matplotlib._api.deprecation.MatplotlibDeprecationWarning: An artist whose label starts with an underscore was passed to legend(); such artists will no longer be ignored in the future.  To suppress this warning, explicitly filter out such artists, e.g. with `[art for art in artists if not art.get_label().startswith('_')]`.

This should fix the break seen in #4759.

### CODE REVIEW

**Comment by bkhelifi** [comment]
The CI fails because of  `ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities`. But this is unrelated to this PR.

**Review by bkhelifi — APPROVED** [review]
Thanks @QRemy

**Comment by QRemy** [comment]
> The CI fails because of `ModuleNotFoundError: No module named 'astropy.coordinates.angle_utilities`. But this is unrelated to this PR.

I tried to fix that direclty in this PR but I could open an other one instead.

**Review by registerrier — APPROVED** [review]
Thanks @QRemy. This looks good.

I think having the angular_utilities change in another PR would be better. But this can go as is.
This part of the PR can be backported too to ensure CI runs on bugfix branches with future versions.

**Pull request merged**
