### PR TITLE
css for sphinx v15

### PR DESCRIPTION
**Pull request by stahanna**
**Description**

This pull request ...

**Dear reviewer**

### CODE REVIEW

**Comment by registerrier** [comment]
You can check the result here  : https://stahanna.github.io/gammapy-docs-preview/

**Comment by cgalelli** [comment]
My situation with the dark theme: 
Capture d’écran 2024-03-08 à 14 28 32

**Comment by adonath** [comment]
Thanks, @cgalelli! I guess this is completely expected, our CSS and images are not suited for a dark theme. It would require much more work to adapt it...

**Comment by Astro-Kirsty** [comment]
Thanks @stahanna 

Here are my comments:
- various drop down menus do not actually drop down
	- https://stahanna.github.io/gammapy-docs-preview/getting-started/index.html#tutorials-overview
	- https://stahanna.github.io/gammapy-docs-preview/user-guide/howto.html
- on the right hand side it should show what is available on the page, but the font appears to be in white, so it does not show (see screen shot). This is happening on every page
image

**Review by registerrier — COMMENTED** [review]
Thanks @stahanna ! Good to see that the accordion issue is solved.

Some additional comments:
- the top bar background is gray. Could it be white for better readibility?
- the top bar does not show all menu items at once. Can it be broadened?
- the font could be a bit larger

**Comment by bkhelifi** [comment]
Thanks a lot @stahanna ... It looks nice.
I have a simple question. In the API page (https://stahanna.github.io/gammapy-docs-preview/api-reference/index.html), it seems that the dots are not present. Do you see the same with your browser?

**Comment by stahanna** [comment]
@bkhelifi I checked the pandas documentation and they miss the ::marker as well in the API section (already since the v 1.5) not sure if I can fix it easily then

**Review by registerrier — APPROVED** [review]
Thanks @stahanna . This looks good.

We decided in the dev call to go ahead and merge this PR now. Further changes will be done in follow-up PRs.

**Comment by registerrier** [comment]
CI fail is unrelated. Merging now.

**Comment by maxnoe** [comment]
@registerrier The CI failure is *NOT* unrelated: the conda based CI fails precisely due to the changes in `environment-dev.yaml` in this PR.

**Pull request merged**
