### PR TITLE
Add SpectrumObservationStacker

### PR DESCRIPTION
**Pull request by joleroi**
This PR
* [x] refactors the ``stack`` method on SpectrumObservation into a stand-alone class ``SpectrumObservationStacker``
* [x] add some test to ``test_observation`` because some functions where not tested/buggy

This was needed since the function required counts vectors, aeff, and edisp to be present which is not always the case. The class can stack all objects independently and is thus reusable for flux points computation methods (where one counts have to be stacked)

### CODE REVIEW

**Comment by cdeil** [comment]
Do you think it should be part of the public Gammapy API?
I.e. should it be listed in `__all__` and appear in the docs?
Or will only few people need to use it directly?

Is there something specific I should review?
I'm very short on time, and generally +1 to put such algorithms in separate classes if they consist of several steps.

**Comment by joleroi** [comment]
> Or will only few people need to use it directly?

I guess I could be hidden in the public API (and exposed via a ``stack`` function on SpectrumObservationList)

> Is there something specific I should review?

I guess it's fine, I will remove the class from the public API and then merge if tests pass

**Comment by cdeil** [comment]
I'm 50:50 on whether such classes should be part of the public API.

For experts it's nice to be able to find and read via the docs how spectral analysis works.
The concern is that beginners will get lost with too many classes.

Maybe we should err on the side of having many things in the API docs, at least for now?
One advantage would be that then the docstrings are built by Sphinx and checked for syntax / formatting.

Looking at the current docs for this class:
https://github.com/joleroi/gammapy/blob/c5d121c2a866ee0c603393281ca2393519e84b77/gammapy/spectrum/observation.py#L434
I think it would be good to have a little more in the class-level docstring.
Ideally a usage example that shows how to execute an example and access the results.
(my main point is that one has to read the code at the moment to find out what results are available, having that mentioned in the docstring, or putting them as properties that are computed on access would make this better, no?

**Comment by joleroi** [comment]
> Maybe we should err on the side of having many things in the API docs, at least for now?

I don't really care. But I'd tend to have rather too much than too little stuff in the API. For beginners we `just` need to make nice tutorial notebooks

> I think it would be good to have a little more in the class-level docstring.

Done

**Pull request merged**
