### PR TITLE
Use Sherpa class interface in SpectrumFit

### PR DESCRIPTION
**Pull request by joleroi**
* [x] add to_sherpa methods to IRF classes and PHACountsSpectrum class
* [x] Reproduce test results using the sherpa class interface
* [x] Add old sessions based fit as example to the docs

This is important since otherwise the only valid input for a spectral fit are PHA files (not SpectrumObservation instances)

### CODE REVIEW

**Comment by joleroi** [comment]
The ``SpectrumFit`` class cannot be removed since it does non-obvious stuff, like bringing the sherpa optimizers in a valid energy range and handling the sherpa data correctly. It will transform into a thin wrapper around ``sherpa.fit.Fit`` though. Nothing else is in scope for this class.

**Comment by joleroi** [comment]
@cdeil @adonath Ready for review

**Comment by cdeil** [comment]
This PR contains partially the same commits as #671.
I left comments there.
Probably I should have looked at this one first?

**Comment by joleroi** [comment]
No. the other one was the first in stack. Sorry I should have left a WIP.

**Comment by joleroi** [comment]
Yes, but don't worry I will apply your comments to this one!

**Comment by joleroi** [comment]
I adressed the comments @cdeil  left in https://github.com/gammapy/gammapy/pull/671. Does someone want to test this, or can I merge?

**Comment by adonath** [comment]
Looks good to me, no further comments...

**Pull request merged**
