### PR TITLE
Fix spectrum fit for case of no EDISP

### PR DESCRIPTION
**Pull request by joleroi**
@cdeil This fixes your issue

### CODE REVIEW

**Comment by joleroi** [comment]
@cdeil Thanks, I can't reproduce the error locally, can such a large deviation just be due to a different architecture?

**Comment by cdeil** [comment]
You have `index=2.296`, on travis-ci `index=2.302`, the difference is `0.006`. I would say this is a small, not a large numerical difference, it's easily possibly that the optimiser stops a little differently on different machines / compilers.

So my suggestion would be to put `atol=0.02` here (to have some margin for extra error on other machines / compilers).

**Comment by cdeil** [comment]
Remaining travis-ci fails for Astropy dev version are from `gammapy.astro`, completely unrelated.
Merging this now.

@joleroi - Thanks!

**Comment by cdeil** [comment]
Unrelated fails in master should be fixed by https://github.com/gammapy/gammapy/commit/cc5b77bbc9f95e560ca4f24b4aa957341f6089b9 now.

**Pull request merged**
