### PR TITLE
Remove elements deprecated in version 1.2 before version 1.3

### PR DESCRIPTION
**Pull request by QRemy**
Remove elements deprecated in version 1.2 before version 1.3

### CODE REVIEW

**Comment by QRemy** [comment]
There is a number of `GammapyDeprecationWarning` related to pointing in 
`gammapy.data.pointing` and `gammapy.data.observations` without version indication, what should we do about them ?

**Review by bkhelifi — APPROVED** [review]
Thanks a lot, @QRemy . It was needed

**Comment by bkhelifi** [comment]
Some tests are still failing, @QRemy

**Comment by QRemy** [comment]
missing 

```
    is_norm = deprecated_attribute("is_norm", "1.2")
    norm_min = deprecated_attribute("norm_min", "1.2")
    norm_max = deprecated_attribute("norm_max", "1.2")
    norm_n_values = deprecated_attribute("norm_n_values", "1.2")
    norm_values = deprecated_attribute("norm_values", "1.2")
```

**Comment by registerrier** [comment]
Apparently the gaussian line custom spectral model in the Models API tutorials is failing. The amplitude parameter is defined with an is_norm argument. For some reason, we did not have a deprecation warning on the docs...

**Comment by QRemy** [comment]
Ready now.

**Review by bkhelifi — APPROVED** [review]
Thank you very much

**Pull request merged**
