### PR TITLE
Fix Wstat

### PR DESCRIPTION
**Pull request by joleroi**
There was a bug in 

https://github.com/gammapy/gammapy/blob/master/dev/sherpa/stats/xspec_stats.py

and the same one in 

https://github.com/gammapy/gammapy/blob/master/gammapy/stats/fit_statistics.py

This PR fixes this and updates all examples and docs

### CODE REVIEW

**Comment by joleroi** [comment]
see https://github.com/sherpa/sherpa/issues/314

**Comment by cdeil** [comment]
@joleroi - Thanks!

@registerrier - Could you please review the WSTAT values for `n_on=0` and `n_off=0` cases in the table at the end of this section?
http://docs.gammapy.org/en/latest/stats/fit_statistics.html#poisson-data-with-background-measurement
Is that correct?

@joleroi and @registerrier  - Are Gammapy WSTAT results now consistent with XSPEC or Sherpa results? I think it would be good to know if that's the case, and either way add a note to the Gammapy docs page?

**Comment by joleroi** [comment]
> @joleroi and @registerrier - Are Gammapy WSTAT results now consistent with XSPEC or Sherpa results?

Yes they agree with Sherpa

see https://github.com/gammapy/gammapy/blob/master/dev/sherpa/stats/compare_wstat.py
and https://github.com/gammapy/gammapy/blob/master/gammapy/stats/tests/test_fit_statistics.py

For XSPEC we don't know, because we only have the implementation you added to ``dev`` 

https://github.com/gammapy/gammapy/blob/master/dev/sherpa/stats/xspec_stats.py

and we don't know if it's correct or not :wink: (but for now it looks fine)

**Comment by cdeil** [comment]
@registerrier - Do you know how to run XSPEC directly to check? I guess people are still commonly using it, and it is relevant to know if Gammapy / Sherpa is the same or not, right?

**Comment by registerrier** [comment]
I am not sure the tests described above can be done in an easy way with XSPEC. 

I would say that as long as we understand what we put in and we have agreement with sherpa, we are fine. No?

**Comment by cdeil** [comment]
@registerrier - My understanding is that Sherpa WSTAT is new and not very well tested / documented (see e.g. https://github.com/sherpa/sherpa/issues/314).
So a comparison with XSPEC or other codes, and a derivation of our formul, especially for the WSTAT for bins with `n_on=0` or `n_off=0`, would be good.

But yes, if it's not easy to do with XSPEC, and our results are consistent with Sherpa and based on well-checked formulas, it's good enough. @registerrier - I was mainly pinging you to review the formulas and description in this docs section one last time (before WSTAT is ready for 1.0 and publication):
http://docs.gammapy.org/en/latest/stats/fit_statistics.html#poisson-data-with-background-measurement

**Pull request merged**
