### PR TITLE
Generalise instrument response classes

### PR DESCRIPTION
**Pull request by kbruegge**
This replaces all the code in the irf subpackage except for the PSF related stuff. 
Use like this.
```
from gammapy.irf import InstrumentResponse
irf = InstrumentResponse.from_fits(path, extension='EFFECTIVE AREA')
point = {'THETA': 3.5*u.deg, 'ENERG': 1*u.TeV}
interpolated_result = irf.evaluate(point)
```

### CODE REVIEW

**Comment by joleroi** [comment]
@mackaiver  I don't have much time to review things at the moment, but I would be interested in the discussion that led to this PR, since it potentially has quite a large impact.

What exactly do you mean by 'replace'? This PR certainly only adds code so it's not obvious to me. If you mean we should get rid of all the old IRFs classes I wonder where you want to put all the IRFs-specific functionalty. e.g. [this](http://docs.gammapy.org/dev/api/gammapy.irf.EnergyDispersion2D.html#gammapy.irf.EnergyDispersion2D.to_energy_dispersion ) and [that](http://docs.gammapy.org/dev/api/gammapy.irf.EffectiveAreaTable.html#gammapy.irf.EffectiveAreaTable.from_parametrization)

**Comment by kosack** [comment]
I think I can answer that: The idea of this is just to replace a huge amount of boilerplate code for IRF reading with something more generic - so far it does not replace anything, since it would be a larger effort to migrate existing classes to use a common IRF reading framework. 

The main driver is that fact that IRFs will evolve, with new dimensions added, and this makes that trivial (the dimensionality + which columns of an event form a point in the phase space are defined at run-time, rather than being hard-coded).

So in principle, this could replace a lot of existing code and make future IRFs easier, once it is deemed to work equivalently.

**Comment by mackaiver** [comment]
See  #1298

**Comment by mackaiver** [comment]
Also d932ae0 seems to add unfinished code.

**Comment by cdeil** [comment]
Yes, I added unfinished code in d932ae0 . The thing is, I don't want to merge this as-is, without knowing if the scheme works / is useful to replace our existing IRF functionality. For me, d932ae0 is the direction to go, so I put it here in case you or someone else wants to continue. I'll be back at work Wednesday next week and can then come back to this.

**Comment by adonath** [comment]
Potentially the `Map` class in `gammapy,.maps` can be extended / generalised to also be used for IRF handling. While this PR goes in the right direction, there was no activity since ~2 years and I think currently there is no interest / time to continue the work. 

In general the re-factoring of `gammapy.irf` is a larger task and should probably be planned with a short PIG document first. I'll go ahead and close the PR now....

**Pull request closed without merging**
