### PR TITLE
Add first version of Phasogram class

### PR DESCRIPTION
**Pull request by msjacob**
Work in progress, do not merge.

### CODE REVIEW

**Comment by cdeil** [comment]
Here's the example we had from this morning, with an idea how to handle multiple pulsars:
https://gist.github.com/cdeil/f068cf487fbcff657cc014c64909f0b8

My suggestion would be that you add a page `docs/time/pulsar.rst` and start writing documentation there, showing this as an example how to handle multiple pulsars (as opposed to making something in the Gammapy code to handle multiple pulsars, at least for now).

**Comment by cdeil** [comment]
@msjacob @dcfidalgo - What should we do here?

Maybe close PR without merging?

This is a pull request from @msjacob  from Feb 2017. I think we wanted to do it as a "practice" PR to learn the coding workflow, and the idea was to maybe attach phasogram-based psr detection methods to this class later. Do you think we should have a `gammapy.time.Phasogram` class that basically wraps a `astropy.table.Table`? Or would it be better to directly use `Table` to store a phasogram where needed?

**Comment by msjacob** [comment]
Hello !
Yes, I’m closing this ! I don’t think there was ever a use for a Phasogram class, I didn’t really know where I was going with this at the time, as you said it was during a practice session to learn how to contribute to Gammapy.
A phasogram is really just a normal histogram. I think the phases should just be stored in a new column when it’s needed, and then users can make a histogram of any parameter they want.

**Comment by cdeil** [comment]
@msjacob - Makes sense. Thanks!

**Pull request closed without merging**
