### PR TITLE
Display progress bars in Analysis, Fit methods and Estimator classes

### PR DESCRIPTION
**Pull request by luca-giunti**
**Description**
I used `tqdm` to provide a progress bar in Analysis, Fit methods and Estimator classes.

In some places, there are warnings that break the progress bar, namely:
```
In: analysis_1d.get_datasets()
Out:
  0%|          | 0/4 [00:00<?, ?it/s]No background model defined for dataset cMBPsezR


 25%|██▌       | 1/4 [00:00<00:00,  3.24it/s]No background model defined for dataset gdLztbDM


 50%|█████     | 2/4 [00:00<00:00,  3.30it/s]No background model defined for dataset SQLYi5zW


 75%|███████▌  | 3/4 [00:00<00:00,  3.36it/s]No background model defined for dataset IeRiDiuG


100%|██████████| 4/4 [00:01<00:00,  3.41it/s]
```
In these cases, I guess we should probably display all the warnings after the progress bar is closed, but I wouldn't know how... 

**Dear reviewer**
In my local machine, I get a weird error when I test `pytest gammapy/analysis/test_analysis.py`: a very long traceback ending in `ValueError: I/O operation on closed file`. Hopefully someone knows how to fix this...

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @luca-giunti! I already have a few general comments:

Please move the `show_pbar` to the `__init__` methods and make it a class argument, so that it becomes configurable in future. Maybe also choose a more explicit name such as `show_progress`, or `show_progress_bar`. I would also prefer the default to be `show_progress=False`, because in many cases (and most places in our tutorials) the execution is fast and one does not really need to know the progress, if something takes just a few seconds.

In general we need to think a bit about what is useful to show as progress (energy bins, pixels, parameters, etc.) and maybe document it with a prefix / suffix to the progress bar. We also have to see what we do with nested loops.

It seems `tqdm` has an `auto` submodule, which chooses a nicer visualisation when working in notebooks:
```python
from tqdm.auto import trange
from time import sleep

for i in trange(4, desc='1st loop'):
    for j in trange(5, desc='2nd loop'):
        for k in trange(50, desc='3rd loop', leave=False):
            sleep(0.01)
```
In general I'm not sure we should introduce `tqdm` as a required dependency, maybe we just treat as optional, so when its installed, users get a progress bar if not, they don't. But Ideally we can handle this in one single place. I'll think about it once more...

**Comment by luca-giunti** [comment]
> Thanks @luca-giunti! I already have a few general comments:
> 
> Please move the `show_pbar` to the `__init__` methods and make it a class argument, so that it becomes configurable in future. Maybe also choose a more explicit name such as `show_progress`, or `show_progress_bar`. I would also prefer the default to be `show_progress=False`, because in many cases (and most places in our tutorials) the execution is fast and one does not really need to know the progress, if something takes just a few seconds.
> 
Agreed!
> In general we need to think a bit about what is useful to show as progress (energy bins, pixels, parameters, etc.) and maybe document it with a prefix / suffix to the progress bar. We also have to see what we do with nested loops.

Ideed. I agree we should document the "units" of the progress (i.e. energy bin, dataset, ...) on the bar itself. It's actually easy with `tqdm(desc="")`.  I will add this.

Regarding the nested loops, in this PR I just assumed that people would always be interested on the most external layer. For example, calling `LightCurveEstimator.run()` would display the progess over time bins, but not the progress of the `stat_profile()` that is called within each single bin. I think this is a reasonable guess, but I am open to different ideas.



> It seems `tqdm` has an `auto` submodule, which chooses a nicer visualisation when working in notebooks:
> 
> ```python
> from tqdm.auto import trange
> from time import sleep
> 
> for i in trange(4, desc='1st loop'):
>     for j in trange(5, desc='2nd loop'):
>         for k in trange(50, desc='3rd loop', leave=False):
>             sleep(0.01)
> ```
I tried this, but than I tested in a jupyter lab nb and the bar was not rendered. Apparently, one needs the ipywidgets jlab extension to be installed (read the FAQ at the bottom of this [page](https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension)). Is it still OK to use it?

> In general I'm not sure we should introduce `tqdm` as a required dependency, maybe we just treat as optional, so when its installed, users get a progress bar if not, they don't. But Ideally we can handle this in one single place. I'll think about it once more...

Fine, let me know about that!

In general, we have to agree on a coherent list of functions and methods that can (optionally) be called with a `show_progress_bar=True` option. For the moment, in my PR I considered:
- `Fit.stat_profile()`, `Fit.stat_contour()` methods
- the following estimators: `ASmoothMapEstimator`, `ExcessMapEstimator`, `ExcessProfileEstimator`, `FluxPointsEstimator`, `LightCurveEstimator`, `ParameterEstimator`
- the following `Analysis` methods: `._map_making()`, `_spectrum_extraction`

These are basically the places where I could spot potentially time consuming `for` loops. If you have others in mind, please comment. I also thought about adding `Datastore.get_observations()` to the list, but finally I didn't, as in general it should be fast.

**Comment by Bultako** [comment]
I have found [Enlighten](https://python-enlighten.readthedocs.io) which solves the logging breaks. 

The pros:
- it is an out of the box solution that does not require touching lines of code across multiple scripts using logging,  just replacing `tdqm` by `enlighten`
- actually it is the only solution that I've found so far..

The cons:
- it does not work in notebooks :(

**Comment by adonath** [comment]
@luca-giunti I have spend some time researching as well and I couldn't find a solution either. The best reference I found so far was https://github.com/tqdm/tqdm/issues/313

**Comment by Bultako** [comment]
my 2 cents about this..

- logging breaks
I do not see an easy solution, apart from Enlighten the only solution that I see is unifying the direction output of all loggers under a unique handler that would stream out the logs with `tdqm.write()` method. This would require some work because we create a logger at the beginning of each script that logs with `log = logging.getLogger(__name__)`. There's more, I think it is better to provide the possibility to keep different handlers, as we do now, which would allow us to send gammapy and dependency libraries to different streams, as an example. If there are logs that continuously break the progress bar I would just modify the level of these logs and send them as a lower level or modify my user log level to filter them out and receive only info logs (we have done a similar thing when we disable astropy or numpy warnings in the past). If it is an error log I think it is normal that it breaks the bar, if it is a warning and it is really noisy we can filter them out, if it is an error log should be a warning, just modif the level it has been set in the gammapy code.

- behavior of progress bar
`tqdm` provides a `disable` flag to not display the bar, so the `dummy` class in the context manager is not needed.

- pbar.py script
as a cause of the previous item, I think this `pbar.py` script  is not really needed and we could call `tqdm` directly instead of the `pbar` context manager.

**Comment by adonath** [comment]
I fully agree with you here @Bultako. I think redirecting the output is not a good solution, we'd like to keep full functionality for the logging. I think the best thing we can do for now is reduce the number of warnings (see e.g #139, #3006) and allow in some cases that they break the progress bar...

**Comment by adonath** [comment]
@luca-giunti Do you see any chance of getting this into Gammapy soon?

**Comment by luca-giunti** [comment]
@adonath I'm on it. I'll open a new PR cause this is full of merge conflicts at this point

**Comment by adonath** [comment]
Superseded by #3343.

**Pull request closed without merging**
