### PR TITLE
Extend changelog for v0.15

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This PR extends the changelog for Gammapy v0.15. I've added the most important bug fixes, API changes and new features since the beginning of the coding sprint.

**Dear reviewer**
Please check the "what's new" section for completeness and make suggestions for improving the
wording.

### CODE REVIEW

**Comment by cdeil** [comment]
@adonath - Thanks!

My suggestions:

- Start by mentioning the new `gammapy.analysis`. Link to it's docs page and the "first analysis" notebook.
- Then as second I would mention the improvements to data reduction and datasets like you do, and link to the "second analysis" notebook.
- Then I would mention significant progress on documentation, linking to "overview", "howto" and "tutorials", maybe mention the PIG, and say that it's work in progress and ask for user feedback.
- I wouldn't specifically say "support for HAWC data". People expect that to mean events, maps, analysis support. Really it's just spectral points used in that tutorial. Suggest to change that tutorial to avoid the confusion, but for now, to just not claim "support for HAWC data".
- For catalog, suggest to link to the docs page
- Not sure if the position error and spatial model region feature needs a mention
- Definitely do mention that we now have support and tutorials for binned simulation, via the new observation class. That's super important for CTA users, but also existing IACTs.
- Mention that there are many breaking changes and removals, since we improve consistency as we move to v1.0? E.g. the change `dataset.model` to `dataset.models` will trip up all existing users, their scripts will break. But there's other such changes, like `read` / `write`, or `likelihood` -> `stat`, map reproject. I don't sugegst to list all the breaking changes, they are already in the PR list, in the summary I would just acknowledge that this is a rather big breaking release. "This release contains several breaking changes and removal of non-essential parts of Gammapy (see PR list below), which we made to improve consistency and quality throughout Gammapy, as we develop towards Gammapy v1.0". Something like that.
- Wording could be improved in parts, but that can either be skipped, or done in a second go.

I think this will make the "what's new" more useful for users, if they get links to the docs and examples what's new.

**Comment by adonath** [comment]
Thanks @cdeil and @registerrier, I'll address your comments now...

**Comment by adonath** [comment]
Thanks @cdeil  and @registerrier for the comments.

**Comment by cdeil** [comment]
@adonath - Thank you for taking the time to write a great "what's new" entry. I think it's very important to point users to the right places and get good feedback. This is a good release for a 2 month dev cycle.

**Pull request merged**
