### PR TITLE
Change missing links in notebooks

### PR DESCRIPTION
**Pull request by registerrier**
This small PR corrects 4 notebooks which have incorrect links to other notebooks or documentation. This mostly comes from modifications introduced by PR #2139 and PR #2137 .

### CODE REVIEW

**Comment by cdeil** [comment]
@registerrier - Thanks!

We'll have to try and improve our MD <-> RST and Notebook <-> Sphinx tooling to auto-detect and such issues from raw URLs in the future.

**Comment by Bultako** [comment]
Thanks @registerrier 
I would modif the link in `hgps.ipynb`. I think it is better to link one notebook from another notebook just with its *.ipynb filename, as you have done in `sed_fitting_gammacat_fermi.ipynb`, so we could stay in the same version/release of the docs when browsing.

This raises the question "what to do with the absolute links to the API docs from notebooks?" The API docs evolve with time, which means that old versions of notebooks would eventually always link to the last devel version of the API docs.

**Comment by cdeil** [comment]
> what to do with the absolute links to the API docs from notebooks?

I think we need the equivalent of the RST directive to link to API docs. And also the other way around really - it would be great to have a way to link to headings or labels in notebooks via a `:ref:` or some other directive from docstrings or RST files.

This has the drawback that the "raw" notebooks don't contain working links, only the notebooks after a build step. But that's probably a tradeoff we're willing to make to get rid of raw URLs?

I did not look at nbsphinx or in general MD <-> RST markup / tooling yet - maybe they have a solution for this that we could adopt?

**Comment by Bultako** [comment]
> it would be great to have a way to link to headings or labels in notebooks via a :ref: or some other directive from docstrings or RST files.

We can already link from RST to HTML notebooks or notebook anchors, using relative links to the tutorials and replacing the .ipynb by a the html extension in the filename linked. See https://docs.gammapy.org/0.11/development/howto.html#link-to-a-notebook-from-the-docs

For links .ipynb -> RST/HTML I would use relative links that will be conveniently converted to absolute links having the right doc version in the URL. This kind of conversion is already done in https://github.com/gammapy/gammapy/blob/master/gammapy/utils/docs.py#L167 for notebooks generated in `docs/build/html/_static/notebooks` (these are linked from every HTML tutorial at the blue box on top). Right now the conversion of relative links is done in these notebooks so that they do not break in the general doc-strcuture. (The notebooks are generated in the doc building process) But we could change this behavior and convert to absolute links to the gammapy doc webpage.

At this moment, the notebooks downloaded with `gammapy download tutorials` may have broken links, because some of them may be relative links. But if we fetch them from `docs/build/html/_static/notebooks` these will have absolute links to the right doc version in http://docs.gammapy.org

**Pull request merged**
