### PR TITLE
Allow e_true argument in edisp.apply

### PR DESCRIPTION
**Pull request by joleroi**
``EnergyDispersion.apply`` had a bug insofar as it assumed the input ``data`` has the same energy axis as the true energy axis of the matrx. This PR fixes this.

Reported by @robertazanin

### CODE REVIEW

**Comment by joleroi** [comment]
I am merging this because @robertazanin needs it :smile:

**Comment by joleroi** [comment]
Ok, it was a bad idea. Master is currently broken, I will fix it in a follow up PR

**Comment by joleroi** [comment]
>  Fix energy dispersion apply if true and reco energy axis is different

is not what this PR does

**Comment by cdeil** [comment]
The basic idea behind the pull request titles at the moment is that I want to use them 1:1 in the changelog: http://docs.gammapy.org/en/latest/changelog.html#gammapy-0p6-release

So basically I want to have them high-level and start either with "Fix" or "Add" or "Improve" in most cases.

Clearly there are other options to organise and handle pull requests and changelog and we should discuss offline ... this was just to explain why I changed it (apparently incorrectly in this case).

**Comment by joleroi** [comment]
> So basically I want to have them high-level and start either with "Fix" or "Add" or "Improve" in most cases.

I see, I'll stick to this scheme in the future

**Pull request merged**
