### PR TITLE
delete sphinx restrictions for build docs

### PR DESCRIPTION
**Pull request by stahanna**
**Description**

This pull request ...

**Dear reviewer**

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @stahanna! Do you have a preview of how the docs look like after?

**Comment by registerrier** [comment]
There is a multiprocessing error appearing. We had this before, right @adonath ?

**Comment by adonath** [comment]
> There is a multiprocessing error appearing. We had this before, right @adonath ?

Yes, seems familiar, but right now I cannot remember the fix.

**Comment by stahanna** [comment]
gammapy-tuto

**Comment by registerrier** [comment]
So apparently, we need to still impose astropy<5.3 for the `build_docs` to run on the CI. I think it passed locally without constraints.

**Comment by stahanna** [comment]
gammapy-docs-index

**Comment by registerrier** [comment]
This PR is superseded by #5118 . Closing now.

**Pull request closed without merging**
