### PR TITLE
Add SpectrumAnalysisIACT

### PR DESCRIPTION
**Pull request by joleroi**
This PR introduces ``SpectrumAnalysisIACT`` which does a full 1D spectral analysis starting from an ``ObservationList``.

It needed quite some changes in ``gammapy.spectrum`` to implement this, so I know that some people won't be happy. Let's not merge this until we agreed that it's worth the pain of updating all user scripts etc. The major change is that all classes related to spectral analysis must be instantiated without data now, and the data is passed directly to the ``run`` method (similar to what @adonath did e.g. for the ``BasicImageEstimator``). That way chaining the separate classes into the ``SpectrumAnalysisIACT`` is straightforward.

This PR will basically be unreviewable. If you want to give feedback, have a look at https://github.com/gammapy/gammapy-extra/blob/master/notebooks/spectrum_pipe.ipynb and tell me if you like the API.

### CODE REVIEW

**Comment by joleroi** [comment]
This PR is stuck, because it completely breaks the [LightCurveEstimator](https://github.com/gammapy/gammapy/blob/master/gammapy/time/lightcurve.py#L123). This is not easy to fix, because the ``LightCurveEstimator`` is 100% coupled to the ``SpectrumExtraction`` (which is changed in this PR). I discussed offline with @jjlk and we agreed that it's ok to break the ``LightCurveEstimator`` for now. Comments? Opinions?

**Comment by cdeil** [comment]
I'm OK to break LC and , if one of you promises to bring it back in the next few days.
I've never tried, but it should be possible to add one line at the top of the LC test file to temporarily disable the tests there (to have a diff that's as short as possible)
```
pytestmark = pytest.mark.skip('TODO: fix me')
```

Also, @joleroi - do you want me to review this PR? I'd also be happy to just try it out once it lands in master.

**Comment by joleroi** [comment]
> Also, @joleroi - do you want me to review this PR? I'd also be happy to just try it out once it lands in master.

No it's fine, I'll merge today and then you can try the notebook

**Comment by joleroi** [comment]
As discussed offline, we will close this PR and split the useful changes it introduces into smaller PRs

**Pull request closed without merging**
