### PR TITLE
Updating astropy_helpers to v3.2

### PR DESCRIPTION
**Pull request by bsipocz**
This PR updates to the 3.2 tag of the helpers. Please do not merge yet as I would like to make sure packages are working with it before pushing the actual release to pypi.

### CODE REVIEW

**Comment by bsipocz** [comment]
travis failures are the same as on master, but the azure ones seem related (setuptools 30.3 is required by the helpers, but older ones are being picked up).

**Comment by bsipocz** [comment]
This is good to go now.

**Comment by cdeil** [comment]
Locally I now see a bunch of deprecation warnings after merging in this astropy-helpers update:
```
$ python setup.py build
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/setup_helpers.py:165: AstropyDeprecationWarning: The package argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/setup_helpers.py:170: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/setup_helpers.py:176: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/setup_helpers.py:190: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/version_helpers.py:244: AstropyDeprecationWarning: The packagename argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/version_helpers.py:249: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/version_helpers.py:255: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/version_helpers.py:269: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
```

@bsipocz - Do you see that as well with Gammapy master? Any pointers to what we need change in `setup.py` or `setup.cfg`, e.g. a link to edits from another affiliated package?

**Comment by Bultako** [comment]
@cdeil @bsipocz

I do also have these warnings, worst it makes the notebook conversion process to fail.

```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/gammapy-dev/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/usr/share/miniconda/envs/gammapy-dev/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/vsts/work/1/s/docs/conf.py", line 181, in <module>
    gammapy_sphinx_notebooks(setup_cfg)
  File "/home/vsts/work/1/s/build/lib.linux-x86_64-3.7/gammapy/utils/docs.py", line 201, in gammapy_sphinx_notebooks
    parse_notebooks(filled_notebooks_folder, url_docs, git_commit)
  File "/home/vsts/work/1/s/build/lib.linux-x86_64-3.7/gammapy/utils/docs.py", line 152, in parse_notebooks
    strcell = DOWNLOAD_CELL.format(**ctx)
KeyError: 'git_commit'

/home/vsts/work/1/s/astropy_helpers/astropy_helpers/setup_helpers.py:165: AstropyDeprecationWarning: The package argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/home/vsts/work/1/s/astropy_helpers/astropy_helpers/setup_helpers.py:170: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/home/vsts/work/1/s/astropy_helpers/astropy_helpers/setup_helpers.py:176: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/home/vsts/work/1/s/astropy_helpers/astropy_helpers/setup_helpers.py:190: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/home/vsts/work/1/s/astropy_helpers/astropy_helpers/version_helpers.py:244: AstropyDeprecationWarning: The packagename argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/home/vsts/work/1/s/astropy_helpers/astropy_helpers/version_helpers.py:249: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/home/vsts/work/1/s/astropy_helpers/astropy_helpers/version_helpers.py:255: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/home/vsts/work/1/s/astropy_helpers/astropy_helpers/version_helpers.py:269: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
Sphinx Documentation subprocess failed with return code 2
##[error]Bash exited with code '2'.
##[section]Finishing: Run Sphinx documentation build
```

https://dev.azure.com/gammapy/gammapy/_build/results?buildId=1009&view=logs

**Comment by cdeil** [comment]
@Bultako - For the `git_commit` key, we had a long discussion last year: #1828

I think the conclusion was that it shouldn't be used, only `gammapy.version` should be used to access version information, no?

**Comment by bsipocz** [comment]
Thanks @cdeil for uncovering this issue.

**Comment by bsipocz** [comment]
@cdeil - We're updating the package helpers in the near future, that will be the best guide to see what to update. However photutils already transitioned, e.g. with this PR: https://github.com/astropy/photutils/pull/614

**Pull request merged**
