### PR TITLE
Legend option for ReflectedRegionsBackgroundEstimator.plot()

### PR DESCRIPTION
**Pull request by IAMinaya**
As discussed in issue [#1847](https://github.com/gammapy/gammapy/issues/1847), I have added the option for adding the legend into the plot (set as False by default).

### CODE REVIEW

**Comment by registerrier** [comment]
You could also add a test with option `add_legend=True`  in `TestReflectedBackgroundEstimator.test_plot()`in gammapy/background/test/test_reflected.py.

**Comment by IAMinaya** [comment]
Sure! I have just commited the renamed parameter one using add_legend as you suggested, I will do the test one this afternoon.

**Comment by IAMinaya** [comment]
Done! As all you suggested, variable name is more intuitive (add_legend), the default value is False, and a test has been included (and passed) on `TestReflectedBackgroundEstimator.test_plot()`. 
Now the legend won't be plotted except you say `.plot(add_legend=True)`.

**Comment by IAMinaya** [comment]
I missed that "t" in the docstring, thanks for spotting the typo!

**Comment by registerrier** [comment]
OK, thanks. Merging this now.

@IAMinaya  It would be nice to update the spectrum_analysis.ipynb to reflect the change too.

**Pull request merged**
