### PR TITLE
Improve XML serialization

### PR DESCRIPTION
**Pull request by joleroi**
This PR adds
* [x] ``SourceLibrary.to_xml`` to write XML files
* [x] Tests that roundtrip a number of XML model files
* [x] Support for ``SkyShell``

Note that XML :arrow_right: ``SourceLibrary`` :arrow_right: XML will lead to a slightly different file, because ``gammapy`` does not support a ``scale`` for parameters (yet), thus ``scale`` is always set to 1 on write

### CODE REVIEW

**Comment by joleroi** [comment]
I guess this needs more discussion. The [shell example file](https://github.com/gammapy/gammapy-extra/blob/master/test_datasets/models/shell.xml) from ctools has a ``RadialAcceptance`` model which currently has no counterpart in gammapy to my knowledge. Do we have to support only the Fermi-XML files or also the format that is used by ctools?

@robertazanin ?

**Comment by cdeil** [comment]
@joleroi - Apparently we have this fail in master:
https://travis-ci.org/gammapy/gammapy/jobs/373066559#L3831

So this needs to be adapted to the new classes and to call `self.sky_model` instead:
https://github.com/gammapy/gammapy/blob/42416f5c8bd904a27d70ba8607bfe3db582fb6b6/gammapy/catalog/gammacat.py#L447-L466

@joleroi - Do you have time to do this here and finish this PR today?
Or should I make a commit in master where I xfail the test for now and then take care of this in the coming days after this PR is in?

Overall, what do we want? I think this convenience method to turn a catalog into a source library with one method call (and serialise with a second one) is worth keeping? Or should we remove this and replace it with a docs example how to do it with a few lines?

**Comment by cdeil** [comment]
@joleroi - I'll xfail `TestSourceCatalogGammaCat.test_to_source_library` via a commit to master now, so that other unrelated PRs don't show up with CI fails.

**Comment by cdeil** [comment]
Done in https://github.com/gammapy/gammapy/commit/7eb9ed0783a4cfeef63a3d39c10ea4ef31ebb63d

@joleroi - Do you have time to finish up this PR? Or should I continue?

**Comment by cdeil** [comment]
Another fail in Gammapy master:
https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.3406/job/7b85frya493mt8qx#L2502
@joleroi - Please add `@required_data('gammapy-extra')` to tests where you access `GAMMAPY_EXTRA`. I'll leave this to this PR to avoid merge conflicts.

**Comment by joleroi** [comment]
> @joleroi - Do you have time to finish up this PR? Or should I continue?

I will finish this up today

**Comment by cdeil** [comment]
Another fail for `test_xml_to_source_library` that shows up in other PRs:
https://travis-ci.org/gammapy/gammapy/jobs/374275416#L3094

@joleroi - please add `requires_dependency('scipy')` or make the map read or interpolator instantiation delayed on first access (e.g. via a `lazyproperty`).

**Pull request merged**
