### PR TITLE
Remove old code in gammapy.image

### PR DESCRIPTION
**Pull request by cdeil**
This pull request removes a bunch of old code in gammapy.image.

- [x] remove `gammapy/image/models/model.py`
- [x] remove `gammapy/image/models/utils.py`
- [x] rename `gammapy/image/models/models.py` to `gammapy/image/models/shapes.py` to avoid the confusion with the `models.models` part, and to match the already existing `gammapy/image/tests/models/test_shapes.py`.

There's one broken caller, the `SherpaMultiGaussPSF`, not removed here yet.
This is making `gammapy/scripts/tests/test_image_fit.py` fail.
I think I could adapt this with limited effort to keep that part running and still giving the same result.

@adonath - Can you please have a quick look and comment how you think this can move forward?
Do we still need this for HGPS? (if yes, I'd prefer we copy it to the `hgps_analysis` repo)

### CODE REVIEW

**Comment by adonath** [comment]
The `SherpaMultiGaussPSF` is still used in the HGPS analysis:

https://bitbucket.org/search?q=repo%3Ahgps_analysis%20SherpaMultiGaussPSF&account=%7Bf0f1128e-e9cc-4873-b3f1-f5f7031588fc%7D

The `MorphModelImageCreator` seems to be duplicated already:

https://bitbucket.org/hess_software/hgps_analysis/src/1207f2fb80023aa2b0c438134af23f378b7a53b0/code/hgps/scripts/hgps_maps_create_model_counts.py?at=master&fileviewer=file-view-default#hgps_maps_create_model_counts.py-21

I agree we should just copy over the functions to the HGPS analysis repo, when needed, and remove everything else.

**Comment by cdeil** [comment]
@adonath and I discussed offline, and agreed that this could be removed. I've rebased the PR and will merge if CI tests pass.

IMO adding these classes to the HGPS code-base and re-running, re-checking the HGPS morphology fit would be a waste of time. For now no action for HGPS is needed, and if we ever need or want to re-run the morphology fits or do extra checks, I think using latest Gammapy would be much simpler and also very useful, because HGPS results are quite well-checked, i.e. a good reference dataset for 2-dim image likelihood fitting.

**Comment by cdeil** [comment]
I had to bring some of the JSON I/O helper functions back, because of the Sherpa morphology fitting example / test still using it. Would like to merge this in now if CI tests pass.

**Comment by cdeil** [comment]
travis-ci fails are unrelated. Merging this now.

**Pull request merged**
