### PR TITLE
Add methods to convert analytical to Table PSF

### PR DESCRIPTION
**Pull request by joleroi**
So far the PSF functionality is somewhat messy, in the sense that there is no clear path from a 2D PSF (as function of energy and offset) to a 1D PSF (as function of energy)

* TripleGaus:
2D (gammapy.irf.EnergyDependentMultiGaussPSF) -> 1D (gammapy.morphology.MultiGauss2D)

* King:
2D (gammapy.irf.PSFKing) -> 1D (missing)

* Table
2D (gammapy.irf.EnergyDependentTablePSF) -> 1D (gammapy.irf.TablePSF)

This PR tries to order this somehow, by
* [ ] Add to_table_psf to KingPSF and 3GaussPSF
* [ ] Use EnergyDependentTablePSF for plotting and converting to 1D

### CODE REVIEW

**Comment by cdeil** [comment]
"messy" is such a hard word ... I would prefer we call it "organically grown", OK?
:-)

I would say it is worth adding tests while you improve things here, even if the API is still very much in flux / to be improved.

**Comment by joleroi** [comment]
Legend:
energy : what you think
offset : distancen between pointing position and target position
theta : radial distance from target position

I just discussed with @adonath now I think it would be a good idea to add a new class that holds for a given energy and offset a 1D PSF table (as function of theta). Such a class does not exists yet (or at least we have not found one). The ``EnergyDependentTablePSF`` has no information about the offset.
With such a class one possible workflow would be:
KingPSF -> TablePSF(offset, energy) -> TablePSF(energy)
where the last step is the same as for all other IRFs.

What do you think?

**Comment by cdeil** [comment]
> class that holds for a given energy and offset a 1D PSF table (as function of theta)

This is the [gammapy.irf.TablePSF](https://gammapy.readthedocs.org/en/latest/api/gammapy.irf.TablePSF.html) class, no?

There's confusion in that `offset` is sometimes wrt. pointing and sometimes source position at the moment.
Maybe renaming offset wrt. source position `rad` as suggested here
http://gamma-astro-data-formats.readthedocs.org/en/latest/irfs/index.html#irf-axes
would be a good first step?
(leaving the decision whether to everywhere name things `theta` or `offset` for the offset in the field of view for another PR)

**Comment by joleroi** [comment]
Yes you are right, I phrased it incorrectly. I meant a class that holds the PSF (as function of theta) as function of offset and energy. Parallel to ``EffectiveAreaTable2D`` and ``EnergyDispersion2D``

**Comment by cdeil** [comment]
Yes, this class is still missing in Gammapy.

The format spec is here:
http://gamma-astro-data-formats.readthedocs.org/en/latest/irfs/psf/psf_table/index.html

This is implemented (but completely untested) in the HAP exporter ... if you plan to add it you can use this file:
https://github.com/gammapy/gammapy-extra/blob/master/datasets/hess-crab4-hd-hap-prod2/run023400-023599/run023523/hess_psf_table_023523.fits.gz

**Comment by joleroi** [comment]
It seem logical to me to go via this (missing) class when sampling an analytical PSF (like King or 3Gauss). But I might be wrong, that's  why I wanted to discuss this before writing too much code

**Comment by cdeil** [comment]
Without having thought about it much ... I think you're right: sampling first, i.e. getting keeping the analytical PSF classes as small as possible sounds like a good idea to me.

**Comment by cdeil** [comment]
@joleroi - Status?

Do you have something for this already or have time to do it until tomorrow?
If no, I or @adonath should try to do it, because the King PSF -> TablePSF is the missing building block to get morphology fits for ParisAnalysis.

**Comment by joleroi** [comment]
No, I don't have anything ready. This is a bigger project IMO, but maybe it's possible to hack something together for the Morphology analysis - up to you.

**Comment by joleroi** [comment]
This is partly covered by https://github.com/gammapy/gammapy/pull/526

**Comment by cdeil** [comment]
I'm closing this now. Please file individual new PRs or issues concerning the enhancements discussed here.
The [PSFKing.to_table_psf](http://docs.gammapy.org/en/latest/api/gammapy.irf.PSFKing.html#gammapy.irf.PSFKing.to_table_psf) and [EnergyDependentMultiGaussPSF.to_table_psf](http://docs.gammapy.org/en/latest/api/gammapy.irf.EnergyDependentMultiGaussPSF.html#gammapy.irf.EnergyDependentMultiGaussPSF.to_table_psf) methods exist by now, so to a certain extend this has been implemented in other PRs.

**Pull request closed without merging**
