### PR TITLE
Use FluxPoints as lightcurve in gammapy.catalog

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request refactors `gammapy.catalog` to use `FluxPoints` to represent lightcurves of sources. For this it introduces the `fermi-fgl` format for `TimeMapAxis` to support the `Hist_Start` HDU in the Fermi catalogs.

**Dear reviewer**

### CODE REVIEW

**Review by registerrier — APPROVED** [review]
Thanks @adonath. This looks good.

In the long run, we need a better way to pass format options to `Axes.read`.

**Comment by adonath** [comment]
Thanks @registerrier! 

> In the long run, we need a better way to pass format options to Axes.read

I there anything specific you have in mind?

**Comment by registerrier** [comment]
> Thanks @registerrier!
> 
> > In the long run, we need a better way to pass format options to Axes.read
> 
> I there anything specific you have in mind?

Well, probably a registry of external methods, so that this can be added without changing the core code of the axes/geom framework. This way one would not need to expose the specific format of 4fgl which is only specific to gammapy.catalog.

**Comment by adonath** [comment]
Yes, I agree this makes a lot of sense. Methods like https://github.com/gammapy/gammapy/blob/master/gammapy/maps/axes.py#L1118 have grown a lot and a nice way to resolve this is a registry system for different formats.

**Pull request merged**
