### PR TITLE
Add a how-to for memory issues caused by large datasets.

### PR DESCRIPTION
**Pull request by registerrier**
**Description**

This pull request adds an how-to to suggest solutions to memory issues appearing when large maps are used for `MapDataset.create`. 
The text proposes some solutions to issue #3192 .

**Dear reviewer**

Is it clear enough @adonath @luca-giunti @AtreyeeS ?

### CODE REVIEW

**Comment by AtreyeeS** [comment]
Thanks @registerrier ! This is quite clear.

I imagine that for very large datasets, some stacking is inevitable? Not all can be saved in memory?

**Comment by luca-giunti** [comment]
I find it clear enough, thanks for this!

**Comment by luca-giunti** [comment]
I find it clear enough, thanks for this!

**Review by adonath — APPROVED** [review]
Thanks @registerrier, no further comments from my side...

**Pull request merged**
