### PR TITLE
Improve integration of background model

### PR DESCRIPTION
**Pull request by lmohrmann**
This PR improves the integration of the background model in `make_map_background_irf` by oversampling the energy nodes if required.

This plot exemplary shows the relative deviation for the central pixel between the result of the integral and the input data:
int_dev

It's not yet clear to me why there's not visible improvement after n=10 (n is the minimum required number of interpolation nodes per decade). Ideas?

(N.B. The deviations at high energies seem to be related to problems with the inter-/extrapolation due to zero pixels - the deviation at ~600GeV is maybe more of an issue)

### CODE REVIEW

**Comment by registerrier** [comment]
I think no improvement is visibly after n=10, because the background is stored with 7 bins per decades, no? 
The 600 GeV discrepancy might be caused by the rapid rise of the background. Could you show the dependency of the background rate with energy?

**Comment by lmohrmann** [comment]
@registerrier 
I don't really see how an analytical calculation would solve the issue here. The problem was that the integral was computed with a too coarse energy binning. Could you elaborate a bit more?

> I think no improvement is visibly after n=10, because the background is stored with 7 bins per decades, no?

Well, I would still expect that I can re-obtain the original node values if I choose an energy binning for the integration that is fine enough.

> The 600 GeV discrepancy might be caused by the rapid rise of the background. Could you show the dependency of the background rate with energy?

Not quite, this is the energy bin at which the distribution peaks:
int_counts
But yes, the integration fails here because the shape is no longer a nice power law. It should become more accurate with increasing number of evaluation nodes, though (?).

**Comment by adonath** [comment]
@lmohrmann and @registerrier Actually I have another idea how to resolve this.

For containment computation of the PSF I changed to a different approach: instead of evaluating and integrating the (differential) psf value, I computed the cumulative sum of the psf value (using cumtrapz), based on the binned data. Then I interpolate this integral. This has the advantage of being very efficient, because you don't have to use oversampling and the cumulative data (histogram) is typically more stable against noise as well. The "extrapolation" of the integral is also more clearly defined: if the energy is smaller than the minimal energy it is zero, for large energies it is just the total sum. I'd like to try and change the `BKG3D.evaluate_integrate()` and see if this works.

@registerrier In the past you've made the argument, that you cannot interpolate "integrated" values. But actually with the approach I described above, you actually can, no? I.e **not** interpolate the differential quantity and integrate, but interpolate the integrated (cumulative) distribution. Do you see any issues with this?

**Comment by registerrier** [comment]
Thanks for the plot @lmohrmann. Indeed the interpolation becomes poor if the derivative varies strongly, it is probably unavoidable to have some inconsistencies at peak values. Or to limit them, we need more nodes to better describe the behavior of the function, no?

@adonath, this sounds indeed like a good idea and it is very similar to integrating the interpolated function actually. 
I suppose this works because you are taking the difference of the interpolated cumulative function between 2 energies.

 My point regarding maps of integrated quantities was that interpolating on the per bin values does not necessarily mean something: e.g. if you want to oversample a count map, you need to divide the interpolation value by the oversampling factor.

**Comment by lmohrmann** [comment]
@adonath 
Sounds like a good proposal to me. Which time scale do you envisage for this? Will it be ready for the release this week? If not, could we merge this PR before, to have an intermediate solution?

**Comment by lmohrmann** [comment]
Sorry... I was trying to rebase and have included lots of commits from others by accident. In any case, @adonath needs to decide whether the proposed change should be made or something better is to be implemented. I can open a new PR if needed.

**Comment by adonath** [comment]
@lmohrmann I have working prototype for my proposed integration method (https://github.com/adonath/gammapy/tree/background_integration) and a first quick test seemed to give nice results: the total number of predicted background counts is preserved independent of the number of bins that is used for the evaluation.

However the differences I see in our tests are in the order 5%, so I'm a bit hesitant to merge the change so shortly before the v0.11. I'd prefer to do some more testing first, to check in detail if the proposed method works as expected (you can actually check out the branch I linked above and run your testing script as well...).

In general I think we should add `axes` arguments to our `Map.upsample()` and `Map.downsample()` method and also add a `MapAxis.upsample()` and `MapAxis.downsample()` method. I think it's actually useful in other contexts as well.

Concerning this PR I'd like to talk again to @registerrier what to do.

**Comment by lmohrmann** [comment]
This has been solved in #2142 .

**Pull request closed without merging**
