### PR TITLE
Simplify `PHACountsSpectrum`

### PR DESCRIPTION
**Pull request by adonath**
This PR simplifies the `PHACountsSpectrum`, so that it becomes easier to refactor and finally remove in following PRs. It includes the following changes:

- Remove `.to_sherpa()`method. The data can be written to file (there is a `use_sherpa` option, which writes in a sherpa compatible format) and read with sherpa again. I think there is no strong motivation to directly convert to `DataPHA` object.
- Remove the `SpectrumDatasetOnOff.livetime` setter, so that the info is not duplicated on the `counts` and `counts_off` objects anymore.
- Remove the `SpectrumDatasetOnOff.mask_safe` setter, so that the array is not duplicated on the `counts` and `counts_off` objects anymore.
- Remove the `PHACountsSpectrum.offset` attribute, which only used internally in `SpectrumExtraction`, but never for likelihood evaluation or I/O.
- Remove attributes from `PHACountsSpectrum` defining the filenames for I/O. The creation of filenames was moved to the `.to_hdulist()` methods instead.
- Remove the unused `reset_thresholds()` method.

### CODE REVIEW

**Comment by cdeil** [comment]
> Remove the SpectrumDatasetOnOff.livetime setter, so that the info is not duplicated on the counts and counts_off objects anymore.

How is livetime handled now?

I think it should be an attribute that's separate and can be different for on and off, no?
E.g. the off spectrum might be from a dedicated off run that didn't have the exact length as the on run (or a longer time interval or multiple off runs were used to get decent off statistics).

Just now I also remembered #137 - not sure if we want to support that at some point, but I think the case of different off livetime should be supported.

That's my only comment (based on the issue description) - the rest looks good.

**Comment by adonath** [comment]
> How is livetime handled now?

Basically the same way, but only as a single attribute on the `SpectrumDatasetOnOff`. Previously there were attributes on the ON and OFF spectrum, but they were effectively set to the same value and only used for I/O. The ratio of the ON / OFF exposure was handled only with the `backscale` arguments. So this PR does not take away any functionality in this regard... 

Just because I don't know: why do you need the OFF lifetime in addition to the exposure ratio? Because `alpha` includes the area as well as time ratio and you might want to have this info separately?

**Comment by registerrier** [comment]
Technically, a use case for different `livetime` for ON and OFF spectra is the 1D lightcruve where the OFF is extracted run-wise and the ON on the user defined time bins.

If we follow the notations defined in `stats/data.py`, the `a_OFF` should contain both the geometric and time exposures, since `alpha=a_ON/a_OFF`. Otherwise the correct definition of `alpha` is
`(t_ON*backscal_ON)/(t_OFF*backscal_OFF)`.

In a sense, if we are only to read from OGIP we can convert from `t_OFF*backscal_OFF` to `a_OFF`. If we want to also write to OGIP, keeping track of `t_OFF` and `backscal_OFF` independently might be a good idea.

**Comment by adonath** [comment]
Thanks for the explanation @registerrier. Independent of this PR, I think this is up to debate. We could add e.g. `lifetime_off` or just store those numbers (optionally) away in a`meta` attribute.

**Pull request merged**
