### PR TITLE
Add a deduplication method to SourceCatalogue

### PR DESCRIPTION
**Pull request by QRemy**
This adds a deduplication method to SourceCatalogue that return a new catalogue merging entries within a given radius.
Positions of the merged objects are set to the coordinates mean.
Provide a solution for  #3414

### CODE REVIEW

**Comment by QRemy** [comment]
For now I convert this to a draft, we will come back to improvements of the catalogue module and its relation to object detection and filtering methods after 1.0

**Comment by adonath** [comment]
Just for reference here is a more efficient similar implementation, that I found on my hard disk:
```python3
from gammapy.catalog import SourceCatalog3FGL
from astropy import units as u
from scipy.sparse.csgraph import connected_components
from scipy import ndimage
import numpy as np

catalog = SourceCatalog3FGL()

pos = catalog.positions
separation = pos.separation(pos[:, None])
mask = (separation < 5 * u.deg)
n_groups, labels = connected_components(mask)

lon_mean = ndimage.mean(pos.data.lon, labels=labels, index=range(n_groups))
lat_mean = ndimage.mean(pos.data.lat, labels=labels, index=range(n_groups))
```

**Comment by QRemy** [comment]
Thanks @adonath, I will try with this. I think an extra loop is still needed to make it recursive.

**Comment by QRemy** [comment]
Closing this for now I will probably implement first what commented before https://github.com/gammapy/gammapy/pull/3417#issuecomment-876304491 :

> * introduce a dedicated SeedCatalogue object with some predefined columns names, move the deduplicate method there and make `findpeaks` and any future detection methods return this object.

**Pull request closed without merging**
