### PR TITLE
Implement WcsNDMap.to_region_nd_map_histogram

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request implements `WcsNDMap.to_region_nd_map_histogram`. The idea is as following:

- `WcsNDMap.to_region_nd_map_histogram` creates a `RegionNDMap` with a bins axis to present a histogram.
- This way it allows to represent "ND histograms": so a histogram for each extra axis in the map.
- This is mostly useful for plotting and serialization

### CODE REVIEW

**Comment by adonath** [comment]
CC @MRegeard, please test the functionality if you have time. E.g. you can start by using this code:

```python3
from gammapy.maps import MapAxis, Map
import numpy as np

random_state = np.random.RandomState(seed=0)

energy_axis = MapAxis.from_energy_bounds("1 TeV", "10 TeV", nbin=3)

data = Map.create(axes=[energy_axis], width=10, unit="cm2 s-1", binsz=0.02)
data.data = random_state.normal(
    size=data.data.shape, loc=0, scale=np.array([1.0, 2.0, 3.0]).reshape((-1, 1, 1))
)

hist = data.to_region_nd_map_histogram()
hist.plot(axis_name="bins")
```
Which should create the following plot:

image

**Comment by adonath** [comment]
This turned out to be a bit more complex than expected. There is also some code duplication with `.to_region_nd_map()`, I'm happy for any suggestions. Maybe we could introduce a shared method, like `Map.cutout_region()`, that cutout the map based on some region definition and masks out values, that are not inside the region or similar...

**Comment by MRegeard** [comment]
Let me check your code.

**Comment by adonath** [comment]
@MRegeard I think for fitting we also need a solution to represent the un-binned data. So this is one more reason to introduce something like `Map.cutout_and_mask_region()`. I can propose another PR...

**Comment by adonath** [comment]
See #4510.

**Comment by adonath** [comment]
Will rebase after #4510 has been merged.

**Review by registerrier — DISMISSED** [review]
Thanks @adonath . This looks good. 
I suppose the code that was merged in #4510 should be removed from this PR.

I have left one suggestion to try to build the histogram with a `fill_by_coord`

**Review by registerrier — APPROVED** [review]
Thanks @adonath . Looks good

**Pull request merged**
