### PR TITLE
`plot_distribution` in tutorials

### PR DESCRIPTION
**Pull request by MRegeard**
This PR is a follow up of #4408. 
It introduce the `plot_distribution` visualization function in the tutorials.

### CODE REVIEW

**Comment by MRegeard** [comment]
The second commit on the 3D analysis tutorial change slightly the output, because it plot the distribution per bin.

**Review by QRemy — DISMISSED** [review]
Thanks @MRegeard, looks good, no comments from my side.

**Comment by MRegeard** [comment]
By adapting the two tutorials with this function, I get the feeling that it is heavy to use... I am not entirely sure that we should advertise it right now.

**Comment by registerrier** [comment]
> By adapting the two tutorials with this function, I get the feeling that it is heavy to use... I am not entirely sure that we should advertise it right now.

Maybe part of the difficulty is with the `lambda` function that is a bit complex to explain. Maybe, one could define a specific case where `func="gauss"` which will internally create the 2 parameters gaussian function.

**Comment by MRegeard** [comment]
> > By adapting the two tutorials with this function, I get the feeling that it is heavy to use... I am not entirely sure that we should advertise it right now.
> 
> Maybe part of the difficulty is with the `lambda` function that is a bit complex to explain. Maybe, one could define a specific case where `func="gauss"` which will internally create the 2 parameters gaussian function.

Yes I thought about that. A new function that would only deal with gaussian distribution. Something like `plot_gaussian_distribution.

**Comment by bkhelifi** [comment]
And this new function could add a legend with the fitted parameters ;)

**Comment by MRegeard** [comment]
> And this new function could add a legend with the fitted parameters ;)

Yes of course, in this case it would be really easy to implement !

**Review by bkhelifi — APPROVED** [review]
Thanks for the update!

**Comment by MRegeard** [comment]
Pending bug fix in #4775 to be sure that everything is ok !

**Comment by MRegeard** [comment]
It gives this for the two tutorial that I have updated :

Capture d’écran 2023-10-02 à 14 18 41
and 

Capture d’écran 2023-10-02 à 14 19 02

**Review by QRemy — APPROVED** [review]

**Review by registerrier — APPROVED** [review]
Thanks @MRegeard . This looks fine.

I think these examples show that we could find good defaults for these plots, or maybe provide specialized plot functions for specific types of maps that would alleviate the interaction with `plt.hist` and the `Axes`.

Maybe it could be worth opening a follow-up issue for this.

**Pull request merged**
