### PR TITLE
Add code quality build in CI

### PR DESCRIPTION
**Pull request by cdeil**
Now that we have some make targets to check code quality (added in #314), we should run them on travis-ci.
- [ ] Make pylint run OK on travis-ci (i.e. fail the build if there's an issue)
- [ ] Fix pylint warnings

On my machine I get these errors: https://gist.github.com/cdeil/25601836ca0a8584ffcd
(at the end, pylint crashes when trying to do some code analysis for ROOT ... this should be fixed or skipped)

This can be extended to cover pylint warnings or flake8 in this or separate future PRs.

### CODE REVIEW

**Comment by adonath** [comment]
@cdeil Personally, I use a pylint plugin in my editor and try to fix the files I touch anyway. But I agree it would be nice to have a general set up and integrate this into our development / release workflow. I also think both of your suggestions are possible.

The most cleanest, but also strictest solution would be to add the pylint check to our Travis builds, as you suggested in your initial comment. I could only imagine this being problematic, if there are to many false positives, that might be annoying to fix for contributors...but this solution would ensure, that code quality issues are found early and can probably also help to find minor bugs earlier.

In your experience, what's the effort of fixing those pylint issues before a release as a lead developer? If the effort is small (< 1/2 day) I think it's OK to stick with the `make pylint` solution for a while.

**Comment by cdeil** [comment]
> In your experience, what's the effort of fixing those pylint issues before a release as a lead developer?

It depends. Currently what's broken is the XML serialisation. Fixiing that would be several days of development. But that just means we have to come to a clean state once. For now we could skip that file in `make pylint`, which takes a few seconds.

pylint is very stable, issues appear and disappear only with Gammapy code changes, not very often.

So either way to operate isn't much hassle: "small cleanup as you go", i.e. often follow-up commit on each PR when you merge it in. Or "cleanup when you like" at times of your choosing, but not be bothered by stuff like code style of (usually trivial) issues static analysis can find while reviewing / integrating PRs.

So it's really up to you, since you'll do most PR review / merging in the coming months.

Maybe I skip the remaining few false positives and XML serialisation and add the CI build here?
And then if it annoys you, you remove that build or mark it "allowed fail" in the coming weeks?

**Comment by cdeil** [comment]
Discussed with @adonath just now: will fix the handful remaining pylint errors or mark them as ignored, and will add one CI build that runs pylint and thus shows static analysis results in the log, but make the build optional, i.e. don't turn CI red if that build fails.

**Comment by cdeil** [comment]
@adonath - Please have a look.

I'll fix a few small lint issues that are just very small edits and unlikely to conflict with ongoing work.

But basically I think this is ready - a CI build that runs our code quality checks, shows the result in the log, but doesn't turn CI red.

**Pull request merged**
