### PR TITLE
Fix grid plot with label axis

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request fixes a bug that prevented a `LabelMapAxis` being plot with `plot_grid()`. I still have to add a unit test...

### CODE REVIEW

**Review by registerrier — APPROVED** [review]
Thanks @adonath . This looks good to me.

Do we need a similar scheme for maps with a time axis?

**Comment by adonath** [comment]
> Do we need a similar scheme for maps with a time axis?

Probably yes, it declares a different node type.

**Comment by adonath** [comment]
I'll include a fix in this PR as well.

**Review by registerrier — APPROVED** [review]
Thanks @adonath !

**Pull request merged**
