### PR TITLE
Make the FluxPointEstimator work on multiple observations

### PR DESCRIPTION
**Pull request by lmohrmann**
These are some small fixes to make it possible to run the `FluxPointEstimator` on a `SpectrumObservationList` (rather than a single `SpectrumObservation`).

The most important point is that the computation of upper limits needs to be fixed, since that relied on there being only a single entry in the `result` attribute of the fit.

The changes in gammapy/spectrum/fit.py are necessary to catch cases in which one of the observations in the list has no "safe" bins within the energy bounds specified by the `FluxPointEstimator`.

### CODE REVIEW

**Comment by lmohrmann** [comment]
@adonath @joleroi Has either of you time to have a quick look at this?

If not, @cdeil, could you have a look or suggest another reviewer?

Thanks!

**Comment by cdeil** [comment]
@lmohrmann - Can you please adapt the tests to make this pass?
```
python -m pytest -v gammapy/spectrum/tests/test_flux_point.py
```
https://gist.github.com/cdeil/ff27083f3afa01de418c6fef1d49f1ec

We plan to heavily work on 1D spectral analysis, but I'd suggest we just merge this in as soon as CI passes and then continue on Monday from master.

**Comment by lmohrmann** [comment]
@cdeil I think the failing tests were due to a small bug I introduced. Could you check again? I tried to run the tests using the command you pasted above, but this fails like so:
```
INTERNALERROR>   File "/home/hpc/caph/mpp227/software/gammapy/gammapy/maps/sparse.py", line 4, in <module>
INTERNALERROR>     from ._sparse import find_in_array, merge_sparse_arrays
INTERNALERROR> ImportError: No module named _sparse
```

The CI fails are unrelated, I think.

**Comment by cdeil** [comment]
@lmohrmann - If you use `python -m pytest`, you're running from the source folder. So you have to do an in-place build, using `pip install -e .` (this is running `python setup.py develop`, which is running `python setup.py build_ext -i`, so those are really equivalent if you prefer to use `setup.py` instead of `pip`)

The `python setup.py test` builds and copies everything to a temp folder for each test invocation, so the issue doesn't appear there. But that is slower, so I prefer `python -m pytest` and` pip install -e .`.

**Pull request merged**
