### PR TITLE
Tweak in MapEvaluator.need_update for performance

### PR DESCRIPTION
**Pull request by QRemy**
This PR introduce a performance tweak in MapEvaluator.need_update that replaces `skycoord.separation` by `angular_separation` in order to avoid unnecessary frame and unit equivalence comparison.

### CODE REVIEW

**Comment by QRemy** [comment]
Added a test to avoid update if there is no free spatial parameters (solve fail related to `TemplateSpatialModel`)

**Comment by adonath** [comment]
Thanks a lot @QRemy! One last suggestion to try: maybe it is an option to also check for `if parameters_spatial_changed` in `.need_update` and only check for the separation if this is the case?

**Comment by adonath** [comment]
Thanks @QRemy, it seems there are now test fails https://github.com/gammapy/gammapy/pull/3353/checks?check_run_id=2557044541#step:9:1865, I can also reproduce them locally....not sure what is happening. Maybe see if they can be fixed with limited effort...

**Review by adonath — APPROVED** [review]
Thanks @QRemy, the remaining test fails seems unrelated. I think adding the `lon_0` and `lat_0` parameters to the `TemplateSpatialModel` is still a good idea, however this can be done in a follow up PR.

**Pull request merged**
