### PR TITLE
YAML template for settings in high-level interface

### PR DESCRIPTION
**Pull request by Bultako**
This PR adds a `get_template()` method in the high-level interface `config` class, to provide the end-user with a mean to inspect allowed values for the params/values in the settings.

```
In [1]: from gammapy.scripts import Analysis                                                                                                                                          

In [2]: a = Analysis()                                                                                                                                                                
INFO:gammapy.scripts.analysis:Setting logging config: {'level': 'INFO'}

In [3]: a.config.get_template()                                                                                                                                                       
#    general:
#        logging:
#            level: INFO
#            filename: mylogfile.log
#            filemode: w
#            format: %(asctime)s - %(message)s
#            datefmt: %d-%b-%y %H:%M:%S
#        outdir: .
[.....]

```

### CODE REVIEW

**Comment by cdeil** [comment]
I'm not sure I understand how this is useful. You just dump the JSON schema on the console?
If that is the goal, suggest to call this method `print_schema`.

Would it be more useful to show users how to get the default config, to be able to edit it from Python, or how to dump it to a YAML file to be able to edit it there?
```
import yaml
from gammapy.scripts import Config
config = Config()
config.settings
print(yaml.dump(config.settings))
```

In the end we probably want something in the middle.
We want to add "description" keys in the JSON schema, and dump those into comments so that users can dump a `config.yaml` file that works out of the box, yet has a lot of comments how to edit it to do what they want.

I'm not sure if this is possible, we would need a method that starts with the JSON Schema, and transforms it into a new data structure partly automatically, partly doing special processing.

I think Fermipy and many others just bite the bullet and maintain a documentation RST file in parallel with the schema and code, relying on devs and code review to keep them consistent.
Example: https://fermipy.readthedocs.io/en/latest/config.html

@Bultako - Maybe start a `docs/scripts/analysis.rst` file where you briefly document examples and use cases as you send PRs and I always start my code review from there.
This is very little code, if you want to merge this in, just go ahead.

**Comment by Bultako** [comment]
>  You just dump the JSON schema on the console?

It is not the JSON schema, but a template for a configuration file, with all possible parameters and example values. Yep, I could rename it to `print_template()`

The few lines of code that you provide to dump the settings are already implemented in the `Config` class.

```
from gammapy.scripts import Analysis
analysis = Analysis()
print(analysis.config)    # displays the actual settings in YAML format at any moment
```

> I'm not sure if this is possible, we would need a method that starts with the JSON Schema, and transforms it into a new data structure partly automatically, partly doing special processing.

This is feasible.
Note how the template is described with # comments in the schema.
For example, we could use our custom syntax to declare default params with # and comments with  ##, and then pre-process with this before creating the *default* config data structure, or dump it to a file with the comments.

Linking the default config, schema, template, etc.. to the documentation is another thing. I don't think we should worry too much about this now. And yes, I can also already start with documentation, even more if it helps to the review.

**Comment by cdeil** [comment]
I see, you're just adding commented lines in the schema files, and are using those as example config.

🙈 🙉 🙊 

This is a solution for the problem how to maintain schema and example together.
But it's really easy to mistype or mis-indent, and no editor will help you inside the comments in YAML.

In fact, if you try the current version, you'll find that there's several YAML parsing errors. They are impossible to spot, things like the % character needing to be quoted or the indentation off by a few spaces.

I think it might be better to go down the route of adding "description" or maybe also "example" fields on the schema and to process those to arrive at the "template" for the user, instead of continuing with the commented approach.

@Bultako - Thoughts?

**Comment by Bultako** [comment]
@cdeil 

Yep, I think we should consider this simple solution just in the scope of documentation and user help. It's true it should not be used to generate a valid bullet-proof configuration file (note also for example the multiple values assigned to some params like *filter_type* or *frame*, which is not valid), but I think it is quite useful for the user to have an idea on how to set the params. Maybe also we could also link it to the the RST docs somehow, and maintain the docs and the schema in the same schema file. 

I've changed the name and added an optional param to fetch only one specific section.

```
In [10]: a.config.print_template("flux")                                                                                                                       
#    flux:
#        fp_binning:
#            lo_bnd: 1
#            hi_bnd: 10
#            nbin: 11
#            unit: TeV
#            interp: log
```

> I think it might be better to go down the route of adding "description" or maybe also "example" fields on the schema and to process those to arrive at the "template" for the user, instead of continuing with the commented approach.

Yes, we have already a "description" field, and we could also add the "example" field in the schema and nothing will break. So, building a valid template file or data structure is just a matter of custom processing of the schema, but also for us to decide what we really want to provide (which and how many templates, which fields, which comments, etc.)

**Comment by Bultako** [comment]
After discussion off-line with @cdeil we have decided to not display the *comments in schema* template, since it provides a not-tested (and also not-valid) commented config that users would be tempted to uncomment and use it as initial default config.

This PR will hence continue with the addition of custom fields in the schema, and processing it to dump a default config file in YAML format with commented lines and descriptions.

**Comment by Bultako** [comment]
@cdeil 

I've added a solution for maintenance of settings **how-to text** and settings **default values** in a centralized `schema.yaml` file, using the comments-in-file method for the how-to.

I've also added functionalities to dump the actual configuration in YAML format to a file, instantiate the `analysis` class from a config YAML formatted file, and from a specific template keyword.

```
>>> analysis = Analysis()
>>> analysis = Analysis(template="1d")
>>> analysis = Analysis.from_file("config.yaml")
>>> analysis = Analysis(config=config_dict)
>>> analysis.config.print_help("")
>>> analysis.config.print_help("flux")
>>> analysis.config.dump("myconfig.yaml")
```

Detailed documentation may come in another PR, if this one is merged.

p.s. please, be kind, it's my birthday ;-)

**Pull request merged**
