### PR TITLE
Add map_selection parameter in Analysis 

### PR DESCRIPTION
**Pull request by Bultako**
**Description**

This pull request adds `map_selection` parameter to the Analysis class and YAML files of the High-lelve interface, as an optional param for `MapDatasetMaker`. 

**Dear reviewer**

I have the following warning when `map_selection=['background']`

```
/Users/jer/git/gammapy/gammapy/gammapy/cube/psf_kernel.py:109: RuntimeWarning: invalid value encountered in true_divide
  img += vals.value / vals.sum().value
```

Tests have not been implemented, but test_coverage has not decreased.

### CODE REVIEW

**Comment by adonath** [comment]
@Bultako I can take a look at the warning in master later...

**Comment by cdeil** [comment]
@Bultako - Thanks!

Maybe change the default to `['counts', 'exposure', 'background']` to be consistent with the code?

https://docs.gammapy.org/0.14/api/gammapy.cube.MapMaker.html#gammapy.cube.MapMaker.run

And maybe adapt one of the existing tests to run with `selection = ['exposure', 'background']` and assert after that `counts` isn't set? I'm not sure if that is a good idea / easy. If not, just don't test this new setting, it should work OK.

**Comment by cdeil** [comment]
If you want excellent error messages, I think you'd have to introduce either an `Enum`, or write a validate method. You know, if someone puts `selection = ["spam"]` in the config. Also something that's nice to have, not must have, like the test.

**Comment by adonath** [comment]
@cdeil and @Bultako  The new default is to compute all maps  `["counts", "background", "exposure", "edisp", "psf"]`, see here: https://docs.gammapy.org/dev/api/gammapy.cube.MapDatasetMaker.html#gammapy.cube.MapDatasetMaker

**Comment by cdeil** [comment]
@Bultako - You can import and put `MapDatasetMaker.available_selection` as default.
```
In [1]: from gammapy.cube import MapDatasetMaker                                                                                                             

In [2]: MapDatasetMaker.available_selection                                                                                                                  
Out[2]: ['counts', 'exposure', 'background', 'psf', 'edisp']
```
We'll have to talk about how to keep config and options consistent between AnalysisConfig and the rest of Gammapy, but for now, importing things and setting them as default in `gammapy/analysis/config.py` is the way to go, no?

**Comment by adonath** [comment]
@cdeil I agree maintaining the defaults in `config.py` is the way to go in future...

**Comment by cdeil** [comment]
> I agree maintaining the defaults in config.py is the way to go in future...

Here I was suggesting the opposite. To import the available options from `MapDatasetMaker` and set them also in `config.py`. So `gammapy.analysis.config` is high-level, importing defaults from lower-level places.
Maintaining configs in `config.py` would mean to import `gammapy.analysis.config` in `gammapy.cube` and other places.
It's not clear to me which way to go in Gammapy, how to integrate low- and high-level better.

I think for now for v0.15, we should go the way to import in `config.py` from other places in Gammapy.

@adonath @Bultako  - Agreed? Or go the other way?

**Comment by adonath** [comment]
> I think for now for v0.15, we should go the way to import in config.py from other places in Gammapy.

I agree. Importing from `config.py` will create a lot of circular imports now. So let' avoid it and import from the lower level...

**Pull request merged**
