### PR TITLE
Add note for past releases of docs

### PR DESCRIPTION
**Pull request by Bultako**
This PR adds a small code snippet to `docs/_static/copybutton.js`, so one small note will be inserted  dynamically for all versions of the docs that are not (and will not be in the future) the latest version of the docs.

At this moment these are: 0.6, 0.7, 0.8.

The chosen file is one of the few JS files present in those three versions of he docs, and also in dev. If agreed, next step will be to copy this file in `gammapy-docs` repository.

Screenshots to illustrate:

captura de pantalla 2018-10-04 a las 10 49 52

captura de pantalla 2018-10-04 a las 10 51 49

### CODE REVIEW

**Comment by cdeil** [comment]
We definitely want something like this.

I think probably we should always suggest the latest stable version of the docs to users?
That's what others do:

http://flask.pocoo.org/docs/0.12/
https://docs.djangoproject.com/en/1.10/
https://robpol86.github.io/sphinxcontrib-versioning/v1.1.0/github_pages.html

**Comment by Bultako** [comment]
@cdeil 

Yep.
I've made the modifs, so now it fetches the last stable version and displays it in the link.

**Comment by cdeil** [comment]
I've done the corresponding change to gammapy.org in
https://github.com/gammapy/gammapy-webpage/commit/f3a5371de3eb7f27272a5def95bf880b8aa6d52a

**Comment by cdeil** [comment]
One more change as discussed: only link to the stable docs now: https://github.com/gammapy/gammapy-webpage/commit/6b157f42618f070643f89dfb0e95b812ec8f0e1b

**Pull request merged**
