### PR TITLE
Remove switch for chosing between light/dark themes in docs

### PR DESCRIPTION
**Pull request by morcuended**
**Description**

This pull request simply removes the possibility of switching among light or dark themes for the documentation in the sphinx configuration (options in `"navbar_end"`).

**Dear reviewer**

The current dev version of the documentation still allows to switch between dark and light modes, while it was decided to only support and force the use of the light one. If not supported, it should not be possible to change it. See #5191.

If later on we decide to support the dark mode, we can bring this option back.

### CODE REVIEW

**Review by bkhelifi — APPROVED** [review]
Thanks a lot. If the css can not be changed, this is a better to remove this option

**Comment by Astro-Kirsty** [comment]
The docs look good!

**Comment by bkhelifi** [comment]
I am wondering whether one should not add an issue to offer back the dark theme by changing the css... One of the issues was the text color in this case. To be investaged for the v2.0

**Comment by morcuended** [comment]
> I am wondering whether one should not add an issue to offer back the dark theme by changing the css... One of the issues was the text color in this case. To be investaged for the v2.0

Yes, definitely

**Comment by Astro-Kirsty** [comment]
See https://github.com/gammapy/gammapy/issues/5520 for this new issue

**Pull request merged**
