### PR TITLE
Improve docstring of LogParabola model

### PR DESCRIPTION
**Pull request by joleroi**
See #1155

### CODE REVIEW

**Comment by joleroi** [comment]
@cdeil Good point, it was still wrong. I updated the reference. @cosimoNigro - do you agree with these changes?

**Comment by cosimoNigro** [comment]
Yes it's perfect, Thank you @joleroi!

**Comment by joleroi** [comment]
@cdeil Merging is blocked because your review is missing. Can you give green light or just merge yourself?

**Comment by cdeil** [comment]
Ah, OK. So if a commit is added, Github discards the previous PR approval. Makes sense.
I'll merge now. For the future: of course if it's clear, you can just merge yourself.

**Comment by joleroi** [comment]
> For the future: of course if it's clear, you can just merge yourself.

Somehow this wasn't possible (the merge button was inactive)

**Comment by cdeil** [comment]
@joleroi - If you read the fineprint near the merge button, you'll see that you can still merge by clicking a few times. Nevertheless, I've changed your role just now to "owner" for github.com/gammapy , i.e. you can from now on do owner things like adjust permissions for others etc.

**Pull request merged**
