### PR TITLE
Implement peek methods for map evaluator and psf kernel

### PR DESCRIPTION
**Pull request by luca-giunti**
**Description**

This pull request overrides #4074 (due to merge conflicts)

### CODE REVIEW

**Review by registerrier — COMMENTED** [review]
Thanks @luca-giunti .

Looks good to me. You might just add a test for `MapEvaluator.peek()` with a `WcsNDMap` based dataset.

**Comment by luca-giunti** [comment]
I added the requested test. Probably we could make a better use of fixtures to save lines of code, but I guess it's a general issue that will be addressed consistently at some point

**Comment by adonath** [comment]
@luca-giunti Yes I agree, refactoring of tests should be a priority after v1.0!

**Review by adonath — APPROVED** [review]
Thanks @luca-giunti, no further comments from my side!

**Pull request merged**
