### PR TITLE
MCMC tutorial with emcee

### PR DESCRIPTION
**Pull request by facero**
A first PR for the MCMC tutorial with emcee mentioned in #1923. This is in fact a very nice showcase of the power of the recent `dataset` class !

The notebook simulates a dataset with `gammapy.cube.simulate.simulate_dataset`, runs a chain of walkers, and plots results.
The interface needed with emcee was to define a prior function and a Likelihood function. This was relatively simple thanks to `Dataset` (once you figure out whether you need a + or - for the likelihood ...).

I have many questions and there are many things to improve but the first thing that we should decide is: <br> What is the best spectral model to test here ?
I started with a bright source (Norm=5e-12) and Ecut=50 TeV for 20h. Should we try a fainter source, a higher Ecut (100 TeV ?). It seems to reconstruct the parameters well but I want to try PeVatrons and/or fainter sources but maybe this is not the point of this tutorial. Any thoughts ?

Then there are several things that could be improved :

- How do I update the sky model of an existing dataset ?
This `dataset.model = sky_model` updates the model but the dataset gives always the same likelihood, independently of the new model like if its not reading it.

- Once I understand this, it is simple to compute the Npred for each sampler chain and overlay the sample models on top of the data.

- Currently bkg parameters can be included in the Likelihood as they do not appear in dataset.parameters.free_parameter. This is normal are these parameters are in dataset.background_model.parameters. Not sure how to access them easily. Freezing Bkg parameter for now.

### CODE REVIEW

**Comment by adonath** [comment]
Thank you very much @facero. This is indeed a very nice show-case for the `MapDataset`.

Just a few preliminary comments:

- In https://github.com/gammapy/gammapy/commit/1ae6f22597133f4cd5af266b6e563d9594fd0772 I implemented a setter for `MapDataset.model`. Because of #2071, the model were cached and not updated, when the model was changed. This is solved now.

- Can you run `gammapy jupyter --src tutorials/MCMC_fitting.ipynb strip` to remove the output cells. The notebook will be executed and rendered as part of our docs build. And maybe also run gammapy jupyter --src tutorials/MCMC_fitting.ipynb black` to apply a uniform code style to the code cells.

- A nitpicky moment: maybe rename the notebook to `mcmc_sampling.ipynb`. I think (strictly
speaking) running an MCMC sampler is not a fitting in a classical sense.  


The problem concerning the background parameters I didn't understand yet. If the background parameters are free they should be included in `MapDataset.parameters.free_parameters` and are available for sampling as well. 

Concerning which spectral model to use I don't have a strong opinion. I think this tutorial does not have to show a scientifically super meaningful analysis. I think assuming any plausible spectral model is probably fine.

**Comment by facero** [comment]
Thanks ! I will implement those changes.
I've just retried the bkg stuff and indeed it now works. I can now have norm and tilt in MCMC. Maybe somthing has changed recenlty. The norm and tilt param were not showing in free_param during the sprint.

One thing still is when doing `print(dataset.model)` the bkg param do not appear as they are not part of a Skymodel. From a user point of view I would like to see all the param from my model (SKy or not Sky).

 
@registerrier , @cdeil  any other comments ?

**Comment by adonath** [comment]
@facero You can alway print the full parameter list using:

```python3
print(dataset.parameters)
```

Or print the background model separately:

```python3
print(dataset.background_model)
```

One thing that is currently missing in Gammapy is the back-reference of parameters to their models and datasets they belong to. Once we have this we can add a nicer API to work with the global model parameter list.

**Comment by facero** [comment]
Indeed the `print(dataset.parameters)` works but it doesn't have the nice print that `print(dataset.model)` has but it might be related to what you mention.

**Comment by facero** [comment]
@adonath I'e updated the notebook (strip, black) and added a cool plot showing the SED of 100s of samples:
MCMC

**Comment by registerrier** [comment]
Hi @facero . We should merge the PR first.

**Comment by adonath** [comment]
@registerrier Do you have any further comments? From my side it's OK to merge.

**Comment by registerrier** [comment]
OK to merge from my side too. There is an unrelated Travis fail. But as far as I can see the notebook introduced by this PR is not tested in the tutorial check. Is it expected?

**Comment by adonath** [comment]
Thanks @registerrier, you're right. I just added the notebook to the index file. Let's wait for Travis-CI to finish the testing and then merge...

**Comment by Bultako** [comment]
Just a small reminder, if you want to make it visible in the docs, we also need to provide a link somewhere in the RST files. For example in `docs/tutorials.rst`.

> Thanks @registerrier, you're right. I just added the notebook to the index file.

**Comment by adonath** [comment]
Thanks @Bultako, I just linked the notebook in the docs.

**Comment by facero** [comment]
apparently Travis CI failed because of fermipy related tests. how do you handle this usually ?

**Comment by adonath** [comment]
@cdeil already opened PR: https://github.com/fermiPy/fermipy/pull/273

**Comment by facero** [comment]
is this PR blocked because of the fermipy issue ?

**Comment by adonath** [comment]
@facero No, it was blocked because of busy maintainers :-). I'll merge now...

**Pull request merged**
