### PR TITLE
Remove spectrum butterfly class

### PR DESCRIPTION
**Pull request by cdeil**
This PR removes the spectrum butterfly class.

It was implemented as a QTable sub-class with one method `plot` added in, which was duplicating the code in `SpectralModel.plot_error`. (I'll fix an issue in `SpectralModel.plot_error` in a separate PR, that's how I stumbled on this code).

We can always re-introduce `SpectrumButterfly` later (with a table member instead of as a Table sub-class) if we find it useful, but for now I'd suggest we remove it (to avoid the code duplication with `SpectralModel.plot_error`

@adonath @joleroi - Thoughts?

### CODE REVIEW

**Comment by cdeil** [comment]
I made the fix for SpectralModel.plot_error directly in master: a97eb548
It fixes the plotting issue for all butterflies in gamma-cat: https://github.com/cdeil/gamma-cat-status/commit/dfe3757751a66bc7a5f9b14cce0cc4f4adf5b55d
I think this could be considered an MPL bug, so I also filed an issue in the MPL tracker: https://github.com/matplotlib/matplotlib/issues/8623

**Comment by adonath** [comment]
+1 To remove the current `SpectrumButterfly` class. It doesn't hold up to our implementation standards and doesn't offer any useful extra features. I'm not even sure if we need a `SpectrumButterfly` class at all...maybe this can be just handled by an improved `TableModel` or `SpectralTemplate` class.

Currently the `spectrum_simulation_cta.ipynb` notebook is not working...because of a call to `SpectrumButterfly.plot()`

**Comment by cdeil** [comment]
I'm merging this now, and will fix spectrum_simulation_cta.ipynb next.

**Comment by cdeil** [comment]
Notebook adapted in https://github.com/gammapy/gammapy-extra/commit/1fc5bf636799718041718b4da3256b70bfb88af6

**Pull request merged**
