### PR TITLE
Follow-up PR on Lomb Scargle detect function

### PR DESCRIPTION
**Pull request by wegenmat**
This is a follow-up PR from #1070 that adds the Lomb Scargle periodogram and a plot function to `gammapy.time`.

The changes of  f2cd0cc1d63116c18bb69cdcfce629561ce42d6d are appoved.
Additionally, following improvements are implemented.

- fixed bug in cvm-significance, 
- replaced long reference link of Sueveges by shorter one,
- reduced test cases for lomb_scargle and plot_periodogram to only one minimal working example, resulting in a test time of < 10s.

Following issues occured:
- The plotting style in library functions was previously changed to be set by the user, which causes the Latex-formatted labels to appear as raw string, eg `\textbf{period}` instead of proper Latex font.
- The significances of the period are ~ 100 %. There should be a possibility to relativse this, i.e. in comparison to the 2nd highest periodogram peak or by returning all peaks exceeding a defined significance rather than returning the significance of a single peak.

### CODE REVIEW

**Comment by cdeil** [comment]
@wegenmat - Thanks!

> fixed bug in cvm-significance

It's a bad sign that you fixed a bug but didn't have to update the reference values in the tests.
Can you change or extend the tests so that the bahaviour of this and the other functions is really established by a numerical `assert_allclose`?

> Latex

Please get rid of LaTeX in the labels. I can see how it can be nice, but not everyone has it installed / working, and it's not supported for all output formats (e.g. SVG for the web).
So not using LaTeX from Gammapy is the simple / safe thing to do.
Note that users that want it can still set it with one or two lines after calling our plot function.

**Comment by cdeil** [comment]
@wegenmat - One more thing: currently both the module is called `lomb_scargle` (i.e. the file is called `lomb_scargle.py`) and the function is called `lomb_scargle`. That causes a warning in the docs build, and it is also confusing to users, because it's not obvious that `import gammapy.time.lomb_scargle` imports the function, not the module, and it's not easily possible to get at the module at all. In general this is something best avoided, to have the same name for the module and the function.

There's two options here: change the name of the function or the module. I don't care either way, @wegenmat please choose and apply the change in this PR. A possible rename of the function could be `compute_lomb_scargle` or `run_lomb_scargle`. A possible rename of the module could be `period.py` or something else more general if other things are added there in the future. Or just `ls.py` as shortcut for `lomb_scargle.py` to avoid the naming conflict.

**Comment by wegenmat** [comment]
- removed Latex from plot labels
- established `asser_allclose` for returned significance criteria (this demands for significances to always be finite, so their computation was improved)
- renamed `lomb_scargle.py` to more general `period.py` to avoid name conflicts and allow for future period detection functions to be added there

**Comment by cdeil** [comment]
@wegenmat - Thanks!

Diff looks good to me. I'm merging this in, and will then see if Faissal has time to review in the coming days.

**Comment by cdeil** [comment]
@wegenmat - I did some more polishing of the code in a follow-up commit in master: b47634d7
The diff is only so large because I moved the `lomb_scargle` function from the bottom to the top of the file, because I think that's where one should start to read, and only then read the helper functions. For the tests, I changed to 10 bootstrap samples to be faster.

**Pull request merged**
