### PR TITLE
Add AbsorbedSpectralModel class

### PR DESCRIPTION
**Pull request by jjlk**
Hi @cdeil and @joleroi , 

I added a small class, `AbsorbedSpectralModel`, which takes in input one `SpectralModel` and one `TableModel` objects. Only the `evaluate` method is implemented for now. I also added a test.

For now it does not handle sherpa stuff for fitting, it's the basic implementation to be able to do some predictions at very high energy (step 1). Do you mind if we merge it as it is, since people might be interrested in things like that?

I'll discuss tomorrow with @registerrier to see if it's possible to find an easy way to fit together the parameter from the `TableModel` and the parameters of the models (à la sherpa, step 2).

Step 1 is fine for now.

See ya! ++

### CODE REVIEW

**Comment by cdeil** [comment]
At the moment you've put this:
```python
    def evaluate(self, energy):
        flux = self.spectral_model.__call__(energy)
        absorption = self.table_model.__call__(energy)
        return flux * absorption
```

I think it should be either this
```python
    def evaluate(self, energy):
        flux = self.spectral_model(energy)
        absorption = self.table_model(energy)
        return flux * absorption
```
or this
```python
    def evaluate(self, energy):
        flux = self.spectral_model.evaluate(energy)
        absorption = self.table_model.evaluate(energy)
        return flux * absorption
```

At the moment all three give the same output, but once we adopt proper Parameter / Model classes, `__call__` will be a sophisticated wrapper around `evaluate`.
In any case, the way Python classes with `__call__` defined are supposed to be used is to use them like functions, i.e. just call them:
```python
model = Model()
val = model(par=42) # executes `model.__call__(self=model, par=42)` under the hood
```

If you don't have an opinion, I'd suggest to call `evaluate` on the components for now.

**Comment by cdeil** [comment]
For the test, I'd suggest to make it simpler / faster / shorter by:
- making a table model with ~ 3 nodes directly instead of reading a file from disk
- just asserting on one or two result values, instead of re-coding the implementation of evaluate (a product) in the test.
- If you want values that can be verified to be really correct, you could use a simple PL with index 2 or 0, and evaluate it at energies of 1 and 10, where it's possible to get the right values in your head. And for the absorption model you could do the same, e.g. make it a two-node model with absorption 0.5 at 1 TeV and 0.1 at 10 TeV.

Both of my comments are suggestions, not blockers. I'm signing off on this PR now and unsubscribe because I'm very busy this week. @joleroi or @jjlk - Feel free to merge anytime.

**Comment by joleroi** [comment]
> I'll discuss tomorrow with @registerrier to see if it's possible to find an easy way to fit together the parameter from the TableModel and the parameters of the models (à la sherpa, step 2).

FYI: I was working with @adonath to find a general solution to fit our model with Sherpa, but we got stuck here. https://github.com/astropy/astropy/issues/5615

Let me know if you want to adress @cdeil's comment or ignore them, so I can merge :wink:

**Comment by jjlk** [comment]
Hi @joleroi ,
I changed the `x.__call__` function to `x()`, as suggested by @cdeil . I didn't use the `x.evaluate` function because it requires all the arguments from the model I used (they have no default values) and we are not suposed to know wich model is used inside the `AbsorbedSpectralModel` class, right?.

For the test I agree that it could be much simpler and less time consuming, but do you mind if we merge it as it is for now @joleroi ? I'll fixed that later =)

> FYI: I was working with @adonath to find a general solution to fit our model with Sherpa, but we got stuck here. astropy/astropy#5615

Ok. I'm not used at all to sherpa. But I guess that it is something we have to work on to have a convenient way to deal with models. Not sure to have a lot of time to give in the next days but I'll try!

Thanks

**Comment by jjlk** [comment]
I close this issue because things have already be implemented in PR #842.

I still have to improve the `TableModel` class by getting ride of the tests dealing with existence of array or not. It will be done in an other PR.

**Pull request closed without merging**
