### PR TITLE
Fix rst testcode

### PR DESCRIPTION
**Pull request by MRegeard**
This PR is related to #5480.

I run `pytest --doctest-glob="*.rst" docs/user-guide/*` and fix the output diff caused by numpy 2.

### CODE REVIEW

**Review by bkhelifi — APPROVED** [review]

**Comment by bkhelifi** [comment]
@MRegeard can you update your branch and check the tests?

**Comment by Astro-Kirsty** [comment]
Thanks Maxime, but can you run it on all rst:
`pytest --doctest-glob="*.rst" docs/`

There are some other code tests which are failing on this branch :)

**Review by bkhelifi — APPROVED** [review]
Thanks

**Review by registerrier — APPROVED** [review]
Thanks @MRegeard !

**Pull request merged**
