### PR TITLE
Add normalize attribute to `TemplateSpatialModel` serialization

### PR DESCRIPTION
**Pull request by QRemy**

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @QRemy! Please provide a short description (one sentence...) of the content of the PR next time...

 I was wondering whether we should remove the `normalize` argument completely. I think the Fermi XML spec does not have such an argument either. What do you think?

**Comment by QRemy** [comment]
I think it's useful to keep this option.  For example you want to have the normalize False when using  a gas map, but True when fitting a morphological template obtained form residuals.

**Comment by adonath** [comment]
@QRemy I agree. I just checked with @cdeil, that the Fermi Science Tools as well as gammalib have similar options:
- `"map_based_integral"` (https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/xml_model_defs.html#SpatialMap)
- `"normalize"` (http://cta.irap.omp.eu/gammalib-devel/doxygen/classGModelSpatialDiffuseMap.html#afb99a59c33796fd7c4b9573c6a25a084)

So let's keep it. I have two minor comments then:
- Please rebase after #2353
- Remove the in place `.normalize()` method and move the code to `__init__()` in the `if normalize:` block . Then rename the parameter consistently (in the serialisation as well) to `normalize`.

**Comment by cdeil** [comment]
@qremy or @adonath when you merge this in: could you please change to consistent `normalize` with `z` also in `gammapy/irf/psf_check.py` and the docstrings?
See  https://gist.github.com/cdeil/b4b97a5f029ae7123f1ad2b69dab52aa#file-gistfile1-txt-L15

(we already decided and changed to consistent `optimize`, `serialize`, ...)

**Comment by adonath** [comment]
Thanks @QRemy!

**Pull request merged**
