### PR TITLE
fix cube_pipe test

### PR DESCRIPTION
**Pull request by JouvinLea**
@cdeil @adonath 
The cube pipe class was broken. Since there was an xfail on the test, nobody noticed ....
I fixed the issue with the exposure unit and I fix the test. I have to change the ```empy_like``` method of the ```SkyCube```class but I think there was a mistake. Indeed when you were creating the Skycube at the end if the data have unit you multiply again by u.unit so there was an issue for the exposure because it was in m4s-2 when you were calling empty_like....

I had to change the value for the total exposure in the test, this is not a big change but I don't know exactly why....

### CODE REVIEW

**Comment by adonath** [comment]
@JouvinLea Thanks!

Indeed I haven't thought about the unit handling in `SkyCube.empty_like()`, when introducing #935. When I think about it again, I'd suggest to do the following:

- add a `unit` argument to `SkyCube.empty_like()` with default `unit=''`
- remove the unit taken from the reference `SkyCube` or `SkyImage`

This way the user has to specify a unit on init, or get's a cube with dimensionless units, which makes more sense as the current behaviour (where the unit is the same as the reference).

Currently `SkyImage.data` is a plain numpy array, but `SkyCube.data` is a quantity, that's why Travis-CI fails.

**Comment by adonath** [comment]
@JouvinLea If you have time could check whether re-activating `test_image_pipe()` works as well. See also #900.

**Comment by JouvinLea** [comment]
@adonath 
I made the changes!! Is is fine?
 For test_image_pipe it works for me locally so this is weird, what is the error you get?

**Comment by adonath** [comment]
Yes, the changes are fine!

Concerning the test fail on Travis-CI I'm a bit puzzled. It seems like the tests fail on Mac OS only, which I've never seen before. See [here](https://travis-ci.org/gammapy/gammapy/jobs/208693418#L923) and [here](https://travis-ci.org/gammapy/gammapy/jobs/208693419#L915). Maybe @cdeil has an idea what could cause test fails on Mac OS only?

**Comment by adonath** [comment]
Maybe #925 is related as well?

**Comment by cdeil** [comment]
I think this is the same issue as #925.
In principle rewriting the background classes to use NDDataArray is the proper solution.
I did not try to track down why we get NaN values on Mac only.
Probably the extrapolation behaviour of whatever interpolator we call at the moment is not well defined.

I can look into this issue in the coming days.
If someone has a short snippet to reproduce the issue quickly for testing, that would help.
But probably it's best if I just debug that, as I do see the issue locally.

**Comment by JouvinLea** [comment]
@cdeil @adonath 
But I have a Mac and I don't have any issue...

**Comment by cdeil** [comment]
@JouvinLea - we can't merge things that break continuous integration in master.
So my suggestion here would be that you just don't remove the `xfail` here, and leave a comment in #925 that this still needs to be done, with a link to the travis-ci build that shows the fail.
It would also be great if you could squash the commits here into one. Having a git history where we xfail the text, then re-activate it, then x-fail again, then in the future re-activate it is confusing, so it's best to squash such changes before merging things in master.

@adonath - are you happy with the fixes implemented here, i.e. if @JouvinLea does this change, can this go in?

**Comment by JouvinLea** [comment]
@cdeil @adonath 
I squashed the commits and put the xfail again.
The failing test are not linked to this PR right?

**Comment by adonath** [comment]
@JouvinLea Yes, the Travis-CI fail is unrelated. I'll merge the PR now. Thanks!

**Pull request merged**
