### PR TITLE
Adapt tutorial figure handling

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request is a follow up to #4174. It adapts the following:

- Do not use `plt.figure()` where figures are created internally
- Use `display()` to show tables. This defaults to prints for scripts and html for notebooks (however I noticed it does not seem to work with sphinx gallery....)
- Call `plt.show()` at the end of tutorials to make sure plots are shown when executed as script.

ToDo:
- [x] Adapt `data` tutorials
- [x] Adapt `api` tutorials

### CODE REVIEW

**Comment by registerrier** [comment]
data and API tutorials have been adapted along the same lines.
conf.py has been modified but the `display` function does not yield better output.

**Comment by registerrier** [comment]
Also is there a simple way to split code cells to avoid having three consecutive `print` that are display all at once. See e.g.
https://github.com/gammapy/gammapy/blob/89b9fc79727e3ef5323fffed8e8d1f19a97338fc/examples/tutorials/api/models.py#L426

**Comment by adonath** [comment]
@registerrier I think you can use:
```python3
# %%
msg = "Hello World"
print(msg)

# %%
msg = "Hello again"
print(msg)

```

**Comment by registerrier** [comment]
Thanks @adonath , it works. It looks much better like this

**Review by registerrier — APPROVED** [review]
Thanks @adonath . This looks good.

**Pull request merged**
