### PR TITLE
Python 3 tests exit with code 247 on travis-ci

### PR DESCRIPTION
**Pull request by cdeil**
Since today the Gammapy Python 3 tests fail on travis-ci ... they simply abort with exit code 247, e.g. in `test_diffuse.py` or `test_flux_point.py`:

https://travis-ci.org/gammapy/gammapy/jobs/46076272#L2124
https://travis-ci.org/gammapy/gammapy/jobs/46079771#L2124

Most likely the issue is a segfault in `numpy` (called via `Quantity`).

@astrofrog @eteq Have you seen this with Astropy or other affiliated packages? Do you know how to debug this, e.g. how to get a C traceback printed to the log?

I'll try to reproduce it in an Ubuntu VM locally now ...

### CODE REVIEW

**Comment by cdeil** [comment]
The issue is that this test uses roughly as much memory as there is available on travis-ci, which causes a `MemoryError` which causes the `python` process running the tests to be killed.

To reproduce:

time python setup.py test -V -t gammapy/spectrum/tests/test_flux_point.py -a '-k test_compute_differential_flux_points -s'

```python
import gammapy.spectrum.tests.test_flux_point as t
t.test_compute_differential_flux_points(x_method='table', y_method='model')
```

The issue is that this function isn't vectorised and uses lists to process `1e6` "segments":
```python
xmin = <Column name='ENERGY_MIN' unit=None format=None description=None>
array([  1.,  10.])
xmax = <Column name='ENERGY_MAX' unit=None format=None description=None>
array([  10.,  100.])
function = <function test_compute_differential_flux_points.<locals>.diff_flux_model at 0x7f06b673fbf8>, segments = 1000000.0
 
    def _integrate(xmin, xmax, function, segments=1e6):
        """Integrates method function using the trapezium rule between xmin and xmax.
        """
        indices = np.arange(len(xmin))
        y_values = []
        for index in indices:
>           x_vals = np.arange(xmin[index], xmax[index], 1.0 / segments)
E           MemoryError
 
gammapy/spectrum/flux_point.py:178: MemoryError
```

**Comment by cdeil** [comment]
For future reference: with  https://github.com/astrofrog/psrecord it's super-easy to make a plot how much CPU and memory are used while running the tests ... here's the results for Gammapy after reducing `nsegments` to `1e3` for the problematic test here:
```
psrecord 'python setup.py test' --log record.log --plot record.png --include-children
```
image

**Comment by cdeil** [comment]
Just for fun ... here's what the Astropy build looks like:
record

It looks reasonable.
And it's nice to see there's all cores used in the Gammapy tests that use multiprocessing (TS map computation).

**Comment by eteq** [comment]
@cdeil - I have not seen this before, but good you figured it out - thanks for the graphs for astropy too.  Out of curiosity, was the memory limit you were hitting 3GB (which I think is the travis VMs limit), or some lower barrier?

**Comment by cdeil** [comment]
@eteq - Yes ... the Gammapy tests were right at the limit of 3 GB for Python 3 and thus failed in random, but nearby tests shortly after the one that used so much memory because of an implementation error.

I emailed travis-ci support and they gave me ssh access to a VM to debug this a day later, but using Docker containers locally is quicker and should work in 99% of cases. I've taken notes on how to replay the commands that run on travis-ci here:
https://github.com/gammapy/gammapy/tree/master/dev/docker

**Pull request merged**
