### PR TITLE
Add norm background table

### PR DESCRIPTION
**Pull request by JouvinLea**
This PR save in a Table the background normalization for each run when we compute the images for a set of runs.

### CODE REVIEW

**Comment by JouvinLea** [comment]
@cdeil 
If you agree with the API is it ok to merge? The failed test oin Travis is not due to what I changed in this PR

**Comment by cdeil** [comment]
Can you name the field `bkg_scale`, please?

This is the field name @mimayer uses for ParisAnalysis obs tables already:
http://gamma-astro-data-formats.readthedocs.io/en/latest/data_storage/obs_index/index.html#notes

And ideally there would be a test with an assert statement on the `bkg_scale` for one or two runs from a test dataset.

**Comment by JouvinLea** [comment]
Done!!! is it better?

**Comment by cdeil** [comment]
Thank you!

**Pull request merged**
