### PR TITLE
Extend options for energy thresholds

### PR DESCRIPTION
**Pull request by lmohrmann**
This PR adds more options to define energy thresholds for `SpectrumObservation` objects. For now, I only added the possibility to define the `hi_threshold` in the same way as is possible for the `lo_threshold`. I will probably add more if I find the time, but this could be merged already.

Note that I also added options to reset the energy thresholds.

### CODE REVIEW

**Comment by lmohrmann** [comment]
I also added the option to define the energy threshold via the energy bias. Note that I needed to pull in the changes made in PR #1120.

**Comment by joleroi** [comment]
One general comment: I don't think the calculation of energy thresholds should happen in ``SpectrumExtraction``. I know that there was such functionality before and you just extended it, but I never liked it this way. The reason is quite simple. All information that is needed to compute an energy threshold is contained in the ``SpectrumObservation``. Therefore there should be a ``EnergyThresholdComputer`` class (I just made up that name, it can be different) that takes a ``SpectrumObservation`` as input and calculates the energy thresholds.
That way it is also possible to test different methods to compute an energy threshold for an observation that is e.g. saved to disk. Right now you would have to run the SpectrumExtraction every time.

That said, I am fine with merging this PR if @lmohrmann needs the functionality and does not have the time so set up the threshold computation the way I suggested (or does not want to because the disagrees).

**Comment by lmohrmann** [comment]
@joleroi Well, I did move the computation to `SpectrumObservation`. The `compute_energy_threshold` function in `SpectrumExtraction` simply calls the routine that is implemented in `SpectrumObservation`. I guess one could also implement this using a separate class as you suggest, but that seems to be a minor detail to me (?).

**Comment by joleroi** [comment]
@lmohrmann 
As long as the ``compute_energy_threshold`` just calls functionality that is implemented in the "right" place, it's fine for me. The new ``compute_energy_threshold`` method is already quite long and will probably grow, so at some point in the future it might need to be turned into a class, but probably not now.

**Comment by cdeil** [comment]
I'm seeing this fail in master:
```
$ python -m pytest -v gammapy/time/tests/test_lightcurve.py

<snip>

   @pytest.fixture(scope='session')
    def spec_extraction():
        data_store = DataStore.from_dir('$GAMMAPY_EXTRA/datasets/hess-crab4-hd-hap-prod2/')
        obs_ids = [23523, 23526]
        obs_list = data_store.obs_list(obs_ids)
    
        target_position = SkyCoord(ra=83.63308, dec=22.01450, unit='deg')
        on_region_radius = Angle('0.11 deg')
        on_region = CircleSkyRegion(center=target_position, radius=on_region_radius)
        target = Target(on_region=on_region, name='Crab', tag='ana_crab')
    
        exclusion_file = '$GAMMAPY_EXTRA/datasets/exclusion_masks/tevcat_exclusion.fits'
        allsky_mask = SkyImage.read(exclusion_file)
        exclusion_mask = allsky_mask.cutout(
            position=target.on_region.center,
            size=Angle('6 deg'),
        )
        bkg_estimator = ReflectedRegionsBackgroundEstimator(on_region=on_region,
                                                            obs_list=obs_list,
                                                            exclusion_mask=exclusion_mask)
        bkg_estimator.run()
    
        e_reco = EnergyBounds.equal_log_spacing(0.2, 100, 50, unit='TeV')  # fine binning
        e_true = EnergyBounds.equal_log_spacing(0.05, 100, 200, unit='TeV')
        extraction = SpectrumExtraction(obs_list=obs_list,
                                        bkg_estimate=bkg_estimator.result,
                                        containment_correction=False,
                                        e_reco=e_reco,
                                        e_true=e_true)
        extraction.run()
>       extraction.define_energy_threshold('area_max', percent=10.0)
E       AttributeError: 'SpectrumExtraction' object has no attribute 'define_energy_threshold'

gammapy/time/tests/test_lightcurve.py:82: AttributeError
```
@joleroi or @lmohrmann - can one of you please fix? (commit directly to master would be OK in this case)

**Comment by lmohrmann** [comment]
The method is now called `compute_energy_threshold`, and the arguments should be `method_lo='area_max', method_hi='area_max', area_percent_lo=10.0, area_percent_hi=10.0`. Just now I'm realizing that currently, it's no longer possible to e.g. not apply a high energy threshold at all. That's probably not ideal, I can make a PR for this later today (and include the changes required to make the test work).

**Comment by cdeil** [comment]
@lmohrmann - OK, thanks!
Yes, if it's more than a change for this one caller, better to go through a PR.

**Comment by lmohrmann** [comment]
Done, see #1124

**Pull request merged**
