### PR TITLE
Make non-FITS table file from FluxPoints overwritable

### LINKED ISSUE #5253: FluxPoints.write() is ignoring overwrite when file extension is not FITS
**Gammapy version**

1.2

**Bug description**

When writing a `FluxPoints` table (_.ecsv_) to file it is not possible to overwrite it.

**Expected behavior**

The `overwrite` argument should be taken into account.

**To Reproduce**

From any analysis get a `FluxPoints` instance (in my case it was from obtained from `LightCurveEstimator.run()`)
and call the `write()` method with `overwrite=True`.

You will get the following error,

`OSError: File xxxxxx.ecsv already exists. If you mean to replace it then use the argument "overwrite=True".`

**Other information**

The bug is here: https://github.com/gammapy/gammapy/blob/2475a006e02ac1497eccc362de61e68a5f7a10eb/gammapy/estimators/points/core.py#L270

It should be sufficient to pass the `overwrite` argument to `table.write()`, because the default (inherited from `astropy.table.Table.write()`) is `False`.

### PR DESCRIPTION
**Pull request by HealthyPear**
**Description**

See #5253.

Propagated `astropy.table.Table.write()` overwrite to `FluxPoints.write()` when file extension is not `.fits`.

This pull request closes #5253.

### CODE REVIEW

**Review by registerrier — APPROVED** [review]
Thanks @HealthyPear . This looks good. Could you maybe check why the test is not failing with the current version?

**Comment by HealthyPear** [comment]
Sure. Could you point me to the test function? I am not familiar with the test suite of this project.

**Comment by registerrier** [comment]
> Sure. Could you point me to the test function? I am not familiar with the test suite of this project.

Here it is:
https://github.com/gammapy/gammapy/blob/2475a006e02ac1497eccc362de61e68a5f7a10eb/gammapy/estimators/points/tests/test_core.py#L213

**Comment by HealthyPear** [comment]
I think the problem is that you are writing that file in the `tmp_path`, but you never stored it there before, you load it from `"$GAMMAPY_DATA/tests/spectrum/flux_points/`, which is not the same path, so there is not overwriting in the first place.

We should either copy the  original file in `tmp_path` (or maybe even touch a dummy one) and only then attempt to write the table file.

**Comment by registerrier** [comment]
> We should either copy the original file in `tmp_path` (or maybe even touch a dummy one) and only then attempt to write the table file.

touching a dummy file with the same name sounds good to me.

**Comment by registerrier** [comment]
This cannot be backported to v1.0.x because export to non-FITS file was not available in v1.0.

https://github.com/gammapy/gammapy/blob/547b342cd5327f851a85899abb4a8ab32fac0809/gammapy/estimators/points/core.py#L174-L179

**Pull request merged**
