### PR TITLE
Change flux map attribute axis type 

### PR DESCRIPTION
**Pull request by registerrier**
**Description**

This pull request changes the axis type of the `FluxMaps.dnde` and `FluxMaps.e2dnde` attributes to `center`. This correctly represents differential quantities.

For now a static methods changes the `MapAxis._node_type` keyword. Possibly it could be better to add a setter on the `MapAxis.node_type` itself.

This solves #3766.

**Dear reviewer**

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @registerrier! Strictly speaking the change of the `_node_type` is not sufficient, because internally the handling of the nodes and interpolation is different for the different node types. However in practice it should still be fine and I think we can go with the solution you propose. If there are maybe the other use cases to change the node type we could introduce a minimal API like:

```
ax = axis.to_node_type("center")
geom = geom.replace_axis(axis=axis)
Map.from_geom(geom=geom, data=m.data)
```
Where the `geom.replace_axis()` already exists.

**Comment by registerrier** [comment]
I have introduced the solution you suggested, which is indeed cleaner.

Yet there is a serious issue since one cannot create `node_type=center` `MapAxis` with only 1 bin. See #1952

**Comment by adonath** [comment]
I realized the situation is a bit tricky here: internally in Gammapy I think we'd like to keep the info on `e_min` and `e_max` even when changing the node type. However especially in the case of one energy bin  the information will be lost, once the node type is changed. So maybe we have to work with an independent `Map.is_differential_quantity` attribute or similar...

**Comment by registerrier** [comment]
Merging now.

**Pull request merged**
