### PR TITLE
Fix stacking of cutouts 

### LINKED ISSUE #3368: Stacking of Map cutouts is erroneous
** Bug description **

If we have 2 maps which are themselves cutouts (eg; maps obtained from our `MapMaker` process), and then we perform a cutout on them

`map1 = dataset1.counts.cutout(dataset1.counts._geom.center_skydir, width=2.0*u.deg)`
`map2 = dataset2.counts.coutout(dataset2.counts._geom.center_skydir, width=2.0*u.deg)`

and then want to stack `map1` and `map2` onto a large target Geom, 

```
counts = Map.from_geom(geom)
cutout = dataset1.counts.cutout(dataset1.counts._geom.center_skydir, width=2.0*u.deg)
counts.stack(cutout)
```

 just stacks in one corner according to the pixel index, forgetting the geometries.

** Reason **

I discussed this privately with @adonath and the reason is that in
https://github.com/gammapy/gammapy/blob/master/gammapy/maps/wcsnd.py#L789 we only check for the alignment of the WCS and not the actual position. So when stacking a cutout from a cutout into the initial geom, the WCS projections are aligned, but the slices are not valid anymore. The slices from the smallest cutout are only valid for the bigger cutout and not the initial parent geometry.

This is a reminder issue to fix before 1.0 release

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request fixes #3368. The fix includes recomputing the slices using `overlap_slices` from `astropy` in a new method called `WcsGeom.cutout_slices()`. This is slightly slower for stacking and cutouts however it should still be fast enough and correct now. This also allows to remove the `cutout_info` completely and simplify the code in this regard.

The PR also adds a unit test, however in general it might be a good idea to improve the testing to cover all cases like partial cutouts etc.

### CODE REVIEW

**Comment by AtreyeeS** [comment]
Just to confirm? Cutouts computed previously will still have the same error, but maps and cutouts created anew should be fine?

**Comment by adonath** [comment]
@AtreyeeS No, the change also fixes the behaviour backwards. Previously we relied on the `cutout_info`, but after having thought about this I realised this is not necessary and slices can be just re-computed based on the `WCS` information instead. Unfortunately I didn't have the idea before and introduced the `cutout_info` instead. So old files will have the `cutout_info` in the header, however it will be just un-used and in new files it is not written anymore.

**Review by AtreyeeS — APPROVED** [review]
Thanks a lot @AtreyeeS ! This fixes the issue as far as I could test

**Comment by adonath** [comment]
Thanks @AtreyeeS, the remaining doc test fail is unrelated...

**Pull request merged**
