### PR TITLE
Add SpectrumEventSampler

### PR DESCRIPTION
**Pull request by joleroi**
This PR add the class ``SpecturmEventSampler`` to draw events according to a given spectral model shape. Tested for PowerLaw and ExponentialCutoffPowerLaw.

### CODE REVIEW

**Comment by cdeil** [comment]
For the power-law, you could call this existing function (even if it's just 2 lines):
http://docs.gammapy.org/en/latest/api/gammapy.utils.random.sample_powerlaw.html

For the general case, the warning that this will give incorrect results for many spectra (assumption should be everything except ECPL) doesn't appear in the public docstrings. If you want, we can put this in, but I would suggest making this caveat visible and leaving a TODO item or open a GH issue that this should be replaced by a more general method:

Compute the inverse CDF on logE grid with 10 or 100 points per decade, then sample uniform and transform using the inverse CDF. That will work for any spectrum, can take any AEFF into account, and you can directly give the number of events you want into one Numpy array call.

**Comment by joleroi** [comment]
> Compute the inverse CDF on logE grid with 10 or 100 points per decade

To do that I would have to get the PDF corresponding to a given spectral model first, right? How would you do that?

**Comment by cdeil** [comment]
I admit that this is not something you do in 1 hour, it takes some work: maybe a full day to have a well-debugged and -tested version?

Roughly you:
1. compute finely binned `n_pred` (like in normal fitting or binned simulation that we have already)
2. normalise `n_pred` to be a `pmf` (divide by sum), then `np.cumsum` to get the `cdf`
3. compute the inverse cdf and interpolate it
4. sample the cdf, using inverse transform sampling

Note that in Gammapy we already have
https://github.com/gammapy/gammapy/tree/master/gammapy/utils/distributions
The main work would be to improve what's there, or to throw it away and start with something small and clean. I'll leave another comment in #74 now with suggestions. (I wanted to work on this for a long time, but it's nowhere near the top of my TODO list).

If you or others need this feature you have heve, you  could just leave a TODO comment and link to #74 and #761 encouraging a better implementation and merge it in now.

**Comment by joleroi** [comment]
I don't think this feature is urgently needed - closing this.

**Pull request closed without merging**
