### PR TITLE
Corrections in docstrings and model definitions

### PR DESCRIPTION
**Pull request by QRemy**
Random corrections in docstrings and model definitions
Merge fast or wait for more ? (maybe check all the model definitions at least)

### CODE REVIEW

**Review by registerrier — APPROVED** [review]
Thanks @QRemy . This looks good!

**Comment by registerrier** [comment]
This type of PR can be merged fast. 
Any idea why there is this error that appears from time to time on MacOS?

**Comment by QRemy** [comment]
same problem as here https://github.com/gammapy/gammapy/pull/3869#issuecomment-1087692091 no ?

**Comment by registerrier** [comment]
Merging. CI fail is unrelated.

**Pull request merged**
