### PR TITLE
Update astropy-helpers to latest master

### PR DESCRIPTION
**Pull request by astrofrog**
This is an automated update of the astropy-helpers submodule to v1.1.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.

*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @astrofrog know!*

### CODE REVIEW

**Comment by cdeil** [comment]
@astrofrog - Thank you!

This astropy-helpers update makes the Gammapy Sphinx build fail:
https://travis-ci.org/gammapy/gammapy/jobs/134452710

This is something @bsipocz and I already noticed a while ago (see #466).
We weren't able to pinpoint or fix the problem, though.

@astrofrog - Do you have time to have a look?

**Comment by astrofrog** [comment]
@cdeil - do you mean this error?

```
/home/travis/build/gammapy/gammapy/build/lib.linux-x86_64-2.7/gammapy/time/plot.py:docstring of gammapy.time.plot_fermi_3fgl_light_curve:35: WARNING: Exception occurred in plotting gammapy-time-plot_fermi_3fgl_light_curve-1
 from /home/travis/build/gammapy/gammapy/docs/api/gammapy.time.plot_fermi_3fgl_light_curve.rst:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "/home/travis/build/gammapy/gammapy/build/lib.linux-x86_64-2.7/gammapy/time/plot.py", line 91, in plot_fermi_3fgl_light_curve
    fermi_cat = fetch_fermi_catalog('3FGL')
  File "/home/travis/build/gammapy/gammapy/build/lib.linux-x86_64-2.7/gammapy/catalog/fermi.py", line 133, in fetch_fermi_catalog
    filename = download_file(url, cache=True)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/utils/data.py", line 1098, in download_file
    raise e
URLError: <urlopen error [Errno 101] Network is unreachable>
```

**Comment by cdeil** [comment]
I missed that error ... restarted that build now.

This Sphinx build doesn't have that error, but still failed:
https://travis-ci.org/gammapy/gammapy/jobs/134452716
Any idea which warning causes the fail?

**Comment by astrofrog** [comment]
Well, there are a lot of warnings... One that looks a little different from the others is:

```
WARNING:gammapy.image.maps:No valid units found for extension None
```

Also, do you use ``OrderedDict`` in ``gammapy``?

**Comment by cdeil** [comment]
> Also, do you use OrderedDict in gammapy?

Yes. We support Python 2.7 and 3 only and import `OrderedDict` directly from `collections`.
That should be an OK thing to do, no?

**Comment by astrofrog** [comment]
@cdeil - yes, I'm just not sure why there are warnings related to that in the docs

**Comment by bsipocz** [comment]
@astrofrog - we see that same warning in the astropy sphinx build as well when running it with python 3.5.

**Comment by bsipocz** [comment]
@cdeil @astrofrog - Looking at the sphninx output again, I think upgrading the helpers to at least to the unreleased 1.1.3 or master will make it pass as there aren't any actual sphinx warnings but somewhat unrelated upstream ones, and https://github.com/astropy/astropy-helpers/pull/223 recognizes it.

**Comment by cdeil** [comment]
I think I slightly favour updating to `astropy-helpers` mater then, to check that it really works with Gammapy. But just closing this PR and updating when then next stable astropy-helpers release occurs would be fine with me as well.

@astrofrog, @bsipocz  - Any preference?

**Comment by astrofrog** [comment]
We might as well check if the latest master version fixes it, so doing that now.

**Comment by cdeil** [comment]
Tests passed on travis-ci.
I"m merging this now.

Thanks!

**Comment by bsipocz** [comment]
@cdeil - I think it's totally fine to use intermediate/master helpers rather than the release even in a released version of a package.

**Pull request merged**
