### PR TITLE
Rename ParameterList to Parameters

### PR DESCRIPTION
**Pull request by cdeil**
This PR renames `ParameterList` to `Parameters`.

The problem with `ParameterList` is that it suggests that this is a list. But it's not a list, you can't e.g. slice into it and it doesn't have other list methods like append, index, insert, reverse, sort.

I considered sub-classing list here, and also sub-classing `OrderedDict`, but decided to pursue this existing direction of having a wrapper class with a small API.

I'll send a follow-up PR shortly that makes the `parameters` attribute private, improving the public API to work with `Parameters`.

### CODE REVIEW

**Comment by joleroi** [comment]
> I'll send a follow-up PR shortly that makes the parameters attribute private, improving the public API to work with Parameters.

FYI, at the moment we loop over ``Parameters`` in many places and I think it would be nice to keep this possibility

**Comment by adonath** [comment]
As `Parameters` implements a `__getitem__` method it should be possible to do loop over `Parameters` directly...

**Comment by cdeil** [comment]
I think you'd have to add an `__iter__` to allow `for par in parameters`, like this:
```
def __iter__(self):
    return self._parameter_list.__iter__()
```
I think the discussion whether to split out the covariance into a separate class, or whether there's a better way to get / set parameter errors, is still open. That might also influence how we want to expose the parameters exactly.

I didn't have time to work on Parameters more, so unless you already did this, these things are for v0.9.

**Comment by adonath** [comment]
@cdeil No, `__getitem__` just works fine (see [PEP 234](https://www.python.org/dev/peps/pep-0234/#python-api-specification)):

```python
from gammapy.spectrum.models import PowerLaw
pwl = PowerLaw()

for p in pwl.parameters:
    print(p)
```
So for syntactic sugar we could get rid of all `for par in parameters.parameters:` statements...

**Comment by cdeil** [comment]
Ah, OK. Great!

> So for syntactic sugar we could get rid of all for par in parameters.parameters: statements...

I think we should: try to expose a small API that let's callers do what they need to do with the parameters and covariance, without depending on the exact implementation (a Python list for parameters and a Numpy array for covariance).

**Pull request merged**
