### PR TITLE
Extrapolate for AEFF evaluation

### PR DESCRIPTION
**Pull request by JouvinLea**
i just change the way you interpolate the effective_area because I add nan value otherwise for high energy range....

### CODE REVIEW

**Comment by cdeil** [comment]
I think we should make this change (and actually do it for all other interpolations, too).

We've had trouble with `NaN` from interpolators several times, and it's annoying for users to not get any result or plot because of that. Gammalib is also extrapolating and it's a reasonable thing to do.

@joleroi - OK?

**Comment by joleroi** [comment]
I don't think you changes does anything, nan is the default value in scipy interpolators

http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RegularGridInterpolator.html

I don't like the interpolation, because it can give crazy stuff if there's a strange wiggle at the high energy end of the effective area. I would set it to 0, and maybe give a warning that someones is extrapolation outside a 'sane' region.

**Comment by cdeil** [comment]
@leajouvin  changed to `None` ... @joleroi - I think you read this as `NaN`.

Her change does change from NaN in the output to extrapolated values:

> fill_value : number, optional
If provided, the value to use for points outside of the interpolation domain. If None, values outside the domain are extrapolated.

I know that we've discussed this extensively before ... I think for now extrapolating or putting zero would be better than raising an error so that users get some result.

**Comment by JouvinLea** [comment]
I agree with Christoph!!
But at least it was not raisin an error. It’s just it’s better to extrapolate than to have nan value...

**Comment by joleroi** [comment]
Oh sorry. I was distracted by the HESS1U talk :)

I extrapolated an effarea in a crazy range yesterday and I got 'Nan' - no error. But do what you think is right :+1:

**Comment by cdeil** [comment]
Now I remember ... we did discuss this extensively and even wrote down a policy
https://gammapy.readthedocs.org/en/latest/development/howto.html#interpolation-and-extrapolation
and I did go through and make all interpolators consistent.

So @JouvinLea , you're asking us to change from "medium safe" to "least safe" here.

May I ask why it's needed? Maybe it's a good thing that you got NaN when evaluating your AEFF for energies where you don't know the AEFF really? And it's easy to work around by putting a valid energy band?

**Comment by JouvinLea** [comment]
It just that the interpolator in defined on the log_center of your true energy used for the effective_area.
For the PA data I used for RXJ1713 images, the last bin is at 80 TeV.  If I want to produce an image on a range like 30-100 TeV, it will give me nan value for the exposure since you sum over all the energy bins...

**Comment by joleroi** [comment]
Can't you change the behaviour for you use case and leave the default behaviour as it is? 
Sorry, this might be a stupid question, I don't really know your use case

**Comment by cdeil** [comment]
But PA has no events and valid response beyond 50 TeV, so if you have to choose a max of 70 or 80 TeV here that's a reasonable thing to have to do.

I'm 50:50 between leaving what we have now ("medium safe") and changing to what you propose (called "least safe" in the current HOWTO entry).

@JouvinLea - Do you still think we should make the change (extrapolate or zeros instead of NaN)?
If yes, we'll take a quick vote here to decide.

**Comment by JouvinLea** [comment]
ok let’s put nan value

**Comment by cdeil** [comment]
Closing this PR for now.

(If you come across this discussion in the future and have an opinion, please, please leave a comment to let us know what you think.)

**Pull request closed without merging**
