### PR TITLE
Description of the arguments of the class `Observation'

### PR DESCRIPTION
**Pull request by bkhelifi**
**Description**

This pull request completes the docstring description of all arguments of the class and of the `create` function. It is associated to the PR #4768

### CODE REVIEW

**Review by morcuended — APPROVED** [review]

**Review by registerrier — APPROVED** [review]
Thanks @bkhelifi . This looks good. 
Do we have a scheme defined for punctuation of parameters and returned objects in docstrings?

**Comment by morcuended** [comment]
> Do we have a scheme defined for punctuation of parameters and returned objects in docstrings?

I see phrases ending or not with period indistinctly in the docstrings. I guess we should follow https://peps.python.org/pep-0257/ (which recommends the use of periods)

Also realize that in some cases in which parameter description is indicated in several lines, are rendered like if they were in the same line:
image

docstring looks like:
image

**Comment by registerrier** [comment]
> > Do we have a scheme defined for punctuation of parameters and returned objects in docstrings?
> 
> I see phrases ending or not with period indistinctly in the docstrings. I guess we should follow https://peps.python.org/pep-0257/ (which recommends the use of periods)
> 
> Also realize that in some cases in which parameter description is indicated in several lines, are rendered like if they were in the same line: image
> 

At some point, we will need to make all docstrings uniform. This might require a reminder issue.

Merging for now.

**Comment by Astro-Kirsty** [comment]
Resolves PR #4768

**Pull request merged**
