### PR TITLE
Fix EnergyDispersion2D.plot_bias()

### PR DESCRIPTION
**Pull request by joleroi**
This fixes a plotting issue in ``EnergyDispersion2d.plot_bias()``. I don't know when it was introduced.

### CODE REVIEW

**Comment by cdeil** [comment]
The long-term plan is that we use `pytest-mpl` to compare plot screenshots to make sure plots don't break. This will take some time to set up in a good maintainable way, there's an issue.

For now, short-term, if you want to make sure plots don't break, in some cases it's possible to add a test that makes a plot, and then accesses some values via the matplotlib API, like values of a given point in the plot, or a given pixel for an image, and makes one `assert` on that.
This should work pretty well, and it's not too bad -- you just have to make the plot interactively and play with tab completion in IPYthon for 1 minute to find a number to assert on.

We don't have examples for such plotting tests yet, but if anyone has time, they would be very valuable to have as very high-level tests to avoid plots breaking like what happened here and several times before.

**Comment by joleroi** [comment]
Please file an issue :wink: (copy and past your comment)

**Comment by jjlk** [comment]
Hi @joleroi , 
it's working again!

figure_1

**Comment by jjlk** [comment]
@joleroi , @cdeil , 
Merge of what?

**Comment by jjlk** [comment]
@joleroi , @cdeil 
Hi again, ok to merge this PR?

**Comment by cdeil** [comment]
I don't remember what this was about.
@joleroi - Merge, no?

**Pull request merged**
