### PR TITLE
Fix mean PSF computation to use default energy binning

### PR DESCRIPTION
**Pull request by JouvinLea**
@cdeil 
I forgot to add a default energy binning in the method mean psf....

### CODE REVIEW

**Comment by adonath** [comment]
@JouvinLea Please note, that `cube_kernels` is a duplication of `EnergyDependentTablePSF.kernels()`. Or is there another reason why the `cube_kernels` method is needed?

**Comment by cdeil** [comment]
@adonath - Assigning to you for review.

This PR was a suggestion by me today, related to #917, with the goal to remove the `make_mean_psf_cube` method from the notebook:
http://nbviewer.jupyter.org/github/gammapy/gammapy-extra/blob/master/notebooks/cube_analysis_part2.ipynb

The mean computation was available on the obs list class, but there was no convenience method to make a 3D PSF kernel.

So the idea was that sometimes a list of 2d kernels is needed (given by `EnergyDependentTablePSF.kernels` and sometimes, like in the notebook, a 3d kernel (the `EnergyDependentTablePSF.cube_kernel` method added here).
It's computing the same kernel in 2 formats, for convenience. We felt like it wan't worth calling one method from the other, because it's just a few lines of code. But that could be changed, if you think it's better make a suggestion @adonath .

---

@JouvinLea -
* I think the new method should be `cube_kernel` (singular), because it returns just one object.
* And the docstring is still copy & paste, needs to be updated.
* There should be a test where it's executed once (right next to the `kernels` test (which hopefully exists), exercising the same example.

**Comment by JouvinLea** [comment]
@cdeil 
I fix the issue here this is only a very small PR concerning the default energy binning for the mean PSF...
Is it possible to merge this one quickly it's really a very small change?

**Comment by cdeil** [comment]
This change now looks good to me.

Could you please squash the commits here?

At the moment you have three commits, where you add and then remove again a method, and it'll be confusing to have this in the git history:
https://github.com/gammapy/gammapy/pull/921/commits

**Comment by cdeil** [comment]
@JouvinLea @joleroi @registerrier  - In Gammapy master, we currently have three remaining test fails concerning PSF:
https://travis-ci.org/gammapy/gammapy/jobs/206150249#L1805
(the same fails are in master, they are not due to the change in this PR)

Any thoughts on when this was introduced? Please point to a commit in gammapy or gammapy-extra if you do.

Any thoughts on how we should fix this?

**Comment by adonath** [comment]
@leajouvin I included this fix in https://github.com/gammapy/gammapy/commit/8bd8a16212960cb4f01c139e45de160da6a3ebc7, because I needed it for the cube analysis tutorial
at the MPIK Python workshop.

**Pull request closed without merging**
