### PR TITLE
Fix data_fits_name for "bg_cube" scheme in FOVCube

### PR DESCRIPTION
**Pull request by lmohrmann**
This is a small fix to bring this class in line with the specs, see http://gamma-astro-data-formats.readthedocs.io/en/latest/irfs/full_enclosure/bkg/index.html#bkg-3d.

### CODE REVIEW

**Comment by lmohrmann** [comment]
@cdeil We should definitively talk. We're not using Gammapy to build the model, at least not beyond the `DataStore`, which we use to load the data in the beginning. But of course the script could be implemented into Gammapy at some point. I'd like to do some testing before we do that, though. (This will also be quite some work, so we might need to find someone to do it).

**Comment by cdeil** [comment]
Sounds good. The work that is starting now is more generic IRF and maps and analysis code. Your expertise / review on use of e.g. FOV coordinates in upcoming PRs would be appreciated, I'll ping you. Writing new code in Gammapy to make background models would anyways be something that's best only started in a month or two.

**Comment by cdeil** [comment]
@lmohrmann - This PR broke our docs build:
```
$ python setup.py build_docs

/Users/deil/code/gammapy-docs/build/dev/gammapy/docs/background/models.rst:69: WARNING: Exception occurred in plotting plot_bgcube
 from /Users/deil/code/gammapy-docs/build/dev/gammapy/docs/background/plot_bgcube.py:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py", line 529, in run_code
    six.exec_(code, ns)
  File "<string>", line 9, in <module>
  File "/Users/deil/code/gammapy-docs/build/dev/gammapy/build/lib.macosx-10.13-x86_64-3.6/gammapy/background/fov_cube.py", line 383, in read
    return cls.from_fits_table(hdu, scheme)
  File "/Users/deil/code/gammapy-docs/build/dev/gammapy/build/lib.macosx-10.13-x86_64-3.6/gammapy/background/fov_cube.py", line 246, in from_fits_table
    .format(scheme_dict['data_fits_name'], header['TTYPE7']))
ValueError: Expecting data axis (BKG) in fourth place, not (Bgd)
```

I'm not quite sure what to do here.

I think the best way to move forward would be to simply delete the old and outdated docs pages:
* http://docs.gammapy.org/dev/background/models.html
* http://docs.gammapy.org/dev/background/make_models.html
and associated "make example data" helper functions in Gammapy.

We have CTA 1DC data now, and the HESS test data release -> can use that for documentation examples.

We need to write better code to make background models first and then can write new high-level docs how to build them.

If we fix  / edit the docs pages not first we're wasting time, no?

@lmohrmann @leajouvin - Thoughts?

**Comment by lmohrmann** [comment]
@cdeil Sounds reasonable to me!

**Pull request merged**
