### PR TITLE
Add spectral table model

### PR DESCRIPTION
**Pull request by jjlk**
The purpose of this PR is to implement a spectral class initiated with energy and flux values (array).  The class implementation follows closely what has been done in [naima](http://naima.readthedocs.io/en/latest/_modules/naima/models.html#TableModel).

### CODE REVIEW

**Comment by cdeil** [comment]
Thanks!
Let me know when I should have a look.
Please ignore the travis-ci fails for now, they are unrelated (other recent changes in Gammapy and Sherpa).

**Comment by jjlk** [comment]
Hi @cdeil, 
Ready for a review!
I added a test for the TableModel class. I generate energy and flux points according to a power law (with parameters took from the PowerLaw test) and I verified that the values are the same (hope it's not machine dependant). I tried to pass the function table_model() as a pytest.fixture but failed. Thanks!

**Comment by cdeil** [comment]
Looks good to me. 
Personally I would have put the scipy import where it's used and not the initialiser, but I don't see any big advantage either way.

@joleroi - I'm assigning to you for final review.

Eventually we also want the translation to Sherpa table model so that it can be fit easily and a test that this works. But maybe just merge this now and then when someone has time to do this (and the current Sherpa issues on travis-ci are sorted out) we add it?

**Comment by cdeil** [comment]
travis-ci fails are unrelated:
https://travis-ci.org/gammapy/gammapy/jobs/170448989#L1729

Merging this now.

**Pull request merged**
