### PR TITLE
Observation grouping and misc cleanup and fixes

### PR DESCRIPTION
**Pull request by cdeil**
This PR fixes the `test_background_cli_all` test for the `gammapy-background-model` tool that @JouvinLea and I implemented recently and removes the `xfail` flag for the that test.

The core of the issue was that the obs selection methods modified the input table.
I've fixed this and also cleaned up some things about the observation code.

### CODE REVIEW

**Comment by JouvinLea** [comment]
@cdeil 
I wanted to start to implement the class for this background model as we discussed last week! Should I start an other PR for that?

**Comment by cdeil** [comment]
I should finish this PR before you start.
I could probably do that before lunch.

Before you start on the class, can we have a quick Skype call to discuss API?
I'm available until 3.30 pm.  1 pm?

**Comment by cdeil** [comment]
Also -- there's four open pull request for gammapy.spectrum from you.
(I know the issue was that too much was changing and it wasn't clear at first how best to implement this)

Getting the functionality / all useful code from all of those four pull requests in `master` and closing the PRs should be your priority.

Transferring the background modeling code to a class is something that I can also do tomorrow.

**Comment by JouvinLea** [comment]
ok for a skype around 2pm?

**Comment by JouvinLea** [comment]
the latest one is grouping_renamed, you can close the other PRs!

**Comment by JouvinLea** [comment]
or if you want we can skype now?

**Comment by cdeil** [comment]
2pm is better for me.

**Comment by JouvinLea** [comment]
ok! See you at 2pm!

**Comment by cdeil** [comment]
@leajouvin @joleroi - I've found several severe issues with the current ObservationGroups class.

I'll try finishing this up and fixing it before 2 pm.

One core problem was that `obs_groups_table` was a class-level mutable data member:
```python
class ObservationGroups(object):
    obs_groups_table = Table()
```
https://github.com/gammapy/gammapy/blob/master/gammapy/data/observation.py#L490

This (and other issues) were the root cause of why the background grouping test only failed when run together with other tests.
pytest only starts one Python interpreter and only imports `gammapy.data` once per test session.
And class-level code (stuff that's not in `__init__` or methods gets executed on import.
So when the background grouping ran, some old, other obs group table was stored in `obs_groups.obs_groups_table`.

:scream:

**Comment by cdeil** [comment]
@joleroi - This is mostly ready, I'd like to merge this soon.

One fail that shows up on travis-ci is `gammapy/spectrum/tests/test_counts_spectrum.py:test_n_pred`:
https://travis-ci.org/gammapy/gammapy/jobs/112795325#L1904

Did I introduce a change / issue here?
Or should I ignore this and you'll fix it in #476  or elsewhere?

**Comment by joleroi** [comment]
Yes I have seen this error,  I don't 100% understand why it arises but I fix it in #476

**Comment by cdeil** [comment]
Getting closer ... coming soon!

**Comment by cdeil** [comment]
Merging this now.

**Pull request merged**
