### PR TITLE
WIP: Add Ramin format shower I/O C package

### PR DESCRIPTION
**Pull request by pflaumenmus**
TODO before this can be merged into gammapy:
- [ ] Figure out how to correctly write `setup_package.py` so that the build and import works.
- [ ] Add writer for this format
- [ ] Add unit tests (write two MB or random values, read them back and assert equal)
- [ ] Add docstrings and at least a few sentences what this is in `docs/shower`.

Note the related PR #39

### CODE REVIEW

**Comment by cdeil** [comment]
@pflaumenmus Do you still think it might be useful to add this to Gammapy? Or would it be better to add a Python wrapper to MESS or a separate C library for ROI I/O?

Either way is fine with me ... I'm just going through old pull requests for Gammapy and try to finish things up, because I want to cut the 0.3 release on Monday.

**Comment by pflaumenmus** [comment]
The more flexible way is to have it as a separate C library (in MESS) and then wrap it into Python, because then, it can be used outside Python as well.

**Comment by cdeil** [comment]
So OK if we close this pull request (PR) for now?

(We can always re-open later or make new PRs for Gammapy if we want.)

**Comment by pflaumenmus** [comment]
Yes, alright.

**Pull request closed without merging**
