### PR TITLE
Remove fit from events sampling tutorial

### PR DESCRIPTION
**Pull request by QRemy**
Remove the part showing a fit from the events sampling tutorial so the aim of the tutorial is more focused.

### CODE REVIEW

**Review by bkhelifi — APPROVED** [review]
This is a valid point. Maybe you can just refer at the end the tutorial to explore the simulated data, but this is not mandatory.

**Comment by QRemy** [comment]
> This is a valid point. Maybe you can just refer at the end the tutorial to explore the simulated data, but this is not mandatory.

The last sentence of the tutorial already mention this

` 
Then you can create the observations from the data store and make your own analysis following the instructions in the [Low level API](https://docs.gammapy.org/dev/tutorials/starting/analysis_2.html) tutorial.`

**Review by adonath — APPROVED** [review]
Thanks @QRemy, I agree the tutorial is already long enough.

**Comment by registerrier** [comment]
I propose not to backport this change as it is only touching documentation.

**Comment by fabiopintore** [comment]
thanks @QRemy . The tutorial is indeed quite long, so if you all agree that the fitting steps are not necessary, then it's fine to me as well. 
However, I suppose that, if not strictly needed, removing information may be not an optimal option. Even if redundant because shown in other tutorials, cross-topic information are appreciated by the beginner users, which may have a broader view in one-shot rather than searching for explanations in other tutorials.

**Pull request merged**
