### PR TITLE
PIG 2 - New low-level analysis code

### PR DESCRIPTION
**Pull request by registerrier**
This is provides a description of the proposed low level analysis scheme for image/cube analysis.

A description of the PSF kernels is still missing.

Please comment. @cdeil @adonath @bkhelifi @leajouvin

### CODE REVIEW

**Comment by cdeil** [comment]
@registerrier - you currently have "PIG 2 - Organization of low-level analysis code" as title for the PIG and "Initial commit for the PIG 002" as title for the PR.

Can you please make them the same?

Do you plan to also outline 1-d spec analysis here, or only map-based analysis?
Maybe "PIG 2 - New low-level map-based analysis code"?

**Comment by cdeil** [comment]
I saw a mention of "4D EDISP cube". Do we want to have spatially-dependent PSF / EDISP? Or only support spatially constant PSF / EDISP?

So far, in IACT, spatially dependent PSF / EDISP wasn't used. But for CTA with the higher precision it's probably needed at some point. There is no format spec yet, but ctools already has some FITS formats for that that we could probably just use if they are reasonable and in line with the maps formats that Matthew defined in the open spec. See [ctpsfcube](http://cta.irap.omp.eu/ctools/users/reference_manual/ctpsfcube.html) [ctedispcube](http://cta.irap.omp.eu/ctools/users/reference_manual/ctedispcube.html).

I think PSF / EDISP application in the likelihood fit would in many cases still be for a PSF kernel / EDISP matrix that isn't spatially varying, for simplicity and good speed, no? And spatially-dependent PSF / EDISP is something we would maybe implement separately later?

So @registerrier and all - what should we implement now, in the coming weeks? Is it extensible to the case of spatially-dependent PSF / EDISP in a backwards-compatible way (possibly by just adding new classes and functions for that case)? Or do we have to do the full design now?

**Comment by registerrier** [comment]
The mention of a 4D object EDISP is mostly because to actually compute exposure in reco energy we need to convolve Expo(X,Y,Etrue) with EDISP(Etrue, Ereco). This is done in practice through a 4D EDISP(X,Y,Etrue, Ereco) which will be transient in memory.

**Comment by cdeil** [comment]
This EDISP would probably dominate memory use. If it's not spatially dependent, then it should be possible to use Numpy broadcasting with a 2D EDISP and avoid the 4D. In the existing cube code from Lea, is it a 2D or 4D array? There's also the question with which maps EDISP works. Maybe just put these as questions in the document for now, and then we look at this in detail later this week?

**Comment by cdeil** [comment]
@registerrier - thank you for all your work on this!

**Comment by cdeil** [comment]
I've done a little big of cleanup and clarified how the decision was done on PIG 2 in 77ad6a92.

**Pull request merged**
