### PR TITLE
Remove infinite values from models

### PR DESCRIPTION
**Pull request by registerrier**
At the moment, models can return infinite values for some weird choice of parameters. This likely contributes to issue #1868 . In this case the minimizer tests spectral indices as large as 100 and `PowerLaw.__calc__` can return `np.inf` which breaks the statistics evaluation.

This PR adds `numpy.nan_to_num` in `Model.__calc__` methods to prevent such situations to happen. A test is added too.

### CODE REVIEW

**Comment by cdeil** [comment]
@registerrier - I see, for very steep power-law spectra the flux goest to + infinity at low energies:
```
>>> import numpy as np
>>> np.power(1e-3, -100)
9.99999999999998e+299
>>> np.power(1e-3, -200)
__main__:1: RuntimeWarning: overflow encountered in power
inf
```

I'm not sure the fix here to put `np.nan_to_num` is a good one.

It probably still has a good chance to lead to arbitrary results or to get the optimiser stuck, because bins with very large numbers besides the bins where inf occurs are kept, leading to complete numerically unstable result?

Also, if you don't wrap the evaluate in `with np.errstate` like e.g. [here](https://github.com/gammapy/gammapy/pull/1701/files#diff-8b56cb9409f551e1a8ec1c96689236bfR839), users will still see the `RuntimeWarning`.

We could suppress them `with np.errstate`, but we'll still have a solution that silently drops bins and gives arbitrary results, and the extra call will overall slow down our model evaluation.

Maybe we should just keep model eval as-is, and (grumble, grumble) start using parameter limits. That's what Sherpa does:
```
>>> from sherpa.models import PowLaw1D
>>> m = PowLaw1D()
>>> m.gamma = 200
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/joint-crab/lib/python3.6/site-packages/sherpa/models/model.py", line 196, in __setattr__
    par.val = val
  File "/Users/deil/software/anaconda3/envs/joint-crab/lib/python3.6/site-packages/sherpa/utils/__init__.py", line 156, in __setattr__
    object.__setattr__(self, name, val)
  File "/Users/deil/software/anaconda3/envs/joint-crab/lib/python3.6/site-packages/sherpa/models/parameter.py", line 169, in _set_val
    raise ParameterErr('edge', self.fullname, 'maximum', self.max)
sherpa.utils.err.ParameterErr: parameter powlaw1d.gamma has a maximum of 10
>>> m.gamma.max = 200
>>> m.gamma = 200
>>> m(1e-3)
inf
```

@registerrier - Thoughts?

**Comment by registerrier** [comment]
Obviously replacing 1e1000 or 1e501 with 1e308 will lead to incorrect npred and likelihood but it prevents the minimizer to become stuck once there is a `nan`.
I don't know about the RunTimeWarning. Keeping them silent will make error tracking complex, no?

The better approach is indeed to define sensible min and max values for every parameter of any model. There is no way to avoid it, I think. We will have to add this soon.

One minimal option could be to enforce the nan_to_num on the npred calculation in `MapFit` to be sure that the stat value is never `nan`.

**Comment by registerrier** [comment]
Also as a side note, at the moment the evaluate method does not use `Quantity`:
```
    def evaluate(energy, index, amplitude, reference):
        """Evaluate the model (static function)."""
        return amplitude * np.power((energy / reference), -index)
```
but `SpectralModel.__calc__` uses `Quantity`:
```
    def __call__(self, energy):
        """Call evaluate method of derived classes"""
        kwargs = dict()
        for par in self.parameters.parameters:
            kwargs[par.name] = par.quantity

        return self.evaluate(energy, **kwargs)
```
This makes `__calc__` nearly 10 times slower because of units.
```
In [47]: p1=PowerLaw(amplitude="1e-12 cm-2 s-1 TeV-1", index=2, reference="1 TeV")

In [48]: %timeit p1(np.logspace(-1,1,100)*u.TeV)
219 µs ± 11.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [49]: %timeit p1.evaluate(np.logspace(-1,1,100),2,1e-12,1)
25.5 µs ± 1.02 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Probably `PowerLaw.evaluate` should be able to deal more efficiently with units.

**Comment by registerrier** [comment]
OK after discussion in the dev meeting we decided to leave it as is for now. To be rediscussed when @adonath is back in the broader context of Modeling (https://github.com/gammapy/gammapy/projects/7).

**Comment by adonath** [comment]
I'm also -1 to add the handling of invalid numbers such as `NaN` and `inf` to the model evaluation. I think the behaviour of numpy in those cases (e.g. division by zero or numerically unstable values) is well defined and we should not change it.

As @cdeil suggested we could add reasonable min and max default values for model parameters, which is what sherpa does. I think this might resolve the issue.

A second question is how to handle `NaN` values in the per bin likelihood, which I think can happen for other reasons as well (missing data etc.). There I think it is fine to leave it up to the user to handle those values with a custom mask, passed to the `Fit`. This should be maybe documented...

**Comment by cdeil** [comment]
@adonath - Close this PR? Maybe open a new issue concerning data filter, which is discussed a bit above.

The parameter min / max will be improved shortly, that is already covered by #1878 .

**Pull request closed without merging**
