### PR TITLE
Fix mpl 1.5 color_cycle deprecation warning

### PR DESCRIPTION
**Pull request by bsipocz**
I had an abandoned attempt on this earlier this year, but this is now inspired by https://github.com/astropy/astropy/pull/5569/ and thus should work.
🎄 🎁

### CODE REVIEW

**Comment by cdeil** [comment]
@bsipocz - Is this ready for merging? Can you check the build logs?

I'm very short on time at the moment, and would prefer to just merge this now without further testing and if there are any issues resolve them later.

**Comment by bsipocz** [comment]
For some weird reason this doesn't seem to work, so give me some more time to investigate.

**Comment by cdeil** [comment]
@bsipocz - It works for me locally with MPL 2.0 pre.

Just FYI: this color cycler isn't very important to use. You could also remove it. Also - I'd be OK to bump the supported version for MPL to 1.5 in `setup.py`.

So, don't spend too much time finding a solution here that works for old MPL versions. Just remove the custom `axes.color_cycle` or implement some other solution that works with MPL 1.5 and later, and let me know when this is ready to merge.

**Comment by bsipocz** [comment]
I got it. It works for both of us, as it needs astropy 1.3 for this to be fixed there and if it's not then ``gammapy_mpl_style`` inherits the ``color_cycle`` due to ``gammapy_mpl_style = astropy_mpl_style`` even though we try to fix it later.
I would say it's not worth trying to patch around it for this short time till the new release.

**Comment by cdeil** [comment]
OK. Merging this now. Thank you!

**Pull request merged**
