### PR TITLE
Fix bug in map .fits.gz write (change map data transpose)

### PR DESCRIPTION
**Pull request by cdeil**
I think I've found a bug in WCSMapND write.

The image orientation is incorrect in this example:
https://nbviewer.jupyter.org/gist/cdeil/2feb9e784d128d43867a707c0ca23092

At first I thought it's a bug in reproject, but maybe it's just in write and I was always looking at incorrectly images from DS9.

@woodmd - You're busy with new things, right?
If so, I'll have a look at this tomorrow and try to debug / fix it.

### CODE REVIEW

**Comment by cdeil** [comment]
I attached a commit with a regression test (all of the asserts are failing before the fix), and then the attempted fix to avoid having transposed Numpy arrays as map data objects.

It fixes the regression tests, and most things still work. However sparse map I/O is failing for some existing tests (but not the new one). I haven't figured out yet how to trigger the sparse map I/O issue with a simple test case or how to fix it.

I'm offline now, but I'll try to fully resolve this tomorrow. @woodmd - If you could have a look and comment if you're OK with the changes so far, that would be very helpful.

**Comment by cdeil** [comment]
@woodmd - might the issue be here?
https://github.com/gammapy/gammapy/blob/b949c8dd9f2993d973e83d557fa06e314807cf34/gammapy/maps/wcsmap.py#L209

Looks like in `WcsMap.make_hdu` you are modifying `self.data`.
That shouldn't be the case, `make_hdu` should leave `self.data` alone, no?

**Comment by cdeil** [comment]
I can confirm that changing
```
data = self.data
```
at the top of `WcsMap.make_hdu` to
```
data = self.data.copy()
```
resolves the remaining failing tests:
```
gammapy/maps/tests/test_wcsnd.py::test_wcsndmap_read_write[None-10.0-GAL-AIT-skydir0-None] FAILED                                                  [ 70%]
gammapy/maps/tests/test_wcsnd.py::test_wcsndmap_read_write[None-10.0-GAL-AIT-skydir1-axes1] FAILED                                                 [ 71%]
gammapy/maps/tests/test_wcsnd.py::test_wcsndmap_read_write[None-binsz2-GAL-AIT-skydir2-axes2] FAILED                                               [ 71%]
gammapy/maps/tests/test_wcsnd.py::test_wcsndmap_read_write[None-10.0-GAL-AIT-skydir3-axes3] FAILED                                                 [ 71%]
gammapy/maps/tests/test_wcsnd.py::test_wcsndmap_read_write[None-binsz4-GAL-AIT-skydir4-axes4] FAILED                                               [ 71%]
```
Is that the proper fix or is there a better way?

**Comment by woodmd** [comment]
> Looks like in WcsMap.make_hdu you are modifying self.data.
That shouldn't be the case, make_hdu should leave self.data alone, no?

I think I had assumed `np.ravel` makes a copy but looking at the documentation now I see that's not the case.  You're correct that `make_hdu` should not be modifying `self.data`.  

> Is that the proper fix or is there a better way?

Yes that would be fine although somewhat inefficient for the non-sparse case.  A copy isn't needed when `sparse=False` so you could instead move this inside the if/else statement:
```
if sparse:
    data = self.data.copy()

    ...

    elif hdu == 'PRIMARY':
        hdu_out = fits.PrimaryHDU(self.data, header=header)
    else:
        hdu_out = fits.ImageHDU(self.data, header=header, name=hdu)
```

**Comment by cdeil** [comment]
@woodmd - Thanks for the tips.

Fix in e203822c - one question I have is why you always go to 64-bit float? Isn't the main application for the sparse format count maps? Do you want to use 64 bit float for those?
(I'd like to simplify the code there a bit more and resolve the one TODO I added for now)

**Comment by cdeil** [comment]
I've done some more small fixes in  d3cf7ce and e1fd764 and then removed the data transpose in the default HPX map data init in 8fb4b4d4 as you suggested.

The only remaining cases where we transpose map data arrays are those:
```
$ ack 'data\.T' gammapy/maps
gammapy/maps/hpxnd.py
324:        return self.data.T[idx]
373:            return np.sum(self.data.T[pix] * wts, axis=0)
399:            val += np.nansum(wts * wt * self.data.T[pix[:1] + pix_i], axis=0)
416:        idx_local = np.ravel_multi_index(idx_local, self.data.T.shape)
419:        self.data.T.flat[idx_local] += weights
424:        self.data.T[idx_local] = vals

gammapy/maps/wcsnd.py
127:        return self.data.T[idx]
167:            data = self.data.T
177:        return map_coordinates(self.data.T, pix, order=order, mode='nearest')
241:        idx = np.ravel_multi_index(idx, self.data.T.shape)
244:        self.data.T.flat[idx] += weights
248:        self.data.T[idx] = vals
439:        data = map_coordinates(self.data.T, pix, order=order, mode='nearest')
```

@woodmd - I think all of those are OK, and while probably they could be rewritten to avoid the transpose, there's no need? Is this PR ready to merge?

**Comment by woodmd** [comment]
> Fix in e203822 - one question I have is why you always go to 64-bit float? Isn't the main application for the sparse format count maps? Do you want to use 64 bit float for those?

Yes this was an oversight.  There should be some logic here to generate the appropriate FITS data type keyword from the numpy array dtype.  This somewhat goes to the question of whether we want to support integer data types at all.  At present the code doesn't really support them because we use `np.nan` as a guard value for undefined pixels (undefined pixels arise for multi-resolution geometries and some all-sky WCS projections).  To fully support integer types we would need to update the logic for handling guard values in a way that depends on the data type or perhaps rewrite the handling of undefined pixels entirely with a mask array.  I've begun to think that having a mask array would be a better design than the current guard value approach but that's probably better discussed in a separate thread.  Maybe you want to open a new issue on the topic of integer support?

> I think all of those are OK, and while probably they could be rewritten to avoid the transpose, there's no need? Is this PR ready to merge?

Yes I agree that these don't need to be rewritten.  Looks ready to merge.

**Comment by cdeil** [comment]
> I've begun to think that having a mask array would be a better design than the current guard value approach but that's probably better discussed in a separate thread. Maybe you want to open a new issue on the topic of integer support?

@woodmd - I've opened #1350 . It's not clear to me if introducing mask arrays is necessary or a better solution, so I've put it as an open question.

**Comment by cdeil** [comment]
@woodmd - Thank you for the advice and review here!

**Pull request merged**
