### PR TITLE
Suppress some matplotlib outputs in tutorials

### PR DESCRIPTION
**Pull request by bkhelifi**
**Description**

This pull request is associated to the Issue #4327. It adds semicolons when necessary

**Dear reviewer**
During my commits, I have noticed that `black` automatically suppresses some semicolons. One might need to configure back if possible (a new issue?)

### CODE REVIEW

**Review by adonath — DISMISSED** [review]
Thanks @bkhelifi, no comments from my side.

**Review by AtreyeeS — CHANGES_REQUESTED** [review]
Thanks @bkhelifi ! Can you also please adapt the following notebooks while you are at it? Then we can close the issue 
- analysis-1d/sed_fitting.py
- analysis-3d/analysis_3d.py, analysis-3d/analysis_mwl.py
- analysis-time/light_curve_flare.py
- api/fitting.py
- data/*

**Comment by adonath** [comment]
@bkhelifi I just realized that the problem with `black` is maybe a non-issue. Let me explain:

- As we want our tutorials to work with notebooks as well as scripts. We always have to call `plt.show()`, when a plot is ready to be shown. 
- This means all plotting cells should end with a `plt.show()` statement
- It seems the cases where we end e.g. with `plt.legend()` miss the `plt.show()` statement anyway.
- In cases where the definition of a plot is split into multiple cells it should be merged into a single one. 
- Once all the plotting cells end correctly with `plt.show()`, it should suppress the matplotlib output as well as be compliant with `black`

**Review by AtreyeeS — DISMISSED** [review]
Thanks a lot @bkhelifi ! Its noteworthy how many typos survived in our docs after the extensive 1.0 checking !!

**Review by adonath — DISMISSED** [review]
Thanks @bkhelifi, I have no further comments. I just need to double check whether this affects any other open PR.

**Comment by AtreyeeS** [comment]
Hi @bkhelifi ! Can you please add a `plt.show` after the `.peek()` in `cta.py`
This is specially necessary for `irfs["psf"].peek()` , otherwise the results of `plot_containment_radius_vs_energy` and the last axis of peek merge to give a very confusing plot as in:  https://docs.gammapy.org/1.0.1/tutorials/data/cta.html#point-spread-function

**Review by QRemy — APPROVED** [review]

**Pull request merged**
