### PR TITLE
Fix NoDataAvalaible exceptions in datasets/fermi.py

### PR DESCRIPTION
**Pull request by adonath**
This PR fixes the Exception handling in `datasets/fermi.py` and add a regression test.

### CODE REVIEW

**Comment by cdeil** [comment]
@adonath - Thanks for fixing the bug!

About `test_galdiff` -- does this work?

- What if I have `GAMMAPY_FERMI_LAT_DATA` set? Then the test will fail with `Failed: Expecting Exception`, no? So this is no good.
- Also: the check should be for the more explicit `NoDataAvailableError`, no?
- And finally, the assert should be de-dented to be after the with block, no? 

See http://doc.pytest.org/en/latest/assert.html

Overall, writing a test for this seems hard, because of the various cases to consider.
I think my suggestion would be to just remove `test_galdiff`.
:-)

**Comment by adonath** [comment]
@cdeil Indeed I didn't realize the test doesn't make sense, I only thought about Travis-CI. I'll remove it :-)

**Comment by adonath** [comment]
Travis-CI fails are unrelated, I'm merging this now.

**Comment by cdeil** [comment]
@adonath - I'm getting this error when I run tests locally:
https://gist.github.com/cdeil/96a06eba004c982773be168ea1c4a8f1

Does it make sense to you? Can you fix please?
Or should I investigate?

**Pull request merged**
