### PR TITLE
Improve spectrum analysis

### PR DESCRIPTION
**Pull request by joleroi**
This PR includes
* Add simple high level test of 4 crab runs that diffs the result files to reference files
* Simpilfy analysis by hardcoding output files, everything happens within one folder now

### CODE REVIEW

**Comment by cdeil** [comment]
Gammapy master build is currently broken because `test_spectrum_extraction_from_configfile` fails:
https://travis-ci.org/gammapy/gammapy/jobs/109928139#L884

And there's some other issues in this PR:
https://travis-ci.org/gammapy/gammapy/jobs/109909252#L885

Doing result file compare is nice I think, but if the error message doesn't point out the difference, that's a problem. There probably are nice ways to define a helper function that's hooked into the pytest assert report machinery for this. But maybe for now just do normal asserts on a few key result numbers and make a separate issue to implement result file comparison properly?

**Comment by joleroi** [comment]
@cdeil 
1) You have to change the title of this PR, otherwise it's not funny
2) test_spectrum_extraction_from_configfile is remove in this PR. The fail in master is due to changes in gammapy-extra.
3) I will have a look

**Comment by cdeil** [comment]
I just put "Improve spectrum analysis" for the PR title.

**Comment by joleroi** [comment]
https://travis-ci.org/gammapy/gammapy/jobs/110108424#L1394

This looks like it's your fault :wink:

**Comment by joleroi** [comment]
I would say merge since the remaining failures seem unrelated

https://travis-ci.org/gammapy/gammapy/jobs/110129753#L1615
https://travis-ci.org/gammapy/gammapy/jobs/110129750#L1640
https://travis-ci.org/gammapy/gammapy/jobs/110129752#L1494

**Comment by cdeil** [comment]
I just now fixed the other issues in master ... should be OK again.

**Pull request merged**
