### PR TITLE
Fix ci hangs due to  coverage 6.3 by pinning to 6.2

### PR DESCRIPTION
**Pull request by maxnoe**
See nedbat/coveragepy#1310

### CODE REVIEW

**Comment by maxnoe** [comment]
@Bultako @adonath @registerrier Can we merge this? This is blocking all other PRs at the moment.

**Comment by Bultako** [comment]
Thanks @maxnoe !!

**Comment by bkhelifi** [comment]
At the bottom, one changes maybe change also:
```
  - nbformat==5.0.8
  - h5py==2.10.0

```
to
```
  - nbformat=5.0.8
  - h5py=2.10.0
```

**Comment by maxnoe** [comment]
@bkhelifi That wouldn't be a change in semantics. Changing `python==3.7` to `python=3.7` means any `3.7.x` is ok. But when specifying all three version numbers there is no difference between `=` and `==`

**Pull request merged**
