### PR TITLE
Improve fit results

### PR DESCRIPTION
**Pull request by luca-giunti**
**Description**

This pull request addresses issue #3868 

It is the best I could do in the limited available time. I made some quick tests and it seems to work, but I haven't had the time to play a lot with it

### CODE REVIEW

**Review by registerrier — APPROVED** [review]
Thanks @luca-giunti . See minot inline comment.

@adonath @QRemy , can the proposed change, that removes the deep copy of the input map in `TemplateSpatialModel.__init__` be problematic? I am not sure why this was implemented this way initially.

**Comment by luca-giunti** [comment]
@registerrier from my side this should be OK

**Review by registerrier — APPROVED** [review]
thanks @luca-giunti .

Exposing `Datasets.parameters` is probably a good idea. I think we rarely show it. 
I think it would be better to use a property for `OptimizeResults.parameters` rather than a `copy` (i.e. use `OptimizeResults.models.parameters`.

**Review by adonath — APPROVED** [review]
Thanks @luca-giunti!

I implemented @registerrier comment and renamed `data_deepcopy` to just `copy_data`, where the use of the verb slightly improves readability of the code.

**Pull request merged**
