### PR TITLE
Clean syntax to make links to docs in notebooks

### PR DESCRIPTION
**Pull request by Bultako**
This PR addresses issue #2175  and it provides the following features:

- consistent syntax to link to notebooks **from RST and dosctrings**:
```
`Maps in first steps with Gammapy <../notebooks/first_steps.ipynb#Maps>`__
```
- consistent syntax to make links to documentation **within MD cells of notebooks**
    * to notebooks: `[Maps in first steps with Gammapy](first_steps.ipynb#Maps)`
    * to RST doc files: `[Help](../getting-started.rst#help)`
    * to API ref docs: 
```
       - `~gammapy.maps`
       - `~gammapy.maps.Geom`
       - `~gammapy.maps.Geom.is_image`
       - `~gammapy.maps.Geom.is_image()`
```
- check of broken links to API ref during docs building
- update of how-to documentation accordingly

These improvements in notebook integration within docs are performed in `tutorials_links.py` script executed at the end of the docs building process.

So, do not use the markdown syntax to make formatted links to API ref doc of classes and methods, these issues (https://github.com/spatialaudio/nbsphinx/issues/89 and  https://github.com/spatialaudio/nbsphinx/issues/36) are still not solved  by ``nbsphinx``. Instead, use the standard RST API linking syntax shown above.

### CODE REVIEW

**Comment by Bultako** [comment]
@cdeil 
I've made in https://github.com/gammapy/gammapy/pull/2480/commits/a1f0c0708edf77776bcdc61df01329a8bcc3c6d6 the modifs we agreed on the call this morning.

**Comment by cdeil** [comment]
@Bultako - Thanks!

What about changing those to relative links:
https://gist.github.com/cdeil/13fdf6da8b2ee25b3952d1493b00176b

OK if I do this and then merge this PR?

**Comment by Bultako** [comment]
Most (if not all) of the links of your gist file could be replaced by the RST API x-linking syntax. Yes, you could try replacing those absolute links in the MD cells into  
```
`~gammapy.class.method`
```  

They will still be absolute links in the final *downloadable*  notebooks, though without the broken format issue shown in https://github.com/gammapy/gammapy/issues/2175#issuecomment-543088418

If everything is fine, ok to merge.

**Comment by cdeil** [comment]
@Bultako - OK. I'll build the docs now locally, and then do some cleanup of the IPYNB notebooks before merging this.

**Comment by cdeil** [comment]
@Bultako - Looks like the local HTML docs still link to docs.gammapy.org/dev (see screenshot):

Screenshot 2019-10-23 at 14 13 36

I thought the idea was to create local x-links, like how Sphinx does it, so that the docs can be browsed & tested locally?

**Comment by cdeil** [comment]
@Bultako - I've started to do some cleanup in the notebooks: aa3d4d0b7def866189ce1490454e8d0c42473208

Could you please modify the processing to make fourth-level API links like  `~gammapy.modeling.models.SpectralModel` or `gammapy.modeling.models.PowerLaw2SpectralModel` work?

And I see this warning:
```
/Users/deil/work/code/gammapy/docs/notebooks/first_steps.ipynb:134: WARNING: File not found: 'getting-started.html#download-tutorials'
```
Could you please check and fix that formatting?

**Comment by cdeil** [comment]
@Bultako - I've done some more tutorial notebook cleanup here.

The one remaining task for this PR is to fix links for sub-sub-sub packages, like `~gammapy.modeling.models.SpectralModel`. That should resolve these warnings:
```
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/spectrum_simulation.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/spectrum_simulation.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/fermi_lat.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/models.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/sed_fitting_gammacat_fermi.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/cta_1dc_introduction.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/spectrum_analysis.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/spectrum_analysis.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/spectrum_analysis.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/spectrum_analysis.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/spectrum_analysis.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.astro.darkmatter.html does not exist in docs/_static/notebooks/astro_dark_matter.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.astro.population.html does not exist in docs/_static/notebooks/source_population_model.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/hgps.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/first_steps.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/first_steps.ipynb.
WARNING:__main__:docs/_build/html/api/gammapy.modeling.models.html does not exist in docs/_static/notebooks/first_steps.ipynb.
```

@Bultako - do you have time for this now? Or should we just merge this in and then do that later, to avoid merge conflicts / tutorial edits being blocked?

**Comment by Bultako** [comment]
> do you have time for this now? Or should we just merge this in and then do that later, to avoid merge conflicts / tutorial edits being blocked?

this is easy to fix
I'll add a commit to fix it a bit later today

**Comment by cdeil** [comment]
@Bultako - Thanks!

**Pull request merged**
