### PR TITLE
Set  apply_irf["edisp"]=False in create_fermi_isotropic_diffuse_model

### PR DESCRIPTION
**Pull request by QRemy**
Set  apply_irf["edisp"]=False in create_fermi_isotropic_diffuse_model

See https://fermi.gsfc.nasa.gov/ssc/data/access/lat/BackgroundModels.html :

Screenshot 2024-12-18 at 14 55 21

### CODE REVIEW

**Review by adonath — APPROVED** [review]
Thanks @QRemy, maybe put the link as a comment for reference?

**Comment by facero** [comment]
ah good point. Thanks @QRemy .
Did you notice some changes in the spectral results ?

**Comment by QRemy** [comment]
@adonath the page link is already in the docstring and I don't see a way to point this specific section except with a highlight https://fermi.gsfc.nasa.gov/ssc/data/access/lat/BackgroundModels.html#:~:text=unbinned%20likelihood%20analysis.-,Disabling%20Energy%20Dispersion,-For%20certain%20data which is a bit long (can we use a markdown link in the docstring ?)

**Review by MRegeard — APPROVED** [review]
Thanks @QRemy, that's a good catch !

**Comment by MRegeard** [comment]
@facero, I think it shouldn't change anything for Gammapy right now since we don't provide a way to read the energy dispersion of the LAT.

**Pull request merged**
