### PR TITLE
Add test to make sure OGIP files are readable with sherpa

### PR DESCRIPTION
**Pull request by joleroi**
I received the following issue via slack from @registerrier 

>it seems it is not possible to open the ogip files produced with SpectrumExtraction directly into sherpa at the moment.
It ends up with SystemError: error return without exception set.
Any idea on why that is?

Indeed, there was not test to make sure that our OGIP files are readable with Sherpa, so I added one. However, I cannot reproduce the issue described. @registerrier can you have a look at [the test](https://github.com/gammapy/gammapy/pull/847/files#diff-8a3a149acc144cd2c63f9bffb70e6a84R115) and tell me if I'm doing something different from what you do?

### CODE REVIEW

**Comment by registerrier** [comment]
The issue is due to the incorrect type assigned to the quality flag.
The OGIP definition states that the quality is a 2-byte integer whereas the code uses an int64. 
See:
https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node7.html
To correct one needs to change:
`quality = np.zeros(self.energy.nbins, dtype=int)`
to 
`quality = np.zeros(self.energy.nbins, dtype='i2')`
in the constructor of PHACountsSpectrum

**Comment by cdeil** [comment]
Travis-ci fail is unrelated: https://travis-ci.org/gammapy/gammapy/jobs/195239530#L1827

@joleroi - Maybe it's worth to file an issue in the Sherpa tracker, providing an example test file and asking if they can improve the error message to be more explicit, not so cryptic?

**Comment by joleroi** [comment]
> The issue is due to the incorrect type assigned to the quality flag.
The OGIP definition states that the quality is a 2-byte integer whereas the code uses an int64.

Do you understand why the test I added did not fail? Is this related to using sherpa in Ipython vs. using it from the command line? This would be odd, no?

**Comment by registerrier** [comment]
It's odd indeed. 
I suppose it's a version issue. My standalone version is 4.8.1 whereas the bundled one is 4.8.0.
The files also make XSpec crash in a dirty way even after the change. There might be still some issues with data types.  
XSPEC12>data 1 pha_obs33747.fits
libc++abi.dylib: terminating with uncaught exception of type RedAlert
Abort

**Comment by joleroi** [comment]
> Travis-ci fail is unrelated

I am merging this, I will file a reminder issue about the data types

**Pull request merged**
