### PR TITLE
Fix IACTBasicImageEstimator psf method

### PR DESCRIPTION
**Pull request by gallanty**
Changed psf() method to return image with odd number of pixels and
PSF centered in the middle of the central pixel.
PSF image FOV set to 99% containment radius.
PSF sky position is that for which the PSF is computed (center of
the reference image by default for now).

### CODE REVIEW

**Comment by cdeil** [comment]
I'd suggest this way to set `rad_max`:
```
        if rad_max is None:
            rad_max = psf_mean.containment_radius(containment_fraction)
        else:
            rad_max = Angle(rad_max)
```

**Comment by cdeil** [comment]
@gallanty - Implementation looks good to me now. Let me know when you're done here and then I'll merge.

**Comment by gallanty** [comment]
SkyImage.data now filled directly with TablePSF.kernel() output.
[Was previously filled via TablePSF.evaluate() method using pre-existing code, there was no bug.  Latest result differs from that earlier one by less than 1% - but I agree it is cleaner this way.]
Implemented user-accessible containment_fraction parameter to psf() method, as well as overriding rad_max parameter, as you suggested Friday.  Added a few lines to the docstring which should document this.

**Comment by cdeil** [comment]
@gallanty - Looks good to me. Thanks!

**Pull request merged**
