### PR TITLE
Display the default model parameters in docstrings

### PR DESCRIPTION
**Pull request by Astro-Kirsty**
Resolves issue [#4732](https://github.com/gammapy/gammapy/issues/4732)

### CODE REVIEW

**Review by bkhelifi — APPROVED** [review]
Thanks a lot @Astro-Kirsty for the effort.

**Review by QRemy — APPROVED** [review]
Thanks @Astro-Kirsty, do you want to add also the defaults for spatial and temporal models in this PR ? (we can also do than in a separate one)

**Comment by Astro-Kirsty** [comment]
Thanks @bkhelifi and @QRemy.

Let's add a separate PR for the spatial and temporal (don't know I'll have time this week to implement those)

**Review by registerrier — APPROVED** [review]
Thanks @Astro-Kirsty . 

I wonder if there is a way to build the docstring programmatically for the parameter class attributes.

**Pull request merged**
