### PR TITLE
Add the covariance in the write function of FitResult

### PR DESCRIPTION
**Pull request by bkhelifi**
**Description**

This pull request is associated to the issue #5306. All is in the title...

**Dear reviewer**
The read function of FitResult needs to be created... into a separated PR.

### CODE REVIEW

**Comment by QRemy** [comment]
Looking at the code of FitResult.write it seems that there is some duplication with `Models.write()`.
Why not adding `optimize_results` and `covariance_results` options to  `Models.write()` so it can add these entries in the model file directly and so the `FitResult.write` will be reduced to `Models.write(..., optimize_results=optimize_results.to_dict(), covariance_results..to_dict()) `

**Review by registerrier — COMMENTED** [review]
Thanks @bkhelifi . This looks good. It probably misses a test though.

Maybe a general question: can't we include the covariance directly into the main file?

**Comment by registerrier** [comment]
> Looking at the code of FitResult.write it seems that there is some duplication with `Models.write()`. Why not adding `optimize_results` and `covariance_results` options to `Models.write()` so it can add these entries in the model file directly.
> 
> Then the `FitResult.write` will be reduced to `return Models.write(optimize_results=optimize_results.to_dict() covariance_results.to_dict(), **kwargs) ` and we can remove `FitResult.to_dict` and `FitResult.to_yaml`

This would mean that `FitResult` is not really needed, no?

At the moment, we don't really provide a specific object for `confidence`, `contours`, `scan` results. These might go into the `FitResult` too, no? Or is this too connected to a single parameter, hence to parameter estimation?

**Comment by QRemy** [comment]
> At the moment, we don't really provide a specific object for `confidence`, `contours`, `scan` results. These might go into the `FitResult` too, no? Or is this too connected to a single parameter, hence to parameter estimation?

Any of these quantities make sense only with respect to a given model so they have to be exported with them, then we can just give an extra dict to  Models.write as done in #5325.

**Comment by QRemy** [comment]
I will close this as #5325 resolves it.

**Pull request closed without merging**
