### PR TITLE
Add example to `get_irfs_features`

### PR DESCRIPTION
**Pull request by Astro-Kirsty**
This PR adds an example to the docstring of `get_irfs_features`

This is connected to #5016

### CODE REVIEW

**Review by MRegeard — APPROVED** [review]
Thanks @Astro-Kirsty, this looks good.

**Review by adonath — APPROVED** [review]
Nice, thanks @Astro-Kirsty!

**Review by registerrier — COMMENTED** [review]
Thanks @Astro-Kirsty . Can you check the CI failure?

**Comment by Astro-Kirsty** [comment]
Not sure why there was an error, but I re-ran and it is fine now

**Pull request merged**
