### PR TITLE
`DatasetModels.select_from_geom`

### PR DESCRIPTION
**Pull request by MRegeard**
This PR is related to issue #4840. 

It introduce a selection from a geometry on `DatasetModels`. 

This methods create a mask and call `select_mask`.

### CODE REVIEW

**Review by QRemy — APPROVED** [review]
Thanks @MRegeard, no comment from my side.

**Review by adonath — APPROVED** [review]
Thanks @MRegeard, looks good to me!

**Comment by MRegeard** [comment]
Do you know why the CI is failling here ?

**Comment by Astro-Kirsty** [comment]
Thanks @MRegeard. The CI fail is unrelated, and present in many other PRs. 
I suggest we merge

**Pull request merged**
