### PR TITLE
Fix compatibility with pytest 3.x

### PR DESCRIPTION
**Pull request by astrofrog**
This is needed for the test suite to work with pytest 3.x

### CODE REVIEW

**Comment by cdeil** [comment]
@astrofrog - Thank you!

For the discussion whether affliated packages should change from using the bundled pytest version to an external one, is this ongoing, or should we make this change now in Gammapy?

**Comment by astrofrog** [comment]
@cdeil - I would say let's just wait to see how the PR to the core package: https://github.com/astropy/astropy/pull/5694 - if you have opinions, feel free to weigh in. Would it be a problem to require gammapy users to install pytest themselves?

**Comment by cdeil** [comment]
> Would it be a problem to require gammapy users to install pytest themselves to run tests?

No, that's fine.

If possible the transition should be smooth though, i.e.
```
python -c 'import gammapy; gammapy.test()'
```
should work both with the released Gammapy 0.5 (which imports pytest from `astropy.helpers.tests`) and future Gammapy releases that import the system pytest, both with Astropy 1.3 and dev/2.0.

**Comment by cdeil** [comment]
>  if you have opinions, feel free to weigh in. 

See https://github.com/astropy/astropy/pull/5694

> Would it be a problem to require gammapy users to install pytest themselves to run tests?

I think that would be fine, as long as it's possible to have `pytest` as an *optional* dependency.

I'm a little fuzzy on what the best way to declare the dependency would be for pip / conda / Macports / ...
Ideally I do want users to be able to type `gammapy.test()`, i.e. have `pytest` installed by default.
On the other hand, I do want to keep the list of *required* dependencies as short as possible.

But that's a concern not specific to `pytest`, it also applies to `click`, `scipy` and other dependencies, and for pip can be handled with variants like `gammapy[recommended]`.
So that's a separate discussion in Gammapy from the proposed pytest change.

**Pull request merged**
