### PR TITLE
Add interface to HESS FitSpectrum JSON output

### PR DESCRIPTION
**Pull request by cdeil**
In HAP one can dump spectral results to JSON via
```
FitSpectrum --InputFile hap_output.root --OutputJSONFile spec.json --BatchMode --FitModels PowerLaw,ExpCutoffPL3
```

This adds some code to read HESS FitSpectrum JSON output files.
It's useful for batch processing and checks and for the HGPS catalog.

@kingj90 – Let me know what you think of if this is overlapping with things you're working on.

### CODE REVIEW

**Comment by kingj90** [comment]
Well, I guess you have done everything that I did so far and much more. I just don't see how to integrate this smoothely into gammapy.spectrum but I guess nobody knows that ...

**Comment by kingj90** [comment]
Well, I guess you have done everything that I did so far and much more. I just don't see how to integrate this smoothely into gammapy.spectrum but I guess nobody knows that ...

**Comment by cdeil** [comment]
> I just don't see how to integrate this smoothely into gammapy.spectrum but I guess nobody knows that ...

I don't know yet.

It's difficult and we first have to decide if Gammapy uses Sherpa as a library or if Gammapy is a plugin to Sherpa, extending it with things we need. Maybe the best solution is a mix, i.e. sometimes wrap Sherpa, sometimes extend it.

For now I'd say it's OK for everyone to prototype and hack things together to make it work for them in `gammapy.spectrum`.
And then in the coming few months we'll find a good solution and clean up (but already have working code and maybe even unit tests for the major things we need to do / compute, just the API / implementation will change heavily).

**Comment by kingj90** [comment]
Can you merge this so I can add the stuff I did?

**Comment by cdeil** [comment]
Added a changelog entry and moved the TODO list from the GH issue to the docstring in that file.
Merging now (there's no tests, so travis-ci should pass OK)

**Pull request merged**
