### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by maxnoe**
**Description**

This pull request forces the light theme to be used by the docs regardless of system preference.

**Dear reviewer**

### CODE REVIEW

**Comment by Astro-Kirsty** [comment]
Thanks for this @maxnoe. I understand it is still a draft, but at some stage can you please push a preview to your GitHub so we can see how it looks. i.e. https://astro-kirsty.github.io/gammapy-docs-preview/

**Comment by maxnoe** [comment]
Any reason not to use the PR build feature of readthedocs?

**Comment by registerrier** [comment]
Thanks @maxnoe . Updating to `sphinx-design` is a good idea indeed.

I think we should separate the dependencies for the docs build from the rest of the dev environment as there can be conflicting requirements. The correct way to build the docs should be through `tox -e build_docs`.

**Comment by maxnoe** [comment]
I don't think there can be conflicts between docs requirements and the main requirements.

After all, the docs need to execute the tutorial notebooks.

**Comment by registerrier** [comment]
> I don't think there can be conflicts between docs requirements and the main requirements.
> 
> After all, the docs need to execute the tutorial notebooks.

Currently we have an astropy<5.3 imposed for the docs environment (I think because of multiprocessing issues) see https://github.com/gammapy/gammapy/pull/4537

**Comment by maxnoe** [comment]
I can locally build the docs using astropy 6....

**Comment by adonath** [comment]
> Any reason not to use the PR build feature of readthedocs?

We moved away from readthedocs a few years ago, because we required more computational resources to build the docs. Building the tutorials just takes to much time. By now, as an open source project, I think you can request more resources. Or people could also setup their own readthedocs build for their fork. But I haven't tried in a few years. The local build and a preview repo worked fine for most people, because docs changes that require a preview are rather rare.

**Comment by maxnoe** [comment]
Here you go: https://maxnoe.github.io/gammapy-docs-prs/

**Comment by Astro-Kirsty** [comment]
Thanks again. 
The drop down menus (i.e. [here](https://maxnoe.github.io/gammapy-docs-prs/getting-started/index.html#tutorials-overview) and [here](https://maxnoe.github.io/gammapy-docs-prs/user-guide/howto.html#how-to)) do not obviously look like drop downs. I would not know they could expand. Is there a way to change the '-' sign to more of button look for example a '+' or 'v', so it is more obvious?

**Comment by maxnoe** [comment]
That's weird, I see a proper caret for the drop downs

**Comment by Astro-Kirsty** [comment]
This is what I see

Screenshot from 2024-04-03 17-34-48

**Comment by maxnoe** [comment]
Ah, sorry, not the dropdown menus, the accordions.

Will have a look

**Comment by maxnoe** [comment]
Fixed now

**Review by adonath — DISMISSED** [review]
Thanks @maxnoe, looks good to me!

**Review by registerrier — APPROVED** [review]
Thanks @maxnoe . Looks good to me too.

**Comment by registerrier** [comment]
Merging now.

**Pull request merged**
