### PR TITLE
Fix Numpy dev build on travis-ci

### PR DESCRIPTION
**Pull request by cdeil**
This is an attempt to fix the Numpy dev build on travis-ci.

I think the issue might be that `conda install libgfortran` is missing, so no Fortran and Numpy build gives Fortran-related linker errors: https://travis-ci.org/gammapy/gammapy/jobs/482838855#L1597

### CODE REVIEW

**Comment by cdeil** [comment]
Last week the Numpy dev build for Gammapy started to fail. The issue is that `pip install -U git+https://github.com/numpy/numpy.git#egg=numpy` somehow picks up a compiler that can't handle fortran (even though `libgfortran-ng-7.3.0` is installed):
```
 /home/travis/miniconda/envs/test/lib/libopenblas.so: undefined reference to `_gfortran_concat_string@GFORTRAN_7'
  /home/travis/miniconda/envs/test/lib/libopenblas.so: undefined reference to `_gfortran_etime@GFORTRAN_7'
  collect2: error: ld returned 1 exit status
```
I tried a few things (e.g. `export NPY_DISTUTILS_APPEND_FLAGS=1` as suggested in https://github.com/numpy/numpy/issues/12799#issuecomment-456481761), or a `conda install numpy` first before trying the `pip install -U git+https://github.com/numpy/numpy.git#egg=numpy`, but the error always remains the same.

@bsipocz @astrofrog - Have you seen this issue already? Any idea why it started or how to fix it?

**Comment by cdeil** [comment]
Looking at https://github.com/sherpa/sherpa/blob/master/travis/setup_conda.sh it seems that installing miniconda and `conda install numpy` doesn't ship all the gcc compiler components needed.

I find that `apt install gcc` fixes the issue (@adonath - Thanks for the tip!) so I'll try adding that.
We don't really care exactly how the Numpy dev build occurs in our CI, we just want to have it to catch regressions in Numpy that affect us early. Probably we could also just delete that build, since Astropy has a Numpy dev build and for Gammapy this build has never caught an issue (unless I forgot about it).

**Comment by cdeil** [comment]
Still didn't work on travis-ci: https://travis-ci.org/gammapy/gammapy/jobs/483392850

I did file an issue here: https://github.com/conda-forge/numpy-feedstock/issues/124

I'm removing that numpy dev build now. We can try to add it back later if deemed useful.

**Comment by bsipocz** [comment]
@cdeil - I'm fairly certain that you got into conda-forge related issues that we don't see with astropy as we are very conservative to stick with the defaults channel and never use conda-forge for CI. 

I would be a bit worried to remove the numpy-dev build. Many packages (scikit-image, theano and dask comes to my mind, but I'm sure there are more) in this round (for the 1.16 release) got into troubles and had to issue emergency bug fix releases to fix numpy related issues that all their downstream dependents were running into. I'm not familiar with gammapy's downstream very well, if you think it's not many packages then I guess this removal is OK.
A compromise could be to only run numpy-dev from the cron less frequently.

Also, there are plans to switch to use daily builds for dev testing, once we set it up for astropy I plan to ping the affiliated packages' maintainers to know about the option.

**Pull request merged**
