### PR TITLE
Rework SkyCube class

### PR DESCRIPTION
**Pull request by adonath**
This PR refactors the `SkyCube` class as following:

* Removed `.coordinates()` and `.solid_angle()` methods. These can be now accessed via `SkyCube.spatial.coordinates()`, where `SkyCube.spatial` is a property returning a reference `SkyImage`
* Add a simple  `SkyCube.show()` method that works in notebooks with a slider
* Simplify `SkyCube.reproject()` by reusing `SkyImage.reproject()`
* Replace `SkyCube.world2pix()` by `SkyCube. wcs_skycoord_to_pixel()` which takes `SkyCoord` objects and makes it consistent with `SkyImage`
* Replace `SkyCube.pix2world()` by `SkyCube. wcs_pixel_to_skycoord()` which returns `SkyCoord` objects and makes it consistent with `SkyImage`
* Rename `SkyCube.flux()` to `SkyCube.lookup()`, which is now consistent with `SkyImage`

### CODE REVIEW

**Comment by cdeil** [comment]
@adonath - Thanks!

The one change I don't like is `ref_sky_image` -> `spatial`.
With "spatial" I have no idea from the name what it is.
It's a sky image, so having "sky_image" in the name results in more intuitive / readable code, no?

**Comment by adonath** [comment]
I like the name `SkyCube.spatial` in the context, that it is typically used. I.e. I found it more intuitive to read `SkyCube.spatial.coordinates()` or `SkyCube.spatial.footprint()` instead of `SkyCube.ref_sky_image.coordinates()` or `SkyCube.ref_sky_image.footprint()` . I see it more like a bonus for better readable code, because you can always use `SkyCube.sky_image(0).coordinates()`.

**Comment by cdeil** [comment]
>  I found it more intuitive to read SkyCube.spatial.coordinates() or SkyCube.spatial.footprint() instead of SkyCube.ref_sky_image.coordinates() or SkyCube.ref_sky_image.footprint() .

I think that's because you just wrote it and know what king of object `spatial` is.
IMO it's clear that the more descriptive name "ref_sky_image" is more intuitive ... makes it clear that it's a `SkyImage` object.

> you can always use SkyCube.sky_image(0).coordinates().

Yes. And I wasn't sure if I should introduce the `ref_sky_image` property.
I'm +1 to keep it because I thought it is good to have this pattern as a separate property, not just documented as part of the `cube.sky_image` docstring.

But that's a different question / suggestion to the change proposed here, which is to rename `ref_sky_image` to `spatial`.

The other change here is `property` -> `lazyproperty`, which I think is a good one.

**Comment by adonath** [comment]
@joleroi Any opinion on `SkyCube.spatial` vs. `SkyCube.ref_sky_image`?

**Comment by joleroi** [comment]
Why not call it ``ref_sky_image`` but return an empty sky image with the right geometry. Than the property would be somehow useful, otherwise you just avoid typing
```
cube.sky_image[0].coordinates
```
which is actually shorter than
```
cube.ref_sky_image.coordinates
```

**Comment by joleroi** [comment]
Why not call it ``ref_sky_image`` but return an empty sky image with the right geometry. Than the property would be somehow useful, otherwise you just avoid typing
```
cube.sky_image[0].coordinates
```
which is actually shorter than
```
cube.ref_sky_image.coordinates
```

**Comment by adonath** [comment]
@joleroi Thanks! That's how it used to be. I'll revert my change.

**Pull request merged**
