### PR TITLE
Update SpectrumFit

### PR DESCRIPTION
**Pull request by joleroi**
This PR rewrite the `~gammapy.spectrum.SpectrumFit` to make it more independent of Sherpa.

With this new version all that's used are the sherpa optimizers, everything else is done 'in-house'. This makes the fit more transparent and easier to extend to our needs. Also the sherpa backend is completely optional and can easily exchanged to e.g. minuit.

pair coding with @adonath 

A follow up PR is needed to

* [ ] Add Parameters class to simplify/improve code
* [ ] Improve ``SpectrumFitResult`` to store all the extra info that's available now due to this change (stats per bin, bins in fit range, etc.)

### CODE REVIEW

**Comment by joleroi** [comment]
@adonath I've put you as reviewer, I don't think it makes sense to review the changes, but if you have time you can have a look at  

https://github.com/joleroi/gammapy/blob/3d6bfaf1cd146132ec71195866ae9dacb565c33c/gammapy/spectrum/fit.py

**Comment by cdeil** [comment]
👍 

Is it necessary to define the classes in `_fit_sherpa`? Or could they be defined separately?
Wouldn't separately be simpler / more readable / better testable / maybe re-usable?

**Comment by joleroi** [comment]
> Is it necessary to define the classes in _fit_sherpa? Or could they be defined separately?
Wouldn't separately be simpler / more readable / better testable / maybe re-usable?

They could be defined separately (which would be more readable), the only issue is that they rely on sherpa imports, so we need some ``if sherpa ... else`` logic. How would you do that?

**Comment by cdeil** [comment]
If this is a generic adapter interface to use Sherpa for fitting, then it should probably go in `gammapy.utils` instead of `gammapy.spectrum`, so that it's usable from other parts of Gammapy as well.

In principle there's nothing wrong with having module-level Sherpa imports at the top. We do have this here: https://github.com/gammapy/gammapy/blob/master/gammapy/cube/sherpa_.py
That is OK if *all* functionality in that file only works with Sherpa, and users / tests only will import that file if they need Sherpa.

The pytest test collection doesn't import all `*.py` files, it only imports all `test_*.py` files during test collection. So if tests are marked as `requires_dependency('sherpa')` like in https://github.com/gammapy/gammapy/blob/master/gammapy/cube/tests/test_sherpa_.py, that's OK.

(Side comment to @adonath - why the trailing underscore on those files in `gammapy.cube`. suggest to remove them. IMO where it's easy to choose names that aren't used by others, it's nice to avoid it. But e.g. we also have `gammapy.utils` and it's up to users to keep it straight that it's different from `astropy.utils`.)

If you have to sub-class from an optional dependency, and have to be able to import and use that file without having the optional dependency installed, I think try-except is the most common pattern. Here's an example: https://github.com/astropy/astropy/blob/master/astropy/visualization/mpl_normalize.py#L16

**Comment by joleroi** [comment]
> If this is a generic adapter interface to use Sherpa for fitting, then it should probably go in gammapy.utils instead of gammapy.spectrum, so that it's usable from other parts of Gammapy as well.

It's not, the Sherpa classes are Monkey patched to call methods on ``SpectrumFit``. I have not idea how to make this more general (without re-implementing a whole fitting framework)

> In principle there's nothing wrong with having module-level Sherpa imports at the top. We do have this here: https://github.com/gammapy/gammapy/blob/master/gammapy/cube/sherpa_.py

Will do that, thanks!

**Comment by cdeil** [comment]
🐒 🙉 🙉 🙊  - oh my!

**Comment by joleroi** [comment]
> :monkey: :hear_no_evil: :hear_no_evil: :speak_no_evil: - oh my!

what? :laughing:

**Comment by joleroi** [comment]
This PR breaks two test

* ``test_method_fit``
https://github.com/gammapy/gammapy/pull/844/files#diff-b4343765f77158545b2cb72859e06e77R189

The sherpa optimizer is now hard coded to ``simplex`` for reasons explained [here](https://github.com/joleroi/gammapy/blob/1e31cdf5cc29086238695cf8527e284d3a7ce9cc/gammapy/spectrum/fit.py#L248). @leajouvin do you urgently need another optimizer or can we keep it like that for now>

* ``test_stats_per_bin``
https://github.com/gammapy/gammapy/pull/844/files#diff-b4343765f77158545b2cb72859e06e77R159

Will be resolved in a follow up PR

**Comment by joleroi** [comment]
I added a small fix requested by @JouvinLea . It should not affect the test, let's still wait for them to pass ...

**Pull request merged**
