### PR TITLE
Add Parameter class to SpectralModel

### PR DESCRIPTION
**Pull request by joleroi**
Work in progress

I did not use the Parameter class in ``gammapy.utils.modelling``. There, the entire class hirarchy in ``gammapy.spectrum.models`` is duplicated - so clearly someone needs to take the time to merge these two efforts. During this step also the Parameter classes can easily be merge.

### CODE REVIEW

**Comment by cdeil** [comment]
@joleroi - I suggest we spend the time this week and merge the parameter, parameter list and model classes. I think it's mostly straight-forward and just needs to be done? Maybe you finish up your PRs and when we try to do some pair-coding in the coming days? (E.g. I'm completely free Thursday afternoon.)

**Comment by cdeil** [comment]
> I did not use the Parameter class in gammapy.utils.modelling. There, the entire class hirarchy in gammapy.spectrum.models is duplicated - so clearly someone needs to take the time to merge these two efforts. During this step also the Parameter classes can easily be merge.

OK to merge if you want. But that merging will have to be done in the next few days anyways.
A compromise could be that you merge the Parameter and ParameterList classes you're adding here into the existing classes in `gammapy.utils.modeling` instead of introducing new ones, and leave the merging of the spectral model classes for later.

**Comment by joleroi** [comment]
@adonath and I merged the Parameter class into ``gammapy.utils.modelling``

**Comment by cdeil** [comment]
🎉 

(my preference would be that you just merge and I try it out in the coming days, unless you have a specific question or want me to review it)

**Comment by joleroi** [comment]
There's one remaining test failure I don't understand

https://travis-ci.org/gammapy/gammapy/jobs/200271615#L1174

@adonath this is your code isn't it? Can you have a look. The issue is related to using the spectral models with the ``uncertainties`` package.  It works in [model_with_uncertaintes](https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/results.py#L204) because of [this hack](https://github.com/gammapy/gammapy/pull/871/files#diff-90d93e3f87faba7604669476830a4b80R77). In the failing test the ``uncertainties`` package is used in a different way (that I don't understand).

**Comment by joleroi** [comment]
As discussed offline I xfailed the failing test

**Comment by joleroi** [comment]
failing tests related to gammacat will be fixed in TODO (@cdeil)

**Comment by cdeil** [comment]
I'm working on the gammacat tests in #815 and will try to fix things there.
(or xfail there and leave it to next week)

**Comment by cdeil** [comment]
@joleroi - What about this fail (I see it locally, didn't check on travis-ci yet).
Can you see it? Fix it?
```
______________________________________________________________ TestSpectrumFitResult.test_model_with_uncertainties _______________________________________________________________

self = <gammapy.spectrum.tests.test_results.TestSpectrumFitResult object at 0x1604609e8>

    @requires_dependency('uncertainties')
    def test_model_with_uncertainties(self):
>       actual = self.fit_result.model_with_uncertainties.parameters.index.s
E       AttributeError: 'ParameterList' object has no attribute 'index'
```

**Comment by joleroi** [comment]
Fixed in https://github.com/gammapy/gammapy/commit/71279675f5147f6df9fe7c90c1f6cc7454d862fc

**Pull request merged**
