### PR TITLE
Correct FluxPointsEstimator to handle empty datasets slices

### PR DESCRIPTION
**Pull request by registerrier**
**Description**

This pull request proposes a correction for issue #3505 . 

Most of the difficulty comes from the fact that, because of the inheritance, information is lost when going to the various `.run()` methods. Since only the lowest level `ParameterEstimator.run()` can compute the resulting dictionary, if it fails at a higher level (e.g. here with the impossibility to find the reference model on an empty `Datasets`), no result dict can be returned. 
This PR re-introduces a `nan_result` method that will produce a `dict` filled with nans for all expected entries. This is non ideal as any change at the lower level will require to update there as well.

At least a test is added to ensure that these issues do not go under the radar.

Opinions @adonath ?

**Dear reviewer**

### CODE REVIEW

**Comment by adonath** [comment]
The conclusion here was to try and internal API, where the `datasets` and `models` are passed in to estimators separately. Did you have time to try this @registerrier? Or do you want me to take this over?

**Comment by registerrier** [comment]
> The conclusion here was to try and internal API, where the `datasets` and `models` are passed in to estimators separately. Did you have time to try this @registerrier? Or do you want me to take this over?

Thanks @adonath . I am currently updating the PR to pass `models` along `datasets` in `FluxEstimator` and `ParameterEstimator` as this is a blocker for hess validation. This should be ready before the next dev call.

**Comment by registerrier** [comment]
> The conclusion here was to try and internal API, where the `datasets` and `models` are passed in to estimators separately.

Trying to implement a solution where we pass `Models` down to the `ParameterEstimator` we still have the issue that the `FluxEstimator` has to compute a reference flux for the energy range, which it can't do if an empty `Datasets` is passed to `run`. It is therefore probably unavoidable to compute part of the result dictionary on the highest level.
Otherwise one has to pass the energy interval to `run`.

**Comment by adonath** [comment]
@registerrier I resolved the merge conflict and will merge now.

**Pull request merged**
