### PR TITLE
Fix test fail in dev deps

### PR DESCRIPTION
**Pull request by AtreyeeS**
This fixes the test fails arising from astropy 6.0.0rc1 #4898

### CODE REVIEW

**Comment by maxnoe** [comment]
@AtreyeeS This should be unnecessary, the issue is going to be fixed in astropy itself:

Sorry, I forgot to link the issue I opened with astropy here: https://github.com/astropy/astropy/issues/15601

**Comment by AtreyeeS** [comment]
Thanks @maxnoe for raising this issue in astropy! 
I will keep the PR open till the next astropy rc

**Comment by registerrier** [comment]
Thanks @AtreyeeS and @maxnoe !

**Comment by registerrier** [comment]
Fix has been introduced in astropy . Closing now.

**Pull request closed without merging**
