### PR TITLE
Make gammapy.time great again

### PR DESCRIPTION
**Pull request by cdeil**
This PR contains misc improvements to `gammapy.time`:
- [x] Improve `exptest` docstring
- [x] Add high-level docs
- [x] Fix make_random_times_poisson_process implementation and test
- [x] Improve `examples/example_exptest.py`

WIP, do not merge!

### CODE REVIEW

**Comment by joleroi** [comment]
great_again

**Comment by cdeil** [comment]
It's going to be huuuuuge!

**Comment by cdeil** [comment]
https://www.youtube.com/watch?v=c2DgwPG7mAA

**Comment by cdeil** [comment]
I merged this locally.

**Comment by joleroi** [comment]
Thank you @cdeil. You've done a great job and I think that's beautiful, beautiful, beautiful. You've taken control over your software project back.
https://www.youtube.com/watch?v=qGsegBT7kCI

**Comment by adonath** [comment]
Following an election within the Gammapy developer community the `gammapy.time` package has been removed from office in https://github.com/gammapy/gammapy/pull/2931.

joe-biden

**Pull request closed without merging**
