### PR TITLE
Restrict sphinx applehelp version

### PR DESCRIPTION
**Pull request by adonath**
See title

### CODE REVIEW

**Review by registerrier — COMMENTED** [review]
Thanks @adonath . Apparently 1.0.7 still requires sphinx>5.0. An older version seems to be necessary.

**Comment by Astro-Kirsty** [comment]
It seems that this fixes one issue but creates a new one with `sphinx-panels`, at least on my laptop
''sphinx-panels 0.6.0 requires sphinx<5''

**Comment by MRegeard** [comment]
Apparently you need version 1.0.4 or before. Because 1.0.5 and after require Sphinx >=5.0.

**Comment by Astro-Kirsty** [comment]
Yes, however this breaks something else.

```
Sphinx version error:
The sphinxcontrib.devhelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```

**Comment by adonath** [comment]
We had a working CI ~ a week  ago, so there must be some solution. I'll check...

**Comment by adonath** [comment]
The setup seems to work again, but I had to restrict multiple version of the sphinx contrib packages...

**Review by Astro-Kirsty — APPROVED** [review]
Thanks @adonath. 

It appears to working well now!

**Review by MRegeard — APPROVED** [review]
Thanks @adonath for fixing that !

**Comment by adonath** [comment]
Thanks for the review @Astro-Kirsty and @MRegeard !

**Comment by registerrier** [comment]
@meeseeksdev backport to v1.0.x

**Comment by registerrier** [comment]
@meeseeksdev backport to v1.1.x

**Pull request merged**
