### PR TITLE
WIP: Add SED viewer

### PR DESCRIPTION
**Pull request by cdeil**
Implement an interactive SED viewer using IPython widgets.

It should be able to display flux points from the Fermi catalogs or published TeV spectra and then have controls to "manually fit" (or get good starting values) for simple SED models as the one implemented in `gammafit`.

### CODE REVIEW

**Comment by joleroi** [comment]
FYI: You can get FluxPoints from the Fermi catalogs via
```
from gammapy.spectrum import DifferentialFluxPoints, IntegralFluxPoints

# Load .e.g 3FGL cat and define source

diff_points = DifferentialFluxPoints.from_3fgl(source)
int_points = IntegralFluxPoints.from_3fgl(source)
```

**Comment by cdeil** [comment]
@joleroi - Thanks for implementing this!

Long-term, I think the `FluxPoints` object shouldn't have to know about the Fermi catalogs, i.e. it should be organised the other way around.
```python
from gammapy.catalog import source_catalogs
cat = source_catalogs['3fgl']
flux_points = cat[source].flux_points
```
I.e. the Fermi catalog objects have a method or property that returns a `FluxPoints` object.

Thoughts?

**Comment by joleroi** [comment]
The Flux points module does not know about the Fermi catalogs, you pass it the source dict

```
from gammapy.catalog import source_catalogs
cat = source_catalogs['3fgl']
source = cat['myfavouritesource']
flux_points = DifferentialFluxPoints.from_3fgl(source)
```

But I guess your API is still nicer ....

**Comment by cdeil** [comment]
> The Flux points module does not know about the Fermi catalogs

If you put this method on the `FluxPoints` class, you've coupled catalog and flux points in a way that `FluxPoints` knows about catalog and would have to add other `from_hgps` methods etc, no?
`DifferentialFluxPoints.from_3fgl`

**Comment by joleroi** [comment]
I had a different understanding of 'knows about' ... I will copy the methods over in some future PR

**Comment by joleroi** [comment]
Update: http://docs.gammapy.org/en/latest/spectrum/plotting_fermi_spectra.html 
by @adonath

**Comment by cdeil** [comment]
I'm closing this old PR.  It was mostly me trying to learn how it might be possible to make a Jupyter widget and expose it from a library.

In principle, Jupyter and JupyterLab widgets to interactively work with gamma-ray data are welcome in Gammapy. But in this case of an SED viewer it's hard to make a really useful GUI, and probably we should just try to use existing GUIs (especially http://cxc.cfa.harvard.edu/iris/) and see how to  interface to them with Gammapy.

**Pull request closed without merging**
