### PR TITLE
Remove cta_utils and CTASpectrumObservation

### PR DESCRIPTION
**Pull request by cdeil**
@joleroi - Look, I found another `Target` class to delete, following your lead in #1490.

This PR removes `gammapy.scripts.cta_utils`, which had a `CTASpectrumObservation`, which from what I can tell does almost exactly what [gammapy.spectrum.SpectrumSimulation](http://docs.gammapy.org/dev/api/gammapy.spectrum.SpectrumSimulation.html) does. There even was a TODO comment that the two should be merged.

I would suggest to merge this now and continue removing duplicated / non-essential things.

But then we still should make the existing examples that people in CTA use work again, i.e. migrate this notebook to use `gammapy.utils.SpectrumSimulation`:
http://docs.gammapy.org/dev/notebooks/cta_simulation.html

### CODE REVIEW

**Comment by cdeil** [comment]
@jjlk - FYI.

**Comment by cdeil** [comment]
I'll just go ahead. We can always bring back stuff if people complain and really some features get lost in the cleanup.

**Comment by joleroi** [comment]
Agreed

> But then we still should make the existing examples that people in CTA use work again, i.e. migrate this notebook to use gammapy.utils.SpectrumSimulation:
http://docs.gammapy.org/dev/notebooks/cta_simulation.html

I put it on my agenda

**Comment by jjlk** [comment]
Hi @cdeil , @joleroi ,
Those utility classes are currently used in the analyses of several ongoing CTA consortium papers (EBL, LIV, AGN, GRB, Pevatron). I think we have to wait a bit before removing everything (I'm not the only user of those scripts).

 (CC to @registerrier , @bkhelifi , @santiagopita , @jlenain , @ctrichard , @cboisson, and +)

**Comment by cdeil** [comment]
@jjlk and all - we're not removing everything. The strategy is to never remove something, unless there is an equivalent or better way to do the same thing.

In this case, I think `gammapy.scripts.cta_utils.CTASpectrumObservation` was basically a duplicate of `gammapy.spectrum.SpectrumSimulation`, except that the API was slightly different how the IRF object is passed in. So updating should be a matter of adapting the import and a few lines, changing your script to `gammapy.spectrum.SpectrumSimulation`. We're more than happy to help with this, feel free to ask anytime or complain about specific things on Slack or mailing list of Github issues. In some cases also using Gammapy v0.7 and keeping things as-is might be an option instead of updating to Gammapy v0.8.

Just to explain the reason for the cleanup: we have 37,000 lines of code in Gammapy, and about half of that is duplication of functionality. We have to move to a better, clean package to be able to succeed with Gammapy in general, and for the CTA ST selection in the fall specifically. So we're trying to balance short-term pain for the few (10s) of current users with the long-term benefit for the coming years for 100s or 1000s of users. This removal of e.g. `gammapy.scripts.cta_utils.CTASpectrumObservation` has to come, we can't have multiple classes that do the same thing long-term, we don't have the manpower to maintain, and it's also a disservice to users. If really needed, we can add it back, but please try to change to `SpectrumSimulation` first and let us know if that doesn't work for you.

All - please join the Gammapy call this Friday 10 am (https://github.com/gammapy/gammapy-meetings/tree/master/2018-07-20) or let me know if a separate short call would be helpful.

**Comment by jjlk** [comment]
I underdstand your points. But please keep in mind that the main reason we introduced `CTASpectrumObservation` was to handle the FITS point-like IRFs, that we converted from ROOT files provided by the ASWG group, with the `CTAPerf` class (also written in the `~gammapy.scripts`). And please consider also that the tools have been tested and used since more than one year.

 I'll try to join the call next Friday ++

**Comment by cdeil** [comment]
@jjlk - I understand.

But we still have to do this clean-up, either now before the v0.8 release or in a few weeks after the v0.8 release, or at the very latest before Gammapy v1.0 this fall.

Note that this cleanup of `CTASpectrumObservation` and `CTAPerf` in `gammapy.scripts` is just a small part of all the work that is going on in Gammapy. We've also introduced `gammapy.maps` and are very far along with the rewrite of all map-based analysis. That means every user of `SkyImage` and `SkyCube` will have to adapt their scripts in the coming weeks. The same holds for the other parts of Gammapy, e.g. `gammapy.irf` or `gammapy.data` or `gammapy.spectrum`.

Let's work together to make this transition. I think on the Gammapy side, the changes to `SpectrumSimulation` needed to support your analyses are small (I just saw #876, moving this to the v0.8 milestone now), and also for you the time investment to update your scripts for your papers should be small, if you choose to update to Gammapy v0.8 for them. And we're happy to help.

> I'll try to join the call next Friday ++

Great!

**Pull request merged**
