### PR TITLE
Reformat content in docs How To

### PR DESCRIPTION
**Pull request by Bultako**
This PR intends to address[ feedback received](https://github.com/gammapy/gammapy/issues/3746#issuecomment-1022363488) for the `How To` section. 

For the moment it just implements cosmetic modifs in the dropdown boxes, also adding links to the related tutorials.
Additions or modifications in the content or the list of items could be done in the review process of this PR.

You may access how the docs shows with this PR in the [usual link](https://www.iaa.csic.es/~jer/gammapydocs/userguide/howto.html).

### CODE REVIEW

**Comment by adonath** [comment]
Thanks a lot @Bultako, this is very nice! Is it possible implement this as a Sphinx extension / directive to avoid the repetitive HTML code?

**Comment by adonath** [comment]
See maybe: https://www.sphinx-doc.org/en/master/development/tutorials/helloworld.html

**Comment by Bultako** [comment]
@adonath 
sphinx directives added

**Review by registerrier — APPROVED** [review]
Thanks @Bultako ! This looks really good. No comment from my side.

**Review by adonath — APPROVED** [review]
Thanks @Bultako, no further comments from my side either..

**Pull request merged**
