### PR TITLE
Add a simple tutorial for doing 2D image analysis

### PR DESCRIPTION
**Pull request by AtreyeeS**

### CODE REVIEW

**Comment by adonath** [comment]
Thanks, @AtreyeeS! Somehow the notebook `.ipynb` file is corrupted. Neither the github rendering works, nor can I open it locally with jupyter. Can you please check?

Three minor comments already:
- Can you rename the notebook to the shorter `image_fitting.ipynb`?
- Please add the notebook to the `docs/tutorials.rst` page in the section "2-dimensional sky image analysis".
- Also add the notebook to the `tutorials/notebooks.yaml` file, so that it will be listed for downloads.

**Comment by adonath** [comment]
I'll do an in-depth review once I can see the content of the notebook...

**Comment by AtreyeeS** [comment]
Hello Axel! I deleted the old tutorial and replaced it with a new one. The git rendering seems to work now.

Have added the link in the rst file as well.

**Comment by adonath** [comment]
@AtreyeeS Thanks, the notebook looks very good to me! Here are a few minor comments for improvements:

- Change title to `Fitting 2D images with Gammapy ` to make it consistent with the sherpa notebook
- Define a "global" energy range `e_min, emax = [0.1, 10] * u.TeV` at the beginnig of the notebook, that is used consistently throughout the tutorial
- Pass a reference spectrum `spectrum = PowerLaw2(index=2)` to `MapMaker.make_images()` just to make it explicit, that a weighted exposure map is computed.
- Use the same energy spectrum to compute the mean PSF (right now I'm not sure, whether the correct exposure- and source-spectrum weighted PSF is computed, can you check?) I presume you have to either call `PSFKernel.make_image()` or `EnergyDependentTablePSF.table_psf_in_energy_band()`, which is not the case at the moment.
- Maybe change to `PowerLaw2` for the model fit? The integrated flux might be the more intuitive parameter.

Except for the correct exposure weighted PSF the changes are optional. Do whatever you have time for and we'll merge before today evening.

**Comment by AtreyeeS** [comment]
Thanks @adonath! I have made the changes.

Regarding calling a `PSFKernel.make_image()`,  directly calling `PSFKernel.from_table_psf()` using a 2D geometry. So this should be fine I believe.

**Comment by adonath** [comment]
@AtreyeeS Thanks for the implementing the comments!

As far as I can tell [`energy_dependent_table_psf_to_kernel_map`](https://github.com/gammapy/gammapy/blob/master/gammapy/cube/psf_kernel.py#L82) only evaluates the PSF at the energy center and does not compute an exposure weighted PSF. So the correct way should rather be:

```
table_psf = make_mean_psf(observations, src_pos)

# this line is missing
table_psf_2d = table_psf.table_psf_in_energy_band((e_min, e_max), spectrum=spectrum)

# PSF kernel used for the model convolution
psf_kernel = PSFKernel.from_table_psf(table_psf_2d, geom2d, max_radius="0.3 deg")
```

If you don't have time I can add this change to your PR...

**Comment by AtreyeeS** [comment]
Thanks @adonath for this! Clears my concept as well.
Implemented the weighing now.

**Comment by adonath** [comment]
Thanks @AtreyeeS! I've added a few minor commits (mostly clean up, such as removing unused imports and fixing typos) and added the notebook to out notebook index file `notebooks.yaml`, so that users can download it. I'll wait for the Travis build and merge. No changes further needed from your side. Thanks again!

**Pull request merged**
