### PR TITLE
Add notebook role to sphinx build

### PR DESCRIPTION
**Pull request by joleroi**
This PR adresses #749 

Please review

### CODE REVIEW

**Comment by cdeil** [comment]
@joleroi - Thank you very much!

Did you verify that it works locally by looking at the generated HTML?

I don't have time now, but I'll review tonight.
(I'm also OK to merge in master and if it works on RTD it's fine with me, if you prefer.)

**Comment by joleroi** [comment]
> Did you verify that it works locally by looking at the generated HTML?

Si

I have to catch the case that gammapy-extra is not available (at the moment I check if a given notebooks exists by looking at $GAMMAPY_EXTRA/notebooks.yaml to avoid dead links). Then I will merge if tests pass.

**Comment by joleroi** [comment]
Tests passed before, I only renamed to ``gp-extra-notebook``.

Merging this, will check if the online docs look ok in master.

**Comment by cdeil** [comment]
There was a typo (missing second backtick) in the `gp-extra-notebook` directives.
Fixed directly in master in 088d7934e035d1e439e2de0b1cc861674d035465

(and I changed to NBViewer, which does a better notebook rendering than Github, e.g. allowing to link to sub-section titles and later also table of contents and CSS styling)

**Pull request merged**
