### PR TITLE
Remove Github API in gammapy download CLI

### PR DESCRIPTION
**Pull request by Bultako**
This PR removes dependency of the Github REST API to download notebooks anda datasets from tutorials. It uses lookup index files delivered by http://gammapy.org web page:

* http://gammapy.org/download/data/gammapy-data-index.json
* http://gammapy.org/download/tutorials/gammapy-0.8-tutorials.yml
* http://gammapy.org/download/install/gammapy-0.8-environment.yml

The `test_notebook.py` script makes use of the config tutorials yaml file served by http://gammapy.org, this local config file for notebooks has been removed. The environment yml file will be removed in a next PR grouping fixes for Binder related with this files structure. 

Most of the code of `gammapy download` CLI has been refactored, and the interface / options have been simplified.

<pre>
$ gammapy download
Usage: gammapy download [OPTIONS] COMMAND [ARGS]...

  Download datasets and notebooks.

  Download notebooks published as tutorials and the related datasets needed
  to execute them. It is also possible to download individual notebooks or
  datasets. The files are copied into a folder created at the current
  working directory.

  Examples
  --------

  $ gammapy download notebooks
  $ gammapy download datasets
  $ gammapy download --release 0.8 tutorials
  $ gammapy download --src first_steps notebooks
  $ gammapy download --src fermi_3fhl --out localfolder datasets

Options:
  --out TEXT      Folder where the files will be copied.
  --src TEXT      Specific notebook or dataset to download.
  --release TEXT  Gammapy release for notebboks.
  -h, --help      Show this message and exit.

Commands:
  datasets   Download datasets
  notebooks  Download notebooks
  tutorials  Download tutorial notebooks and datasets
</pre>

### CODE REVIEW

**Comment by cdeil** [comment]
This sounds great.

One question: shouldn't `notebooks,yaml` remain in this repo, because it should be version-coupled to the notebooks and `docs/tutorials.rst` overview page.
Having it only in another repo will lead to versioninig / maintenance issues like we had with gammapy-extra, no?

Maybe keeping / maintaining it here, and putting a copy (versioned?) in `gammapy-webpage` so that it's accessed by users from there is worth considering?

It's just a question, I don't have an answer here. I think that last suggestion isn't complete, because it means things for dev version and released versions will be too different?

**Comment by Bultako** [comment]
@cdeil 

> One question: shouldn't notebooks,yaml remain in this repo,

We have `gammapy-0.8-environment.yml` and `gammapy-0.8-tutorials.yml` in `webpage` repo, they are used by `gammapy download` when we try to download tutorials for **stable release 0.8** We can only download tutorials and environments for stable versions, which means that for every release we should get these two files clean, with links to `http://rawgithup/gammapy/v0.8` in the case of the noteboks.yml files and fixed versions of dependencies and `gammapy` for the environment.yml file.

**Comment by cdeil** [comment]
So for the dev version we don't need the `notebooks.yaml` file, if working in-place with the notebooks?
Then it's OK.

If it's accessed for the docs build, then there would be a problem, right?
So I assume docs build doesn't go via the `notebooks.yaml`, but uses glob for the notebooks folder?

**Comment by Bultako** [comment]
`notebooks.yaml` is only accessed by  `gammapy download` and `test_notebooks.py`
btw, does `test_notebooks.py` really need it ? it is used mainly to skip tests if some requirements are not fulfilled.

Ok, for the `dev` version, we will need to update `notebooks.yaml` for additions/removal of notebooks or modifications of datasets used.

**Comment by cdeil** [comment]
Without having thought about it much, naively I would think that having the notebooks.yaml here in the Gammapy repo and maintaining / evolving it here, and also using it for testing and docs build would be best, and then as part of the release steps a stable copy is put on gammapy.org. I guess then gammapy download would need an if / else and for the dev version accesses the file in a different way than for stable versions? Is this the simplest / most maintainable setup? I'm not sure. @Bultako - Maybe just continue as you think best and merge everything in, and then we have a look and try it tomorrow at 10?

**Pull request merged**
