### PR TITLE
Fix Fermi catalog flux point upper limits

### PR DESCRIPTION
**Pull request by adonath**
This PR addresses the issues described in #856:

1.  Fix an issue with the covariance matrix in `SourceCatalogObject2FHL` and `SourceCatalogObject1FHL`.
2. Add upper limit information in to the flux points

For `PKS 2155-304` the plot looks now as following:
fermi_pks_2155_304

@jjlk Does it look allright to you?

### CODE REVIEW

**Comment by jjlk** [comment]
Hi @adonath , it looks awsome =)

**Comment by cdeil** [comment]
@adonath - Thank you!

Travis-ci passed, I'm merging this now.

In the test removed here you had `int_points.to_differential_flux_points`.
Like I said, I think it would be nice to expose that as a method (and probably the other way around should be added as well).
Or do you prefer to only have it as a standalone function?

In any case, the int -> diff flux conversion should be pointed out to users, as it's something to be aware of when plotting and analysing flux points.
So I'm +1 to change the docs examples to have int -> diff as an explicit step, e.g. here:
http://docs.gammapy.org/en/latest/spectrum/plotting_fermi_spectra.html

**Comment by cdeil** [comment]
The docs example with an upper limit is nice.

Can we change the source at to one that has upper limits:
http://docs.gammapy.org/en/latest/spectrum/plotting_fermi_spectra.html
or, for now, just add the script you developed here to `examples`?

**Comment by adonath** [comment]
@cdeil  I will add a method `FluxPoints.to_flux_points_dnde()` in a sperate PR and change (or add) the docs example accordingly.

**Comment by cdeil** [comment]
@adonath - Thanks!

I've been thinking about whether `FluxPoints.to_dnde()` should modify the object in-place or return a new object, with a copy of the table, i.e. no link back. And whether both directions `to_dnde` and `to_flux` should be added.

I think I'd be +1 to "yes" on both questions, but I don't see strong pros and cons yet. So do as you think best, just wanted to mention it, or get an opinion from @jjlk or @joleroi on what we should do, before you spend the time to implement it and modify docs / tests.

**Comment by cdeil** [comment]
@adonath - Did we forget to merge this? Or are you still working in this branch?

**Pull request merged**
