### PR TITLE
Exchange value by factor and scale in Parameter

### PR DESCRIPTION
**Pull request by joleroi**
Triggered by #1531 

With the current changes, the behaviour of ``Parameter`` to the outside does not change at all. Only the way the Parameter value is stored internally changes, namely by storing the parameter value as ``factor`` and ``scale``

In addition I added two methods to ``ParameterList`` (I'm not happy with the names, please make suggestions). One to scale all parameters such that ``factor`` is or order 1 (``scale_parameters_to_unity``) and one that reverts this such that ``scale=1`` (``scale_parameters_to_1``). The idea is that the first of these methods be called before the fit, to have useful values for the optimizer (need to be changed to work on ``factor`` rather than ``value``) and the second one be called after the fit, so the user basically doesn't notice that something happend in between.

### CODE REVIEW

**Comment by joleroi** [comment]
Please do not comment yet, I have to think about this a little more

**Comment by adonath** [comment]
Just a quick comment: I think the scaling should never be exposed in the public API, except maybe for the parameter init, where the scale is once set and the never changed. I think all the scaling and back-scaling should only happen internally prior to and after the fit.

**Comment by cdeil** [comment]
I'll have a closer look and merge this in now. Let's try to have a working example of a fit with scaled parameters by tomorrow 10 am, and then we can still change / refactor tomorrow.

**Comment by cdeil** [comment]
@joleroi - This is what @adonath and I would suggest: a156a421

The idea is to leave `covariance` in the `ParameterList` object to always be the covariance matrix for values, and to only add a helper method to set it from the covariance matrix for factors.

I'll try to add unit tests for this now, but basically that's the proposal.

**Comment by cdeil** [comment]
I added a bit of unit tests for Parameter and type validation also. E.g. earlier I made the mistake of passing a float for name because I didn't remember that it comes first and `str` was silently casting to a str.

This PR adds the separation to factor and scale, and already uses that in the optimiser interface.
It doesn't activate the "rescale" before the fit yet, that's till commented out.
Let's discuss this tomorrow morning and continue on this in a new PR.

Merging ...

@joleroi  - Thanks!

**Pull request merged**
