### PR TITLE
Replace deprecated property Observation.pointing_radec

### PR DESCRIPTION
**Pull request by QRemy**
Replace deprecated method Observation.pointing_radec() by Observation.get_pointing_icrs() in get_irfs_features

### CODE REVIEW

**Comment by QRemy** [comment]
On a side note maybe we could have `time` optional in `obsservation.get_pointing_icrs()` and if time is None : time =self.tmid
because in most of cases we just use tmid.

**Comment by bkhelifi** [comment]
Hi @QRemy ,

If you start to replace this deprecated function, maybe this PR should update at the same time much more files:
- documentation: EventList.rst, ObservationTable.rst, Observation.rst,
- in the tutorials cta.py, hess.py, makers.py, analysis_2.py, cta_data_analysis.py

A side comment:
In `gammapy/data/event_list.py`, we have the function `pointing_radec` that is not deprecated. Is it normal?

**Comment by adonath** [comment]
> On a side note maybe we could have time optional in obsservation.get_pointing_icrs() and if time is None : time =self.tmid because in most of cases we just use tmid.

I commented about this as well https://github.com/gammapy/gammapy/pull/4220/files#r1082899314

I think the compromise would be to introduce a property `obs.pointing_icrs_tmid`, which make it explicit that the mid of runtime is used. What do you think @maxnoe?

**Comment by QRemy** [comment]
> I think the compromise would be to introduce a property `obs.pointing_icrs_tmid`, which make it explicit that the mid of runtime is used. What do you think @maxnoe?

and should `pointing_radec` in `EventList` and `ObservationTable` be renamed in the same way for consistency ?

**Comment by maxnoe** [comment]
> What do you think @maxnoe?

My opinion is still that we should it make really explicit that an assumption is made in the code that the pointing doesn't change although in general it could / does change with time in at least one reference system. 

Code should make it easy to use correct (pointing changes with time) and hard to be used wrong (assume fixed pointing).

You could argue that introduction a `observation.pointing_icrs_tmid` makes it easier to later find the places where we do make this assumption. But it also makes it convenient to introduce this assumption to new places, which is probably something we don't want.

This is connected to e.g. these TODOs here:

https://github.com/gammapy/gammapy/blob/32393ccdba5b5665a7c51b9e4d3111009e84e35e/gammapy/makers/utils.py#L154-L161
for which I didn't find an issue, so maybe one should be created.

**Comment by maxnoe** [comment]
> and should pointing_radec in EventList and ObservationTable be renamed in the same way for consistency ?

It should probably be deprecated on the EventList, see also #4239 

Since in general, pointing can be separate from the `EventList`, only the `FixedPointingInfo` lives on the `EventList` and could be exposed there optionally.

**Review by adonath — APPROVED** [review]
Thanks @QRemy, the PR can go in as is. Let's keep question of introducing the shortcut for `pointing_icrc_tmid` independent...

**Review by registerrier — APPROVED** [review]
Thanks @QRemy. Looks good!

**Comment by registerrier** [comment]
CI fails are unrelated. docs build works. Merging.

**Pull request merged**
