### PR TITLE
Update temporal model docs

### PR DESCRIPTION
**Pull request by aaguasca**
**Description**

This pull request addresses issue #4038.

**Dear reviewer**

I have updated the documentation of the temporal models and the temporal model gallery following the template of the linear temporal model. Also, I have rewritten some of the mathematical expressions that appear in the temporal model gallery documentation.
I think the PR is ready to go through review. Do you have any suggestions?

### CODE REVIEW

**Review by adonath — APPROVED** [review]
Thanks @aaguasca, no further comments from my side!

**Comment by adonath** [comment]
@registerrier @bkhelifi Can anybody of you please do the second review here? Thanks!

**Review by bkhelifi — APPROVED** [review]
Thanks a lot!. Fine with me

**Comment by adonath** [comment]
Thanks @aaguasca!

**Pull request merged**
