### PR TITLE
Support for parallel evaluation in FluxPointsEstimator

### PR DESCRIPTION
**Pull request by QRemy**
Support for parallel evaluation in FluxPointsEstimator

### CODE REVIEW

**Review by registerrier — DISMISSED** [review]
Thanks @QRemy ! This looks good. No major comment from my side. 

We have a `n_jobs` parameter defined on the `AnalysisConfig` in the general section. Maybe, one would expect that this is used to change the call in the `Analysis` class. (otherwise defining `n_jobs` among the parameters of the `FluxPointsEstimator` works too).

**Comment by adonath** [comment]
Thanks @QRemy! As this becomes a new pattern, can you maybe propose a new reusable function to handle the pool context and fall-back? 

I'm thinking of something along the lines of:

```python3

results = execute_parallel(func, arguments, backend="")
```
Where `execute_parallel()` would then live in `gammapy.utils`. 

Can we keep the progress for parallel execution as well, maybe via a callback functions?

**Comment by QRemy** [comment]
> Thanks @QRemy! As this becomes a new pattern, can you maybe propose a new reusable function to handle the pool context and fall-back?
> Can we keep the progress bar for parallel execution as well, maybe via a callback function?

I added this in #4406

**Review by registerrier — APPROVED** [review]
Thanks @QRemy . No more comments.

**Pull request merged**
