### PR TITLE
TODO: for datasets/evaluator

### PR DESCRIPTION
**Pull request by Astro-Kirsty**
Adjusting to simplify if statements. Ran the tests and all of them are okay.
For the 2nd TODO, not sure if anything further can be done?

### CODE REVIEW

**Review by adonath — APPROVED** [review]
Thanks @Astro-Kirsty, I think the old version was a bit more readable, but this is just a matter of taste...so I'm fine to merge.

**Review by registerrier — CHANGES_REQUESTED** [review]
Thanks @Astro-Kirsty . The new version is causing some test fails because all conditions have to be tested at once with the `or` syntax.

**Comment by Astro-Kirsty** [comment]
Given that we have test fails and it seems a matter of opinion on the style of code, I would suggest we keep the old version and remove the TODO. Any issues?

**Comment by Astro-Kirsty** [comment]
Do we want to create an issue for the long term goal of rewriting `MapEvaluator` then?

**Review by registerrier — APPROVED** [review]
Thanks @Astro-Kirsty

**Pull request merged**
