### PR TITLE
Add more tests for SpectrumFit.fit_range

### PR DESCRIPTION
**Pull request by joleroi**
This is a PR towards solving #1224 

It adds

* A test for a fit to two observations with different low energy thresholds

### CODE REVIEW

**Comment by joleroi** [comment]
Hi @cosimoNigro 
Sorry for taking so long to get started on this. I do not understand the problem with the fit range entirely, so the first thing I added is a tests to check that two observations with different low energy thresholds are treated correctly by the fitter (they are)

**Comment by cosimoNigro** [comment]
Hello @joleroi, thanks a lot for taking care of this issue. 
Maybe I was not clear enough in Issue #1224, so I wrote a snippet to trigger the exact issue that concerns me.
Suppose we have two `SpectrumObservation`s, with two different binnings and two different energy ranges. In the following snippet I have 
* `SpectrumObservation_1` with `energy_1 = np.logspace(np.log10(0.3), np.log10(2), 21) * u.TeV` so 20 bins in the range 300 GeV, 2 TeV
* `SpectrumObservation_2` with `energy_2 = np.logspace(np.log10(0.5), np.log10(30), 41) * u.TeV` so 40 bins in the range 500 GeV, 30 TeV
I built counts, effective area and edisp with dummy values.
If you run `SpectrumFit` on a `SpectrumObservationList` defined by the aforementioned event lists you will get this output
```python

Fit result info 
--------------- 
Model: PowerLaw

Parameters: 

	   name     value   error       unit      min max frozen
	--------- --------- ----- --------------- --- --- ------
	    index 4.033e+00   nan                 nan nan  False
	amplitude 7.609e-11   nan 1 / (cm2 s TeV) nan nan  False
	reference 1.000e+00   nan             TeV nan nan   True 

Statistic: 107.675 (wstat)
Fit Range: [ 0.3  2. ] TeV


Fit result info 
--------------- 
Model: PowerLaw

Parameters: 

	   name     value   error       unit      min max frozen
	--------- --------- ----- --------------- --- --- ------
	    index 4.033e+00   nan                 nan nan  False
	amplitude 7.609e-11   nan 1 / (cm2 s TeV) nan nan  False
	reference 1.000e+00   nan             TeV nan nan   True 

Statistic: 107.675 (wstat)
Fit Range: [ 0.3  2. ] TeV
```
It always print out as `Fit range` the energy range of the first event list, as I mentioned in #1224. What I did not understand is if this printed out informaton is relevant (i.e. he is only fitting in the energy range of the first event list) or not. Note I am explictly feeding the `fit_range` to encompass both the energy ranges of the two event lists. I don't think this issue is related to the energy thresholds but to the energy range / binning feeded to sherpa (you take it from the first event list
https://github.com/gammapy/gammapy/blob/master/gammapy/spectrum/fit.py#L371).

You will never have this issue if you use data from the same instrument.
Thanks and sorry if the snippet is long
```python
import numpy as np
import astropy.units as u
from gammapy.spectrum import PHACountsSpectrum, SpectrumObservation, SpectrumObservationList, SpectrumFit
from gammapy.spectrum.models import PowerLaw
from gammapy.irf import EffectiveAreaTable, EnergyDispersion
import matplotlib.pyplot as plt

# binnning 1
energy_1 = np.logspace(np.log10(0.3), np.log10(2), 21) * u.TeV
energy_1_ctr = np.sqrt(energy_1[:-1] * energy_1[1:])

edisp_1 = EnergyDispersion.from_gauss(
    e_true=energy_1, e_reco=energy_1,
    sigma=0.1, bias=0,
)

# dummy counts on and off arrays
on_1 = 1e2 * (energy_1_ctr / (0.5 * u.TeV))**(-3.5)
off_1 = 0.2 * on_1

on_counts_1 = PHACountsSpectrum(energy_1[:-1], energy_1[1:], data = on_1)
on_counts_1.livetime = 20 * u.min

off_counts_1 = PHACountsSpectrum(energy_1[:-1], energy_1[1:], data = off_1,  is_bkg = True)
off_counts_1.livetime = 20 * u.min

# dummy effective area 1
area_1 = 1.5e5 * np.ones_like(on_1) * u.Unit('m^2')
eff_area_1 = EffectiveAreaTable(energy_1[:-1], energy_1[1:], area_1)

# SpectrumObservation 1 
SpectrumObservation_1 = SpectrumObservation(
    on_vector = on_counts_1, 
    aeff = eff_area_1, 
    off_vector = off_counts_1, 
    edisp = edisp_1
)
# check
SpectrumObservation_1.peek()
plt.show()

# binnning 2
energy_2 = np.logspace(np.log10(0.5), np.log10(30), 41) * u.TeV
energy_2_ctr = np.sqrt(energy_2[:-1] * energy_2[1:])

edisp_2 = EnergyDispersion.from_gauss(
    e_true=energy_2, e_reco=energy_2,
    sigma=0.1, bias=0,
)

# dummy counts on and off arrays
on_2 = 1e2 * (energy_2_ctr / (1 * u.TeV))**(-4.2)
off_2 = 0.2 * on_2

on_counts_2 = PHACountsSpectrum(energy_2[:-1], energy_2[1:], data = on_2)
on_counts_2.livetime = 20 * u.min

off_counts_2 = PHACountsSpectrum(energy_2[:-1], energy_2[1:], data = off_2,  is_bkg = True)
off_counts_2.livetime = 20 * u.min

# dummy effective area 2
area_2 = 1e5 * np.ones_like(on_2) * u.Unit('m^2')
eff_area_2 = EffectiveAreaTable(energy_2[:-1], energy_2[1:], area_2)

# SpectrumObservation 2 
SpectrumObservation_2 = SpectrumObservation(
    on_vector = on_counts_2, 
    aeff = eff_area_2, 
    off_vector = off_counts_2, 
    edisp = edisp_2
)
# check
SpectrumObservation_2.peek()
plt.show()

obs_list = SpectrumObservationList([SpectrumObservation_1, SpectrumObservation_2])
# fit
model = PowerLaw(
    index=2 * u.Unit(''),
    amplitude=1e-12*u.Unit('cm-2 s-1 TeV-1'),
    reference=1*u.TeV,
)
fit_range = [0.3, 30] * u.TeV
fit = SpectrumFit(obs_list, model, fit_range = fit_range)
fit.fit()
print(fit.result[0])
```

**Comment by joleroi** [comment]
@cosimoNigro Thanks for the code snippet. I still don't understand the issue though.

You have two observations.
* 300 GeV - 2 TeV
* 500 GeV - 30 TeV

You set the fit range to
* 300 GeV - 30 TeV

So both observations should be fitted over their entire respective energy range, that's exactly what happens
```
print(fit.result[0].fit_range) 
[ 0.3  2. ] TeV  
print(fit.result[1].fit_range) 
[  0.5  30. ] TeV
```

If you restrict the fit range, let's say to 450 GeV - 10 TeV you also get the expected output
```
print(fit.result[0].fit_range) 
[ 0.4820570  2. ] TeV  
print(fit.result[1].fit_range) 
[  0.5  9.73037686 ] TeV
```

Just to make sure that we're on the same page. ``fit.result`` is a list of fit results for all observations, so ``fit.result[0]`` will always give you the energy range in which the first observations is fitted.  The best fit model is the same for all entries in ``fit.result`` since the model is jointly fit to all observations. The fit results for all observations differ merely in the fitted range, predicted counts (that's all I can think of right now)

Is this issue resolved, or am I still missing something?

**Comment by cosimoNigro** [comment]
Hi @joleroi,
thanks a lot for the clarification, my fault: I didn't take a look carefully on how the `fit.result` was defined. 
Everything makes sense now.
I will approve your changes now in order that you can merge.
Thank you.
I think we can also close Issue #1224.

**Comment by joleroi** [comment]
>  my fault: I didn't take a look carefully on how the fit.result was defined.

Depends on how you look at it. I would say it's the documentations fault ...

**Pull request merged**
