### PR TITLE
Adding build with numpy pre-release to the travis matrix

### PR DESCRIPTION
**Pull request by bsipocz**
Using python2.7, thus it can be tested with sherpa (and the numpy dev has been already tested with 3.5).

### CODE REVIEW

**Comment by bsipocz** [comment]
Not sure about the reason of the timeout in the pre-release test, but I vaguely remember seeing this before, and will figure it out tomorrow.

In addition all but two sphinx errors are fixed, and I'm not sure about the root of those remaining ones. Also this fixed a test failure due to a missing requirement.

**Comment by cdeil** [comment]
Thank you!

If you're not able to figure out why this test hangs with `numpy 1.11.0rc1` today,
then my suggestion would be to add it to the `allow_failures` list for now.
(because I don't like leaving CI broken in the Gammapy master branch, so tge Sphinx fixes here should go in soon)
```
gammapy/astro/population/tests/test_spatial.py::TestMorphologyModels::test_fitter1D[model_class0-test_parameters0] <- ../../home/travis/miniconda/envs/test/lib/python2.7/site-packages/astropy/modeling/tests/test_models.py
```
https://travis-ci.org/gammapy/gammapy/jobs/113022085#L1125

@joleroi - Can you hold off touching the spectrum code for one day to avoid merge conflicts?

**Comment by bsipocz** [comment]
This last one fixes all the outstanding sphinx errors. However master changed in the meantime (but still failing). Do you want me to rebase this, or will continue to work on master?

ping @joleroi

**Comment by cdeil** [comment]
I think @joleroi didn't see my comment here and fixed the Sphinx build in master: https://github.com/gammapy/gammapy/commit/94574ae7bfae0f64ef33f531407fb61f899621d1

@bsipocz - Can you please rebase this PR?

**Comment by bsipocz** [comment]
@cdeil - Done.

**Comment by cdeil** [comment]
Merging this now. Thanks!

**Comment by bsipocz** [comment]
I'll come back to the halting issue, hopefully in a few days time; ``photutils`` also shows something similar.

**Pull request merged**
