### PR TITLE
Migrate Travis CI to Github actions

### PR DESCRIPTION
**Pull request by Bultako**
This PR makes CI in Github actions split in two parallel jobs: code and documentation tests.
All tests are done in a conda environment, and some of the tests deployed in Travis have been removed.
The whole CI takes less than 30 min.

### CODE REVIEW

**Comment by adonath** [comment]
Thanks a lot @Bultako, it seems it's already running! I'll take a closer look at the YAML file now...

**Comment by Bultako** [comment]
I have made some modifs along with the discussion held with @adonath in the gammapy coding sprint.

- All jobs run in parallel following the matrix strategy defined in `ci.yml 
- I have finally opted to use conda to build the envs since it is the install method proposed to users in the docs.
- Tests run with a small set of core dependencies to time execution except for windows, mac and notebooks (linux)
- All tests run without `GAMMAPY_DATASET`, except notebooks and others (docs build)
- Tests for windows fail building the conda env
- Tests for Linux Python3.6 fail in the gammapy code
- Tests coverage is done only for Linux  Python3.7
- Tests for the code chunks in RST files are disabled.
- There ar a total number of 9 tests spending about 20 min.

**Comment by adonath** [comment]
Thanks a lot @Bultako, this looks really good! Concerning your comments:

- The conda install of `healpy` and `sherpa` on Windows is a known issue, those packages are not available. So for this we need a workaround. Either a second environment file or or not rely on the file based setup for Windows. 
- The test fail on 3.6 could be a real issue, maybe we miss the `dataclasses` dependency required by `pydantic`? See https://pydantic-docs.helpmanual.io/install/
- Given we have a nice testing matrix for GitHub-actions now, I think we can possibly remove our Azure CI...
- The code coverage report in this PR shows a really bad coverage, any idea why?
- Minor: can we add this option https://github.com/cta-observatory/ctapipe/pull/1544/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR13, to get coloured pytest output?

**Comment by Bultako** [comment]
Ok
All tests passed in 25 min. 
We can maybe make it shorter, at the prize of having more jobs..

**Review by adonath — APPROVED** [review]
Thanks a lot @Bultako! Let's merge this now and then improve in follow-up PRs if needed...

**Pull request merged**
