### PR TITLE
Improve exposure SkyCube computation

### PR DESCRIPTION
**Pull request by JouvinLea**
@adonath 
This PR is just to change how you compute the exposure cube for offset > offset_max. As we discussed it's now 0.

### CODE REVIEW

**Comment by JouvinLea** [comment]
@adonath 
I don't understand the issue on Travis?

**Comment by adonath** [comment]
@JouvinLea Thanks! The fail on Travis-CI is not related to your changes.

Can you add an additional assert in `gammapy/cube/tests/test_exposure.py`, that checks if the exposure is really zero for `offset > offset_max`? Then it's ready to merge...

**Comment by JouvinLea** [comment]
I added the test for offset > offset max and it passed can we merge now?

**Comment by JouvinLea** [comment]
@adonath 
Is it possible to merge? It's just I need that for my 3D analysis.... and I don't want to wait too long since then the rebase will be difficult...

**Comment by adonath** [comment]
@JouvinLea Merged, Thanks!

**Pull request merged**
