### PR TITLE
Add license to dev folder files

### PR DESCRIPTION
**Pull request by Astro-Kirsty**
As mentioned [here](https://github.com/gammapy/gammapy/pull/4854#discussion_r1370547292) the dev folder did not have licenses. 
This PR solves this

### CODE REVIEW

**Review by bkhelifi — APPROVED** [review]
Thanks a lot @Astro-Kirsty

**Comment by MRegeard** [comment]
Thanks @Astro-Kirsty, 
There are actually a lot more files that don't have the license comment at the beginning. 

If you run this small script :

```
import os

def check_license(directory):
    license_comment = '# Licensed under a 3-clause BSD style license - see LICENSE.rst'
    
    for root, _, files in os.walk(directory):
        for filename in files:
            if filename.endswith('.py'):
                file_path = os.path.join(root, filename)
                with open(file_path, 'r', encoding='utf-8') as file:
                    first_line = file.readline().strip()
                    if first_line != license_comment:
                        print(f"File '{file_path}' does not have the correct license comment.")

if __name__ == '__main__':
    directory_path = input("Enter the directory path to search for Python files: ")
    check_license(directory_path)
```

**Comment by MRegeard** [comment]
You can actually run this script, that will do it for you !

```
import os


def add_license_comment(directory):
    license_comment = '# Licensed under a 3-clause BSD style license - see LICENSE.rst'

    for root, _, files in os.walk(directory):
        for filename in files:
            if filename.endswith('.py'):
                file_path = os.path.join(root, filename)
                with open(file_path, 'r', encoding='utf-8') as file:
                    lines = file.readlines()
                with open(file_path, 'w', encoding='utf-8') as file:
                    if not lines:
                        file.write(license_comment + '\n')
                    else:
                        first_line = lines[0].strip()
                        if first_line != license_comment:
                            lines = [license_comment + '\n'] + lines
                        file.writelines(lines)


if __name__ == '__main__':
    directory_path = input("Enter the directory path to search for Python files: ")
    add_license_comment(directory_path)
```

**Comment by MRegeard** [comment]
@registerrier, @bkhelifi, @AtreyeeS, @adonath, do we want a script like this in the dev rep that we can run from time to time to be sure that the license is in all the files ?

**Comment by Astro-Kirsty** [comment]
+1 for adding a script like this in the dev rep!!

**Comment by Astro-Kirsty** [comment]
Added the license to the rest of the files!

Did not add to `gammapy.extern.xmltodict`, due to the line `#!/usr/bin/env python`
Does this need to be specified here?

**Comment by MRegeard** [comment]
>Did not add to gammapy.extern.xmltodict, due to the line #!/usr/bin/env python
Does this need to be specified here?

You can probably put it just after this line.

**Review by registerrier — APPROVED** [review]
Thanks @Astro-Kirsty . Good point.

I assume empty files might not need a license :-) But that's fine as they might be filled later.

An option could be to include this type of check as part of the CI code checks.

**Comment by registerrier** [comment]
> Added the license to the rest of the files!
> 
> Did not add to `gammapy.extern.xmltodict`, due to the line `#!/usr/bin/env python` Does this need to be specified here?

This is external package. I don't think we should re-license it.

**Comment by registerrier** [comment]
Merging now.

**Pull request merged**
