### PR TITLE
Add tests for gammapy download

### PR DESCRIPTION
**Pull request by Bultako**
This PR add tests for `gammapy download` CLI as proposed in https://github.com/gammapy/gammapy/pull/1763#issuecomment-418855754

### CODE REVIEW

**Comment by cdeil** [comment]
Testing with web requests is tricky.

This is failing, an issue with the Github API response:
https://travis-ci.org/gammapy/gammapy/jobs/427157805#L4550
It's working for me locally.

Do you know if Github API calls require a Github account? Or maybe they are blocked from Travis-CI because people are hammering Github API from there?

I'm not sure what to do here. Of course we want to test our code, but web request create a point of high failure rate, so we got rid of all of them in the Gammapy tests about a year ago, fetching all data we need before starting the tests.

Will Github API calls still be in the download soon, or will they be changed to fetch an index file? Then you could just mark the tests xfail for now and merge this in as-is, and activate them later.

Just slightly related: I saw this a few days ago:
https://www.anaconda.com/blog/developer-blog/intake-taking-the-pain-out-of-data-access/
I haven't looked in detail yet, but I think they also do a static web server with an index file (which they call "catalog").

**Comment by Bultako** [comment]
I have tried to fix it adding a User-Agent to the request headers, as it is suggested in in the [docs of the Github API](https://developer.github.com/v3/#user-agent-required, without success :(

I agree we will have to get rid of the GitHub API soon and use index files, so we can test our code here. Ok to `xfail` this test for the moment..

**Comment by cdeil** [comment]
OK. I saw that you now let the exception occur, and it contains more info what is going on. I think that's good.

**Comment by cdeil** [comment]
Thanks!

**Pull request merged**
