### PR TITLE
Unify Dataset mask handling

### PR DESCRIPTION
**Pull request by adonath**
This PR implements a uniform mask handling for all dataset classes we have:
- Rename the  current `mask` attributes to `mask_fit`
- Introduce a second mask `mask_safe` which define the safe data range for each dataset
- Remove the global mask on `Datasets`
- Make the `MapDataset.mask_fit` a numpy array for consistency.

### CODE REVIEW

**Comment by cdeil** [comment]
@adonath - I think you are aware, but this is still not great:

https://github.com/gammapy/gammapy/blob/aea18a3d2f9ae0e92bf4af51066bdbaf12b96ec3/gammapy/spectrum/dataset.py#L347-L359

Probably what we want is to have `mask_likelihood = mask_user & mask_safe` computed on `__init__` or `setup`, and then 
```
    def likelihood(self):
        return np.sum(self.likelihood_per_bin(), dtype=np.float64)
```
and `self.likelihood_per_bin` would access only `mask_likelihood` (or for components without convolution could work with pixel arrays).

This `likelihood` could even be in the base class (currently the same method is copy & pasted a few times).

Concerning the parameters input, I've opened  #2180 as a reminder, but concerning mask, we have the datasets PIG anywhere and that PR is still open.

**Comment by adonath** [comment]
Thanks @cdeil, yes I'm aware of this. I think we have to decide on the final design for masks and parameters in the context of parallel evaluation of datasets. For the use case of flux point estimation (but probably also for others) it's definitely needed to modify the `mask_fit` attribute of the datasets after init, if you don't want to make copies of complete datasets all the time. So I guess we also need an update system for the `mask_fit` of the dataset...

**Comment by registerrier** [comment]
`mask_fit` is of course something that needs to be updated. A user nearly always needs to change the fit range during the analysis. Having to re-create a dataset to change the fit range is extremely cumbersome. 

So I still think the best solution is to make a `mask`property:
```
@property
def mask(self):
      return self.mask_fit & self.mask_safe
```

**Comment by cdeil** [comment]
Agree that having a combined mask is a good idea. Could be called `mask` or `mask_likelihood` or `mask_total` or something like that.

This would allow to remove duplicated code and to just access that mask from the likelihood methods, simplifying testing and being a little bit faster.

I think discussions of how to update masks, and whether / when to cache them will take longer and will be settled via PIG(s). But @adonath - if you think introducing the total mask for likelihood fitting is useful / possible now, go ahead.

**Pull request merged**
