### PR TITLE
Fix parameter type for PiecewiseNormSpectralModel  and NaimaSpectralModel

### PR DESCRIPTION
**Pull request by QRemy**
Fix parameter type for PiecewiseNormSpectralModel  and NaimaSpectralModel.
Resolve issue #3376.

### CODE REVIEW

**Review by registerrier — COMMENTED** [review]
Thanks @QRemy ! 

This solves the issue, but this will appear again when users define models with explicit `Parameter` instantiation in their `__init__` method. Can't we find a way to have them set on init? For instance, adding a `SpectralModel.__init__()` method that will set all parameters type  to `'spectral'`? Could that work?

**Comment by QRemy** [comment]
@registerrier I moved the fix to the `Model` base class such as `parameter._type` is set to match `model._type`

**Comment by adonath** [comment]
Thanks @QRemy! I think we could possibly manually invoke the descriptor protocol, by implementing `__getattribute__` on the `Model` base class like so:

```python3
from gammapy.modeling import Parameter, Parameters
from gammapy.modeling.models import Model

def __getattribute__(self, name):
    value = object.__getattribute__(self, name)
    
    if isinstance(value, Parameter):
        return value.__get__(self, None)

    return value
    
Model.__getattribute__ = __getattribute__

class MyModel(Model):
    _type = "my-model"
    par_a = Parameter("par_a", value=1)    

class MyOtherModel(Model):
    _type = "my-other-model"
    
    def __init__(self):
        par_a = Parameter("par_a", value=1)
        self.default_parameters = Parameters([par_a])
        super().__init__()
        
m = MyModel()
m.par_a
print(m.par_a.type)

m_other = MyOtherModel()
m_other.par_a
print(m_other.par_a.type)
```
I'm not 100% whether this has any side effects, but the toy implementation above seems to work.

The problem with the setting of `_type` on init is that we cannot reset the parameter like:
```python3
model.par = Parameter("par", value=1)
```
Which currently works...

**Review by adonath — COMMENTED** [review]
Thanks @QRemy, no further comments from my side...

**Review by adonath — APPROVED** [review]
Looks good!

**Pull request merged**
