### PR TITLE
Temporal model integration

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request implements a general `TemporalModel.integral`, method that works with arrays and internal oversampling.

### CODE REVIEW

**Comment by AtreyeeS** [comment]
@adonath : What is the status here? Do we merge this and I continue on #3838 ?

**Review by registerrier — APPROVED** [review]
Thanks @adonath ! This looks good to me. 

The merge conflict should be solved though.

**Comment by adonath** [comment]
Thanks @AtreyeeS  and @registerrier! I resolved the merge conflicts...

**Comment by bkhelifi** [comment]
Thanks @adonath ! This looks good to me.

**Review by bkhelifi — APPROVED** [review]

**Pull request merged**
