### PR TITLE
Changed image_fitting_with_sherpa tutorial to use DC1 runs

### PR DESCRIPTION
**Pull request by AtreyeeS**
This addressed #1811

### CODE REVIEW

**Comment by AtreyeeS** [comment]
> @AtreyeeS - Thanks!
> 
> When you compute the PSF kernel, can you just re-use the same energy axis from above?
> Less code and guarantees consistency in energy range, no?
>

We need to have the PSFKernel with one energy bin only, because there is no `make_images` for PSFKernels.
But making the entire map with one energy bin fails because of #1830

> The iterative fitting takes over 5 min. We run all notebooks in CI, so it would be nice if they all executed quickly. Also for users I think having notebooks that execute very quickly (less than a minute) is better, because to learn you have to play with parameters and re-execute many times.
> 
> So I'd suggest to just fit two or max three sources to get something simple and quick.
> 

Changed the number of sources!
> We could add another notebook showing how to make a little catalog pipeline that iteratively adds sources, but I think we should rather build that using Gammapy, and not put it in a Sherpa intro notebook.

**Comment by cdeil** [comment]
> We need to have the PSFKernel with one energy bin only, because there is no make_images for PSFKernels.

Why not do this, and avoid introducing a new energy axis and geom, which is many lines and has the potential to be inconsistent with the maps?
```
psf_kernel_2d = psf_kernel.data.sum(axis=0)
fits.writeto("psf_kernel_2d.fits", psf_kernel_2d, overwrite=True)
```
A PSF kernel has no WCS, so no need to write one to FITS.

If you prefer, you could also use this line if you don't want to do `axis=0` with the hard-coded axis index:
```
psf_kernel_2d = psf_kernel.psf_kernel_map.sum_over_axes().data
```

**Comment by AtreyeeS** [comment]
> Why not do this, and avoid introducing a new energy axis and geom, which is many lines and has the potential to be inconsistent with the maps?
> 
> ```
> psf_kernel_2d = psf_kernel.data.sum(axis=0)
> fits.writeto("psf_kernel_2d.fits", psf_kernel_2d, overwrite=True)
> ```

Done! I was a bit unsure if just summing over the energies was correct, and hence the jugglery.
Thanks!

**Comment by cdeil** [comment]
@AtreyeeS - One more thing: I see PNG images in your notebook and you have 10 commits here. That will bloat the Gammapy code repo over time, hence the idea to always strip the output before committing:
```
jupyter notebook --src tutorials/image_fitting_with_sherpa.ipynb black
jupyter notebook --src tutorials/image_fitting_with_sherpa.ipynb strip
```
This will be documented in the dev docs shortly, it was just added.

But to avoid having these PNGs (embedded in the notebook JSON file) the git history, please squash all commits here into a single one. Or if it's easier for you, close this PR and make a new one starting from master.

> I was a bit unsure if just summing over the energies was correct

Maybe it would be a bit better to compute a spectrum-weighted PSF kernel when going to 2D:

https://github.com/gammapy/gammapy/blob/cf8767d12694653b053d234c6dd9e770b53bccd9/gammapy/cube/exposure.py#L46

And add that as a method with a docstring and test on the PSFKernel class?
Up to you and @registerrier to decide on that.

**Comment by cdeil** [comment]
Concerning the notebook. I think it would be nice if you make it clearer that this has 2 completely separate parts that just communicate via files, and the second one is just using Sherpa.

The second part starts with the heading "Read the maps and store them in a sherpa model". You could make that more prominent and add a sentence or two there saying that here really the main part of the notebook using Sherpa starts, the rest was just to prepare example images and PSF.

**Comment by AtreyeeS** [comment]
> Maybe it would be a bit better to compute a spectrum-weighted PSF kernel when going to 2D:
> 
> [gammapy/gammapy/cube/exposure.py](https://github.com/gammapy/gammapy/blob/cf8767d12694653b053d234c6dd9e770b53bccd9/gammapy/cube/exposure.py#L46)
> Line 46 in [cf8767d](/gammapy/gammapy/commit/cf8767d12694653b053d234c6dd9e770b53bccd9)
>  def _map_spectrum_weight(map, spectrum=None): 
> And add that as a method with a docstring and test on the PSFKernel class?
> Up to you and @registerrier to decide on that.

Yes, we do need a "weighted" PSF while going to 2D.
I am adding it in the main repo as a separate function, and will add this notebook after that.
Closing this PR for now.

**Comment by adonath** [comment]
@AtreyeeS Please also note https://github.com/gammapy/gammapy/issues/1740. There is already a method on the `EnergyDependentTablePSF` to compute a weighted `TablePSF` from which you could compute the kernel.

**Pull request closed without merging**
