### PR TITLE
Add robust periodogram to gammapy.time

### PR DESCRIPTION
**Pull request by wegenmat**
This is a follow-up PR from #1137. 
The old PR was closed due to complex history.

@cdeil suggested to change to a RobustPeriodogramRegression class, packed into a class with the same API like LombScargle in Astropy to avoid the code duplication of the significance computation functions. It should take either a LombScargle or RobustPeriodogramRegression instance as input (or only pass the one data member from that class that is needed in)

### CODE REVIEW

**Comment by cnachi** [comment]
@wegenmat @cdeil : post discussions over email and in person, my suggestion was just like the main lomb_scargle routine, we essentially use the astropy FAP for now to complete this pull request and this would be self-consistent. A newer and improved computation of the FAP would be more work and lines of code, and was wondering if writing a new PIG for new FAP computation would be the way to go ?

**Comment by cdeil** [comment]
@wegenmat - What should we do here? Close or revive?

Apologies for not attending to this, and for the overlap / confusion with similar additions being done in Astropy while you were working on this in Gammapy.

By now there's merge conflicts, so resolving those would be a minimal step needed if you want this to go it.

**Comment by cnachi** [comment]
@wegenmat @cdeil : it needs to be closed with the version of periodogram that simply calls astropy. what do we need to do for this ?

**Comment by wegenmat** [comment]
This robust periodogram can not call astropy, because it is a new routine to calculate the periodogram. But for the FAP-computation, astropy can be used. I will implemet this asap and than, this PR can be closed. The code for the robust periodogram would need to be reviewed once it is implemeted without FAP

**Comment by wegenmat** [comment]
You are okay with this, @cnachi and @cdeil ?

**Comment by cnachi** [comment]
Yes FAP with astropy is what I meant ; I am ok with this - i.e. your periodogram code and then calling astropy for FAP. Of course, in the notes it should clearly state that this FAP assumes white noise.

**Comment by cdeil** [comment]
@wegenmat - please go ahead and do what you think best!
(I'm afraid I don't have time to learn about periodograms or review what exists in Astropy or what you have here, i.e. you won't get useful feedback from me here.)

**Comment by wegenmat** [comment]
I deleted what can be computed with a 'astropy' method:

- Lomb-Scargle implementation
- Sepctral window function
- false alarm probability

**Comment by cdeil** [comment]
@wegenmat - Do you have time to rebase this PR, so that it can go in?

**Comment by wegenmat** [comment]
I still have to implement some modifications. Once this is done, I will rebase this PR and it can go in.

**Comment by cdeil** [comment]
Superseded by  #1492.

**Pull request closed without merging**
