### PR TITLE
Make links in notebooks point to right docs version

### PR DESCRIPTION
**Pull request by Bultako**
This PR addresses issue https://github.com/gammapy/gammapy/issues/2175

It modifies how `_statics/notebooks/*.ipynb` are generated in the doc build process, making absolute links pointing to https://docs.gammapy.org/ to point to the release version declared in command `make docs-all release=vx.z`. 

Links in the `download/tutorials/gammapy-x.z-tutorials.yml` YAML files in `gammapy-webpage` repository have been already modified to point to their right version of https://docs.gammapy.org/vx.z/_statics/notebooks/*.ipynb as well as the links in the old tutorials docs pointing them to their right version (instead of dev). Note that for next releases the links in the tutorials YAML file in `gammapy-webpage` should be pointing to https://docs.gammapy.org/vx.z/_statics/notebooks/*.ipynb notebooks.

As suggested in https://github.com/gammapy/gammapy/issues/2175#issuecomment-497283199 finding broken links in notebooks can be easily done with other tools.

### CODE REVIEW

**Comment by cdeil** [comment]
This is not really what I had in mind in #2175. I was thinking we could put some special markup in the MD cells that does not include the https://docs.gammapy.org, and also that when building the docs locally, it would create links to the local docs. The problem with linking to https://docs.gammapy.org is that when we change classes and those aren't on https://docs.gammapy.org links will be broken - i.e. devs that work on Gammapy don't have a way to test the docs if it's not self-contained.

So really I'd suggest we do something like  https://nbsphinx.readthedocs.io/en/0.3.5/markdown-cells.html#Links-to-Domain-Objects or some other syntax like `:ref:` that gets processed.

But this is probably still an improvement, so OK to go ahead and merge if you like.

I see you replace "dev". There is one notebook that has "stable" hard-coded instead:
```
$ ack "docs.gammapy.org/stable" tutorials
tutorials/first_steps.ipynb
542:    "* Select all the sources from the 2FHL catalog which are contained in the Galactic Center region. The methods [`WcsGeom.contains()`](https://docs.gammapy.org/stable/api/gammapy.maps.WcsGeom.html#gammapy.maps.WcsGeom.contains) and [`SourceCatalog.positions`](https://docs.gammapy.org/stable/api/gammapy.catalog.SourceCatalog.html#gammapy.catalog.SourceCatalog.positions) might be helpful for this. Add markers for all these sources and try to add labels with the source names. The function [ax.text()](http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.text.html#matplotlib.axes.Axes.text) might be also helpful.\n",
```
Maybe fix that also in this PR?

**Comment by Bultako** [comment]
> The problem with linking to https://docs.gammapy.org is that when we change classes and those aren't on https://docs.gammapy.org links will be broken - i.e. devs that work on Gammapy don't have a way to test the docs if it's not self-contained.

Links will not be broken in the generated HTML-fixed version of the notebooks, because these are relative links. 

Links to new classes in the API present in the *.ipynb files will be broken only in the desktop of the doc maintainer. This also happens with links made with the special tag-mechanism that you propose, you cannot browse from the MD cells in those notebooks, moreover I feel more pleasant to paste URLs directly instead of using this add-on mechanism that you have to know and remember. Finally, the *links-broken* notebooks are still not public, once they are pushed and published in `gammapy-docs` as part of the new docs release, the links are not broken anymore. 

> I see you replace "dev". There is one notebook that has "stable" hard-coded instead:

I think I will make a new PR to fix links in notebooks.
See https://github.com/gammapy/gammapy/issues/2175#issuecomment-497283199

**Comment by cdeil** [comment]
@Bultako - So you want to merge this PR as-is?

OK, please go ahead!

I do feel that it is important to have a docs build with fully working and testable docs locally or in CI, and that this scheme of "it will work once docs.gammapy.org is updated" is problematic. So please leave #2175 open for now and we discuss and resolve it in Erlangen.

FYI: I did update all ADS links in  a9ca5c02b191a0f03212163c106e35f45f05850c just now via a commit in master. I don't think it affects any of the edits you're doing.

**Comment by Bultako** [comment]
Merging now.
We'll polish the details in Erlangen.

**Pull request merged**
