### PR TITLE
Improve DataStore and DataManager

### PR DESCRIPTION
**Pull request by joleroi**
- [x] Fix bug in gammapy that prevents PA datastore to be read (see https://github.com/gammasky/hess-host-analyses/issues/30#issuecomment-183398236 )
- [x] Make HESS crab4 data available as test DataManager
- [x] Fix DataStore tests
- [x] Fix DataManager tests

### CODE REVIEW

**Comment by joleroi** [comment]
Ready to merge

**Comment by cdeil** [comment]
There's a bunch of tests that use yaml and fail in the build that runs Gammapy with only the required dependencies:
https://travis-ci.org/gammapy/gammapy/jobs/109152290#L1689

@joleroi - Do you think we should make pyyaml a required dependency? keep it optional and mark those tests as
```
@requires_dependency('yaml')
```
I'm 50:50 on this ... if large parts of Gammapy can be used without YAML it's good that it's optional. But it's also annoying and the vast majority of users will not have an issue installing pyyaml.

**Comment by joleroi** [comment]
let's wait if the tests pass

**Comment by cdeil** [comment]
Tests passed ... merging this now.

**Pull request merged**
