### PR TITLE
Improve stats function to compute excess for given Li&Ma significance

### PR DESCRIPTION
**Pull request by oscarblanchbigas**
Adapt test_sensitivity; do the root finding of Lima formula with its square and make it working for requested significance close to 0; and add a check that we look for positive significance.

@cdeil - Please check the negative excess handling and if this really works for arrays.

### CODE REVIEW

**Comment by kosack** [comment]
here's some old sensitivity code I made that could help: 

https://bitbucket.org/kosack/commonsens/src

see the sensitivity.py and stats.py

**Comment by cdeil** [comment]
I've attached a commit here ( 4d0f8a46 ) that (hopefully) improves the tests and code in `gammapy.stats.poisson`. We discussed two days ago and thought that "sensitivity" is unclear, so I changed to "excess_matching_significance" which is pretty clear, no? This is a low-level stats function that wouldn't be called often, just when computing flux sensitivities for spectra or maps.

The implementation is also changed a bit compared to what @oscarblanchbigas you put - after thinking a bit about it, the case that really needs to be special-handled is `n_on <= 0`, for the cases where the caller asks for an excess matching a very low significance, that isn't possible with `n_on >=0`, or when the optimiser runs into that range `n_on <= 0`.

I think this is working, and all that's missing here is to adjust the test to have reference value NaN for those "impossible cases".

But I wanted to ask for some feedback / review here concerning this thinking and the new implementation. Is it correct? Is it numerically stable for all cases? Can it be written in a better way (using Python/numpy/scipy only, without going to Cython or Numba)? @oscarblanchbigas @mackaiver @kosack @adonath - if you have time, please have a look.

**Comment by cdeil** [comment]
@oscarblanchbigas doesn't have time this week.

@mackaiver - could you please review this and give some feedback (or edit directly and add a commit)? I'd like to finish this up.

**Comment by mackaiver** [comment]
Look's okay to me. Don't know how edge cases should be handled so I can't say much about that.  Howerver what about the code which is currently here? Seems like there are again two solutions to the same problem.
`gammapy/scripts/cta_sensitivity.py` ?

**Comment by cdeil** [comment]
The idea would be to update `gammapy/scripts/cta_sensitivity.py` and to call the `gammapy.stats` function from there. Before doing it, a test with an assert on that excess number should be added.
I'll just finish up here and merge this later today and leave that to you or @bkhelifi for a follow-up PR.

**Comment by cdeil** [comment]
@mackaiver - Thanks for the review!

**Comment by cdeil** [comment]
Now with f7a9564a I think this is really working correctly.

@mackaiver @oscarblanchbigas - If you have time, please have another look.

If not, I'll still merge this tomorrow morning and then everyone can try it via master and comments are still welcome of course.

**Comment by cdeil** [comment]
@oscarblanchbigas - Thanks for this contribution!

**Pull request merged**
