### PR TITLE
Add binary operations to SkyMask

### PR DESCRIPTION
**Pull request by adonath**
This PR moves binary operations from `image/utils.py` to the `SkyMask` class, adds `.close()` and `.erode()` and corresponding test.

### CODE REVIEW

**Comment by cdeil** [comment]
@adonath - FYI: I gave this as a task to @OlgaVorokh to move the dilate function to a method and she had started on it. We talked on Slack and decided to go with this PR because it's further along.
Please let us know when you start to work on gammapy.image in the coming days / weeks so that we can avoid overlap.

**Comment by cdeil** [comment]
Can you please accept lists as inputs and auto-convert to numpy array on input like most Numpy functions do? From the test just pass a list of lists, i.e. remove the boilerplate `np.array` for the structure element.

Is the complicated structure element validation with Kernel and normalisation really needed?
Can't we just support arrays?
It should be possible to get an array from a Kernel with just a few characters, so that can be left to the caller, no?

**Comment by adonath** [comment]
@cdeil @OlgaVorokh  Sorry, that wasn't clear to me. I didn't plan to do this beforehand, it was just a spontaneous decision this afternoon to clean up a bit for the upcoming gammapy 0.5 release. I don't have any further plans to work on `gammapy.image` that could interfere with your work for the next weeks.

**Comment by adonath** [comment]
@cdeil Yes, you're right:
```
structure = Tophat2DKernel(5).array
SkyMask.erode(structure)
```
and

```
structure = [[1, 1, 1],
             [1, 1, 1],
             [1, 1, 1]]
SkyMask.erode(structure)
```

Work both perfectly fine. The scipy functions do the input validation internally. So I removed the kernel support.

**Comment by cdeil** [comment]
@adonath - Thanks!

I'm merging this now.
Overall I'm not convinced

**Comment by cdeil** [comment]
Sorry, I hit "comment" on the last comment too soon. I now typed it out:
https://github.com/gammapy/gammapy/pull/657#issuecomment-236275779

Merging this now.

**Pull request merged**
