### PR TITLE
Fix TableModel to be able to use the CountsPredictor

### LINKED ISSUE #1074: Problem with expected counts for TableModel
Hi @joleroi and @cdeil ,
When using the `CountsPredictor` class with a `TableModel` (which inheritate from `SpectrumModel`), the code explode because it expects the model to have some parameters in order to use the good units:
```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

/Users/zeljka/cta/tools/anagammapy/ana_simmygrb_june17.py in <module>()

     69 # Simulation

     70 simu = CTAObservationSimulation.simulate_obs(

---> 71     perf=perf, target=target, obs_param=params)

     72 

     73 # print simulation results


/Users/zeljka/cta/tools/gammapy/gammapy/scripts/cta_utils.pyc in simulate_obs(perf, target, obs_param, obs_id)

    118                                            livetime=livetime,

    119                                            edisp=perf.rmf)

--> 120         predicted_counts.run()

    121         npred = predicted_counts.npred

    122         # set negative values to zero (interpolation issue)


/Users/zeljka/cta/tools/gammapy/gammapy/spectrum/utils.pyc in run(self)

    148 

    149     def run(self):

--> 150         self.integrate_model()

    151         self.apply_aeff()

    152         self.apply_edisp()


/Users/zeljka/cta/tools/gammapy/gammapy/spectrum/utils.pyc in integrate_model(self)

    158             ref_unit = None

    159             try:

--> 160                 for unit in self.model.parameters['amplitude'].unit.bases:

    161                     if unit.is_equivalent('eV'):

    162                         ref_unit = unit


AttributeError: 'unicode' object has no attribute 'bases' 

```

Do you have a quick way to fix this?

Thanks (@zelmar, @jjlk)

### PR DESCRIPTION
**Pull request by jjlk**
Hi, this PR fixes #1074.     
Oké to merge @joleroi ?

### CODE REVIEW

**Comment by jjlk** [comment]
hi @joleroi , can we merge ?

**Comment by jjlk** [comment]
Hi @joleroi , 
Are the failling tests related to this PR? It looks like so right?

**Comment by joleroi** [comment]
@jjlk Yes, you are right, there are more places where the ``unit`` is expected to be an ``astropy.units.Unit`` object not a string. 
https://travis-ci.org/gammapy/gammapy/jobs/278241260#L1159

Can you fix this or should I?

**Comment by jjlk** [comment]
HI @joleroi , could you do it? I'll owe you

**Comment by joleroi** [comment]
@jjlk ok

**Pull request merged**
