### PR TITLE
Adding gammapy-extra to appveyor builds

### PR DESCRIPTION
**Pull request by bsipocz**
This is to add gammapy extras to the appveyor builds. This needs to be done with some powershell hackary.

Not sure it works yet, but obviously I can't test it locally. I try to cancel all travis builds, as this PR makes no changes that affect the travis builds.

### CODE REVIEW

**Comment by bsipocz** [comment]
@cdeil - It's not working yet, but later this week I try to come back and finish this off.

**Comment by cdeil** [comment]
Thanks!

I see the error:
```
git : Cloning into 'gammapy-extra'...
At line:3 char:5
+     git clone https://github.com/gammapy/gammapy-extra.git
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cloning into 'gammapy-extra'...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.115/job/8twfn9qdc2u5xnr1#L154

Any idea how to resolve it?

There's one more weird thing I noticed ... there's `pandas` and `Pandas` listed here:
- https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.115/job/8twfn9qdc2u5xnr1#L614
- https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.115/job/8twfn9qdc2u5xnr1#L616
It should be only listed once, right?
I didn't check yet if the same is happening on Mac or Linux builds.

**Comment by cdeil** [comment]
@bsipocz  - I'll make the Gammapy 0.4 release this Sunday.
I'm not sure we have a single Windows user yet, so getting this in is not critical.

So changing the milestone to 0.5 for now ... if it's ready by Sunday it can of course still get in.

**Comment by bsipocz** [comment]
@cdeil - Sure, sorry about this. Maybe I can finish it up tomorrow, but it depends on whether the stuff I'm working on now is up and running by then.

**Comment by cdeil** [comment]
@bsipocz - Maybe appending `2> $null` to the git clone command as suggested here helps?
http://help.appveyor.com/discussions/problems/555-accessing-another-repository-during-a-build#comment_33824969

**Comment by bsipocz** [comment]
I'm sorry @cdeil that I didn't respond to this sooner. There was travis failures on your PR, so I'm rebasing this to see how it stands with the current master.

**Comment by bsipocz** [comment]
@cdeil - It looks like your fix did the trick, and now this is ready to be merged.

**Comment by cdeil** [comment]
The git clone now doesn't error, but I'm not sure if it's working.

I see this in the build log, i.e. the tests using the example files from gammapy-extra don't run:
```
Gammapy test data availability:
gammapy-extra ... no
hess ............ no

GAMMAPY_EXTRA = c:\projects\gammapy-extra
```
https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.726/job/x333nfm1avje23p4#L632

```
gammapy\datasets\tests\test_load.py::test_gammapy_extra SKIPPED
```
https://ci.appveyor.com/project/cdeil/gammapy/build/1.0.726/job/x333nfm1avje23p4#L902

The implementation of the check for the gammapy-extra data is implemented here:
https://github.com/gammapy/gammapy/blob/8e143904ae003201141a098fe6aa80295f464e0f/gammapy/datasets/core.py#L214

Maybe this doesn't work on Windows? Or the git clone of gammapy-extra isn't working after all?

@vorugantia -- You're on Windows, right? Could you try fetching gammapy-extra as described [here](https://gammapy.readthedocs.io/en/latest/datasets/index.html?highlight=gammapy_extra#gammapy-extra) and then try to run the Gammapy tests and check whether the gammapy-extra data is found?

**Comment by vorugantia** [comment]
I followed the instructions from the docs. I could git clone gammapy-extra and import it in IPython, but I couldn't set the system environment variable. According to [this link](http://stackoverflow.com/questions/18701783/windows-equivalent-of-export) "export" does not work in Windows command prompt, you need to use the "set" keyword instead. I just did it manually from "Advanced system settings --> "Environment variables" in the Control Panel, and everything works fine.

**Comment by cdeil** [comment]
@vorugantia - Thanks for investigating!

Currently [here](https://github.com/gammapy/gammapy/pull/431/files#diff-180360612c6b8c4ed830919bbb4dd459R39) @bsipocz  is setting
```
$env:GAMMAPY_EXTRA="c:\projects\gammapy-extra"
```
I think that part is working, because the test log shows
```
GAMMAPY_EXTRA = c:\projects\gammapy-extra
```

@bsipocz - Could you maybe run these commands on appveyor so that we see what's what?
```
python -c 'import os; print(os.environ)'
python -c 'from gammapy.datasets import gammapy_extra; print(gammapy_extra.dir)'
python -c 'from gammapy.datasets import gammapy_extra; print(gammapy_extra.is_available)'
python -c 'from gammapy.datasets import gammapy_extra; import os; print(os.listdir(str(gammapy_extra.dir)))'
python -c 'from gammapy.utils.scripts import make_path; print(make_path("$GAMMAPY_EXTRA/README.rst").absolute())'
```
@vorugantia - If you could also run these commands as well as `python setup.py test -V` for gammapy, and paste the outputs in gists at https://gist.github.com/ , that would probably be helpful to find the difference wrt. what's going on on the Appveyor cloud server.

**Comment by bsipocz** [comment]
@cdeil - It's in the latest log, I may have time this night to look at it but most probably can come back to it later this week.

**Comment by vorugantia** [comment]
@cdeil - Sorry I couldn't do it earlier, but here is the gist for those commands you requested I run: [Link](https://gist.github.com/vorugantia/0f796da2eba611889a26028449b8f0c8#file-gammapy). Let me know if there's anything else you need.

**Comment by cdeil** [comment]
@bsipocz - The output isn't informative ... it's not clear if the env variable isn't passed to the Python process, or if there's a bug in path handling in Gammapy on Windows (e.g. `Path` or `make_path` not working as it does on Linux / Mac).

Could you please put these commands one by one (not in a combined script) ... the output might shed a light on what's going on:
```
python -c 'import os; print(os.environ)'
python -c 'from gammapy.datasets import gammapy_extra; print(gammapy_extra.dir)'
python -c 'from gammapy.datasets import gammapy_extra; print(gammapy_extra.is_available)'
python -c 'from gammapy.datasets import gammapy_extra; import os; print(os.listdir(str(gammapy_extra.dir)))'
python -c 'from gammapy.utils.scripts import make_path; print(make_path("$GAMMAPY_EXTRA/README.rst").absolute())'
```

**Comment by cdeil** [comment]
Thierry via email:
```
1. Windows
- I succeeded running the GammaPy examples in anaconda3 on Windows (at least the "first_steps" notebook that has no Sherpa dependencies.
Here is the way to set the variable for windows (in fact it is the same as in Linux).
 
os.environ['GAMMAPY_EXTRA']='D:/Analyse/GammaPy/gammapy-extra/'
# check
print(os.getenv('GAMMAPY_EXTRA'))
print(os.listdir(os.getenv('GAMMAPY_EXTRA')))
 
I think it is easier to fix it in a notebook (or script), and might require a special python config module for all os (?).
```
So at least we know how users can make it work on Windows.
But we still don't have a solution how to set or configure the environment variable before running continuous integration tests.

I guess we could have a code snippet in `conftest.py` that checks `os.environ` if we're running on APPVEYOR, and if yes, sets` GAMMAPY_EXTRA to the known absolute location on Appveyor?
@bsipocz - Do you think that's feasible? Do you want to attempt to do it here in this PR?

**Comment by cdeil** [comment]
I'm closing this old issue. Appveyor was removed (see #818).

We now have Windows builds (including gammapy-extra and gammapy-data) on Azure pipelines and everything works well. See e.g. https://dev.azure.com/gammapy/gammapy/_build/results?buildId=257

**Pull request closed without merging**
