### PR TITLE
add a new class Data3DInt

### PR DESCRIPTION
**Pull request by JouvinLea**
@adonath 
Hi,
This is the new class and your test is still passing with the new implementation.
I didn't find a way in python to define two calc functions with different argument I'm not sure it's possible so I have also to create a new class Combined3DInt. I don't know exactly what I can do for the test since locally with my script it works perfectly using the model of NormGauss2DInt that you implemented and that I changed a little bit to be compatible with real coordinates. But I can't use it in the test....
Cheers,
Lea

### CODE REVIEW

**Comment by JouvinLea** [comment]
@adonath 
I don't think that the test that are failling are due to what I implemented!

**Comment by adonath** [comment]
@JouvinLea Thanks for the PR! You have to rebase your branch onto the latest master. There might be conflicts, because I have made changes to `cube.py`. Let me know if you have trouble resolving them and I will help.

**Comment by JouvinLea** [comment]
When I fetched the latest version and that I rebases it on my branch it says:
```
git rebase upstream/master
Current branch spectral_3D_analysis_AxelIntGaussModel is up to date.
```
so I don't understand.... apparently there is no conflict...

**Comment by adonath** [comment]
@leajouvin Dou you have some time to work on this (just a little...)? My suggestion would be, that you just checkout a new branch from latest master and copy over the `Data3DInt` class from this branch to the new branch and make a new PR.

Concerning the models and PSF convolution I would prefer a different solution...but for now can you just add the `CombinedModel3DInt`(so that it works for your usecase) and leave the `CombinedModel3D` unchanged?

**Comment by adonath** [comment]
Superseded by #765

**Pull request closed without merging**
