### PR TITLE
Add GIF maker matplotlib utility class

### PR DESCRIPTION
**Pull request by alankarkotwal**
(See #423 on gammapy/gammapy) Blinking images is very common in astronomy and is a good way to compare two analyses. This utility class implements a animation creator using Matplotlib.

--
Sample use:
```
from gammapy.utils import animmaker as G
import matplotlib.image as mpimg

i1 = mpimg.imread('u1.jpg')
i2 = mpimg.imread('u2.jpg')
i3 = mpimg.imread('u3.jpg')
i4 = mpimg.imread('u4.jpg')

myMaker = G.AnimMaker((i1, i2, i3, i4), duration=500)
myMaker.show_anim()
myMaker.write_anim('anim.gif', enc='imagemagick')
```

### CODE REVIEW

**Comment by cdeil** [comment]
@alankarkotwal - Thanks for the pull request!

Could you please:

- fix the formatting: https://gist.github.com/cdeil/8eaf6a2567a4dbbf9f13
- add a test in `gammapy/utils/tests/test_animmaker.py` that excercises the code
- add a nice example in `examples/example_animmaker.py`

---

The test should be simple and quick ... it's mostly there to make sure the code is working and keeps working. I'm not sure what to do ... maybe just generate 3 small 20 x 10 pixel numpy arrays with zeros and make the gif?
Because matplotlib is an optional dependency, you will have to move the import inside the function or method (instead of at the top of the file) and then for the test put the `@requires_dependency('matplotlib')` decorator on the test function, so that it's skipped if mpl is not available. Example:
https://github.com/gammapy/gammapy/blob/7297ffa73f55fcbca541fec6e5d81296e93c9f60/gammapy/time/tests/test_plot.py#L8

You can run just this test by running
```
python setup.py test -V -t gammapy/utils/tests/test_animmaker.py
```

---

For the example, I have several ideas how to make a nice animation of gamma-ray data with just ~ 20 lines of code.
One option would be to grab this image:
```
from astropy.io import fits
from gammapy.datasets import gammapy_extra
filename = gammapy_extra.filename('datasets/catalogs/fermi/gll_psch_v08.fit.gz')
hdu = fits.open(filename)['Count Map']
```
take a ~ 30 x 10 deg field of view and slide it left to right over the Galactic plane, as in the lower panel here: https://youtu.be/mpIp1oFokNA
Maybe make it so that the output GIF isn't too large, i.e. < 10 MB.
Cutting out the sub-arrays should be easy with [astropy.nddata.Cutout2D](http://astropy.readthedocs.org/en/latest/api/astropy.nddata.Cutout2D.html).

Another option would be to take this event list
https://github.com/gammapy/fhee/blob/master/data/2fhl_events.fits.gz
and make an all-sky movie where either time varies or the lower energy threshold.
If you choose time bins (e.g. weekly or monthly) you might see something like
https://svs.gsfc.nasa.gov/cgi-bin/details.cgi?aid=10819 and a flaring blazar?
This would teach you how to work with astropy Table (or the gammapy EventList class).
It's more work than the other example ... maybe 10 lines if you use the existing make_empty_image and bin_events_in_image utility functions from Gammapy (see example here:
https://github.com/gammapy/gammapy-extra/blob/master/notebooks/gammapy-image-crab.ipynb).

---

Once there is a working test and example, I'll do a more thorough review of this PR.

One thing I already noticed is that you're using a list of input images.
Does this work with an iterator as well?
That would be better (less memory use) if a lot of images are used.
Would it make the API much more complicated to support computing one image at a time and not having a list of all in memory at once?

**Comment by cdeil** [comment]
One more thing ... this needs to show up in the Gammapy API docs or users won't find and use it.

I'm thinking maybe this would fit better in `gammapy.image` instead of starting a separate sub-module in `gammapy.utils` which is already pretty chaotic?

Whereever you decide to put it, there has to be an 
```
__all__
```
list at the start of your module and the class has to be part of a namespace with an existing `automodapi` directive. E.g. https://github.com/gammapy/gammapy/blame/master/docs/image/index.rst#L49 will cause it to appear at https://gammapy.readthedocs.org/en/latest/image/index.html#reference-api if you add `from animmaker import *` to `gammapy/image/__init__.py`.
To test locally and check if the API docs look good, use these commands:
```
python setup.py build_sphinx
open docs/_build/html/index.html
```
(Yes, the Sphinx build is annoyingly slow!)

**Comment by alankarkotwal** [comment]
@cdeil Iterators wouldn't work if you'd want to play the animation continuously, right? To show the animation, Matplotlib's `FuncAnimation` needs to `imshow` every image at every animation iteration, and hence keep all images in memory.

I added the documentation requirements, and am now writing the test for the animation save feature and the example. How do I test the animation display feature automatically?

**Comment by cdeil** [comment]
@alankarkotwal - Thinking about this again, I'm not so sure anymore we're on the right track here ...

What we want is to make little movies (as GIF or real movie files), taking images computed with Gammapy and plotted with matplotlib as input.

Maybe we should go with the approach of saving the individual images in PNG files and then calling `ffmpeg` at the end as done e.g. here?
https://github.com/barentsen/visibility-maps/blob/master/examples/C2011L4.py#L5
I see quite a few advantages of that approach over `matplotlib.animation`:
1. Can use multi-core or multi-CPU cluster to compute the images in parallel
2. Don't need to hold all images in RAM at the same time
3. Simpler to use than `matplotlib.animation`?

I also just now found https://github.com/Zulko/moviepy which might be convenient to use?

If you agree, then the content for this PR would change ... the goal then would be to provide an example script producing a GIF and some documentation (probably best as a separate docs page in `docs/gammapy/image/animation.rst`) explaining how it works and showing the output image (stored in https://github.com/gammapy/gammapy-extra/tree/master/figures).

@alankarkotwal - Thoughts?

**Comment by alankarkotwal** [comment]
That would definitely be better in terms of memory. However, there wouldn't remain a pure Python way of scripting making the GIFs. For instance, if someone wanted to make only GIFs, they'd need to save all images and script in bash to call FFMpeg separately afterwards. We could definitely do that, though.

As for parallelism, the process of computing images is independent of making the GIF. You just need to assemble a list of images (which can be done in parallel as well).

I'll have a look at moviepy and get back to you.

**Comment by cdeil** [comment]
@alankarkotwal - Can we close this PR? Or do you still plan to work on it?

**Comment by alankarkotwal** [comment]
I might not work on it in the near future. I think it is better to close
this for now, if I work on it I'll re-open it.

**Pull request closed without merging**
