### PR TITLE
Deprecate is_norm on parameter

### PR DESCRIPTION
**Pull request by QRemy**
Split #4875 part 3.
Requires #4902 and #4903.

### CODE REVIEW

**Review by registerrier — APPROVED** [review]
Thanks @QRemy . This looks good!

**Comment by registerrier** [comment]
an you just rebase?

**Comment by QRemy** [comment]
Why flake8 complains ? : F811 redefinition of unused 'is_norm' from line 104

**Comment by QRemy** [comment]
> Why flake8 complains ? : F811 redefinition of unused 'is_norm' from line 104

Solved

**Review by registerrier — APPROVED** [review]
Thanks @QRemy . This looks good.

Removing the `_is_norm` definitions when preparing the next release might be error prone. We'll see.

**Pull request merged**
