### PR TITLE
Remove safe mask in background stacking

### PR DESCRIPTION
**Pull request by AtreyeeS**
Signed-off-by: Atreyee Sinha <asinha@ucm.es>

As discussed in #4207

### CODE REVIEW

**Comment by bkhelifi** [comment]
Hi @AtreyeeS , does your test include or deal with the issue mentioned in #4207 during the Fermi analysis? Do we have also tests for the 2 cases of staking into an empty dataset and a non-empty one?

**Comment by AtreyeeS** [comment]
Hi @bkhelifi 

- This PR and associated test should address the Fermi LAT issue mentioned in quantity
- stacking behaves correctly only when stacking into an empty dataset. There is probably no good way to prevent users from doing the wrong thing, except maybe documentation and constant re-iteration in hands on sessions

**Review by registerrier — APPROVED** [review]
Thanks @AtreyeeS !
No comment from my side.

**Review by adonath — APPROVED** [review]
Thanks @AtreyeeS, no further comments from me.

**Pull request merged**
