### PR TITLE
Add psf kernel cube method

### PR DESCRIPTION
**Pull request by JouvinLea**
@adonath @cdeil 
I started this PR to add a cube method to the ```EnergyDependentTablePSF```. I change the method ```kernel```in the ```TablePSF``` class to use fiil_acceptance  and the skyimage that you give as argument.

@adonath 
We need this method different from the kernels one to create directly a SkyCube, Christoph said that this is good to have both method...

For the moment I haven't the same result with this method and with the method in my notebook where I was oversampling the energy binning for each band of the Cube... I will not have the time to investigate this week end ...

### CODE REVIEW

**Comment by cdeil** [comment]
@leajouvin - I'm confused about the difference between this PR and #921 .

Both contain the addition of the `cube_kernels` method.

Did you make one by accident?
Can you close one of the two PRs, or separate them so that their content is separate?

**Comment by cdeil** [comment]
I didn't look closely ... maybe the method is added to separate classes?

In any case -- I'll leave the review of the two PSF kernel PRs to @adonath .

Have a nice weekend!

**Comment by JouvinLea** [comment]
@cdeil Sorry I made a mistake in the other PR it was only to fix the bug on the mean psf, I will remove the commit concerning the cube psf from the other PR.
This is the good PR here concerning the cube...

**Comment by adonath** [comment]
@JouvinLea I decided to preliminary attach this method to the `StackedCubeObsMaker` class in https://github.com/gammapy/gammapy/commit/8bd8a16212960cb4f01c139e45de160da6a3ebc7, because I wanted to clean up the cube analysis tutorial for presentation at the MPIK Python workshop.

My suggestion would be to keep it there for now and later take more time and rethink the structure of the code. Let me know if that is fine by you. Thanks for your contribution again!

**Comment by adonath** [comment]
Adressed in 8bd8a16.

**Pull request closed without merging**
