### PR TITLE
Updating astropy_helpers to 2.0.8

### PR DESCRIPTION
**Pull request by bsipocz**
~Do not merge yet, it's opened for testing and needs to be updated to point to the actual release when it's released.~

@cdeil  - Is there any workarounds that was added recently in order to ship 0.9 but I really need to remove here?

### CODE REVIEW

**Comment by bsipocz** [comment]
@cdeil - actually could you have a look at the passing CI jobs. Are they all look OK?

**Comment by cdeil** [comment]
I tried this branch locally with Sphinx 1.8.2 and Astropy master. It still doesn't work, there's this warning and the output still goes to the `docs/docs` sub-folder.
```
/Users/deil/work/code/gammapy/astropy_helpers/astropy_helpers/sphinx/ext/changelog_links.py:25: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info('[changelog_links] Adding changelog links to "{0}"'.format(docname))
[changelog_links] Adding changelog links to "changelog"
```

**Comment by bsipocz** [comment]
😭

**Comment by astrofrog** [comment]
Ah I figured it out, it's related to ``setup.cfg`` - just remove:

```
source-dir = docs
build-dir = docs/_build
```

I'll try and fix that in astropy-helpers too, but removing them should work just fine

**Comment by astrofrog** [comment]
Oh wait that's standard in the package template... Let me figure out a better fix

**Comment by astrofrog** [comment]
Fix in https://github.com/astropy/astropy-helpers/pull/431

**Comment by bsipocz** [comment]
This can be merged now, pointing to the actual release.

**Comment by cdeil** [comment]
@bsipocz @astrofrog - Thank you for all your work on the helpers!!!

**Pull request merged**
