### PR TITLE
Fix readout of times from obs-index file

### PR DESCRIPTION
**Pull request by lmohrmann**
After discussion in open-gamma-ray-astro/gamma-astro-data-formats#95, times in the obs-index file are stored in mission elapsed time (MET) in FITS files now. This PR reflects this change and reads the start and stop times of an observation from the index file correctly.

### CODE REVIEW

**Comment by cdeil** [comment]
Looks like we have a test case covering tstart, but not tstop:
https://coveralls.io/builds/13787001/source?filename=gammapy%2Fdata%2Fdata_store.py#L567

@lmohrmann - Did you try running the Gammapy tests? Probably the one accessing `tstart` will break and needs to be fixed in this PR.

And if that is not the case, then the test should be improved (or a new one added in https://github.com/gammapy/gammapy/blob/master/gammapy/data/tests/test_data_store.py) to cover those two attributes and include an assert on their value. Finding the test can be done by adding `1/0` or anything that raises an error in the method before running the test.

@lmohrmann - Are you willing to do that or should I take over here?

**Comment by lmohrmann** [comment]
Hi @cdeil, I can try to update the tests as well (but maybe not today).

**Comment by lmohrmann** [comment]
The one existing test accessing tstart does not fail, so it does not need to be fixed. I added a new test that check's some values read from the obs-index file for one observation run.

**Comment by cdeil** [comment]
The diff looks larger than it actually is, because I sorted properties so that all time-related info is together. Most properties are unchanged.

**Pull request merged**
