### PR TITLE
Fix IPython notebook automated tests

### PR DESCRIPTION
**Pull request by joleroi**
This PR implements test for IPython notebooks on travis-ci.

There's a `test_notebooks.py` script, which gets executed via `make test-notebooks` on travis-ci.

Lists of IPython notebooks to test have to be hand-edited in `test_notebooks.py`.

Continues https://github.com/gammapy/gammapy/pull/697

### CODE REVIEW

**Comment by joleroi** [comment]
https://travis-ci.org/gammapy/gammapy/jobs/157646246#L1209

I don't know why gammapy is not installed properly

**Comment by cdeil** [comment]
Gammapy is never installed.

You're running:
```
python setup.py build
```
https://github.com/gammapy/gammapy/blob/master/Makefile#L83

I think you have to run either
```
python setup.py build_ext --inplace
```
or better
```
python setup.py install
```
Maybe you'll also have to `cd` away from the source directory, e.g. via
```
cd $GAMMAPY_EXTRA
```

@joleroi - Can you please try that?

**Comment by cdeil** [comment]
With 2ec36b95c1a76dab6907b45de37367172f92467d the IPython notebook tests passed:

* Python 3: https://travis-ci.org/gammapy/gammapy/jobs/161901942#L1995
* Python 2: https://travis-ci.org/gammapy/gammapy/jobs/161901943#L2016

✌️ 

I'll try to add a few more notebooks to the list and then merge this later today.

**Comment by cdeil** [comment]
There were several issues with how I invoked the subprocesses to pass env, cwd and correct Python version, and how to report exit status and output back.
I tried to fix this in 67caf763103d5135bcb68ec7ee15ec30d64df730 , even though `subprocess.Popen` still baffles me every time.

I also made a fix in `fermi_2fhl.ipynb`, which was broken.

Looks like everything worked though except that `aplpy` is missing:
- https://travis-ci.org/gammapy/gammapy/jobs/161933708#L2060
- https://travis-ci.org/gammapy/gammapy/jobs/161933709#L2072

I'll try to add a commit to install that now ...

**Comment by cdeil** [comment]
There's still two fails in the notebooks:
- https://travis-ci.org/gammapy/gammapy/jobs/161942204#L2046
- https://travis-ci.org/gammapy/gammapy/jobs/161942205#L2281

I'm merging this PR now to have everything together in `master` and will fix those issues in a follow-up PR.

**Pull request merged**
