### PR TITLE
Grouping2

### PR DESCRIPTION
**Pull request by JouvinLea**
Hi Christophe and Johannes,
For the moment I didn’t try to merge anything. This is just for you to see the class SpectrumAnalysis and the method that I add for the grouping.

I have two methods:
	1) « define_spectral_band" in SpectrumAnalysis that defines the GROUP_ID  using the GroupAxis class. For each band, you define a SpectrumObservation object with the GROUP_ID and call the grouping method.  
			
	2) « grouping" in the SpectrumObservation class: you give a SpectrumObservation Object list and the method stacks the ON, OFF, ARF and RMF and return a new SpectrumObservation object.

When you create a SpectrumObservation object, the line "store.filename(obs, 'events’)" checks if the observation exists in the datastore directory. For the bands, this gives an error. I defined a new parameter in the constructor that is False by default and True if we use the band. For the True value it will not test if the observation exists. 

This is really not a satisfactory way to fix the issue but regarding the code structure and especially the fact that the storage and the extraction are in the same class I don’t have really the choice. Perhaps we can separate the extraction of the ON, OFF , ARF and RMF and the storage of these objects. For example to have a class SpectrumObservation that only stores these objects and that is not linked to an event list and can be easily defined for bands. We can define a write_ogip and read_ogip to this class. Separately, in an other class (SpectralExtraction) or in SpectralAnalysis we define the methods needed for the extraction of the ON, OFF …etc (like make_on(), …). 

What do you think? 
Lea

### CODE REVIEW

**Comment by joleroi** [comment]
Hi Lea, 
sorry for leaving this unnoticed so long.
You are absolutely right, I applied the changes you suggested in

https://github.com/gammapy/gammapy/pull/436

Let's talk about how to put the stacking methods in the new scheme next week, ok?

**Comment by JouvinLea** [comment]
ok but this is not merged now?
I must admit that this is difficult to understand on github in the Files changes what you did exactly? Can you just send me the new spectrum_analysis.py file?

**Comment by joleroi** [comment]
Do you have access to this link?

https://github.com/joleroi/gammapy/blob/spectrum/gammapy/spectrum/spectrum_extraction.py

I followed your suggestion and called it spectrum_extraction :+1:

**Comment by joleroi** [comment]
I also merged the other PR now

**Comment by JouvinLea** [comment]
No I get an error….

**Comment by JouvinLea** [comment]
But since you merged I get the new version!
As you said we will see next week see you add different stuff how to implement the grouping in it!

**Comment by cdeil** [comment]
@joleroi - I've assigned this PR to you for review and put the 0.5 milestone.

**Comment by cdeil** [comment]
Superseded by #471.

**Pull request closed without merging**
