### PR TITLE
Improve catalogue notebook

### PR DESCRIPTION
**Pull request by QRemy**
This PR re-arrange the structure of the catalogue notebook, and add or clarify several informations:
- about loading the catalogs
- about table, data, and position(s) properties
- how to select a catalogue subset using boolean mask
- how to create a Models object from a catalogue

### CODE REVIEW

**Review by adonath — DISMISSED** [review]
Thanks a lot @QRemy, I don't have any detailed comments here. I guess one could keep the `Exercises` and `Next steps` sections at the end, but we could also re-introduce those uniformly for all tutorials anyway later...

**Comment by adonath** [comment]
Totally minor: Typically we use American English spelling in Gammapy (at least in the code base...) so for consistency one could always use `catalog` in the notebook as well..

**Review by AtreyeeS — DISMISSED** [review]
Thanks @QRemy ! This looks quite complete now.

Perhaps it would be useful to add some more details on the HGPS calatog - adding examples for getting the large scale diffuse component and the discarded gaussian components.

**Comment by QRemy** [comment]
> Perhaps it would be useful to add some more details on the HGPS calatog - adding examples for getting the large scale diffuse component and the discarded gaussian components.

Added a section about that.

> Totally minor: typically we use American English spelling in Gammapy (at least in the code base...) so for consistency one could always use `catalog` in the notebook as well..

Done for catalog but I did not check the spelling consistancy for the other words

> I guess one could keep the `Exercises` and `Next steps` sections at the end, but we could also re-introduce those uniformly for all tutorials anyway later...

I moved most of the comments from `Next steps` in the introduction as there is not really steps within the API notebooks and the follow-up is to look at analysis notebooks.

For the `Exercises` part, half of the tasks proposed was now somehow shown in the notebook so I removed it. Maybe that instead of many exercise examples dispersed in several notebook we could assemble them into few exercices/solutions notebooks to be used for hands-on sessions (post 1.0).

**Review by adonath — APPROVED** [review]
Thanks a lot @QRemy, I have no further comments.

**Pull request merged**
