### PR TITLE
Change to astropy regions package

### PR DESCRIPTION
**Pull request by cdeil**
This PR
- [x] Adds a dependency on the https://github.com/astropy/regions package.
- [x] Removes the bundled version in `gammapy/extern/regions`
- [x] Removes the use of `pyregion` (except for one case where a TODO was left)

Related: #336 #547  #558 

Work in progress ...

### CODE REVIEW

**Comment by joleroi** [comment]
:fireworks:

**Comment by cdeil** [comment]
@bsipocz @mwcraig - Today Gammapy builds are failing with issue like this one about astropy channel conda packages:
```
Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/astropy/linux-64/aplpy-1.0-py27_0.tar.bz2: https://conda.anaconda.org/astropy/linux-64/aplpy-1.0-py27_0.tar.bz2
```
https://travis-ci.org/gammapy/gammapy/jobs/147488386#L584

Is it useful to mention this to you or are you aware already?

**Comment by mwcraig** [comment]
Thanks, working on it...

**Comment by cdeil** [comment]
travis-ci and appveyor tests passed.
merging this now.

@joleroi @adonath @OlgaVorokh @jjlk - `regions` is now a required dependency of Gammapy for the coming months, until it gets merged into the Astropy core, you will have to install it.

We still need to add docs and integrate `PixCoord` and `regions` this with `SkyImage` and other parts of Gammapy in the coming weeks in other PRs ...

**Pull request merged**
