### PR TITLE
Update test values due to changes in gammapy-extra

### PR DESCRIPTION
**Pull request by joleroi**
As discussed in https://github.com/gammapy/gammapy/issues/688 the PHA reference data in gammapy-extra is outdated. The energy dispersion files have changed. This PR

* Adds a test in ``test_extract`` to assert on an energy dispersion value
* Updates the assert values in ``test_fit`` (after an update of GP extra)

The PR that changed the energy dispersion values was https://github.com/gammapy/gammapy/pull/731. I won't investigate further why

### CODE REVIEW

**Comment by joleroi** [comment]
The last commit updates all test values again, as a fix for

https://github.com/gammapy/gammapy/pull/864

I have no idea where the changed in the float come from. I think it's some unit conversion stuff from within ``astropy.units``.

**Comment by joleroi** [comment]
https://travis-ci.org/gammapy/gammapy/jobs/197811647#L1015

This failure is unrelated to this PR. @cdeil  can you have a look? This is the ``SpectrumEnergyGroupMaker`` you implemented I think.

**Comment by joleroi** [comment]
> This failure is unrelated to this PR. @cdeil can you have a look?

I think I found the bug, and I'm afraid I introduced it ...

**Comment by cdeil** [comment]
The spectrum grouping is completely unfinished, and I'll have to go back to it soon because I need it for HGPS. If you can resolve things now, and if appropriate leave TODO comments or issues for me, I'd prefer not to look at it now.

**Comment by joleroi** [comment]
I don't understand the test failures

https://travis-ci.org/gammapy/gammapy/jobs/198671769#L1870

@cdeil ?

**Comment by cdeil** [comment]
This is a known travis-ci issue, that their build status is currently incorrect.
I think we just have to live with this for a day or two and the'll fix it.

**Comment by joleroi** [comment]
So we can merge this?

**Pull request merged**
