### PR TITLE
Improve mask_fit handling in analysis_3d notebook

### PR DESCRIPTION
**Pull request by registerrier**
**Description**

This pull request clarifies the usage of the mask_fit in analysis_3d. It removes the manual creation of the map which is not the recommended approach.

**Dear reviewer**

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @registerrier, I agree the analysis tutorial is not the right place for this. However I think showing how to create a mask manually is still useful, so maybe we show it in the mask tutorial instead?

**Comment by registerrier** [comment]
Yes indeed. The mask_map notebook lacks completely something for energy. So we need to show how to define a mask in energy manually and with the specific method there. And also how to combine the spatial part and spectral part. I can add that.

I think we also need to refer more frequently to this notebook to help people understand the roles of the different masks and how to create/handle them. I will add a reference here.

**Review by adonath — APPROVED** [review]
Thanks @registerrier, no further comments from my side...

**Comment by adonath** [comment]
Thanks @registerrier!

**Pull request merged**
