### PR TITLE
Make it possible to ignore energy bounds of the effective area table

### PR DESCRIPTION
**Pull request by lmohrmann**
Currently, the energy range that is recommended as "valid" for the effective area table is automatically applied before the spectrum is extracted. This energy range may or may not have been calculated in a way that is useful to the user. With this change, it is possible to ignore the recommended energy range. The default behavior is to still use it.

### CODE REVIEW

**Comment by jjlk** [comment]
Hi @Imohrmann and @joleroi , 
Will this PR handle the issue I posted here: https://github.com/gammasky/HESS-DL3-DR1/issues/38?

Thanks

**Comment by lmohrmann** [comment]
Hi @jjlk, yes, that might actually be the case. As far as I can tell, `define_energy_threshold` only has the ability to exclude further bins. Bins that are already excluded will not be "activated" by this function. By default, bins that are outside of the thresholds coming with the effective area table are already being excluded. This PR would make it possible to ignore those and obtain a range solely defined by whatever `define_energy_threshold` does.

**Comment by jjlk** [comment]
Hi @lmohrmann ,
Great, I'm waiting for the merge! Thanks ++

**Comment by cdeil** [comment]
OK, I'm merging this in then. I presume there will be the need for more fixes / changes / tests / docs concerning defaults and options for energy threshold handling.

If anyone is willing to summarise how it works now (using ~ 1-2 slides and 3-5 min) and maybe even outline options how to handle it better (or at least improve the docs), that would be very welcome for the next Gammapy call on September 11 (https://github.com/gammapy/gammapy-meetings/blob/master/2017-09-11/README.md) or the Gammapy coding sprint the week after (https://github.com/gammapy/gammapy-meetings/blob/master/2017-09_Heidelberg.md) (we can do a session with eZuce connection if people want to join that can't come to Heidelberg to discuss this or any other issues).

**Pull request merged**
