### PR TITLE
Fix loading `FoVBackgroundModel` from dict

### LINKED ISSUE #5079: `FoVBackgroundModel` can't be loaded from dict when it includes a spatial model
# Problem

It seems like all `<SpatialModel>.from_dict()` expect a dictionary with a key 'spatial' (Same for spectral models)

https://github.com/gammapy/gammapy/blob/dc9a88aea9e8f721c3c1f57b39bd98719a061118/gammapy/modeling/models/spatial.py#L286

The `FoVBackgroundModel` handles loading from dict correctly for spectral models
https://github.com/gammapy/gammapy/blob/dc9a88aea9e8f721c3c1f57b39bd98719a061118/gammapy/modeling/models/cube.py#L798

but not for spatial models

https://github.com/gammapy/gammapy/blob/dc9a88aea9e8f721c3c1f57b39bd98719a061118/gammapy/modeling/models/cube.py#L802-L807

# Solution

Should an easy fix
```python
     spatial_model = model_class.from_dict({"spatial": spatial_data}) 
```

### PR DESCRIPTION
**Pull request by StFroese**
**Description**
Fixes #5079

### CODE REVIEW

**Comment by bkhelifi** [comment]
Thank you very much. Can you add a dedicated test to be sure that this bug never happens again?

**Review by QRemy — APPROVED** [review]
Thanks @StFroese , I simplified a bit the changes and  I added some tests using the FoVBackgroundModel.

**Comment by StFroese** [comment]
@QRemy thanks, can also take a look at the issue above where I referenced this PR. Seems like there's some kind of bug

**Review by registerrier — APPROVED** [review]
Thanks @StFroese . This looks fine.

**Pull request merged**
