### PR TITLE
Switch documentation to PyData Sphinx Theme 

### PR DESCRIPTION
**Pull request by Bultako**
This PR changes the documentation Sphinx theme from present [Read the Docs Sphinx Theme](https://sphinx-rtd-theme.readthedocs.io/en/stable/) to [PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/) 
You can browse how it shows in this link https://www.iaa.csic.es/~jer/gammapydocs/index.html

### CODE REVIEW

**Comment by adonath** [comment]
Thanks @Bultako! As the PR touches a lot of files, I'm leaning towards just merging it once the CI is green and implement any comments in follow up PRs. This way other people could already start with improvements to the docs as well. Does this sounds reasonable to you @registerrier and @Bultako?

**Review by registerrier — COMMENTED** [review]
Thanks @Bultako ! 

Indeed, the simplest is probably to merge. The changes/corrections can then be introduced later.

**Comment by Bultako** [comment]
@adonath @registerrier 

Fine with me to merge when you wish.
We have green checks in the CI.

**Review by adonath — APPROVED** [review]
Thanks a lot @Bultako, no further comments from my side. I'll go ahead and merge the PR now and then we can continue with follow up PRs to improve it.

**Pull request merged**
