### PR TITLE
Fix energy bias computation

### PR DESCRIPTION
**Pull request by lmohrmann**
The energy bias computation in `energy_dispersion.EnergyDispersion` is broken. It computes the average log reconstructed energy over all bins of the pdf rather than column-wise. I think this PR should fix this bug, but it would be nice if someone would confirm this (the result can easily be plotted using `plot_bias()`).

### CODE REVIEW

**Comment by lmohrmann** [comment]
Just noticed the code is no longer working if the bias is evaluated at a single true energy. Will fix this!

**Comment by joleroi** [comment]
Thanks for spotting this :+1: Let's wait if tests pass and if they do (which means that this functionality was never testes) add one.

**Comment by lmohrmann** [comment]
@joleroi If I see things correctly, only the case in which the bias was computed for a single true energy is tested in `test_energy_dispersion`. That computation worked fine.

Also note that I pulled the changes made here into PR #1119. It might be more convenient to only merge that PR and ignore this one?

**Comment by joleroi** [comment]
> If I see things correctly, only the case in which the bias was computed for a single true energy is tested in test_energy_dispersion. That computation worked fine.

Let's add another test for an array of true energies. If you don't have time, I can append it to this PR

> Also note that I pulled the changes made here into PR #1119. It might be more convenient to only merge that PR and ignore this one?

IMO it's cleaner to first merge this one since the changes are unrelated (one might have to rebase #1119 then). I don't have a strong opinion, though. As you wish.

**Comment by joleroi** [comment]
The current ``EnergyDispersion`` that is used for testing is created with the [from_gauss](https://github.com/lmohrmann/gammapy/blob/fix-ebias-comp/gammapy/irf/tests/test_energy_dispersion.py#L18) method, which does not allow setting an energy bias. So a new test would not make much sense. There is already a [TODO](https://github.com/gammapy/gammapy/blob/master/gammapy/irf/energy_dispersion.py#L124).

The failures in this PR are unrelated. Merging.

**Comment by cdeil** [comment]
@joleroi - Just in case you hadn't seen it: https://github.com/gammapy/gammapy/pull/1115#issuecomment-327171581
i.e. basically note that `EnergyDispersion2D.from_gauss` is probably the implementation to go with.

**Pull request merged**
