### PR TITLE
Uptade tevcat exclusionmask

### PR DESCRIPTION
**Pull request by JouvinLea**
@cdeil 
The function make_tev_cat exclusion mask was broken so I just fix the few lines for it to work

### CODE REVIEW

**Comment by cdeil** [comment]
@JouvinLea - Thanks!

We now have [gamma-cat](http://docs.gammapy.org/en/latest/api/gammapy.catalog.SourceCatalogGammaCat.html) and want to get rid of TeVCat ASAP.

@JouvinLea - Do you have time to make the change to gamma-cat, or to add a test here for the TeVCat function you're fixing here, so that replacing it with gamma-cat becomes easier?
Or do you want to focus on other things and we just merge this now as-is?

**Comment by JouvinLea** [comment]
I just add the keyword at the end of the method in order to write the mask and read it again with SKyMask

**Comment by adonath** [comment]
I rebased the branch and once Travis-CI passed, I'll merge it.

**Comment by adonath** [comment]
Merged, Thanks @JouvinLea!

**Pull request merged**
