### PR TITLE
Add utility methods to dump catalogs to JSON

### PR DESCRIPTION
**Pull request by cdeil**
This pull request implements utility methods to dump catalogs to JSON.
This is useful for displaying catalog information in web pages.

### CODE REVIEW

**Comment by cdeil** [comment]
@adonath - I've assigned this issue to you and given you write access to my fork.
Thanks for implementing this!

**Comment by cdeil** [comment]
I now think trying to implement our own Table JSON serialisation is pointless / futile ... sorry @adonath for leading you down this path. See https://github.com/astropy/astropy/issues/4604

I'll sleep on this and wait for feedback on https://github.com/astropy/astropy/issues/4604 and then do something here ... probably drop vector columns for now and then call `table.to_pandas().to_json()`.

@kepta - If you want to start with the website displaying 2FHL catalog info already, you could do something like this, i.e. just keep a few columns and it'll work:
```python
from astropy.table import Table
table = Table.read('https://github.com/gammapy/gammapy-extra/blob/master/datasets/catalogs/fermi/gll_psch_v08.fit.gz?raw=true')
cols = ['Source_Name', 'RAJ2000', 'DEJ2000', 'GLON', 'GLAT', 'CLASS']
df = table[cols].to_pandas()
df.to_json()
```

Let me know if you have any questions!

**Comment by adonath** [comment]
@cdeil No problem, using pandas dataframes seems to be the better solution...close PR?

**Comment by cdeil** [comment]
@adonath - If you have time, could you add `to_pandas` methods that remove the array-valued columns or re-format them to multiple single-valued columns?

Having this would be useful e.g. when building this webpage:
https://github.com/gammapy/web-experiments/pull/6
or also the HGPS webpage...

**Comment by cdeil** [comment]
Here's a proposal for a solution:
https://github.com/astropy/astropy/issues/4604#issuecomment-184425733

The key is to get rid of the Numpy data types by calling `to_list`. A Python int is JSON serialisable, but a `numpy.int64` object isn't ... that's what making the tests fail here.

@adonath - Do you have time to do this or should I?

**Comment by cdeil** [comment]
I'm closing this PR now.

For now, we can dump the catalog info we want with a few lines of Python code:
https://github.com/astropy/astropy/issues/4604#issuecomment-184551578
http://nbviewer.jupyter.org/gist/cdeil/5c1a31ae00b3a0eefe84

So it's probably not needed that we introduce JSON dump code in Gammapy.

**Pull request closed without merging**
