### PR TITLE
Add a specialized  `EnergyAxis` 

### PR DESCRIPTION
**Pull request by registerrier**
This PR proposes to introduce an `EnergyAxis` inherited from `MapAxis` to represent energies in `Map`. It could replace the current `EnergyBounds` while providing a standardized way to create `MapAxis` containing energies.
It can contain a specific member to define the nature (reco or true) of the energy axis. I don't how useful this is though.
Opinions @cdeil, @adonath, @AtreyeeS ?

### CODE REVIEW

**Comment by cdeil** [comment]
@registerrier - I would prefer a small PIG for this, that has the energy ranges and axes as scope. It can be one page and discussion can only be a week, and if it then gets implemented ASAP, great!

This PR currently just adds 200 lines of code that does what the existing `Energy` and `EnergyBounds` classes do, without replacing the callers. See https://docs.gammapy.org/0.12/utils/index.html#energy-handling-in-gammapy

I have to admit that I don't clearly see pros and cons over adding an `EnergyAxis` as `MapAxis` subclass, versus an `Energy` class that is a `Quantity` subclass. Or possibly neither of them are needed and we can just use the existing `MapAxis` in some places, or the existing `Quantity` class from Astropy directly. 
The functionality of setting up grids could be done via helper functions like https://docs.gammapy.org/0.12/api/gammapy.utils.nddata.sqrt_space.html or something like
```
import numpy as np
import astropy.units as u 
energy = np.logspace(-1, 1, 20) * u.TeV
```
In itself this functionality probably isn't enough to warrant the introduction of a new class.

There are also 100 functions in Gammapy that sometimes take `emin, emax`, sometimes `energy_min`, `energy_max, sometimes `energy_range`. 
We already decided to use `energy_*`, but where to use a single range and where to use two arguments should be sorted out and get a guideline:
https://docs.gammapy.org/0.12/development/howto.html#coordinate-and-axis-names

Specifically, coming back to this PR, looking at your use cases in the tests here, it's not clear to me why this class is needed, everything can be done just with the existing `MapAxis`, no? And there's no info yet how this interacts with FITS serialisation and analysis code in Gammapy.

@registerrier @adonath - OK to go the PIG route for this? Or do you prefer to just discussion / go ahead for this via issues and PRs?

**Comment by AtreyeeS** [comment]
Without going into the specifics of the PR, I think having an `EnergyAxis` can be a useful abstraction. Having the `is_e_true` attribute can make the code cleaner, and we can have clarity on when we go from true energies to reco energies, something that we seem to discuss often. I think the `node_type` can also be fixed automatically in this case (`center` for `is_e_true=True` and vice verse).

**Comment by adonath** [comment]
I agree with @cdeil here that we should maybe harmonise the energy handling in Gammapy with a (short!) PIG. This PIG would also address naming conventions (`energy`, `e_reco`, `e_true`, `ebounds`, `erange`, `energy_range`, `emin`, `e_max`, `energy_lo`, `energy_hi`, `e_edges` just to name a few...) for energies so that we can make this uniform once and for all in Gammapy.

Whether we really need the `EnergyAxis` object is not 100% clear to me yet. I think the "convenience" provided but the current `EnergyBounds` class, we can easily give up. I think it's totally fine for users to either write `np.logspace(np.log10(e_min), np.log10(e_max), 10) * u.TeV` or use e.g. `MapAxis.from_bounds()` where you can also specify log, sqrt or linear binning. So I think we don't even need any helper methods.

I think in a first step we should try to remove the `Energy` and `EnergyBounds` classes. In cases where it's used with Maps or Spectra or IRFs, we replace it with `MapAxis` in all other cases, we just use a `Quantity` object. I hope this is mostly uncontroversial.

In a second step we can think about introducing the `EnergyAxis` object. I agree with @AtreyeeS and @registerrier , that it might be useful to store some meta information such as `is_e_true` with it. The alternative solution is probably to solve this with a naming convention...I'll think about it once again.

**Comment by cdeil** [comment]
Agree with @adonath - do a small PIG and let's try to put an as-simple solution as possible, i.e. only use `Quantity` and `MapAxis` (which could be moved to utils and named `Axis`, to the location of the current `Energy` and `EnergyBounds` which can be removed).

@AtreyeeS @registerrier - Consider this: Fermi ST and Sherpa don't have the special true and energy axis distinction via a class, how you want to add it. Also: we don't have it for spatial axes either, although there we have the same: some maps are before some after applying IRF (in that case PSF). So the logical thing would be to introduce special stuff on WCS for that? I'm really not convinced it's needed, and am actually pretty sure introducing it would make Gammapy more, not less complex.

In any case, given that the design to put is unclear, a PIG is needed to arrive at a good and agreed solution. So -1 to merge this PR in, suggest to just close it now, and reference it from the PIG.

**Comment by registerrier** [comment]
Well sherpa does have a difference between true and reco energies. The latter do not really exist, it rather relies on channels/PI, and some correspondence is made is some specific cases (e.g. energy range selection/plotting etc).

In most cases, the naming can solve the issue as e.g. in `EnergyDistribution` where the two axes are present at the same time.
Some cases can be ambiguous as e.g. an exposure map in reco energy which might be made to create a flux map. Again probably the name of the function to create the map might be clear regarding what it produces.

We can go for a PIG to check the various schemes used and propose a limited set of usage. I think removing `Energy` and `EnergyBounds` is also a possibility even without introducing an `EnergyAxis`.

Closing the PR. Will add a new PIG for this.

**Comment by cdeil** [comment]
@registerrier - Thank you for agreeing to go the PIG route.

One major question is whether e.g. `gammapy.irf` and `gammapy.spectrum` should depend on `gammapy.maps` and import `MapAxis`, or if `MapAxis` should be moved to `gammapy.utils` and renamed `Axis` before that happens. The question starts with `MapAxis` but then I think both @registerrier and @adonath you think that maybe `gammapy.irf` and `gammapy.spectrum` should be rewritten in a big way to use `Map` objects.

I'm not sure if this is they way to go or not, and how to get to a good design and make progress quickly. I fear that if we try to make that decision the PIG will become very large and discussion will take a long time.

Maybe it is possible to keep the PIG very small, and to just use `MapAxis` from the current location (and to effectively make `gammapy.maps` a foundation low-level package), and to describe when and how `Energy`, `EnergyBounds`, `Quantity` or `MapAxis` should be used?

I think removing `Energy` and `EnergyBounds` and just to use `Quantity` is a good idea - but I'm not 100% sure - note that there's also an `Angle` in Astropy that is a `Quantity` subclass, just like our `Energy`, with some extra specific functionality like wrapping at 180 or 360, or special constructors from strings, and that is both convenient, and also means it's possible to find all places where `Angle` is used very quickly, which is much harder for `Quantity`.

So I just wanted to say: please keep the PIG small in scope. IMO most PIGs we've done were too large and open for much too long and as a result painful to continue after half a year or whatever and thus inefficient. I would prefer PIGs that are discussed for a week or two and then approved and merged.

**Pull request closed without merging**
