### PR TITLE
Small update of the installation instructions

### PR DESCRIPTION
**Pull request by bkhelifi**
**Description**

This pull request tries to orientate users to use the environment file method to install Gammapy as a stand-alone projet. Otherwise, users should check the dependency versions.

It removes also the '$' in the bash commands... Some are making a copy/paste with them and do not understand immediately why it is not working.

### CODE REVIEW

**Comment by QRemy** [comment]
Is it in conflict with #4983 ?

**Review by adonath — COMMENTED** [review]
Thanks @bkhelifi, I have left some inline comments.

**Comment by Astro-Kirsty** [comment]
#4983 has been merged, so this will need to be rebased. 
I suggest removing the adaptions in `index.rst` as this has since been discussed and adjusted in #4983 

Otherwise I agree with removing the `$`

**Comment by QRemy** [comment]
This was close automatically because nothing new was left solving the conflicts with https://github.com/gammapy/gammapy/pull/4983.
Removing the $ in bash commands will be done in a separate PR for the whole documentation.

**Pull request closed without merging**
