### PR TITLE
Issue #4117

### PR DESCRIPTION
**Pull request by adonath**
**Description**

This pull request addresses the issues raised in #4117. It includes the following checks:
- Check that the dataset name is a `str`
- Modify the behavior for `RegionGeom.contains` and `PointSkyRegion`. The implementation in `regions`, does not include the coordinate even if it is exactly at the center of the region. The point sky region here is approximated by a rectangular region of the size of 1x1 pixel.

### CODE REVIEW

**Review by registerrier — COMMENTED** [review]
Thanks @adonath .  

It is not clear to me what we gain by treating the `PointSkyRegion` as a `Rectangle` brings.  Is the issue with `contain` connected with the necessity of taking into account the varying ON region size? Is returning `True` all the time a possibility as well?

**Comment by mireianievas** [comment]
@registerrier astropy.region developers were in favour of keeping False as a returning value (argument they used: a point does not include anything). Which is somewhat logical. 

Yes, one can force PointSkyRegion.contain to return True by setting the meta information as {'include': False} . But I guess the ideal case is to use something different which behaves like PointSkyRegion except it has some dimensions to include the point and return True.

**Comment by adonath** [comment]
@registerrier The use of the `RectangleSkyRegion` here is related to the fact that we internally rely on a `WCS` with finite pixel size. A point source on a WCS grid is represented by a 1x1 pixel, equivalent to our `PointSpatialModel`. I have not checked where it would be relevant for the `RegionGeom` apart from `.contains(), probably methods like `get_wcs_coord_and_weights`.

**Review by registerrier — COMMENTED** [review]
Thanks @adonath.

What is the new behaviour introduced for small bins? They are now skipped? How is the flux points axis defined, then?
Maybe you could clarify why this is needed? I don't see the link with the issue #4117 .

**Comment by adonath** [comment]
@registerrier Those changes kind of happened "accidentally", when I refactored the code. What happened was the following:

- The current code fails for the flux point estimation with datasets of different energy ranges, because quantities like `npred` or `excess`, actually have a `dataset` axes. 
- I decided to introduce the same behavior as for the `LightCurveEstimator`, where we just ues a placeholder value, if datasets do not contribute to the given time bin. 
- This happened by using the same pattern with `FluxPoints.from_stack()`
- However it modified the the behavior for the small energy bins

All in all I'm not even sure whether we should actually allow the flux point computation with "mixed" datasets at all. Users will need to be very careful with choices of energy bins for the different datasets and how they align. I think this will require better documentation...

**Comment by adonath** [comment]
@mireianievas I just talked to @registerrier and we realized that right now we should not allow to use datasets from different instruments for flux point computation in Gammapy. Currently Gammapy uses a "hybrid" methods, where flux points are fitted in reconstructed energy bins. Different instruments have varying energy resolution and bias and this way there is not clear definition of an energy bin anymore. In addition when limiting the fit to a small energy range the handling of systematics becomes more important as well, which requires a more flexible likelihood definition as well. I'll now modify the PR to raise a more meaningful error if flux points are computed with heterogeneous datasets. 

The support for multi-instrument flux points will come once we add unfolding of spectra to Gammapy. There is currently one member of the dev team working on this. So it might come with the next minor feature release v1.1 scheduled for spring next year...

**Pull request merged**
