### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by hugovk**
Some more stuff for https://github.com/gammapy/gammapy/issues/1963.

### CODE REVIEW

**Comment by cdeil** [comment]
@hugovk - Thanks!

@bsipocz - is `ah_bootstrap.py` a file we should update?

It's imported in `setup.py`, and using Python 3 stuff in `setup.py` might not be a good idea (according to https://python3statement.org/practicalities/)

@hugovk - did you run an updater on `ah_bootstrap.py` or is this an updated copy from https://github.com/astropy/package-template/blob/master/ah_bootstrap.py ?

I'm off now, will look at this tomorrow morning.

**Comment by bsipocz** [comment]
Leave `ah_bootstrap.py` out of manual updates, even the old one works perfectly with python3. Otherwise the update is done in #2017

**Comment by hugovk** [comment]
> Leave `ah_bootstrap.py` out of manual updates, even the old one works perfectly with python3. Otherwise the update is done in #2017

Done!

**Comment by cdeil** [comment]
@hugovk - Thank you very much!

I think I had seen https://github.com/asottile/pyupgrade in the past, but didn't remember or find it with Google yesterday. I wish I had, it's exactly the tool that would have done the transformations I applied manually automatically. Overall the Gammapy codebase isn't very large, so with multi-file search and replace it took me less than an hour overall, but still.

Please make some changes:
- [ ] `gammapy/extern/appdirs.py` is an extern / bundled file, we don't want to edit / maintain it. Please revert any edits there.
- [ ] The edits for `setup.py` and I think also for `_astropy_init.py` should be reverted. The recommended way is to leave them such that a clear error message is given if someone tries to use it with Python 2. Currently we have this:
```
$ python2 setup.py install
ERROR: Python (3, 5) or later is required by astropy-helpers
```
With the edits you make here, it fails with an `ImportError` that Python newbies won't understand:
```
$ python2 setup.py install
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import builtins
ImportError: No module named builtins
```
- [ ] Would you be willing to squash the commits here? To avoid having edits / back and forth in critical files like `setup.py` in our project version history?

**Comment by hugovk** [comment]
I've reverted those files. Sure, happy to squash commits.

Let me know when the PR is ready and I'll do it, or you can do it during merge with the "Squash and merge" button:

https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github

**Comment by cdeil** [comment]
> "Squash and merge" button

It's the first time I used this. Seems to work great. Looks like this, one commit in master, no separate merge commit: fdf4870b245fec25890d1f000274a469c45a65a5

So far I never squashed for contributions, because I wanted to have credit preserved. But I guess "hugovk authored and cdeil committed" is OK, i.e. authorship credit is preserved well-enough.

@hugovk - Thank you very much!

**Comment by hugovk** [comment]
All good, thanks!

**Comment by bsipocz** [comment]
> So far I never squashed for contributions, because I wanted to have credit preserved. But I guess "hugovk authored and cdeil committed" is OK, i.e. authorship credit is preserved well-enough.

The credit will still go to the author in this case, I haven't seen it anywhere where the committer gets listed for a commit and not the author.

**Comment by bsipocz** [comment]
> $ python2 setup.py install
ERROR: Python (3, 5) or later is required by astropy-helpers

This will be a cleaner error message with the 3.2 version of the helpers, saying that gammapy requires python 3.5 or later.

**Comment by bsipocz** [comment]
(I'm afraid we didn't backported those changes to the 3.1.x branch, so the release will be out with astropy 3.2 in a few months along with tons of other simplifications in the helpers).

**Pull request merged**
